#ifndef BLOCK_CONSTANTS_H
#define BLOCK_CONSTANTS_H

enum BlockType {
    BLOCK_TYPE_NONE,
    BLOCK_TYPE_SHOT_BLOCK_REFORM,
    BLOCK_TYPE_BOMB_BLOCK_REFORM,
    BLOCK_TYPE_SPEEDBOOSTER_BLOCK_REFORM,
    BLOCK_TYPE_CRUMBLE,
    BLOCK_TYPE_SLOW_CRUMBLE,
    BLOCK_TYPE_MISSILE_NEVER_REFORM,
    BLOCK_TYPE_MISSILE_NO_REFORM,
    BLOCK_TYPE_SUPER_MISSILE_NEVER_REFORM,
    BLOCK_TYPE_SUPER_MISSILE_NO_REFORM,
    BLOCK_TYPE_POWER_BOMB_NEVER_REFORM,
    BLOCK_TYPE_SCREW_NO_REFORM,
    BLOCK_TYPE_SPEEDBOOSTER_BLOCK_NO_REFORM,
    BLOCK_TYPE_BOMB_BLOCK_NEVER_REFORM,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN1,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN2,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN3,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN4,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN1,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN2,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN3,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN4,

    BLOCK_TYPE_COUNT
};

#define ITEM_TYPE_NONE 0x0
#define ITEM_TYPE_MISSILE 0x1
#define ITEM_TYPE_ENERGY 0x2
#define ITEM_TYPE_SUPER_MISSILE 0x3
#define ITEM_TYPE_POWER_BOMB 0x4
#define ITEM_TYPE_ABILITY 0x80

#define CAA_DAMAGE_TYPE_NONE                 0
#define CAA_DAMAGE_TYPE_BEAM                 (1 << 0)
#define CAA_DAMAGE_TYPE_BOMB_PISTOL          (1 << 1)
#define CAA_DAMAGE_TYPE_MISSILE              (1 << 2)
#define CAA_DAMAGE_TYPE_SUPER_MISSILE        (1 << 3)
#define CAA_DAMAGE_TYPE_POWER_BOMB           (1 << 4)
#define CAA_DAMAGE_TYPE_SPEEDBOOST           (1 << 5)
#define CAA_DAMAGE_TYPE_SPEEDBOOST_ON_GROUND (1 << 6)
#define CAA_DAMAGE_TYPE_SCREW_ATTACK         (1 << 7)
#define CAA_DAMAGE_TYPE_BOMB_CHAIN           (1 << 12)

#define TANK_WEAKNESS ((CAA_DAMAGE_TYPE_BEAM | CAA_DAMAGE_TYPE_BOMB_PISTOL | CAA_DAMAGE_TYPE_MISSILE | CAA_DAMAGE_TYPE_SUPER_MISSILE | CAA_DAMAGE_TYPE_POWER_BOMB))

enum BlockLifeType {
    BLOCK_LIFE_TYPE_NONE,
    BLOCK_LIFE_TYPE_NO_NEVER_REFORM,
    BLOCK_LIFE_TYPE_REFORM,
    BLOCK_LIFE_TYPE_BOMB_CHAIN,
    BLOCK_LIFE_TYPE_TANK,
};

enum BlockSubType {
    BLOCK_SUB_TYPE_REFORM,
    BLOCK_SUB_TYPE_SQUARE_NO_REFORM,
    BLOCK_SUB_TYPE_NO_REFORM,
    BLOCK_SUB_TYPE_SQUARE_NEVER_REFORM,
    BLOCK_SUB_TYPE_BOMB_CHAIN,
};

enum BombChainType {
    BOMB_CHAIN_TYPE_VERTICAL1,
    BOMB_CHAIN_TYPE_VERTICAL2,
    BOMB_CHAIN_TYPE_VERTICAL3,
    BOMB_CHAIN_TYPE_VERTICAL4,
    BOMB_CHAIN_TYPE_HORIZONTAL1,
    BOMB_CHAIN_TYPE_HORIZONTAL2,
    BOMB_CHAIN_TYPE_HORIZONTAL3,
    BOMB_CHAIN_TYPE_HORIZONTAL4,

    BOMB_CHAIN_TYPE_END
};

enum SubBombChainRequest {
    SUB_BOMB_CHAIN_REQUEST_HORIZONTAL_WHEN_GOING_UP,
    SUB_BOMB_CHAIN_REQUEST_HORIZONTAL_WHEN_GOING_DOWN,
    SUB_BOMB_CHAIN_REQUEST_VERTICAL_WHEN_GOING_LEFT,
    SUB_BOMB_CHAIN_REQUEST_VERTICAL_WHEN_GOING_RIGHT,

    SUB_BOMB_CHAIN_REQUEST_END
};

#endif
