#ifndef CABLE_LINK_CONSTANTS_H
#define CABLE_LINK_CONSTANTS_H

#define CABLE_LINK_ERROR_SHIFT_HARDWARE 0x10
#define CABLE_LINK_ERROR_SHIFT_CHECKSUM 0x11
#define CABLE_LINK_ERROR_SHIFT_OVERFLOW 0x12
#define CABLE_LINK_ERROR_SHIFT_SIO 0x14
#define CABLE_LINK_ERROR_SHIFT_ID_OVER 0x16

#define CABLE_LINK_ERROR_HARDWARE (1 << CABLE_LINK_ERROR_SHIFT_HARDWARE)
#define CABLE_LINK_ERROR_CHECKSUM (1 << CABLE_LINK_ERROR_SHIFT_CHECKSUM)
#define CABLE_LINK_ERROR_SEND_OVERFLOW (1 << CABLE_LINK_ERROR_SHIFT_OVERFLOW)
#define CABLE_LINK_ERROR_RECEIVE_OVERFLOW (2 << CABLE_LINK_ERROR_SHIFT_OVERFLOW)
#define CABLE_LINK_ERROR_SIO_INTERNAL (1 << CABLE_LINK_ERROR_SHIFT_SIO)
#define CABLE_LINK_ERROR_SIO_STOP (2 << CABLE_LINK_ERROR_SHIFT_SIO)
#define CABLE_LINK_ERROR_ID_OVER (1 << CABLE_LINK_ERROR_SHIFT_ID_OVER)

enum CableLink3005890Stage {
    CABLE_LINK_3005890_STAGE_0, // Clear and setup serial transfer
    CABLE_LINK_3005890_STAGE_1, // Initial link to pair the GBA? Start serial transfer (or fail after half a second)
    CABLE_LINK_3005890_STAGE_2, // Set serial transfer to wait and load the data and size of data
    CABLE_LINK_3005890_STAGE_3, // Transfer the data
    CABLE_LINK_3005890_STAGE_4, // Setup serial transfer
    CABLE_LINK_3005890_STAGE_5, // Transfer the data
    CABLE_LINK_3005890_STAGE_6, // Serial finished

    CABLE_LINK_3005890_STAGE_END
};

#endif
