#ifndef CABLE_LINK_CONSTANTS_H
#define CABLE_LINK_CONSTANTS_H

enum ActiveTransfer {
    ACTIVE_TRANSFER_NONE,
    ACTIVE_TRANSFER_CONNECT,
    ACTIVE_TRANSFER_LINK
};

enum ConnectStage {
    CONNECT_STAGE_FADE_MUSIC,
    CONNECT_STAGE_WAIT_CLEAR_SOUND,
    CONNECT_STAGE_MULTIBOOT_INIT,
    CONNECT_STAGE_MULTIBOOT_PROCESS,
    CONNECT_STAGE_TRANSFER_SEND_TRANSFER_ROM,
    CONNECT_STAGE_TRANSFER_COMPLETE,
    CONNECT_STAGE_TRANSFER_SUCCESS,
    CONNECT_STAGE_MULTIBOOT_TIMED_OUT,
    CONNECT_STAGE_BACKED_OUT,
    CONNECT_STAGE_TRANSFER_FAILURE,
    CONNECT_STAGE_SET_ACTIVE_LINK,
    CONNECT_STAGE_RESTORE_AUDIO,
    CONNECT_STAGE_FINISH
};

enum TransferResult {
    TRANSFER_RESULT_NONE,
    TRANSFER_RESULT_SUCCESS,
    TRANSFER_RESULT_BACKED_OUT,
    TRANSFER_RESULT_TIMED_OUT,
    TRANSFER_RESULT_FAILURE,
    TRANSFER_RESULT_SUCCESS2 // Related to number of received images
};

#endif
