#ifndef CLIPDATA_CONSTANTS_H
#define CLIPDATA_CONSTANTS_H

enum ClipdataAffectingAction {
    CAA_NONE, 
    CAA_REMOVE_SOLID, 
    CAA_MAKE_SOLID_GRIPPABLE, 
    CAA_MAKE_STOP_ENEMY, 
    CAA_MAKE_NON_POWER_GRIP, 
    CAA_BOMB_CHAIN_UNUSED, 
    CAA_UNUSED, 
    CAA_BEAM, 
    CAA_BOMB_PISTOL, 
    CAA_MISSILE, 
    CAA_SUPER_MISSILE, 
    CAA_POWER_BOMB, 
    CAA_SPEEDBOOSTER, 
    CAA_SPEEDBOOSTER_ON_GROUND, 
    CAA_SCREW_ATTACK, 
    CAA_BOMB_CHAIN, 

    CAA_COUNT
};

#define COLLISION_AIR 0x0
#define COLLISION_LEFT_SLIGHT_FLOOR_SLOPE 0x2
#define COLLISION_RIGHT_SLIGHT_FLOOR_SLOPE 0x3
#define COLLISION_LEFT_STEEP_FLOOR_SLOPE 0x4
#define COLLISION_RIGHT_STEEP_FLOOR_SLOPE 0x5
#define COLLISION_PASS_THROUGH_BOTTOM 0x10
#define COLLISION_SOLID 0x11
#define COLLISION_FLAGS_UNKNOWN_F (0x1 | COLLISION_LEFT_SLIGHT_FLOOR_SLOPE | COLLISION_LEFT_STEEP_FLOOR_SLOPE | 0x8)
#define COLLISION_FLAGS_UNKNOWN_F0 (COLLISION_PASS_THROUGH_BOTTOM | 0x20 | 0x40 | 0x80)

enum ClipdataMovement {
    CLIPDATA_MOVEMENT_NONE,
    CLIPDATA_MOVEMENT_ELEVATOR_DOWN_BLOCK,
    CLIPDATA_MOVEMENT_ELEVATOR_UP_BLOCK,

    CLIPDATA_MOVEMENT_NON_POWER_GRIP = 0x6,
    CLIPDATA_MOVEMENT_STOP_ENEMY_BLOCK_SOLID,
    CLIPDATA_MOVEMENT_SPACE_PIRATE_ZONELINE,
    CLIPDATA_MOVEMENT_SPACE_PIRATE_WALLJUMP_POINT,
};

enum HazardType {
    HAZARD_TYPE_NONE,
    HAZARD_TYPE_WATER,
    HAZARD_TYPE_STRONG_LAVA,
    HAZARD_TYPE_WEAK_LAVA,
    HAZARD_TYPE_ACID,
    HAZARD_TYPE_HEAT,
    HAZARD_TYPE_COLD_KNOCKBACK,
    HAZARD_TYPE_COLD,
};

enum GroundEffect {
    GROUND_EFFECT_NONE,
    GROUND_EFFECT_WET_GROUND,
    GROUND_EFFECT_DUSTY_GROUND,
    GROUND_EFFECT_VERY_DUSTY_GROUND,
    GROUND_EFFECT_UNKNOWN,
    GROUND_EFFECT_BUBBLY_GROUND,
};

#define CLIPDATA_ACTOR_SAMUS 0x0
#define CLIPDATA_ACTOR_NON_SPRITE 0x1
#define CLIPDATA_ACTOR_SPRITE 0x2

enum ClipdataType {
    CLIPDATA_TYPE_AIR,
    CLIPDATA_TYPE_SOLID,
    CLIPDATA_TYPE_LEFT_STEEP_FLOOR_SLOPE,
    CLIPDATA_TYPE_RIGHT_STEEP_FLOOR_SLOPE,
    CLIPDATA_TYPE_LEFT_UPPER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_LEFT_LOWER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_RIGHT_LOWER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_RIGHT_UPPER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_ENEMY_ONLY,
    CLIPDATA_TYPE_STOP_ENEMY,
    CLIPDATA_TYPE_TANK,
    CLIPDATA_TYPE_DOOR,
    CLIPDATA_TYPE_PASS_THROUGH_BOTTOM,
};

#define CLIPDATA_TYPE_SOLID_FLAG 0x1000000

enum ClipBehavior {
    CLIP_BEHAVIOR_NONE, // 0x0
    CLIP_BEHAVIOR_ELEVATOR_DOWN, // 0x1
    CLIP_BEHAVIOR_ELEVATOR_UP, // 0x2
    CLIP_BEHAVIOR_DOOR_TRANSITION, // 0x3
    CLIP_BEHAVIOR_VERTICAL_UP_TRANSITION, // 0x4
    CLIP_BEHAVIOR_VERTICAL_DOWN_TRANSITION, // 0x5
    CLIP_BEHAVIOR_NON_POWER_GRIP, // 0x6
    CLIP_BEHAVIOR_STOP_ENEMY_SOLID, // 0x7
    CLIP_BEHAVIOR_SPACE_PIRATE_ZONELINE, // 0x8
    CLIP_BEHAVIOR_SPACE_PIRATE_WALLJUMP_POINT, // 0x9

    CLIP_BEHAVIOR_SHOT_BLOCK_NEVER_REFORM = 16, // 0x10
    CLIP_BEHAVIOR_TOP_LEFT_SHOT_BLOCK_NEVER_REFORM, // 0x11
    CLIP_BEHAVIOR_TOP_RIGHT_SHOT_BLOCK_NEVER_REFORM, // 0x12
    CLIP_BEHAVIOR_BOTTOM_LEFT_SHOT_BLOCK_NEVER_REFORM, // 0x13
    CLIP_BEHAVIOR_BOTTOM_RIGHT_SHOT_BLOCK_NEVER_REFORM, // 0x14
    CLIP_BEHAVIOR_SHOT_BLOCK_NO_REFORM, // 0x15
    CLIP_BEHAVIOR_TOP_LEFT_SHOT_BLOCK_NO_REFORM, // 0x16
    CLIP_BEHAVIOR_TOP_RIGHT_SHOT_BLOCK_NO_REFORM, // 0x17
    CLIP_BEHAVIOR_BOTTOM_LEFT_SHOT_BLOCK_NO_REFORM, // 0x18
    CLIP_BEHAVIOR_BOTTOM_RIGHT_SHOT_BLOCK_NO_REFORM, // 0x19
    CLIP_BEHAVIOR_SHOT_BLOCK_REFORM, // 0x1A
    CLIP_BEHAVIOR_BOMB_BLOCK_NEVER_REFORM, // 0x1B
    CLIP_BEHAVIOR_BOMB_BLOCK_REFORM, // 0x1C
    CLIP_BEHAVIOR_MISSILE_BLOCK_NEVER_REFORM, // 0x1D
    CLIP_BEHAVIOR_MISSILE_BLOCK_NO_REFORM, // 0x1E
    CLIP_BEHAVIOR_SUPER_MISSILE_BLOCK_NEVER_REFORM, // 0x1F
    CLIP_BEHAVIOR_SUPER_MISSILE_BLOCK_NO_REFORM, // 0x20
    CLIP_BEHAVIOR_SPEEDBOOST_BLOCK_NO_REFORM, // 0x21
    CLIP_BEHAVIOR_SPEEDBOOST_BLOCK_REFORM, // 0x22
    CLIP_BEHAVIOR_CRUMBLE_BLOCK, // 0x23
    CLIP_BEHAVIOR_POWER_BOMB_BLOCK_NEVER_REFORM, // 0x24
    CLIP_BEHAVIOR_SCREW_ATTACK_BLOCK_NO_REFORM, // 0x25
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN1, // 0x26
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN2, // 0x27
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN3, // 0x28
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN4, // 0x29
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN1, // 0x2A
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN2, // 0x2B
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN3, // 0x2C
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN4, // 0x2D
    CLIP_BEHAVIOR_SLOW_CRUMBLE_BLOCK, // 0x2E

    CLIP_BEHAVIOR_HIDDEN_ENERGY_TANK = 52, // 0x34
    CLIP_BEHAVIOR_HIDDEN_MISSILE_TANK, // 0x35
    CLIP_BEHAVIOR_HIDDEN_SUPER_MISSILE_TANK, // 0x36
    CLIP_BEHAVIOR_HIDDEN_POWER_BOMB_TANK, // 0x37
    CLIP_BEHAVIOR_ENERGY_TANK, // 0x38
    CLIP_BEHAVIOR_MISSILE_TANK, // 0x39
    CLIP_BEHAVIOR_SUPER_MISSILE_TANK, // 0x3A
    CLIP_BEHAVIOR_POWER_BOMB_TANK, // 0x3B
    CLIP_BEHAVIOR_UNDERWATER_ENERGY_TANK, // 0x3C
    CLIP_BEHAVIOR_UNDERWATER_MISSILE_TANK, // 0x3D
    CLIP_BEHAVIOR_UNDERWATER_SUPER_MISSILE_TANK, // 0x3E
    CLIP_BEHAVIOR_UNDERWATER_POWER_BOMB_TANK, // 0x3F
    CLIP_BEHAVIOR_WATER, // 0x40
    CLIP_BEHAVIOR_STRONG_LAVA, // 0x41
    CLIP_BEHAVIOR_WEAK_LAVA, // 0x42
    CLIP_BEHAVIOR_ACID, // 0x43
    CLIP_BEHAVIOR_BG0_TRIGGER_OPAQUE, // 0x44
    CLIP_BEHAVIOR_BG0_TRIGGER_TRANSPARENT_LEVEL1, // 0x45
    CLIP_BEHAVIOR_BG0_TRIGGER_TRANSPARENT_LEVEL2, // 0x46
    CLIP_BEHAVIOR_BG0_TRIGGER_TRANSPARENT_LEVEL3, // 0x47
    CLIP_BEHAVIOR_BG0_TRIGGER_TRANSPARENT_LEVEL4, // 0x48
    CLIP_BEHAVIOR_BG0_TRIGGER_TRANSPARENT_LEVEL5, // 0x49
    CLIP_BEHAVIOR_BG0_TRIGGER_TRANSPARENT_FULL, // 0x4A
    CLIP_BEHAVIOR_BG0_TRIGGER_BRIGHTER_LEVEL1, // 0x4B
    CLIP_BEHAVIOR_BG0_TRIGGER_BRIGHTER_LEVEL2, // 0x4C
    CLIP_BEHAVIOR_BG0_TRIGGER_BRIGHTER_LEVEL3, // 0x4D
    CLIP_BEHAVIOR_BG0_TRIGGER_BRIGHTER_LEVEL4, // 0x4E
    CLIP_BEHAVIOR_BG0_TRIGGER_DEFAULT_TRANSPARENCY, // 0x4F
    CLIP_BEHAVIOR_WET_GROUND, // 0x50
    CLIP_BEHAVIOR_DUSTY_GROUND, // 0x51
    CLIP_BEHAVIOR_GROUND_EFFECT_UNUSED, // 0x52
    CLIP_BEHAVIOR_BUBBLY_GROUND, // 0x53
    CLIP_BEHAVIOR_VERY_DUSTY_GROUND, // 0x54
    CLIP_BEHAVIOR_GROUND_EFFECT_UNUSED1, // 0x55
    CLIP_BEHAVIOR_GROUND_EFFECT_UNUSED2, // 0x56
    CLIP_BEHAVIOR_GROUND_EFFECT_UNUSED3, // 0x57

    CLIP_BEHAVIOR_NO_DOOR = 127, // 0x7F
    CLIP_BEHAVIOR_GRAY_DOOR, // 0x80
    CLIP_BEHAVIOR_REGULAR_DOOR, // 0x81
    CLIP_BEHAVIOR_MISSILE_DOOR, // 0x82
    CLIP_BEHAVIOR_SUPER_MISSILE_DOOR, // 0x83
    CLIP_BEHAVIOR_POWER_BOMB_DOOR, // 0x84
};

enum Clipdata {
    CLIPDATA_AIR, // 0x0
    CLIPDATA_PASS_THROUGH_BOTTOM, // 0x1
    CLIPDATA_NON_POWER_GRIP, // 0x2

    CLIPDATA_ENEMY_ONLY = 7, // 0x7

    CLIPDATA_STOP_ENEMY_SOLID = 9, // 0x9

    CLIPDATA_SOLID = 16, // 0x10
    CLIPDATA_RIGHT_STEEP_FLOOR_SLOPE, // 0x11
    CLIPDATA_LEFT_STEEP_FLOOR_SLOPE, // 0x12
    CLIPDATA_RIGHT_LOWER_SLIGHT_FLOOR_SLOPE, // 0x13
    CLIPDATA_RIGHT_UPPER_SLIGHT_FLOOR_SLOPE, // 0x14
    CLIPDATA_LEFT_UPPER_SLIGHT_FLOOR_SLOPE, // 0x15
    CLIPDATA_LEFT_LOWER_SLIGHT_FLOOR_SLOPE, // 0x16
    CLIPDATA_STOP_ENEMY_AIR, // 0x17
    CLIPDATA_SPACE_PIRATE_ZONELINE, // 0x18
    CLIPDATA_SPACE_PIRATE_WALLJUMP_POINT, // 0x19
    CLIPDATA_SOLID_UNUSED, // 0x1A
    CLIPDATA_WATER, // 0x1B
    CLIPDATA_WET_GROUND, // 0x1C
    CLIPDATA_DUSTY_GROUND, // 0x1D
    CLIPDATA_GROUND_EFFECT_UNUSED, // 0x1E

    CLIPDATA_DOOR_TRANSITION = 32, // 0x20
    CLIPDATA_LEFT_STEEP_CEILING_SLOPE, // 0x21
    CLIPDATA_RIGHT_STEEP_CEILING_SLOPE, // 0x22
    CLIPDATA_LEFT_UPPER_SLIGHT_CEILING_SLOPE, // 0x23
    CLIPDATA_LEFT_LOWER_SLIGHT_CEILING_SLOPE, // 0x24
    CLIPDATA_RIGHT_LOWER_SLIGHT_CEILING_SLOPE, // 0x25
    CLIPDATA_RIGHT_UPPER_SLIGHT_CEILING_SLOPE, // 0x26
    CLIPDATA_VERTICAL_UP_TRANSITION, // 0x27
    CLIPDATA_VERTICAL_DOWN_TRANSITION, // 0x28
    CLIPDATA_ELEVATOR_UP, // 0x29
    CLIPDATA_ELEVATOR_DOWN, // 0x2A

    CLIPDATA_BUBBLY_GROUND = 44, // 0x2C
    CLIPDATA_VERY_DUSTY_GROUND, // 0x2D

    CLIPDATA_GRAY_DOOR = 48, // 0x30

    CLIPDATA_REGULAR_DOOR = 54, // 0x36

    CLIPDATA_MISSILE_DOOR = 64, // 0x40

    CLIPDATA_SUPER_MISSILE_DOOR = 70, // 0x46

    CLIPDATA_POWER_BOMB_DOOR = 76, // 0x47

    CLIPDATA_TOP_LEFT_SHOT_BLOCK_NEVER_REFORM = 80, // 0x50
    CLIPDATA_TOP_RIGHT_SHOT_BLOCK_NEVER_REFORM, // 0x51
    CLIPDATA_SHOT_BLOCK_NEVER_REFORM, // 0x52
    CLIPDATA_TOP_LEFT_SHOT_BLOCK_NO_REFORM, // 0x53
    CLIPDATA_TOP_RIGHT_SHOT_BLOCK_NO_REFORM, // 0x54
    CLIPDATA_SHOT_BLOCK_NO_REFORM, // 0x55
    CLIPDATA_CRUMBLE, // 0x56
    CLIPDATA_BOMB_BLOCK_NEVER_REFORM, // 0x57
    CLIPDATA_MISSILE_BLOCK_NEVER_REFORM, // 0x58
    CLIPDATA_SUPER_MISSILE_BLOCK_NEVER_REFORM, // 0x59
    CLIPDATA_SPEEDBOOST_BLOCK_NO_REFORM, // 0x5A
    CLIPDATA_POWER_BOMB_BLOCK_NEVER_REFORM, // 0x5B
    CLIPDATA_ENERGY_TANK, // 0x5C
    CLIPDATA_MISSILE_TANK, // 0x5D
    CLIPDATA_SUPER_MISSILE_TANK, // 0x5E
    CLIPDATA_POWER_BOMB_TANK, // 0x5F
    CLIPDATA_BOTTOM_LEFT_SHOT_BLOCK_NEVER_REFORM, // 0x60
    CLIPDATA_BOTTOM_RIGHT_SHOT_BLOCK_NEVER_REFORM, // 0x61
    CLIPDATA_SHOT_BLOCK_REFORM, // 0x62
    CLIPDATA_BOTTOM_LEFT_SHOT_BLOCK_NO_REFORM, // 0x63
    CLIPDATA_BOTTOM_RIGHT_SHOT_BLOCK_NO_REFORM, // 0x64

    CLIPDATA_SLOW_CRUMBLE = 102, // 0x66
    CLIPDATA_BOMB_BLOCK_REFORM, // 0x67
    CLIPDATA_MISSILE_BLOCK_NO_REFORM, // 0x68
    CLIPDATA_SUPER_MISSILE_BLOCK_NO_REFORM, // 0x69
    CLIPDATA_SPEEDBOOST_BLOCK_REFORM, // 0x6A
    CLIPDATA_SCREW_ATTACK_NO_REFORM, // 0x6B
    CLIPDATA_HIDDEN_ENERGY_TANK, // 0x6C
    CLIPDATA_HIDDEN_MISSILE_TANK, // 0x6D
    CLIPDATA_HIDDEN_SUPER_MISSILE_TANK, // 0x6E
    CLIPDATA_HIDDEN_POWER_BOMB_TANK, // 0x6F
    CLIPDATA_VERTICAL_BOMB_CHAIN1, // 0x70
    CLIPDATA_VERTICAL_BOMB_CHAIN2, // 0x71
    CLIPDATA_VERTICAL_BOMB_CHAIN3, // 0x72
    CLIPDATA_VERTICAL_BOMB_CHAIN4, // 0x73
    CLIPDATA_HORIZONTAL_BOMB_CHAIN1, // 0x74
    CLIPDATA_HORIZONTAL_BOMB_CHAIN2, // 0x75
    CLIPDATA_HORIZONTAL_BOMB_CHAIN3, // 0x76
    CLIPDATA_HORIZONTAL_BOMB_CHAIN4, // 0x77

    CLIPDATA_UNDERWATER_ENERGY_TANK = 124, // 0x7C
    CLIPDATA_UNDERWATER_MISSILE_TANK, // 0x7D
    CLIPDATA_UNDERWATER_SUPER_MISSILE_TANK, // 0x7E
    CLIPDATA_UNDERWATER_POWER_BOMB_TANK, // 0x7F
    CLIPDATA_BG0_TRIGGER_OPAQUE, // 0x80
    CLIPDATA_BG0_TRIGGER_TRANSPARENT_LEVEL1, // 0x81
    CLIPDATA_BG0_TRIGGER_TRANSPARENT_LEVEL2, // 0x82
    CLIPDATA_BG0_TRIGGER_TRANSPARENT_LEVEL3, // 0x83
    CLIPDATA_BG0_TRIGGER_TRANSPARENT_LEVEL4, // 0x84
    CLIPDATA_BG0_TRIGGER_TRANSPARENT_LEVEL5, // 0x85
    CLIPDATA_BG0_TRIGGER_TRANSPARENT_FULL, // 0x86
    CLIPDATA_BG0_TRIGGER_BRIGHTER_LEVEL1, // 0x87
    CLIPDATA_BG0_TRIGGER_BRIGHTER_LEVEL2, // 0x88
    CLIPDATA_BG0_TRIGGER_BRIGHTER_LEVEL3, // 0x89
    CLIPDATA_BG0_TRIGGER_BRIGHTER_LEVEL4, // 0x8A
    CLIPDATA_BG0_TRIGGER_DEFAULT_TRANSPARENCY, // 0x8B

    CLIPDATA_WEAK_LAVA = 160, // 0xA0
    CLIPDATA_STRONG_LAVA, // 0xA1
    CLIPDATA_ACID, // 0xA2

    CLIPDATA_END = 176
};

#define CLIPDATA_TILEMAP_FLAG 0x400

enum ClipdataTilemap {
    CLIPDATA_TILEMAP_AIR, // 0x0
    CLIPDATA_TILEMAP_SOLID, // 0x1
    CLIPDATA_TILEMAP_SOLID_BREAKING_1, // 0x2
    CLIPDATA_TILEMAP_SOLID_BREAKING_2, // 0x3
    CLIPDATA_TILEMAP_SOLID_BREAKING_3, // 0x4
    CLIPDATA_TILEMAP_SHOT_BLOCK_REFORM, // 0x5
    CLIPDATA_TILEMAP_BOMB_BLOCK_REFORM, // 0x6
    CLIPDATA_TILEMAP_POWER_BOMB_NEVER_REFORM, // 0x7
    CLIPDATA_TILEMAP_SPEEDBOOST_NO_REFORM, // 0x8
    CLIPDATA_TILEMAP_SPEEDBOOST_REFORM, // 0x9
    CLIPDATA_TILEMAP_SCREW_ATTACK_NO_REFORM, // 0xA
    CLIPDATA_TILEMAP_CRUMBLE, // 0xB
    CLIPDATA_TILEMAP_MISSILE_NEVER_REFORM, // 0xC
    CLIPDATA_TILEMAP_MISSILE_NO_REFORM, // 0xD
    CLIPDATA_TILEMAP_SUPER_MISSILE_NEVER_REFORM, // 0xE
    CLIPDATA_TILEMAP_SUPER_MISSILE_NO_REFORM, // 0xF

    CLIPDATA_TILEMAP_CLOSED_DOOR_TOP_LEFT = 26, // 0x1A
    CLIPDATA_TILEMAP_CLOSED_DOOR_TOP_RIGHT, // 0x1B
    CLIPDATA_TILEMAP_ENERGY_TANK, // 0x1C
    CLIPDATA_TILEMAP_MISSILE_TANK, // 0x1D
    CLIPDATA_TILEMAP_SUPER_MISSILE_TANK, // 0x1E
    CLIPDATA_TILEMAP_POWER_BOMB_TANK, // 0x1F

    CLIPDATA_TILEMAP_CLOSED_DOOR_MIDDLE_TOP_LEFT = 42, // 0x2A
    CLIPDATA_TILEMAP_CLOSED_DOOR_MIDDLE_TOP_RIGHT, // 0x2B
    CLIPDATA_TILEMAP_UNDERWATER_ENERGY_TANK, // 0x2C
    CLIPDATA_TILEMAP_UNDERWATER_MISSILE_TANK, // 0x2D
    CLIPDATA_TILEMAP_UNDERWATER_SUPER_MISSILE_TANK, // 0x2E
    CLIPDATA_TILEMAP_UNDERWATER_POWER_BOMB_TANK, // 0x2F

    CLIPDATA_TILEMAP_CLOSED_DOOR_MIDDLE_BOTTOM_LEFT = 58, // 0x3A
    CLIPDATA_TILEMAP_CLOSED_DOOR_MIDDLE_BOTTOM_RIGHT, // 0x3B
    CLIPDATA_TILEMAP_WATER, // 0x3C
    CLIPDATA_TILEMAP_STOP_ENEMY_AIR, // 0x3D
    CLIPDATA_TILEMAP_SOLID2, // 0x3E
    CLIPDATA_TILEMAP_NON_POWER_GRIP, // 0x3F

    CLIPDATA_TILEMAP_CLOSED_DOOR_BOTTOM_LEFT = 74, // 0x4A
    CLIPDATA_TILEMAP_CLOSED_DOOR_BOTTOM_RIGHT, // 0x4B

    CLIPDATA_TILEMAP_VERTICAL_BOMB_CHAIN1 = 92, // 0x5C
    CLIPDATA_TILEMAP_VERTICAL_BOMB_CHAIN2, // 0x5D
    CLIPDATA_TILEMAP_VERTICAL_BOMB_CHAIN3, // 0x5E
    CLIPDATA_TILEMAP_VERTICAL_BOMB_CHAIN4, // 0x5F
// Missing ones
    CLIPDATA_TILEMAP_HORIZONTAL_BOMB_CHAIN1 = 108, // 0x6C
    CLIPDATA_TILEMAP_HORIZONTAL_BOMB_CHAIN2, // 0x6D
    CLIPDATA_TILEMAP_HORIZONTAL_BOMB_CHAIN3, // 0x6E
    CLIPDATA_TILEMAP_HORIZONTAL_BOMB_CHAIN4, // 0x6F
// Missing ones
    CLIPDATA_TILEMAP_BOMB_NEVER_REFORM = 124, // 0x7C
    CLIPDATA_TILEMAP_SLOW_CRUMBLE, // 0x7D

    CLIPDATA_TILEMAP_GRAY_DOOR_TOP_LEFT = 144, // 0x90
    CLIPDATA_TILEMAP_GRAY_DOOR_TOP_RIGHT, // 0x91
    CLIPDATA_TILEMAP_REGULAR_DOOR_TOP_LEFT, // 0x92
    CLIPDATA_TILEMAP_REGULAR_DOOR_TOP_RIGHT, // 0x93
    CLIPDATA_TILEMAP_MISSILE_DOOR_TOP_LEFT, // 0x94
    CLIPDATA_TILEMAP_MISSILE_DOOR_TOP_RIGHT, // 0x95
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_TOP_LEFT, // 0x96
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_TOP_RIGHT, // 0x97
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_TOP_LEFT, // 0x98
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_TOP_RIGHT, // 0x99
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_TOP_LEFT, // 0x9A
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_TOP_RIGHT, // 0x9B

    CLIPDATA_TILEMAP_GRAY_DOOR_MIDDLE_TOP_LEFT = 160, // 0xA0
    CLIPDATA_TILEMAP_GRAY_DOOR_MIDDLE_TOP_RIGHT, // 0xA1
    CLIPDATA_TILEMAP_REGULAR_DOOR_MIDDLE_TOP_LEFT, // 0xA2
    CLIPDATA_TILEMAP_REGULAR_DOOR_MIDDLE_TOP_RIGHT, // 0xA3
    CLIPDATA_TILEMAP_MISSILE_DOOR_MIDDLE_TOP_LEFT, // 0xA4
    CLIPDATA_TILEMAP_MISSILE_DOOR_MIDDLE_TOP_RIGHT, // 0xA5
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_MIDDLE_TOP_LEFT, // 0xA6
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_MIDDLE_TOP_RIGHT, // 0xA7
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_MIDDLE_TOP_LEFT, // 0xA8
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_MIDDLE_TOP_RIGHT, // 0xA9
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_MIDDLE_TOP_LEFT, // 0xAA
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_MIDDLE_TOP_RIGHT, // 0xAB

    CLIPDATA_TILEMAP_GRAY_DOOR_MIDDLE_BOTTOM_LEFT = 176, // 0xB0
    CLIPDATA_TILEMAP_GRAY_DOOR_MIDDLE_BOTTOM_RIGHT, // 0xB1
    CLIPDATA_TILEMAP_REGULAR_DOOR_MIDDLE_BOTTOM_LEFT, // 0xB2
    CLIPDATA_TILEMAP_REGULAR_DOOR_MIDDLE_BOTTOM_RIGHT, // 0xB3
    CLIPDATA_TILEMAP_MISSILE_DOOR_MIDDLE_BOTTOM_LEFT, // 0xB4
    CLIPDATA_TILEMAP_MISSILE_DOOR_MIDDLE_BOTTOM_RIGHT, // 0xB5
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_MIDDLE_BOTTOM_LEFT, // 0xB6
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_MIDDLE_BOTTOM_RIGHT, // 0xB7
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_MIDDLE_BOTTOM_LEFT, // 0xB8
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_MIDDLE_BOTTOM_RIGHT, // 0xB9
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_MIDDLE_BOTTOM_LEFT, // 0xBA
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_MIDDLE_BOTTOM_RIGHT, // 0xBB

    CLIPDATA_TILEMAP_GRAY_DOOR_BOTTOM_LEFT = 192, // 0xC0
    CLIPDATA_TILEMAP_GRAY_DOOR_BOTTOM_RIGHT, // 0xC1
    CLIPDATA_TILEMAP_REGULAR_DOOR_BOTTOM_LEFT, // 0xC2
    CLIPDATA_TILEMAP_REGULAR_DOOR_BOTTOM_RIGHT, // 0xC3
    CLIPDATA_TILEMAP_MISSILE_DOOR_BOTTOM_LEFT, // 0xC4
    CLIPDATA_TILEMAP_MISSILE_DOOR_BOTTOM_RIGHT, // 0xC5
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_BOTTOM_LEFT, // 0xC6
    CLIPDATA_TILEMAP_SUPER_MISSILE_DOOR_BOTTOM_RIGHT, // 0xC7
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_BOTTOM_LEFT, // 0xC8
    CLIPDATA_TILEMAP_POWER_BOMB_DOOR_BOTTOM_RIGHT, // 0xC9
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_BOTTOM_LEFT, // 0xCA
    CLIPDATA_TILEMAP_NO_HATCH_DOOR_BOTTOM_RIGHT, // 0xCB

    CLIPDATA_TILEMAP_END = 208
};

enum ClipdataDebug {
    CLIPDATA_DEBUG_AIR, // 0x0
    CLIPDATA_DEBUG_SOLID, // 0x1
    CLIPDATA_DEBUG_WATER, // 0x2
    CLIPDATA_DEBUG_DOOR_TRANSITION, // 0x3
    CLIPDATA_DEBUG_NON_POWER_GRIP, // 0x4

    CLIPDATA_DEBUG_RIGHT_STEEP_FLOOR_SLOPE = 16, // 0x10
    CLIPDATA_DEBUG_LEFT_STEEP_FLOOR_SLOPE, // 0x11
    CLIPDATA_DEBUG_RIGHT_LOWER_SLIGHT_FLOOR_SLOPE, // 0x12
    CLIPDATA_DEBUG_RIGHT_UPPER_SLIGHT_FLOOR_SLOPE, // 0x13
    CLIPDATA_DEBUG_LEFT_UPPER_SLIGHT_FLOOR_SLOPE, // 0x14
    CLIPDATA_DEBUG_LEFT_LOWER_SLIGHT_FLOOR_SLOPE, // 0x15
    CLIPDATA_DEBUG_STOP_ENEMY, // 0x16
    CLIPDATA_DEBUG_STOP_ENEMY_SOLID, // 0x17
    CLIPDATA_DEBUG_SPACE_PIRATE_ZONELINE, // 0x18
    CLIPDATA_DEBUG_SPACE_PIRATE_WALLJUMP_POINT, // 0x19

    CLIPDATA_DEBUG_GRAY_DOOR = 48, // 0x30
    CLIPDATA_DEBUG_REGULAR_DOOR, // 0x31
    CLIPDATA_DEBUG_MISSILE_DOOR, // 0x32
    CLIPDATA_DEBUG_SUPER_MISSILE_DOOR, // 0x33
    CLIPDATA_DEBUG_POWER_BOMB_DOOR, // 0x34

    CLIPDATA_DEBUG_TOP_LEFT_SHOT_BLOCK_NEVER_REFORM = 64, // 0x40
    CLIPDATA_DEBUG_TOP_RIGHT_SHOT_BLOCK_NEVER_REFORM, // 0x41
    CLIPDATA_DEBUG_SHOT_BLOCK_NEVER_REFORM, // 0x42
    CLIPDATA_DEBUG_BOMB_BLOCK_NEVER_REFORM, // 0x43
    CLIPDATA_DEBUG_MISSILE_BLOCK_NEVER_REFORM, // 0x44
    CLIPDATA_DEBUG_SUPER_MISSILE_BLOCK_NEVER_REFORM, // 0x45
    CLIPDATA_DEBUG_SPEEDBOOST_BLOCK_NO_REFORM, // 0x46

    CLIPDATA_DEBUG_BOTTOM_LEFT_SHOT_BLOCK_NEVER_REFORM = 80, // 0x50
    CLIPDATA_DEBUG_BOTTOM_RIGHT_SHOT_BLOCK_NEVER_REFORM, // 0x51
    CLIPDATA_DEBUG_SHOT_BLOCK_REFORM, // 0x52
    CLIPDATA_DEBUG_BOMB_BLOCK_REFORM, // 0x53
    CLIPDATA_DEBUG_MISSILE_NO_REFORM, // 0x54
    CLIPDATA_DEBUG_SUPER_MISSILE_NO_REFORM, // 0x55
    CLIPDATA_DEBUG_SPEEDBOOSTER_REFORM, // 0x56
    CLIPDATA_DEBUG_SCREW_ATTACK_NO_REFORM, // 0x57
    CLIPDATA_DEBUG_CRUMBLE_BLOCK, // 0x58
    CLIPDATA_DEBUG_POWER_BOMB_NEVER_REFORM, // 0x59
    CLIPDATA_DEBUG_SLOW_CRUMBLE_BLOCK, // 0x5A

    CLIPDATA_DEBUG_TOP_LEFT_SHOT_BLOCK_NO_REFORM = 96, // 0x60
    CLIPDATA_DEBUG_TOP_RIGHT_SHOT_BLOCK_NO_REFORM, // 0x61
    CLIPDATA_DEBUG_SHOT_BLOCK_NO_REFORM, // 0x62
    CLIPDATA_DEBUG_HIDDEN_MISSILE_TANK, // 0x63
    CLIPDATA_DEBUG_HIDDEN_ENERGY_TANK, // 0x64
    CLIPDATA_DEBUG_HIDDEN_POWER_BOMB_TANK, // 0x65
    CLIPDATA_DEBUG_HIDDEN_SUPER_MISSILE_TANK, // 0x66

    CLIPDATA_DEBUG_BOTTOM_LEFT_SHOT_BLOCK_NO_REFORM = 112, // 0x70
    CLIPDATA_DEBUG_BOTTOM_RIGHT_SHOT_BLOCK_NO_REFORM, // 0x71

    CLIPDATA_DEBUG_MISSILE_TANK = 115, // 0x73
    CLIPDATA_DEBUG_ENERGY_TANK, // 0x74
    CLIPDATA_DEBUG_POWER_BOMB_TANK, // 0x75
    CLIPDATA_DEBUG_SUPER_MISSILE_TANK, // 0x76

    CLIPDATA_DEBUG_VERTICAL_BOMB_CHAIN1 = 120, // 0x78
    CLIPDATA_DEBUG_VERTICAL_BOMB_CHAIN2, // 0x79
    CLIPDATA_DEBUG_VERTICAL_BOMB_CHAIN3, // 0x7A
    CLIPDATA_DEBUG_VERTICAL_BOMB_CHAIN4, // 0x7B
    CLIPDATA_DEBUG_HORIZONTAL_BOMB_CHAIN1, // 0x7C
    CLIPDATA_DEBUG_HORIZONTAL_BOMB_CHAIN2, // 0x7D
    CLIPDATA_DEBUG_HORIZONTAL_BOMB_CHAIN3, // 0x7E
    CLIPDATA_DEBUG_HORIZONTAL_BOMB_CHAIN4, // 0x7F

    CLIPDATA_DEBUG_UNDERWATER_MISSILE_TANK = 131, // 0x83
    CLIPDATA_DEBUG_UNDERWATER_ENERGY_TANK, // 0x84
    CLIPDATA_DEBUG_UNDERWATER_POWER_BOMB_TANK, // 0x85
    CLIPDATA_DEBUG_UNDERWATER_SUPER_MISSILE_TANK, // 0x86

    CLIPDATA_DEBUG_BG0_TRIGGER_OPAQUE = 136, // 0x88
    CLIPDATA_DEBUG_BG0_TRIGGER_TRANSPARENT_LEVEL1, // 0x89
    CLIPDATA_DEBUG_BG0_TRIGGER_TRANSPARENT_LEVEL2, // 0x8A
    CLIPDATA_DEBUG_BG0_TRIGGER_TRANSPARENT_LEVEL3, // 0x8B
    CLIPDATA_DEBUG_BG0_TRIGGER_TRANSPARENT_LEVEL4, // 0x8C
    CLIPDATA_DEBUG_BG0_TRIGGER_TRANSPARENT_LEVEL5, // 0x8D
    CLIPDATA_DEBUG_BG0_TRIGGER_TRANSPARENT_FULL, // 0x8E
    CLIPDATA_DEBUG_BG0_TRIGGER_DEFAUL_TRANSPARENCY, // 0x8F

    CLIPDATA_DEBUG_BG0_TRIGGER_BRIGHTER1 = 152, // 0x98
    CLIPDATA_DEBUG_BG0_TRIGGER_BRIGHTER2, // 0x99
    CLIPDATA_DEBUG_BG0_TRIGGER_BRIGHTER3, // 0x9A
    CLIPDATA_DEBUG_BG0_TRIGGER_BRIGHTER4, // 0x9B

    CLIPDATA_DEBUG_END = 160
};

#endif
