#ifndef COLOR_FADING_CONSTANTS_H
#define COLOR_FADING_CONSTANTS_H

#define EFFECT_CUTSCENE_ESCAPING_CHOZODIA 1
#define EFFECT_CUTSCENE_ESCAPE_FAILED 2
#define EFFECT_CUTSCENE_EXITING_ZEBES 3
#define EFFECT_CUTSCENE_GETTING_FULLY_POWERED 4
#define EFFECT_CUTSCENE_RIDLEY_SPAWN 5
#define EFFECT_CUTSCENE_STATUE_OPENING 6
#define EFFECT_CUTSCENE_INTRO_TEXT 7
#define EFFECT_CUTSCENE_SAMUS_IN_BLUE_SHIP 8

enum ColorFadingEffect {
    COLOR_FADING_FLASH = 1,
    COLOR_FADING_CANCEL,
    COLOR_FADING_WHITE,
    COLOR_FADING_DOOR_TRANSITION,
    COLOR_FADING_FLASH2,
    COLOR_FADING_NO_TRANSITION,
    COLOR_FADING_FLASH_NO_TRANSITION,
    COLOR_FADING_NO_TRANSITION_HUD_HIDE,
    COLOR_FADING_SLOW_WHITE,
    COLOR_FADING_SLOW_BLACK,
    COLOR_FADING_AFTER_ENTER_MOTHER_SHIP,
    COLOR_FADING_ESCAPE_FAILED,
    COLOR_FADING_DEMO_ENDING_AUTO,
    COLOR_FADING_DEMO_ENDING_WITH_INPUT,
    COLOR_FADING_CHOZODIA_ESCAPE,
    COLOR_FADING_TOURIAN_ESCAPE,
    COLOR_FADING_GETTING_FULLY_POWERED,
    COLOR_FADING_RIDLEY_SPAWN,
    COLOR_FADING_STATUE_CUTSCENE,
    COLOR_FADING_INTRO_TEXT,
    COLOR_FADING_LANDING_SHIP,
    COLOR_FADING_SAMUS_IN_BLUE_SHIP,
    COLOR_FADING_TO_WHITE,
    COLOR_FADING_TO_BLACK,

    COLOR_FADING_END
};

#define MONOCHROME_FADING_BLACK 1
#define MONOCHROME_FADING_WHITE 2

#define COLOR_FADING_STATUS_ON_BG 1
#define COLOR_FADING_STATUS_ON_OBJ 2

#define COLOR_FADING_STAGE_STARTED 0
#define COLOR_FADING_STAGE_IN_PROGRESS 1
#define COLOR_FADING_STAGE_FINISHED 2
#define COLOR_FADING_STAGE_AFTER_FINISHED 3

#endif
