#define EFFECT_CUTSCENE_ESCAPING_CHOZODIA 1
#define EFFECT_CUTSCENE_ESCAPE_FAILED 2
#define EFFECT_CUTSCENE_EXITING_ZEBES 3
#define EFFECT_CUTSCENE_GETTING_FULLY_POWERED 4
#define EFFECT_CUTSCENE_RIDLEY_SPAWN 5
#define EFFECT_CUTSCENE_STATUE_OPENING 6
#define EFFECT_CUTSCENE_INTRO_TEXT 7
#define EFFECT_CUTSCENE_SAMUS_IN_BLUE_SHIP 8

#define COLOR_FADING_FLASH 1
#define COLOR_FADING_CANCEL 2
#define COLOR_FADING_WHITE 3
#define COLOR_FADING_DOOR_TRANSITION 4
#define COLOR_FADING_FLASH2 5
#define COLOR_FADING_NO_TRANSITION 6
#define COLOR_FADING_FLASH_NO_TRANSITION 7
#define COLOR_FADING_NO_TRANSITION_HUD_HIDE 8
#define COLOR_FADING_SLOW_WHITE 9
#define COLOR_FADING_SLOW_BLACK 10
#define COLOR_FADING_AFTER_ENTER_MOTHER_SHIP 11
#define COLOR_FADING_ESCAPE_FAILED 12
#define COLOR_FADING_DEMO_ENDING_AUTO 13
#define COLOR_FADING_DEMO_ENDING_WITH_INPUT 14
#define COLOR_FADING_CHOZODIA_ESCAPE 15
#define COLOR_FADING_TOURIAN_ESCAPE 16
#define COLOR_FADING_GETTING_FULLY_POWERED 17
#define COLOR_FADING_RIDLEY_SPAWN 18
#define COLOR_FADING_STATUE_CUTSCENE 19
#define COLOR_FADING_INTRO_TEXT 20
#define COLOR_FADING_LANDING_SHIP 21
#define COLOR_FADING_SAMUS_IN_BLUE_SHIP 22
#define COLOR_FADING_TO_WHITE 23
#define COLOR_FADING_TO_BLACK 24

#define MONOCHROME_FADING_BLACK 1
#define MONOCHROME_FADING_WHITE 2

#define COLOR_FADING_STATUS_ON_BG 1
#define COLOR_FADING_STATUS_ON_OBJ 2

#define COLOR_FADING_STAGE_STARTED 0
#define COLOR_FADING_STAGE_IN_PROGRESS 1
#define COLOR_FADING_STAGE_FINISHED 2
#define COLOR_FADING_STAGE_AFTER_FINISHED 3
