#define CUTSCENE_DATA sNonGameplayRamPointer->cutscene

#define CUTSCENE_NONE 0
#define CUTSCENE_INTRO_TEXT 1
#define CUTSCENE_MOTHERSHIP_MONOLOGUE 2
#define CUTSCENE_COULD_I_SURVIVE 3
#define CUTSCENE_MOTHER_BRAIN_CLOSE_UP 4
#define CUTSCENE_KRAID_RISING 5
#define CUTSCENE_STATUE_OPENING 6
#define CUTSCENE_RIDLEY_IN_SPACE 7
#define CUTSCENE_RIDLEY_LANDING 8
#define CUTSCENE_RIDLEY_SPAWNING 9
#define CUTSCENE_ENTER_TOURIAN 10
#define CUTSCENE_BEFORE_CHARLIE 11
#define CUTSCENE_GETTING_FULLY_POWERED 12
#define CUTSCENE_MECHA_RIDLEY_SEES_SAMUS 13
#define CUTSCENE_SAMUS_IN_BLUE_SHIP 14

#define CUTSCENE_BG_EDIT_HOFS 1
#define CUTSCENE_BG_EDIT_VOFS 2

#define CUTSCENE_SPECIAL_EFFECT_STATUS_ON_SPRITE 1
#define CUTSCENE_SPECIAL_EFFECT_STATUS_SPRITE_ENDED 2
#define CUTSCENE_SPECIAL_EFFECT_STATUS_ON_BG 4
#define CUTSCENE_SPECIAL_EFFECT_STATUS_BG_ENDED 8
