#ifndef CUTSCENE_CONSTANTS_H
#define CUTSCENE_CONSTANTS_H

#define CUTSCENE_DATA sNonGameplayRamPointer->cutscene

enum Cutscene {
    CUTSCENE_NONE,
    CUTSCENE_INTRO_TEXT,
    CUTSCENE_MOTHERSHIP_MONOLOGUE,
    CUTSCENE_COULD_I_SURVIVE,
    CUTSCENE_MOTHER_BRAIN_CLOSE_UP,
    CUTSCENE_KRAID_RISING,
    CUTSCENE_STATUE_OPENING,
    CUTSCENE_RIDLEY_IN_SPACE,
    CUTSCENE_RIDLEY_LANDING,
    CUTSCENE_RIDLEY_SPAWNING,
    CUTSCENE_ENTER_TOURIAN,
    CUTSCENE_BEFORE_CHARLIE,
    CUTSCENE_GETTING_FULLY_POWERED,
    CUTSCENE_MECHA_RIDLEY_SEES_SAMUS,
    CUTSCENE_SAMUS_IN_BLUE_SHIP,

    CUTSCENE_END
};

enum CutsceneStage {
    CUTSCENE_STAGE_STARTING,
    CUTSCENE_STAGE_FADING_IN,
    CUTSCENE_STAGE_INIT,
    CUTSCENE_STAGE_ONGOING,
    CUTSCENE_STAGE_ENDING,
};

enum CutsceneType {
    CUTSCENE_TYPE_NON_GAMEPLAY,
    CUTSCENE_TYPE_BETWEEN_GAMEPLAY,
    CUTSCENE_TYPE_IN_GAMEPLAY,

    CUTSCENE_TYPE_END
};

#define CUTSCENE_BG_EDIT_HOFS (1 << 0)
#define CUTSCENE_BG_EDIT_VOFS (1 << 1)

#define CUTSCENE_SPECIAL_EFFECT_STATUS_ON_SPRITE    (1 << 0)
#define CUTSCENE_SPECIAL_EFFECT_STATUS_SPRITE_ENDED (1 << 1)
#define CUTSCENE_SPECIAL_EFFECT_STATUS_ON_BG        (1 << 2)
#define CUTSCENE_SPECIAL_EFFECT_STATUS_BG_ENDED     (1 << 3)

#endif /* CUTSCENE_CONSTANTS_H */
