#define ENDING_FLAG_NEW_TIME_ATTACK_RECORD 0x1
#define ENDING_FLAG_UNKNOWN 0x10
#define ENDING_FLAG_FIRST_TIME_ATTACK_CLEAR 0x20
#define ENDING_FLAG_FIRST_HARD_MODE_CLEAR 0x40
#define ENDING_FLAG_FIRST_CLEAR 0x80

#define ENDING_IMAGE_OAM_SET_CLEAR_TIME 0
#define ENDING_IMAGE_OAM_SET_YOUR_RATE 1
#define ENDING_IMAGE_OAM_SET_COLLECTING 2

#define ENDING_IMAGE_LINE_CLEAR_TIME 0
#define ENDING_IMAGE_LINE_TIMER 1
#define ENDING_IMAGE_LINE_YOUR_RATE 2
#define ENDING_IMAGE_LINE_COLLECTING 3
#define ENDING_IMAGE_LINE_PERCENTAGE 4
#define ENDING_IMAGE_LINE_NEXT_MISSION 5

#define CREDIT_LINE_TYPE_BLUE 0
#define CREDIT_LINE_TYPE_RED 1
#define CREDIT_LINE_TYPE_WHITE_BIG 2
#define CREDIT_LINE_TYPE_WHITE_SMALL 3
#define CREDIT_LINE_TYPE_UNK_5 5
#define CREDIT_LINE_TYPE_END 6
#define CREDIT_LINE_TYPE_ALL_RIGHTS 10
#define CREDIT_LINE_TYPE_THE_COPYRIGHT 11
#define CREDIT_LINE_TYPE_SCENARIO 12
#define CREDIT_LINE_TYPE_RESERVED 13

#define NUMBER_OF_ENDING_IMAGES 8

#define ENDING_OAM_TYPE_NONE 0
#define ENDING_OAM_TYPE_CHAR 1
#define ENDING_OAM_TYPE_LINE 2
