#ifndef ESCAPE_CONSTANTS_H
#define ESCAPE_CONSTANTS_H

enum Escape {
    ESCAPE_NONE,
    ESCAPE_MOTHER_BRAIN,
    ESCAPE_MECHA_RIDLEY,
};

enum EscapeStatus {
    ESCAPE_STATUS_NONE,
    ESCAPE_STATUS_HAPPENNING,
    ESCAPE_STATUS_FAILED
};

#endif /* ESCAPE_CONSTANTS_H */
