#define PAUSE_SCREEN_NONE 0
#define PAUSE_SCREEN_UNKNOWN_1 1
#define PAUSE_SCREEN_PAUSE_OR_CUTSCENE 2
#define PAUSE_SCREEN_UNKNOWN_3 3
#define PAUSE_SCREEN_CHOZO_HINT 4
#define PAUSE_SCREEN_MAP_DOWNLOAD 5
#define PAUSE_SCREEN_ITEM_ACQUISITION 6
#define PAUSE_SCREEN_SUITLESS_ITEMS 7
#define PAUSE_SCREEN_FULLY_POWERED_SUIT_ITEMS 8
#define PAUSE_SCREEN_UNKNOWN_9 9

#define MAX_AMOUNT_OF_DIFFICULTIES 3

#define DIFF_EASY 0
#define DIFF_NORMAL 1
#define DIFF_HARD 2

#define LANGUAGE_JAPANESE 0
#define LANGUAGE_HIRAGANA 1
#define LANGUAGE_ENGLISH 2
#define LANGUAGE_GERMAN 3
#define LANGUAGE_FRENCH 4
#define LANGUAGE_ITALIAN 5
#define LANGUAGE_SPANISH 6

#define MAX_AMOUNT_OF_LANGUAGES 7


#define GM_SOFTRESET 0
#define GM_INTRO 1
#define GM_TITLE 2
#define GM_FILESELECT 3
#define GM_INGAME 4
#define GM_MAP_SCREEN 5
#define GM_GAMEOVER 6
#define GM_CHOZODIA_ESCAPE 7
#define GM_CREDITS 8
#define GM_TOURIAN_ESCAPE 9
#define GM_CUTSCENE 10
#define GM_DEMO 11
#define GM_GALLERY 12
#define GM_FUSION_GALLERY 13
#define GM_START_SOFTRESET 14
#define GM_ERASE_SRAM 15
#define GM_DEBUG_MENU 16

// For in game

#define SUB_GAME_MODE_DOOR_TRANSITION 0x1
#define SUB_GAME_MODE_PLAYING 0x2
#define SUB_GAME_MODE_LOADING_ROOM 0x3
#define SUB_GAME_MODE_FREE_MOVEMENT 0x6
