enum GameOverCursorAction {
    SAMUS_CURSOR_ACTION_LOADING,
    SAMUS_CURSOR_ACTION_MOVING,
    SAMUS_CURSOR_ACTION_SELECTING,

    SAMUS_CURSOR_ACTION_END
};

#define GAME_OVER_OAM_ID_SUIT_MOVING 1
#define GAME_OVER_OAM_ID_SUIT_LOADING 2
#define GAME_OVER_OAM_ID_SUIT_SELECTING 4
#define GAME_OVER_OAM_ID_SUITLESS_MOVING 5
#define GAME_OVER_OAM_ID_SUITLESS_LOADING 6
#define GAME_OVER_OAM_ID_SUITLESS_SELECTING 8
