#ifndef GAME_STATE_CONSTANTS_H
#define GAME_STATE_CONSTANTS_H

#define PAUSE_SCREEN_NONE 0
#define PAUSE_SCREEN_UNKNOWN_1 1
#define PAUSE_SCREEN_PAUSE_OR_CUTSCENE 2
#define PAUSE_SCREEN_UNKNOWN_3 3
#define PAUSE_SCREEN_CHOZO_HINT 4
#define PAUSE_SCREEN_MAP_DOWNLOAD 5
#define PAUSE_SCREEN_ITEM_ACQUISITION 6
#define PAUSE_SCREEN_SUITLESS_ITEMS 7
#define PAUSE_SCREEN_FULLY_POWERED_SUIT_ITEMS 8
#define PAUSE_SCREEN_UNKNOWN_9 9

#define MAX_AMOUNT_OF_DIFFICULTIES 3

#define DIFF_EASY 0
#define DIFF_NORMAL 1
#define DIFF_HARD 2

enum Language {
    LANGUAGE_JAPANESE,
    LANGUAGE_HIRAGANA,
    LANGUAGE_ENGLISH,
    LANGUAGE_GERMAN,
    LANGUAGE_FRENCH,
    LANGUAGE_ITALIAN,
    LANGUAGE_SPANISH,

    LANGUAGE_END
};



#define GM_SOFTRESET 0
#define GM_INTRO 1
#define GM_TITLE 2
#define GM_FILESELECT 3
#define GM_INGAME 4
#define GM_MAP_SCREEN 5
#define GM_GAMEOVER 6
#define GM_CHOZODIA_ESCAPE 7
#define GM_CREDITS 8
#define GM_TOURIAN_ESCAPE 9
#define GM_CUTSCENE 10
#define GM_DEMO 11
#define GM_GALLERY 12
#define GM_FUSION_GALLERY 13
#define GM_START_SOFTRESET 14
#define GM_ERASE_SRAM 15
#define GM_DEBUG_MENU 16

// For in game

#define SUB_GAME_MODE_DOOR_TRANSITION 0x1
#define SUB_GAME_MODE_PLAYING 0x2
#define SUB_GAME_MODE_LOADING_ROOM 0x3
#define SUB_GAME_MODE_DYING 0x5
#define SUB_GAME_MODE_FREE_MOVEMENT 0x6

#endif /* GAME_STATE_CONSTANTS_H */
