#ifndef GAME_OVER_CONSTANTS_H
#define GAME_OVER_CONSTANTS_H

enum GameOverCursorAction {
    SAMUS_CURSOR_ACTION_LOADING,
    SAMUS_CURSOR_ACTION_MOVING,
    SAMUS_CURSOR_ACTION_SELECTING,

    SAMUS_CURSOR_ACTION_END
};

enum GameOverOamId {
    GAME_OVER_OAM_ID_SUIT_MOVING = 1,
    GAME_OVER_OAM_ID_SUIT_LOADING,

    GAME_OVER_OAM_ID_SUIT_SELECTING = 4,
    GAME_OVER_OAM_ID_SUITLESS_MOVING,
    GAME_OVER_OAM_ID_SUITLESS_LOADING,

    GAME_OVER_OAM_ID_SUITLESS_SELECTING = 8,

    GAME_OVER_OAM_ID_END
};

#endif
