#define HAZE_FLAG_ENABLED_FLAG 0x1
#define HAZE_FLAG_NO_ACTIVE_FLAG 0x7F
#define HAZE_FLAG_ACTIVE_FLAG 0x80

#define HAZE_VALUE_NONE 0
#define HAZE_VALUE_GRADIENT 1
#define HAZE_VALUE_BG3 2
#define HAZE_VALUE_BG3_STRONG_WEAK 3 
#define HAZE_VALUE_BG3_NONE_WEAK 4
#define HAZE_VALUE_BG3_BG2_STRONG_WEAK_MEDIUM 5
#define HAZE_VALUE_BG3_BG2_BG1 6
#define HAZE_VALUE_POWER_BOMB_EXPANDING 7
#define HAZE_VALUE_POWER_BOMB_RETRACTING 8
#define HAZE_VALUE_AFTER_POWER_BOMB 9
#define HAZE_VALUE_COLD 10
