#ifndef HAZE_CONSTANTS_H
#define HAZE_CONSTANTS_H

// Flags unused?
#define HAZE_FLAG_ENABLED_FLAG 0x1
#define HAZE_FLAG_NO_ACTIVE_FLAG 0x7F
#define HAZE_FLAG_ACTIVE_FLAG 0x80

enum HazeValue {
    HAZE_VALUE_NONE,
    HAZE_VALUE_GRADIENT,
    HAZE_VALUE_BG3,
    HAZE_VALUE_BG3_STRONG_WEAK, 
    HAZE_VALUE_BG3_NONE_WEAK,
    HAZE_VALUE_BG3_BG2_STRONG_WEAK_MEDIUM,
    HAZE_VALUE_BG3_BG2_BG1,
    HAZE_VALUE_POWER_BOMB_EXPANDING,
    HAZE_VALUE_POWER_BOMB_RETRACTING,
    HAZE_VALUE_AFTER_POWER_BOMB,
    HAZE_VALUE_COLD,
};

#endif
