#define IGC_CLOSE_UP 4
#define IGC_LONG_BEAM_HINT 7
#define IGC_GETTING_VARIA 9
#define IGC_GETTING_FULLY_POWERED 10

#define IGC_STARTED_FLAG 0x80
#define IGC_NO_STARTED_FLAG 0x7F

enum BackgroundFlash {
    BG_FLASH_SLIGHT_YELLOW,
    BG_FLASH_CHOZO_LONG_TRANSPARENCY,
    BG_FLASH_HEAVY_YELLOW,
    BG_FLASH_QUICK_YELLOW,

    BG_FLASH_END
};
