#define INTRO_TEXT_ACTION_NONE 0
#define INTRO_TEXT_ACTION_START 1
#define INTRO_TEXT_ACTION_SPACE 2
#define INTRO_TEXT_ACTION_UNKNOWN 3
#define INTRO_TEXT_ACTION_NEW_LINE 4
#define INTRO_TEXT_ACTION_END 5