#define MINIMAP_UPDATE_FLAG_NONE 0x0
#define MINIMAP_UPDATE_FLAG_UPPER_LINE 0x1
#define MINIMAP_UPDATE_FLAG_MIDDLE_LINE 0x2
#define MINIMAP_UPDATE_FLAG_LOWER_LINE 0x3

#define MINIMAP_TILE_BACKGROUND 0x140
