#ifndef PARTICLE_CONSTANTS_H
#define PARTICLE_CONSTANTS_H

enum ParticleEffectId {
    PE_SPRITE_SPLASH_WATER_SMALL,
    PE_SPRITE_SPLASH_WATER_BIG,
    PE_SPRITE_SPLASH_WATER_HUGE,
    PE_SPRITE_SPLASH_LAVA_SMALL,
    PE_SPRITE_SPLASH_LAVA_BIG,
    PE_SPRITE_SPLASH_LAVA_HUGE,
    PE_SPRITE_SPLASH_ACID_SMALL,
    PE_SPRITE_SPLASH_ACID_BIG,
    PE_SPRITE_SPLASH_ACID_HUGE,
    PE_SHOOTING_BEAM_LEFT,
    PE_SHOOTING_BEAM_DIAG_UP_LEFT,
    PE_SHOOTING_BEAM_DIAG_DOWN_LEFT,
    PE_SHOOTING_BEAM_UP_LEFT,
    PE_SHOOTING_BEAM_DOWN_LEFT,
    PE_SHOOTING_BEAM_RIGHT,
    PE_SHOOTING_BEAM_DIAG_UP_RIGHT,
    PE_SHOOTING_BEAM_DIAG_DOWN_RIGHT,
    PE_SHOOTING_BEAM_UP_RIGHT,
    PE_SHOOTING_BEAM_DOWN_RIGHT,
    PE_BOMB,
    PE_MISSILE_TRAIL,
    PE_SUPER_MISSILE_TRAIL,
    PE_BEAM_TRAILING_RIGHT,
    PE_BEAM_TRAILING_LEFT,
    PE_CHARGED_LONG_BEAM_TRAIL,
    PE_CHARGED_ICE_BEAM_TRAIL,
    PE_CHARGED_WAVE_BEAM_TRAIL,
    PE_CHARGED_PLASMA_BEAM_TRAIL,
    PE_CHARGED_FULL_BEAM_TRAIL,
    PE_CHARGED_PISTOL_TRAIL,
    PE_SPRITE_EXPLOSION_HUGE,
    PE_SPRITE_EXPLOSION_SMALL,
    PE_SPRITE_EXPLOSION_MEDIUM,
    PE_SPRITE_EXPLOSION_BIG,
    PE_SPRITE_EXPLOSION_SINGLE_THEN_BIG,
    PE_SCREW_ATTACK_DESTROYED,
    PE_SHINESPARK_DESTROYED,
    PE_SUDO_SCREW_DESTROYED,
    PE_SPEEDBOOSTER_DESTROYED,
    PE_MAIN_BOSS_DEATH,
    PE_FREEZING_SPRITE_WITH_ICE,
    PE_FREEZING_SPRITE_WITH_CHARGED_ICE,
    PE_HITTING_SOMETHING_WITH_NORMAL_BEAM,
    PE_HITTING_SOMETHING_WITH_LONG_BEAM,
    PE_HITTING_SOMETHING_WITH_ICE_BEAM,
    PE_HITTING_SOMETHING_WITH_WAVE_BEAM,
    PE_HITTING_SOMETHING_WITH_PLASMA_BEAM,
    PE_HITTING_SOMETHING_INVINCIBLE,
    PE_HITTING_SOMETHING_WITH_MISSILE,
    PE_HITTING_SOMETHING_WITH_SUPER_MISSILE,
    PE_HITTING_SOMETHING_WITH_FULL_BEAM_NO_PLASMA,
    PE_HITTING_SOMETHING_WITH_FULL_BEAM,
    PE_SMALL_DUST,
    PE_MEDIUM_DUST,
    PE_TWO_MEDIUM_DUST,
    PE_SECOND_SMALL_DUST,
    PE_SECOND_MEDIUM_DUST,
    PE_SECOND_TWO_MEDIUM_DUST,
    PE_SAMUS_REFLECTION,
    PE_CHARGING_BEAM,
    PE_ESCAPE,

    PE_END
};

#define PARTICLE_STATUS_NONE               0
#define PARTICLE_STATUS_EXISTS             (1 << 0)
#define PARTICLE_STATUS_ONSCREEN           (1 << 1)
#define PARTICLE_STATUS_EXPLOSION          (1 << 2)
#define PARTICLE_STATUS_NOT_DRAWN          (1 << 3)
#define PARTICLE_STATUS_LIVE_OFF_SCREEN    (1 << 4)
#define PARTICLE_STATUS_LOW_PRIORITY       (1 << 5)
#define PARTICLE_STATUS_ABSOLUTE_POSITION  (1 << 6)
#define PARTICLE_STATUS_X_FLIP             (1 << 7)

#endif /* PARTICLE_CONSTANTS_H */
