#ifndef POWER_BOMB_EXPLOSION_CONSTANTS_H
#define POWER_BOMB_EXPLOSION_CONSTANTS_H

enum PowerBombState {
    PB_STATE_NONE,
    PB_STATE_UNK_1,
    PB_STATE_UNK_2,
    PB_STATE_EXPLODING,
    PB_STATE_IMPLODING,
    PB_STATE_ENDING
};

#endif /* POWER_BOMB_EXPLOSION_CONSTANTS_H */
