#define PROJECTILE_CATEGORY_NONE 0x0
#define PROJECTILE_CATEGORY_BEAM 0x1
#define PROJECTILE_CATEGORY_MISSILE 0x2
#define PROJECTILE_CATEGORY_SUPER_MISSILE 0x3
#define PROJECTILE_CATEGORY_BOMB 0x4
#define PROJECTILE_CATEGORY_POWER_BOMB 0x5
#define PROJECTILE_CATEGORY_CHARGED_BEAM 0x6

#define PROJ_STATUS_NONE 0x0
#define PROJ_STATUS_EXISTS 0x1
#define PROJ_STATUS_ON_SCREEN 0x2
#define PROJ_STATUS_NOT_DRAWN 0x4
#define PROJ_STATUS_HIGH_PRIORITY 0x8
#define PROJ_STATUS_CAN_AFFECT_ENVIRONMENT 0x10
#define PROJ_STATUS_YFLIP 0x20
#define PROJ_STATUS_XFLIP 0x40
#define PROJ_STATUS_UNKNOWN 0x80

#define PROJ_TYPE_BEAM 0x0
#define PROJ_TYPE_LONG_BEAM 0x1
#define PROJ_TYPE_ICE_BEAM 0x2
#define PROJ_TYPE_WAVE_BEAM 0x3
#define PROJ_TYPE_PLASMA_BEAM 0x4
#define PROJ_TYPE_PISTOL 0x5
#define PROJ_TYPE_CHARGED_BEAM 0x6
#define PROJ_TYPE_CHARGED_LONG_BEAM 0x7
#define PROJ_TYPE_CHARGED_ICE_BEAM 0x8
#define PROJ_TYPE_CHARGED_WAVE_BEAM 0x9
#define PROJ_TYPE_CHARGED_PLASMA_BEAM 0xA
#define PROJ_TYPE_CHARGED_PISTOL 0xB
#define PROJ_TYPE_MISSILE 0xC
#define PROJ_TYPE_SUPER_MISSILE 0xD
#define PROJ_TYPE_BOMB 0xE
#define PROJ_TYPE_POWER_BOMB 0xF


#define BOMB_STAGE_INIT 0x0
#define BOMB_STAGE_FIRST_SPIN 0x1
#define BOMB_STAGE_FAST_SPIN 0x2
#define BOMB_STAGE_EXPLODING 0x3
#define BOMB_STAGE_PLACED_ON_LAUNCHER 0x4
#define BOMB_STAGE_FIRST_SPIN_ON_LAUNCHER 0x5
#define BOMB_STAGE_FAST_SPIN_ON_LAUNCHER 0x6
#define BOMB_STAGE_EXPLODING_ON_LAUNCHER 0x7