#define ROOM_SCROLLS_FLAG_NO_SCROLLS 2
#define ROOM_SCROLLS_FLAG_HAS_SCROLLS 3

#define EFFECT_NONE 0x0
#define EFFECT_WATER 0x1
#define EFFECT_STRONG_LAVA 0x2
#define EFFECT_WEAK_LAVA 0x3
#define EFFECT_STRONG_LAVA_HEAT_HAZE 0x4
#define EFFECT_ACID 0x5
#define EFFECT_SNOWFLAKES_COLD_KNOCKBACK 0x6
#define EFFECT_SNOWFLAKES_COLD 0x7
#define EFFECT_HEAT_BG3_HAZE 0x8
#define EFFECT_HEAT_BG2_BG3_HAZE 0x9
#define EFFECT_BG3_GRADIENT 0xA
#define EFFECT_BG2_GRADIENT 0xB
#define EFFECT_HAZE_BG1_BG2_BG3 0xC

#define BG0_MOVEMENT_NONE 0x0
#define BG0_MOVEMENT_WATER_CLOUDS 0x1
#define BG0_MOVEMENT_SNOWFLAKES 0x4

#define RAIN_SOUND_NONE 0x0
#define RAIN_SOUND_ENABLED 0x1
#define RAIN_SOUND_PLAYING 0x2

#define BG_PROP_NONE 0x0
#define BG_PROP_RLE_COMPRESSED 0x10
#define BG_PROP_DISABLE_TRANSPARENCY (BG_PROP_RLE_COMPRESSED | 2)
#define BG_PROP_MOVING 0x31
#define BG_PROP_LZ77_COMPRESSED 0x40
#define BG_PROP_CLOSE_UP (BG_PROP_LZ77_COMPRESSED | 1)
#define BG_PROP_DARK_ROOM (BG_PROP_LZ77_COMPRESSED | 5)
#define BG_PROP_STARTS_FROM_BOTTOM (BG_PROP_LZ77_COMPRESSED | 6)
