#ifndef ROOM_CONSTANTS_H
#define ROOM_CONSTANTS_H

#define ROOM_SCROLLS_FLAG_NO_SCROLLS 2
#define ROOM_SCROLLS_FLAG_HAS_SCROLLS 3

enum RoomEffect {
    EFFECT_NONE,
    EFFECT_WATER,
    EFFECT_STRONG_LAVA,
    EFFECT_WEAK_LAVA,
    EFFECT_STRONG_LAVA_HEAT_HAZE,
    EFFECT_ACID,
    EFFECT_SNOWFLAKES_COLD_KNOCKBACK,
    EFFECT_SNOWFLAKES_COLD,

    EFFECT_HAZARD_END,

    EFFECT_HEAT_BG3_HAZE = EFFECT_HAZARD_END,
    EFFECT_HEAT_BG2_BG3_HAZE,
    EFFECT_BG3_GRADIENT,
    EFFECT_BG2_GRADIENT,
    EFFECT_HAZE_BG1_BG2_BG3,

    EFFECT_HAZE_END
};

#define BG0_MOVEMENT_NONE 0x0
#define BG0_MOVEMENT_WATER_CLOUDS 0x1
#define BG0_MOVEMENT_SNOWFLAKES 0x4

#define RAIN_SOUND_NONE    0
#define RAIN_SOUND_ENABLED (1 << 0)
#define RAIN_SOUND_PLAYING (1 << 1)

#define BG_PROP_NONE 0x0
#define BG_PROP_RLE_COMPRESSED 0x10
#define BG_PROP_DISABLE_TRANSPARENCY (BG_PROP_RLE_COMPRESSED | 2)
#define BG_PROP_MOVING 0x31
#define BG_PROP_LZ77_COMPRESSED 0x40
#define BG_PROP_CLOSE_UP (BG_PROP_LZ77_COMPRESSED | 1)
#define BG_PROP_DARK_ROOM (BG_PROP_LZ77_COMPRESSED | 5)
#define BG_PROP_STARTS_FROM_BOTTOM (BG_PROP_LZ77_COMPRESSED | 6)

#endif
