#ifndef TEXT_CONSTANTS_H
#define TEXT_CONSTANTS_H

enum StoryTextId {
    STORY_TEXT_PLANET_ZEBES,
    STORY_TEXT_THE_TIMING,
    STORY_TEXT_COULD_I_SURVIVE,
    STORY_TEXT_EMERGENCY,
    STORY_TEXT_EXTERMINATE,
    STORY_TEXT_DEFEAT,

    STORY_TEXT_END
};

enum MessageId {
    MESSAGE_DUMMY,
    MESSAGE_ENERGY_TANK_ACQUIRED,
    MESSAGE_MISSILE_TANK_ACQUIRED,
    MESSAGE_FIRST_MISSILE_TANK,
    MESSAGE_SUPER_MISSILE_TANK_ACQUIRED,
    MESSAGE_FIRST_SUPER_MISSILE_TANK,
    MESSAGE_POWER_BOMB_TANK_ACQUIRED,
    MESSAGE_FIRST_POWER_BOMB_TANK,
    MESSAGE_LONG_BEAM,
    MESSAGE_CHARGE_BEAM,
    MESSAGE_ICE_BEAM,
    MESSAGE_WAVE_BEAM,
    MESSAGE_UKNOWN_ITEM_PLASMA,
    MESSAGE_BOMB,
    MESSAGE_VARIA_SUIT,
    MESSAGE_UNKNOWN_ITEM_GRAVITY,
    MESSAGE_MORPH_BALL,
    MESSAGE_SPEED_BOOSTER,
    MESSAGE_HIGH_JUMP,
    MESSAGE_SCREW_ATTACK,
    MESSAGE_UNKNOWN_ITEM_SPACE_JUMP,
    MESSAGE_POWER_GRIP,
    MESSAGE_SAVE_PROMPT,
    MESSAGE_SAVE_COMPLETE,
    MESSAGE_WEAPON_RESUPPLY_COMPLETE,
    MESSAGE_ENERGY_TANK_RECHARGE_COMPLETE,
    MESSAGE_WEAPONS_AND_ENERGY_RESTORED,
    MESSAGE_BRINSTAR_MAP_ACQUIRED,
    MESSAGE_KRAID_MAP_ACQUIRED,
    MESSAGE_NORFAIR_MAP_ACQUIRED,
    MESSAGE_RIDLEY_MAP_ACQUIRED,
    MESSAGE_MOTHER_SHIP_MAP_ACQUIRED,
    MESSAGE_FULLY_POWERED_SUIT,
    MESSAGE_ZEBES_ESCAPE,
    MESSAGE_CHOZODIA_ESCAPE,
    MESSAGE_ENEMY_LOCATION_ABNORMAL,
    MESSAGE_ACTIVATE_EASY_SLEEP,
    MESSAGE_PRESS_SELECT_L_AND_R,
    MESSAGE_EASY_SLEEP_PROMPT,

    MESSAGE_END,

    MESSAGE_NONE = -1,
};

enum FileScreenTextId {
    FILE_SCREEN_TEXT_START_GAME,
    FILE_SCREEN_TEXT_COPY_SOURCE_CHOOSE,
    FILE_SCREEN_TEXT_COPY_DESTINATION_CHOOSE,
    FILE_SCREEN_TEXT_COPY_CONFIRM,
    FILE_SCREEN_TEXT_ERASE_CHOOSE,
    FILE_SCREEN_TEXT_ERASE_CONFIRM,
    FILE_SCREEN_TEXT_FILE_A_CORRUPT_REVERT,
    FILE_SCREEN_TEXT_FILE_B_CORRUPT_REVERT,
    FILE_SCREEN_TEXT_FILE_C_CORRUPT_REVERT,
    FILE_SCREEN_TEXT_FILE_A_CORRUPT_ERASE,
    FILE_SCREEN_TEXT_FILE_B_CORRUPT_ERASE,
    FILE_SCREEN_TEXT_FILE_C_CORRUPT_ERASE,
    FILE_SCREEN_TEXT_ERASE_ALL_REFORMAT,
    FILE_SCREEN_TEXT_ERASE_ALL,
    FILE_SCREEN_TEXT_CONTINUE_NEW,
    FILE_SCREEN_TEXT_CONTINUE_NEW_TIME_ATTACK,
    FILE_SCREEN_TEXT_MESSAGE_OPTION,
    FILE_SCREEN_TEXT_DIFFICULTY,
    FILE_SCREEN_TEXT_DIFFICULTY_HARD,
    FILE_SCREEN_TEXT_ERASE_FILE_CONFIRM,
    FILE_SCREEN_TEXT_LINKING_PLEASE_WAIT,
    FILE_SCREEN_TEXT_UNABLE_TO_DETECT_FUSION,
    FILE_SCREEN_TEXT_LINKING_ERROR,
    FILE_SCREEN_TEXT_TURN_OFF_CONFIRM_LINK,
    FILE_SCREEN_TEXT_DO_NOT_TURN_POWER_OFF,
    FILE_SCREEN_TEXT_DATA_UPLOAD_COMPLETE,
    FILE_SCREEN_TEXT_LINK_COMPLETE,
    FILE_SCREEN_TEXT_BEST_TIME,
    FILE_SCREEN_TEXT_BEST_TIME_100,
    FILE_SCREEN_TEXT_ID_PASSWORD,
    FILE_SCREEN_TEXT_CANT_COPY_TIME_ATTACK,
    FILE_SCREEN_TEXT_LINKING_ERROR_TRY_AGAIN,
    FILE_SCREEN_TEXT_LINKING_ERROR_CHECK_CONNECTION,
    FILE_SCREEN_TEXT_GALLERY_UNLOCK,
    FILE_SCREEN_TEXT_TIME_ATTACK_RECORD_UNLOCK,
    FILE_SCREEN_TEXT_SOUND_TEST_UNLOCK,
    FILE_SCREEN_TEXT_NES_METROID_UNLOCK,

    FILE_SCREEN_TEXT_END
};


enum DescriptionTextId {
    DESCRIPTION_TEXT_LONG_BEAM,
    DESCRIPTION_TEXT_CHARGE_BEAM,
    DESCRIPTION_TEXT_ICE_BEAM,
    DESCRIPTION_TEXT_WAVE_BEAM,
    DESCRIPTION_TEXT_PLASMA_BEAM,
    DESCRIPTION_TEXT_MISSILES,
    DESCRIPTION_TEXT_SUPER_MISSILES,
    DESCRIPTION_TEXT_BOMBS,
    DESCRIPTION_TEXT_POWER_BOMBS,
    DESCRIPTION_TEXT_VARIA_SUIT,
    DESCRIPTION_TEXT_GRAVITY_SUIT,
    DESCRIPTION_TEXT_MORPH_BALL,
    DESCRIPTION_TEXT_POWER_GRIP,
    DESCRIPTION_TEXT_SPEEDBOOSTER,
    DESCRIPTION_TEXT_HIGH_JUMP,
    DESCRIPTION_TEXT_SCREW_ATTACK,
    DESCRIPTION_TEXT_SPACE_JUMP,
    DESCRIPTION_TEXT_UNKNOWN_ITEM,
    DESCRIPTION_TEXT_PISTOL,

    DESCRIPTION_TEXT_END
};

// 0
#define CHAR_SMALL_0 0
// 1
#define CHAR_SMALL_1 1
// 2
#define CHAR_SMALL_2 2
// 3
#define CHAR_SMALL_3 3
// 4
#define CHAR_SMALL_4 4
// 5
#define CHAR_SMALL_5 5
// 6
#define CHAR_SMALL_6 6
// 7
#define CHAR_SMALL_7 7
// 8
#define CHAR_SMALL_8 8
// 9
#define CHAR_SMALL_9 9
// A
#define CHAR_SMALL_A 10
// B
#define CHAR_SMALL_B 11
// C
#define CHAR_SMALL_C 12
// D
#define CHAR_SMALL_D 13
// E
#define CHAR_SMALL_E 14
// F
#define CHAR_SMALL_F 15
// G
#define CHAR_SMALL_G 16
// H
#define CHAR_SMALL_H 17
// I
#define CHAR_SMALL_I 18
// J
#define CHAR_SMALL_J 19
// K
#define CHAR_SMALL_K 20
// L
#define CHAR_SMALL_L 21
// M
#define CHAR_SMALL_M 22
// N
#define CHAR_SMALL_N 23
// O
#define CHAR_SMALL_O 24
// P
#define CHAR_SMALL_P 25
// Q
#define CHAR_SMALL_Q 26
// R
#define CHAR_SMALL_R 27
// S
#define CHAR_SMALL_S 28
// T
#define CHAR_SMALL_T 29
// U
#define CHAR_SMALL_U 30
// V
#define CHAR_SMALL_V 31
// W
#define CHAR_SMALL_W 32
// X
#define CHAR_SMALL_X 33
// Y
#define CHAR_SMALL_Y 34
// Z
#define CHAR_SMALL_Z 35
// :
#define CHAR_SMALL_COLON 36
// _
#define CHAR_SMALL_UNDERSCORE 37
// /
#define CHAR_SMALL_RIGHT_SLASH 38
// Blank
#define CHAR_EMPTY_SPACE 64
// !
#define CHAR_BANG_BANG 65
// "
#define CHAR_DOUBLE_QUOTES 66
// #
#define CHAR_SHARP 67
// $
#define CHAR_DOLLAR_SIGN 68
// %
#define CHAR_PERCENT_SIGN 69
// &
#define CHAR_PERCENT_AMPERSAND 70
// '
#define CHAR_SINGLE_QUOTE 71
// (
#define CHAR_OPENING_PARENTHESIS 72
// )
#define CHAR_CLOSING_PARENTHESIS 73
// *
#define CHAR_ASTERISK 74
// +
#define CHAR_PLUS_SIGN 75
// ,
#define CHAR_COMMA 76
// -
#define CHAR_MINUS_SIGN 77
// .
#define CHAR_DOT 78
// /
#define CHAR_RIGHT_SLASH 79
// 0
#define CHAR_0 80
// 1
#define CHAR_1 81
// 2
#define CHAR_2 82
// 3
#define CHAR_3 83
// 4
#define CHAR_4 84
// 5
#define CHAR_5 85
// 6
#define CHAR_6 86
// 7
#define CHAR_7 87
// 8
#define CHAR_8 88
// 9
#define CHAR_9 89
// :
#define CHAR_COLON 90
// ;
#define CHAR_SEMICOLON 91
// Undefined
#define CHAR_SMALL_SEMICOLON 92
// =
#define CHAR_EQUALS_SYMBOL 93
// 1
#define CHAR_1_DUP 94
// ?
#define CHAR_QUESTION_MARK 95
// Blank
#define CHAR_EMPTY_96 128
// A
#define CHAR_UPPERCASE_A 129
// B
#define CHAR_UPPERCASE_B 130
// C
#define CHAR_UPPERCASE_C 131
// D
#define CHAR_UPPERCASE_D 132
// E
#define CHAR_UPPERCASE_E 133
// F
#define CHAR_UPPERCASE_F 134
// G
#define CHAR_UPPERCASE_G 135
// H
#define CHAR_UPPERCASE_H 136
// I
#define CHAR_UPPERCASE_I 137
// J
#define CHAR_UPPERCASE_J 138
// K
#define CHAR_UPPERCASE_K 139
// L
#define CHAR_UPPERCASE_L 140
// M
#define CHAR_UPPERCASE_M 141
// N
#define CHAR_UPPERCASE_N 142
// O
#define CHAR_UPPERCASE_O 143
// P
#define CHAR_UPPERCASE_P 144
// Q
#define CHAR_UPPERCASE_Q 145
// R
#define CHAR_UPPERCASE_R 146
// S
#define CHAR_UPPERCASE_S 147
// T
#define CHAR_UPPERCASE_T 148
// U
#define CHAR_UPPERCASE_U 149
// V
#define CHAR_UPPERCASE_V 150
// W
#define CHAR_UPPERCASE_W 151
// X
#define CHAR_UPPERCASE_X 152
// Y
#define CHAR_UPPERCASE_Y 153
// Z
#define CHAR_UPPERCASE_Z 154
// [
#define CHAR_OPENING_BRACKET 155
// ¥
#define CHAR_YEN_SIGN 156
// ]
#define CHAR_CLOSING_BRACKET 157
// a
#define CHAR_LOWERCASE_A 193
// b
#define CHAR_LOWERCASE_B 194
// c
#define CHAR_LOWERCASE_C 195
// d
#define CHAR_LOWERCASE_D 196
// e
#define CHAR_LOWERCASE_E 197
// f
#define CHAR_LOWERCASE_F 198
// g
#define CHAR_LOWERCASE_G 199
// h
#define CHAR_LOWERCASE_H 200
// i
#define CHAR_LOWERCASE_I 201
// j
#define CHAR_LOWERCASE_J 202
// k
#define CHAR_LOWERCASE_K 203
// l
#define CHAR_LOWERCASE_L 204
// m
#define CHAR_LOWERCASE_M 205
// n
#define CHAR_LOWERCASE_N 206
// o
#define CHAR_LOWERCASE_O 207
// p
#define CHAR_LOWERCASE_P 208
// q
#define CHAR_LOWERCASE_Q 209
// r
#define CHAR_LOWERCASE_R 210
// s
#define CHAR_LOWERCASE_S 211
// t
#define CHAR_LOWERCASE_T 212
// u
#define CHAR_LOWERCASE_U 213
// v
#define CHAR_LOWERCASE_V 214
// w
#define CHAR_LOWERCASE_W 215
// x
#define CHAR_LOWERCASE_X 216
// y
#define CHAR_LOWERCASE_Y 217
// z
#define CHAR_LOWERCASE_Z 218
// {
#define CHAR_OPENING_BRACE 219
// |
#define CHAR_VERTICAL_BAR 220
// }
#define CHAR_CLOSING_BRACE 221
// X
#define CHAR_X_CROSS 223
// 0
#define CHAR_MINI_0 272
// 1
#define CHAR_MINI_1 273
// 2
#define CHAR_MINI_2 274
// 3
#define CHAR_MINI_3 275
// 4
#define CHAR_MINI_4 276
// 5
#define CHAR_MINI_5 277
// 6
#define CHAR_MINI_6 278
// 7
#define CHAR_MINI_7 279
// 8
#define CHAR_MINI_8 280
// 9
#define CHAR_MINI90 281

// Select button, part 1
#define CHAR_SELECT_1 713
// Select button, part 2
#define CHAR_SELECT_2 714
// Select button, part 3
#define CHAR_SELECT_3 715
// D-pad, up button pressed
#define CHAR_DPAD_UP 768
// D-pad, down button pressed
#define CHAR_DPAD_DOWN 770
// D-pad, left button pressed
#define CHAR_DPAD_LEFT 772
// D-pad, right button pressed
#define CHAR_DPAD_RIGHT 774
// A button
#define CHAR_A_BUTTON 776
// B button
#define CHAR_B_BUTTON 778
// L button
#define CHAR_L_BUTTON 780
// R button
#define CHAR_R_BUTTON 782


#define CHAR_MASK 0xFF00
#define CHAR_WIDTH_MASK 0x8000
#define CHAR_COLOR_MASK 0x8100
#define CHAR_INDENT_MASK 0x8300
#define CHAR_DELAY_MASK 0xE100
#define CHAR_NEW_PAGE 0xFD00
#define CHAR_NEW_LINE 0xFE00
#define CHAR_TERMINATOR 0xFF00

#define TEXT_STATE_NONE -1
#define TEXT_STATE_NOTHING 0
#define TEXT_STATE_NEW_LINE 1
#define TEXT_STATE_ENDED 2
#define TEXT_STATE_UNK_3 3
#define TEXT_STATE_NEW_PAGE 4

#endif /* TEXT_CONSTANTS_H */
