@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
	.type	 sHatchData_Empty,object
	.size	 sHatchData_Empty,8
sHatchData_Empty:
	.byte	0x60
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0xff
	.align	2, 0
	.type	 sCoordsX_Empty,object
	.size	 sCoordsX_Empty,4
sCoordsX_Empty:
	.short	0xffff
	.short	0xffff
	.align	2, 0
	.type	 sLockScreen_Empty,object
	.size	 sLockScreen_Empty,8
sLockScreen_Empty:
	.byte	0x0
	.space	1
	.short	0xffff
	.short	0xffff
	.space	2
	.align 2, 0 @ dont insert nops
