@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sTumblingMissileSpeed,object
	.size	 sTumblingMissileSpeed,96
sTumblingMissileSpeed:
	.short	-0xc
	.short	-0xa
	.short	-0x8
	.short	-0x6
	.short	-0x4
	.short	-0x2
	.short	0x0
	.short	0x0
	.short	0x1
	.short	0x2
	.short	0x4
	.short	0x8
	.short	0xc
	.short	0x10
	.short	0x14
	.short	0x7fff
	.space	64
	.type	 sProjectile_Array326cc8_Unused,object
	.size	 sProjectile_Array326cc8_Unused,64
sProjectile_Array326cc8_Unused:
	.byte	0x18
	.byte	0x0
	.byte	0x10
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x10
	.byte	0x0
	.byte	0x18
	.byte	0x0
	.byte	0x20
	.byte	0x0
	.byte	0x14
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x14
	.byte	0x0
	.byte	0x20
	.byte	0x0
	.byte	0x18
	.byte	0x0
	.byte	0x14
	.byte	0x0
	.byte	0x10
	.byte	0x0
	.byte	0xc
	.byte	0x0
	.byte	0xc
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0xc
	.byte	0x0
	.byte	0xc
	.byte	0x0
	.byte	0x10
	.byte	0x0
	.byte	0x14
	.byte	0x0
	.byte	0x18
	.byte	0x0
	.align	1, 0
	.type	 sBombOAM_Frame0,object
	.size	 sBombOAM_Frame0,8
sBombOAM_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x414d
	.align	1, 0
	.type	 sBombOAM_Frame1,object
	.size	 sBombOAM_Frame1,8
sBombOAM_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x414e
	.align	1, 0
	.type	 sBombOAM_Frame2,object
	.size	 sBombOAM_Frame2,8
sBombOAM_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x414f
	.align	1, 0
	.type	 sBombOAM_Frame3,object
	.size	 sBombOAM_Frame3,8
sBombOAM_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x4150
	.align	1, 0
	.type	 sPowerBombOAM_Frame0,object
	.size	 sPowerBombOAM_Frame0,8
sPowerBombOAM_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x414b
	.align	1, 0
	.type	 sPowerBombOAM_Frame1,object
	.size	 sPowerBombOAM_Frame1,8
sPowerBombOAM_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x414c
	.align	1, 0
	.type	 sPowerBombOAM_Frame2,object
	.size	 sPowerBombOAM_Frame2,8
sPowerBombOAM_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x416b
	.align	2, 0
	.type	 sBombOAM_Slow,object
	.size	 sBombOAM_Slow,40
sBombOAM_Slow:
	.word	sBombOAM_Frame0
	.byte	0x6
	.space	3
	.word	sBombOAM_Frame1
	.byte	0x6
	.space	3
	.word	sBombOAM_Frame2
	.byte	0x6
	.space	3
	.word	sBombOAM_Frame3
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sBombOAM_Fast,object
	.size	 sBombOAM_Fast,40
sBombOAM_Fast:
	.word	sBombOAM_Frame0
	.byte	0x2
	.space	3
	.word	sBombOAM_Frame1
	.byte	0x2
	.space	3
	.word	sBombOAM_Frame2
	.byte	0x2
	.space	3
	.word	sBombOAM_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPowerBombOAM_Slow,object
	.size	 sPowerBombOAM_Slow,32
sPowerBombOAM_Slow:
	.word	sPowerBombOAM_Frame0
	.byte	0x6
	.space	3
	.word	sPowerBombOAM_Frame1
	.byte	0x6
	.space	3
	.word	sPowerBombOAM_Frame2
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPowerBombOAM_Fast,object
	.size	 sPowerBombOAM_Fast,32
sPowerBombOAM_Fast:
	.word	sPowerBombOAM_Frame0
	.byte	0x3
	.space	3
	.word	sPowerBombOAM_Frame1
	.byte	0x3
	.space	3
	.word	sPowerBombOAM_Frame2
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sMissileOAM_Horizontal_Frame0,object
	.size	 sMissileOAM_Horizontal_Frame0,14
sMissileOAM_Horizontal_Frame0:
	.short	0x2
	.short	0xfc
	.short	0x3
	.short	0x30d0
	.short	0x40fc
	.short	0x1f8
	.short	0x4078
	.align	1, 0
	.type	 sMissileOAM_Horizontal_Frame1,object
	.size	 sMissileOAM_Horizontal_Frame1,14
sMissileOAM_Horizontal_Frame1:
	.short	0x2
	.short	0xfc
	.short	0x7
	.short	0x30d1
	.short	0x40fc
	.short	0x1f8
	.short	0x4078
	.align	1, 0
	.type	 sMissileOAM_Diagonal_Frame0,object
	.size	 sMissileOAM_Diagonal_Frame0,14
sMissileOAM_Diagonal_Frame0:
	.short	0x2
	.short	0x1
	.short	0x1
	.short	0x30d0
	.short	0xf8
	.short	0x41f8
	.short	0x405c
	.align	1, 0
	.type	 sMissileOAM_Diagonal_Frame1,object
	.size	 sMissileOAM_Diagonal_Frame1,14
sMissileOAM_Diagonal_Frame1:
	.short	0x2
	.short	0xf8
	.short	0x41f8
	.short	0x405c
	.short	0x3
	.short	0x3
	.short	0x30f0
	.align	1, 0
	.type	 sMissileOAM_Vertical_Frame0,object
	.size	 sMissileOAM_Vertical_Frame0,14
sMissileOAM_Vertical_Frame0:
	.short	0x2
	.short	0x3
	.short	0x1fc
	.short	0x30d0
	.short	0x80f8
	.short	0x1fc
	.short	0x4185
	.align	1, 0
	.type	 sMissileOAM_Vertical_Frame1,object
	.size	 sMissileOAM_Vertical_Frame1,14
sMissileOAM_Vertical_Frame1:
	.short	0x2
	.short	0x7
	.short	0x1fc
	.short	0x30f1
	.short	0x80f8
	.short	0x1fc
	.short	0x4185
	.align	1, 0
	.type	 sSuperMissileOAM_Horizontal_Frame0,object
	.size	 sSuperMissileOAM_Horizontal_Frame0,14
sSuperMissileOAM_Horizontal_Frame0:
	.short	0x2
	.short	0xf8
	.short	0x4002
	.short	0x30d3
	.short	0x40fc
	.short	0x1f8
	.short	0x407a
	.align	1, 0
	.type	 sSuperMissileOAM_Horizontal_Frame1,object
	.size	 sSuperMissileOAM_Horizontal_Frame1,14
sSuperMissileOAM_Horizontal_Frame1:
	.short	0x2
	.short	0x40fc
	.short	0x1f8
	.short	0x407a
	.short	0xfc
	.short	0x5
	.short	0x30d1
	.align	1, 0
	.type	 sSuperMissileOAM_Diagonal_Frame0,object
	.size	 sSuperMissileOAM_Diagonal_Frame0,14
sSuperMissileOAM_Diagonal_Frame0:
	.short	0x2
	.short	0xff
	.short	0x41ff
	.short	0x30d3
	.short	0xf8
	.short	0x41f8
	.short	0x405e
	.align	1, 0
	.type	 sSuperMissileOAM_Diagonal_Frame1,object
	.size	 sSuperMissileOAM_Diagonal_Frame1,14
sSuperMissileOAM_Diagonal_Frame1:
	.short	0x2
	.short	0xf8
	.short	0x41f8
	.short	0x405e
	.short	0x3
	.short	0x3
	.short	0x30f0
	.align	1, 0
	.type	 sSuperMissileOAM_Vertical_Frame0,object
	.size	 sSuperMissileOAM_Vertical_Frame0,14
sSuperMissileOAM_Vertical_Frame0:
	.short	0x2
	.short	0x1
	.short	0x41f8
	.short	0x30d3
	.short	0x80f8
	.short	0x1fc
	.short	0x4186
	.align	1, 0
	.type	 sSuperMissileOAM_Vertical_Frame1,object
	.size	 sSuperMissileOAM_Vertical_Frame1,14
sSuperMissileOAM_Vertical_Frame1:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x4186
	.short	0x5
	.short	0x1fc
	.short	0x30f1
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame0,object
	.size	 sMissileOAM_Tumbling_Frame0,8
sMissileOAM_Tumbling_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x1f8
	.short	0x4078
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame1,object
	.size	 sMissileOAM_Tumbling_Frame1,8
sMissileOAM_Tumbling_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x405c
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame2,object
	.size	 sMissileOAM_Tumbling_Frame2,8
sMissileOAM_Tumbling_Frame2:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x4185
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame3,object
	.size	 sMissileOAM_Tumbling_Frame3,8
sMissileOAM_Tumbling_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x51f8
	.short	0x405c
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame4,object
	.size	 sMissileOAM_Tumbling_Frame4,8
sMissileOAM_Tumbling_Frame4:
	.short	0x1
	.short	0x40fc
	.short	0x11f8
	.short	0x4078
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame5,object
	.size	 sMissileOAM_Tumbling_Frame5,8
sMissileOAM_Tumbling_Frame5:
	.short	0x1
	.short	0xf8
	.short	0x71f8
	.short	0x405c
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame6,object
	.size	 sMissileOAM_Tumbling_Frame6,8
sMissileOAM_Tumbling_Frame6:
	.short	0x1
	.short	0x80f8
	.short	0x21fc
	.short	0x4185
	.align	1, 0
	.type	 sMissileOAM_Tumbling_Frame7,object
	.size	 sMissileOAM_Tumbling_Frame7,8
sMissileOAM_Tumbling_Frame7:
	.short	0x1
	.short	0xf8
	.short	0x61f8
	.short	0x405c
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame0,object
	.size	 sSuperMissileOAM_Tumbling_Frame0,8
sSuperMissileOAM_Tumbling_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x1f8
	.short	0x407a
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame1,object
	.size	 sSuperMissileOAM_Tumbling_Frame1,8
sSuperMissileOAM_Tumbling_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x405e
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame2,object
	.size	 sSuperMissileOAM_Tumbling_Frame2,8
sSuperMissileOAM_Tumbling_Frame2:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x4186
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame3,object
	.size	 sSuperMissileOAM_Tumbling_Frame3,8
sSuperMissileOAM_Tumbling_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x51f8
	.short	0x405e
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame4,object
	.size	 sSuperMissileOAM_Tumbling_Frame4,8
sSuperMissileOAM_Tumbling_Frame4:
	.short	0x1
	.short	0x40fc
	.short	0x11f8
	.short	0x407a
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame5,object
	.size	 sSuperMissileOAM_Tumbling_Frame5,8
sSuperMissileOAM_Tumbling_Frame5:
	.short	0x1
	.short	0xf8
	.short	0x71f8
	.short	0x405e
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame6,object
	.size	 sSuperMissileOAM_Tumbling_Frame6,8
sSuperMissileOAM_Tumbling_Frame6:
	.short	0x1
	.short	0x80f8
	.short	0x21fc
	.short	0x4186
	.align	1, 0
	.type	 sSuperMissileOAM_Tumbling_Frame7,object
	.size	 sSuperMissileOAM_Tumbling_Frame7,8
sSuperMissileOAM_Tumbling_Frame7:
	.short	0x1
	.short	0xf8
	.short	0x61f8
	.short	0x405e
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame0,object
	.size	 sParticleMissileTrailOAM_Frame0,8
sParticleMissileTrailOAM_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x30d5
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame1,object
	.size	 sParticleMissileTrailOAM_Frame1,8
sParticleMissileTrailOAM_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x30f5
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame2,object
	.size	 sParticleMissileTrailOAM_Frame2,8
sParticleMissileTrailOAM_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x30f6
	.align	1, 0
	.type	 sParticleSuperMissileTrailOAM_Frame3,object
	.size	 sParticleSuperMissileTrailOAM_Frame3,8
sParticleSuperMissileTrailOAM_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x4159
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame3,object
	.size	 sParticleMissileTrailOAM_Frame3,8
sParticleMissileTrailOAM_Frame3:
	.short	0x1
	.short	0xf9
	.short	0x1fc
	.short	0x415a
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame4,object
	.size	 sParticleMissileTrailOAM_Frame4,8
sParticleMissileTrailOAM_Frame4:
	.short	0x1
	.short	0xf7
	.short	0x1fc
	.short	0x415b
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame5,object
	.size	 sParticleMissileTrailOAM_Frame5,8
sParticleMissileTrailOAM_Frame5:
	.short	0x1
	.short	0xf3
	.short	0x1fc
	.short	0x415c
	.align	1, 0
	.type	 sParticleMissileTrailOAM_Frame6,object
	.size	 sParticleMissileTrailOAM_Frame6,8
sParticleMissileTrailOAM_Frame6:
	.short	0x1
	.short	0xf1
	.short	0x1fc
	.short	0x415d
	.align	1, 0
	.type	 sParticleSuperMissileTrailOAM_Frame0,object
	.size	 sParticleSuperMissileTrailOAM_Frame0,8
sParticleSuperMissileTrailOAM_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x30d0
	.align	2, 0
	.type	 sMissileOAM_Horizontal,object
	.size	 sMissileOAM_Horizontal,24
sMissileOAM_Horizontal:
	.word	sMissileOAM_Horizontal_Frame0
	.byte	0x2
	.space	3
	.word	sMissileOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sMissileOAM_Diagonal,object
	.size	 sMissileOAM_Diagonal,24
sMissileOAM_Diagonal:
	.word	sMissileOAM_Diagonal_Frame0
	.byte	0x2
	.space	3
	.word	sMissileOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sMissileOAM_Vertical,object
	.size	 sMissileOAM_Vertical,24
sMissileOAM_Vertical:
	.word	sMissileOAM_Vertical_Frame0
	.byte	0x2
	.space	3
	.word	sMissileOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSuperMissileOAM_Horizontal,object
	.size	 sSuperMissileOAM_Horizontal,24
sSuperMissileOAM_Horizontal:
	.word	sSuperMissileOAM_Horizontal_Frame0
	.byte	0x2
	.space	3
	.word	sSuperMissileOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSuperMissileOAM_Diagonal,object
	.size	 sSuperMissileOAM_Diagonal,24
sSuperMissileOAM_Diagonal:
	.word	sSuperMissileOAM_Diagonal_Frame0
	.byte	0x2
	.space	3
	.word	sSuperMissileOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSuperMissileOAM_Vertical,object
	.size	 sSuperMissileOAM_Vertical,24
sSuperMissileOAM_Vertical:
	.word	sSuperMissileOAM_Vertical_Frame0
	.byte	0x2
	.space	3
	.word	sSuperMissileOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sMissileOAM_Tumbling,object
	.size	 sMissileOAM_Tumbling,72
sMissileOAM_Tumbling:
	.word	sMissileOAM_Tumbling_Frame0
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame1
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame2
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame3
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame4
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame5
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame6
	.byte	0x3
	.space	3
	.word	sMissileOAM_Tumbling_Frame7
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSuperMissileOAM_Tumbling,object
	.size	 sSuperMissileOAM_Tumbling,72
sSuperMissileOAM_Tumbling:
	.word	sSuperMissileOAM_Tumbling_Frame0
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame1
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame2
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame3
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame4
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame5
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame6
	.byte	0x3
	.space	3
	.word	sSuperMissileOAM_Tumbling_Frame7
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleMissileTrailOAM,object
	.size	 sParticleMissileTrailOAM,64
sParticleMissileTrailOAM:
	.word	sParticleMissileTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleMissileTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleMissileTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleMissileTrailOAM_Frame3
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame4
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame5
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame6
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleSuperMissileTrailOAM,object
	.size	 sParticleSuperMissileTrailOAM,72
sParticleSuperMissileTrailOAM:
	.word	sParticleSuperMissileTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleMissileTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleMissileTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleSuperMissileTrailOAM_Frame3
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame3
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame4
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame5
	.byte	0x3
	.space	3
	.word	sParticleMissileTrailOAM_Frame6
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sNormalBeamOAM_Horizontal_Frame0,object
	.size	 sNormalBeamOAM_Horizontal_Frame0,8
sNormalBeamOAM_Horizontal_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x1fa
	.short	0x2080
	.align	1, 0
	.type	 sNormalBeamOAM_Horizontal_Frame1,object
	.size	 sNormalBeamOAM_Horizontal_Frame1,8
sNormalBeamOAM_Horizontal_Frame1:
	.short	0x1
	.short	0x40fc
	.short	0x1fa
	.short	0x20a0
	.align	1, 0
	.type	 sNormalBeamOAM_Diagonal_Frame0,object
	.size	 sNormalBeamOAM_Diagonal_Frame0,8
sNormalBeamOAM_Diagonal_Frame0:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x2082
	.align	1, 0
	.type	 sNormalBeamOAM_Diagonal_Frame1,object
	.size	 sNormalBeamOAM_Diagonal_Frame1,8
sNormalBeamOAM_Diagonal_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x2084
	.align	1, 0
	.type	 sNormalBeamOAM_Vertical_Frame0,object
	.size	 sNormalBeamOAM_Vertical_Frame0,8
sNormalBeamOAM_Vertical_Frame0:
	.short	0x1
	.short	0x80fa
	.short	0x1fc
	.short	0x2086
	.align	1, 0
	.type	 sNormalBeamOAM_Vertical_Frame1,object
	.size	 sNormalBeamOAM_Vertical_Frame1,8
sNormalBeamOAM_Vertical_Frame1:
	.short	0x1
	.short	0x80fa
	.short	0x1fc
	.short	0x2087
	.align	1, 0
	.type	 sNormalBeamOAM_Horizontal_Unused_Frame0,object
	.size	 sNormalBeamOAM_Horizontal_Unused_Frame0,8
sNormalBeamOAM_Horizontal_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20a8
	.align	1, 0
	.type	 sNormalBeamOAM_Horizontal_Unused_Frame1,object
	.size	 sNormalBeamOAM_Horizontal_Unused_Frame1,8
sNormalBeamOAM_Horizontal_Unused_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fd
	.short	0x20a8
	.align	1, 0
	.type	 sNormalBeamOAM_Diagonal_Unused_Frame0,object
	.size	 sNormalBeamOAM_Diagonal_Unused_Frame0,8
sNormalBeamOAM_Diagonal_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20a9
	.align	1, 0
	.type	 sNormalBeamOAM_Diagonal_Unused_Frame1,object
	.size	 sNormalBeamOAM_Diagonal_Unused_Frame1,8
sNormalBeamOAM_Diagonal_Unused_Frame1:
	.short	0x1
	.short	0xfd
	.short	0x1fd
	.short	0x20a9
	.align	1, 0
	.type	 sNormalBeamOAM_Vertical_Unused_Frame0,object
	.size	 sNormalBeamOAM_Vertical_Unused_Frame0,8
sNormalBeamOAM_Vertical_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20aa
	.align	1, 0
	.type	 sNormalBeamOAM_Vertical_Unused_Frame1,object
	.size	 sNormalBeamOAM_Vertical_Unused_Frame1,8
sNormalBeamOAM_Vertical_Unused_Frame1:
	.short	0x1
	.short	0xfd
	.short	0x1fc
	.short	0x20aa
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Frame0,object
	.size	 sChargedNormalBeamOAM_Horizontal_Frame0,14
sChargedNormalBeamOAM_Horizontal_Frame0:
	.short	0x2
	.short	0xf8
	.short	0x41fa
	.short	0x20c0
	.short	0xf8
	.short	0x41ff
	.short	0x20c2
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Frame1,object
	.size	 sChargedNormalBeamOAM_Horizontal_Frame1,20
sChargedNormalBeamOAM_Horizontal_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x20c2
	.short	0xf8
	.short	0x4001
	.short	0x20c0
	.short	0xf8
	.short	0x4009
	.short	0x20c2
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Diagonal_Frame0,object
	.size	 sChargedNormalBeamOAM_Diagonal_Frame0,14
sChargedNormalBeamOAM_Diagonal_Frame0:
	.short	0x2
	.short	0xfb
	.short	0x41fb
	.short	0x20c4
	.short	0xfe
	.short	0x41fe
	.short	0x20c6
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Diagonal_Frame1,object
	.size	 sChargedNormalBeamOAM_Diagonal_Frame1,20
sChargedNormalBeamOAM_Diagonal_Frame1:
	.short	0x3
	.short	0xfa
	.short	0x41fa
	.short	0x20c6
	.short	0xff
	.short	0x41ff
	.short	0x20c4
	.short	0x4
	.short	0x4004
	.short	0x20c6
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Vertical_Frame0,object
	.size	 sChargedNormalBeamOAM_Vertical_Frame0,14
sChargedNormalBeamOAM_Vertical_Frame0:
	.short	0x2
	.short	0xfa
	.short	0x41f8
	.short	0x20c8
	.short	0xff
	.short	0x41f8
	.short	0x20ca
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Vertical_Frame1,object
	.size	 sChargedNormalBeamOAM_Vertical_Frame1,20
sChargedNormalBeamOAM_Vertical_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x20ca
	.short	0x1
	.short	0x41f8
	.short	0x20c8
	.short	0x9
	.short	0x41f8
	.short	0x20ca
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Unused_Frame0,object
	.size	 sChargedNormalBeamOAM_Horizontal_Unused_Frame0,8
sChargedNormalBeamOAM_Horizontal_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ce
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Unused_Frame1,object
	.size	 sChargedNormalBeamOAM_Horizontal_Unused_Frame1,8
sChargedNormalBeamOAM_Horizontal_Unused_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20cf
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Unused_Frame2,object
	.size	 sChargedNormalBeamOAM_Horizontal_Unused_Frame2,8
sChargedNormalBeamOAM_Horizontal_Unused_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ee
	.align	1, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Unused_Frame3,object
	.size	 sChargedNormalBeamOAM_Horizontal_Unused_Frame3,8
sChargedNormalBeamOAM_Horizontal_Unused_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ef
	.align	2, 0
	.type	 sNormalBeamOAM_Horizontal,object
	.size	 sNormalBeamOAM_Horizontal,24
sNormalBeamOAM_Horizontal:
	.word	sNormalBeamOAM_Horizontal_Frame0
	.byte	0x3
	.space	3
	.word	sNormalBeamOAM_Horizontal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sNormalBeamOAM_Diagonal,object
	.size	 sNormalBeamOAM_Diagonal,24
sNormalBeamOAM_Diagonal:
	.word	sNormalBeamOAM_Diagonal_Frame0
	.byte	0x3
	.space	3
	.word	sNormalBeamOAM_Diagonal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sNormalBeamOAM_Vertical,object
	.size	 sNormalBeamOAM_Vertical,24
sNormalBeamOAM_Vertical:
	.word	sNormalBeamOAM_Vertical_Frame0
	.byte	0x3
	.space	3
	.word	sNormalBeamOAM_Vertical_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sNormalBeamOAM_Horizontal_Unused,object
	.size	 sNormalBeamOAM_Horizontal_Unused,24
sNormalBeamOAM_Horizontal_Unused:
	.word	sNormalBeamOAM_Horizontal_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sNormalBeamOAM_Horizontal_Unused_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sNormalBeamOAM_Diagonal_Unused,object
	.size	 sNormalBeamOAM_Diagonal_Unused,24
sNormalBeamOAM_Diagonal_Unused:
	.word	sNormalBeamOAM_Diagonal_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sNormalBeamOAM_Diagonal_Unused_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sNormalBeamOAM_Vertical_Unused,object
	.size	 sNormalBeamOAM_Vertical_Unused,24
sNormalBeamOAM_Vertical_Unused:
	.word	sNormalBeamOAM_Vertical_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sNormalBeamOAM_Vertical_Unused_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedNormalBeamOAM_Horizontal,object
	.size	 sChargedNormalBeamOAM_Horizontal,24
sChargedNormalBeamOAM_Horizontal:
	.word	sChargedNormalBeamOAM_Horizontal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedNormalBeamOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedNormalBeamOAM_Diagonal,object
	.size	 sChargedNormalBeamOAM_Diagonal,24
sChargedNormalBeamOAM_Diagonal:
	.word	sChargedNormalBeamOAM_Diagonal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedNormalBeamOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedNormalBeamOAM_Vertical,object
	.size	 sChargedNormalBeamOAM_Vertical,24
sChargedNormalBeamOAM_Vertical:
	.word	sChargedNormalBeamOAM_Vertical_Frame0
	.byte	0x2
	.space	3
	.word	sChargedNormalBeamOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedNormalBeamOAM_Horizontal_Unused,object
	.size	 sChargedNormalBeamOAM_Horizontal_Unused,40
sChargedNormalBeamOAM_Horizontal_Unused:
	.word	sChargedNormalBeamOAM_Horizontal_Unused_Frame0
	.byte	0x4
	.space	3
	.word	sChargedNormalBeamOAM_Horizontal_Unused_Frame1
	.byte	0x4
	.space	3
	.word	sChargedNormalBeamOAM_Horizontal_Unused_Frame2
	.byte	0x4
	.space	3
	.word	sChargedNormalBeamOAM_Horizontal_Unused_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sLongBeamOAM_Horizontal_Frame0,object
	.size	 sLongBeamOAM_Horizontal_Frame0,8
sLongBeamOAM_Horizontal_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x1fc
	.short	0x2080
	.align	1, 0
	.type	 sLongBeamOAM_Horizontal_Frame1,object
	.size	 sLongBeamOAM_Horizontal_Frame1,8
sLongBeamOAM_Horizontal_Frame1:
	.short	0x1
	.short	0x40fc
	.short	0x1fc
	.short	0x20a0
	.align	1, 0
	.type	 sLongBeamOAM_Diagonal_Frame0,object
	.size	 sLongBeamOAM_Diagonal_Frame0,8
sLongBeamOAM_Diagonal_Frame0:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x20c0
	.align	1, 0
	.type	 sLongBeamOAM_Diagonal_Frame1,object
	.size	 sLongBeamOAM_Diagonal_Frame1,8
sLongBeamOAM_Diagonal_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x20c2
	.align	1, 0
	.type	 sLongBeamOAM_Vertical_Frame0,object
	.size	 sLongBeamOAM_Vertical_Frame0,8
sLongBeamOAM_Vertical_Frame0:
	.short	0x1
	.short	0x80fc
	.short	0x1fc
	.short	0x2082
	.align	1, 0
	.type	 sLongBeamOAM_Vertical_Frame1,object
	.size	 sLongBeamOAM_Vertical_Frame1,8
sLongBeamOAM_Vertical_Frame1:
	.short	0x1
	.short	0x80fc
	.short	0x1fc
	.short	0x2083
	.align	1, 0
	.type	 sChargedLongBeamOAM_Horizontal_Frame0,object
	.size	 sChargedLongBeamOAM_Horizontal_Frame0,14
sChargedLongBeamOAM_Horizontal_Frame0:
	.short	0x2
	.short	0x40f8
	.short	0x81fa
	.short	0x2086
	.short	0x40f8
	.short	0x8001
	.short	0x20c6
	.align	1, 0
	.type	 sChargedLongBeamOAM_Horizontal_Frame1,object
	.size	 sChargedLongBeamOAM_Horizontal_Frame1,20
sChargedLongBeamOAM_Horizontal_Frame1:
	.short	0x3
	.short	0x40f8
	.short	0x81f8
	.short	0x20c6
	.short	0x40f8
	.short	0x8002
	.short	0x2086
	.short	0x40f8
	.short	0x800b
	.short	0x20c6
	.align	1, 0
	.type	 sChargedLongBeamOAM_Diagonal_Frame0,object
	.size	 sChargedLongBeamOAM_Diagonal_Frame0,14
sChargedLongBeamOAM_Diagonal_Frame0:
	.short	0x2
	.short	0xfc
	.short	0x41fc
	.short	0x2084
	.short	0x2
	.short	0x4002
	.short	0x20c4
	.align	1, 0
	.type	 sChargedLongBeamOAM_Diagonal_Frame1,object
	.size	 sChargedLongBeamOAM_Diagonal_Frame1,20
sChargedLongBeamOAM_Diagonal_Frame1:
	.short	0x3
	.short	0xfb
	.short	0x41fb
	.short	0x20c4
	.short	0x1
	.short	0x4001
	.short	0x2084
	.short	0x8
	.short	0x4008
	.short	0x20c4
	.align	1, 0
	.type	 sChargedLongBeamOAM_Vertical_Frame0,object
	.size	 sChargedLongBeamOAM_Vertical_Frame0,14
sChargedLongBeamOAM_Vertical_Frame0:
	.short	0x2
	.short	0x80fa
	.short	0x81f8
	.short	0x208a
	.short	0x8001
	.short	0x81f8
	.short	0x208c
	.align	1, 0
	.type	 sChargedLongBeamOAM_Vertical_Frame1,object
	.size	 sChargedLongBeamOAM_Vertical_Frame1,20
sChargedLongBeamOAM_Vertical_Frame1:
	.short	0x3
	.short	0x80f8
	.short	0x81f8
	.short	0x208c
	.short	0x8002
	.short	0x81f8
	.short	0x208a
	.short	0x800b
	.short	0x81f8
	.short	0x208c
	.align	1, 0
	.type	 sParticleChargedLongBeamTrailOAM_Frame0,object
	.size	 sParticleChargedLongBeamTrailOAM_Frame0,8
sParticleChargedLongBeamTrailOAM_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ce
	.align	1, 0
	.type	 sParticleChargedLongBeamTrailOAM_Frame1,object
	.size	 sParticleChargedLongBeamTrailOAM_Frame1,8
sParticleChargedLongBeamTrailOAM_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x208e
	.align	1, 0
	.type	 sParticleChargedLongBeamTrailOAM_Frame2,object
	.size	 sParticleChargedLongBeamTrailOAM_Frame2,8
sParticleChargedLongBeamTrailOAM_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20cf
	.align	1, 0
	.type	 sParticleChargedLongBeamTrailOAM_Frame3,object
	.size	 sParticleChargedLongBeamTrailOAM_Frame3,8
sParticleChargedLongBeamTrailOAM_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ef
	.align	2, 0
	.type	 sLongBeamOAM_Horizontal,object
	.size	 sLongBeamOAM_Horizontal,24
sLongBeamOAM_Horizontal:
	.word	sLongBeamOAM_Horizontal_Frame0
	.byte	0x3
	.space	3
	.word	sLongBeamOAM_Horizontal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sLongBeamOAM_Diagonal,object
	.size	 sLongBeamOAM_Diagonal,24
sLongBeamOAM_Diagonal:
	.word	sLongBeamOAM_Diagonal_Frame0
	.byte	0x3
	.space	3
	.word	sLongBeamOAM_Diagonal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sLongBeamOAM_Vertical,object
	.size	 sLongBeamOAM_Vertical,24
sLongBeamOAM_Vertical:
	.word	sLongBeamOAM_Vertical_Frame0
	.byte	0x3
	.space	3
	.word	sLongBeamOAM_Vertical_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedLongBeamOAM_Horizontal,object
	.size	 sChargedLongBeamOAM_Horizontal,24
sChargedLongBeamOAM_Horizontal:
	.word	sChargedLongBeamOAM_Horizontal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedLongBeamOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedLongBeamOAM_Diagonal,object
	.size	 sChargedLongBeamOAM_Diagonal,24
sChargedLongBeamOAM_Diagonal:
	.word	sChargedLongBeamOAM_Diagonal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedLongBeamOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedLongBeamOAM_Vertical,object
	.size	 sChargedLongBeamOAM_Vertical,24
sChargedLongBeamOAM_Vertical:
	.word	sChargedLongBeamOAM_Vertical_Frame0
	.byte	0x2
	.space	3
	.word	sChargedLongBeamOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleChargedLongBeamTrailOAM,object
	.size	 sParticleChargedLongBeamTrailOAM,40
sParticleChargedLongBeamTrailOAM:
	.word	sParticleChargedLongBeamTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleChargedLongBeamTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleChargedLongBeamTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleChargedLongBeamTrailOAM_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sIceBeamOAM_Horizontal_Frame0,object
	.size	 sIceBeamOAM_Horizontal_Frame0,8
sIceBeamOAM_Horizontal_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41fb
	.short	0x2080
	.align	1, 0
	.type	 sIceBeamOAM_Horizontal_Frame1,object
	.size	 sIceBeamOAM_Horizontal_Frame1,8
sIceBeamOAM_Horizontal_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41fc
	.short	0x2082
	.align	1, 0
	.type	 sIceBeamOAM_Diagonal_Frame0,object
	.size	 sIceBeamOAM_Diagonal_Frame0,8
sIceBeamOAM_Diagonal_Frame0:
	.short	0x1
	.short	0xfa
	.short	0x41f9
	.short	0x2084
	.align	1, 0
	.type	 sIceBeamOAM_Diagonal_Frame1,object
	.size	 sIceBeamOAM_Diagonal_Frame1,8
sIceBeamOAM_Diagonal_Frame1:
	.short	0x1
	.short	0xfb
	.short	0x41fa
	.short	0x2086
	.align	1, 0
	.type	 sIceBeamOAM_Vertical_Frame0,object
	.size	 sIceBeamOAM_Vertical_Frame0,8
sIceBeamOAM_Vertical_Frame0:
	.short	0x1
	.short	0xfb
	.short	0x41f8
	.short	0x2088
	.align	1, 0
	.type	 sIceBeamOAM_Vertical_Frame1,object
	.size	 sIceBeamOAM_Vertical_Frame1,8
sIceBeamOAM_Vertical_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x41f8
	.short	0x208a
	.align	1, 0
	.type	 sIceBeamOAM_Horizontal_Unused_Frame0,object
	.size	 sIceBeamOAM_Horizontal_Unused_Frame0,8
sIceBeamOAM_Horizontal_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x208c
	.align	1, 0
	.type	 sIceBeamOAM_Horizontal_Unused_Frame1,object
	.size	 sIceBeamOAM_Horizontal_Unused_Frame1,8
sIceBeamOAM_Horizontal_Unused_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fd
	.short	0x208c
	.align	1, 0
	.type	 sIceBeamOAM_Diagonal_Unused_Frame0,object
	.size	 sIceBeamOAM_Diagonal_Unused_Frame0,8
sIceBeamOAM_Diagonal_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x208d
	.align	1, 0
	.type	 sIceBeamOAM_Diagonal_Unused_Frame1,object
	.size	 sIceBeamOAM_Diagonal_Unused_Frame1,8
sIceBeamOAM_Diagonal_Unused_Frame1:
	.short	0x1
	.short	0xfd
	.short	0x1fd
	.short	0x208d
	.align	1, 0
	.type	 sIceBeamOAM_Vertical_Unused_Frame0,object
	.size	 sIceBeamOAM_Vertical_Unused_Frame0,8
sIceBeamOAM_Vertical_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x208e
	.align	1, 0
	.type	 sIceBeamOAM_Vertical_Unused_Frame1,object
	.size	 sIceBeamOAM_Vertical_Unused_Frame1,8
sIceBeamOAM_Vertical_Unused_Frame1:
	.short	0x1
	.short	0xfd
	.short	0x1fc
	.short	0x208e
	.align	1, 0
	.type	 sChargedIceBeamOAM_Horizontal_Frame0,object
	.size	 sChargedIceBeamOAM_Horizontal_Frame0,26
sChargedIceBeamOAM_Horizontal_Frame0:
	.short	0x4
	.short	0xf8
	.short	0x41fa
	.short	0x20c0
	.short	0xfc
	.short	0xa
	.short	0x20c2
	.short	0xf8
	.short	0x41ff
	.short	0x20c3
	.short	0xfc
	.short	0xf
	.short	0x20e2
	.align	1, 0
	.type	 sChargedIceBeamOAM_Horizontal_Frame1,object
	.size	 sChargedIceBeamOAM_Horizontal_Frame1,38
sChargedIceBeamOAM_Horizontal_Frame1:
	.short	0x6
	.short	0xf8
	.short	0x41f8
	.short	0x20c3
	.short	0xfc
	.short	0x8
	.short	0x20e2
	.short	0xf8
	.short	0x4001
	.short	0x20c0
	.short	0xfc
	.short	0x11
	.short	0x20c2
	.short	0xf8
	.short	0x400a
	.short	0x20c3
	.short	0xfc
	.short	0x1a
	.short	0x20e2
	.align	1, 0
	.type	 sChargedIceBeamOAM_Diagonal_Frame0,object
	.size	 sChargedIceBeamOAM_Diagonal_Frame0,14
sChargedIceBeamOAM_Diagonal_Frame0:
	.short	0x2
	.short	0xfb
	.short	0x41fb
	.short	0x20c5
	.short	0xff
	.short	0x41ff
	.short	0x20c7
	.align	1, 0
	.type	 sChargedIceBeamOAM_Diagonal_Frame1,object
	.size	 sChargedIceBeamOAM_Diagonal_Frame1,20
sChargedIceBeamOAM_Diagonal_Frame1:
	.short	0x3
	.short	0xfa
	.short	0x41fa
	.short	0x20c7
	.short	0xfe
	.short	0x41fe
	.short	0x20c5
	.short	0x4
	.short	0x4004
	.short	0x20c7
	.align	1, 0
	.type	 sChargedIceBeamOAM_Vertical_Frame0,object
	.size	 sChargedIceBeamOAM_Vertical_Frame0,26
sChargedIceBeamOAM_Vertical_Frame0:
	.short	0x4
	.short	0xfa
	.short	0x41f8
	.short	0x20c9
	.short	0xa
	.short	0x1fc
	.short	0x20cb
	.short	0xff
	.short	0x41f8
	.short	0x20cc
	.short	0xf
	.short	0x1fc
	.short	0x20eb
	.align	1, 0
	.type	 sChargedIceBeamOAM_Vertical_Frame1,object
	.size	 sChargedIceBeamOAM_Vertical_Frame1,38
sChargedIceBeamOAM_Vertical_Frame1:
	.short	0x6
	.short	0xf8
	.short	0x41f8
	.short	0x20cc
	.short	0x8
	.short	0x1fc
	.short	0x20eb
	.short	0x1
	.short	0x41f8
	.short	0x20c9
	.short	0x11
	.short	0x1fc
	.short	0x20cb
	.short	0xa
	.short	0x41f8
	.short	0x20cc
	.short	0x1a
	.short	0x1fc
	.short	0x20eb
	.align	1, 0
	.type	 sParticleChargedIceBeamTrailOAM_Frame0,object
	.size	 sParticleChargedIceBeamTrailOAM_Frame0,8
sParticleChargedIceBeamTrailOAM_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x208c
	.align	1, 0
	.type	 sParticleChargedIceBeamTrailOAM_Frame1,object
	.size	 sParticleChargedIceBeamTrailOAM_Frame1,8
sParticleChargedIceBeamTrailOAM_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x20ce
	.align	1, 0
	.type	 sParticleChargedIceBeamTrailOAM_Frame2,object
	.size	 sParticleChargedIceBeamTrailOAM_Frame2,8
sParticleChargedIceBeamTrailOAM_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ae
	.align	1, 0
	.type	 sParticleChargedIceBeamTrailOAM_Frame3,object
	.size	 sParticleChargedIceBeamTrailOAM_Frame3,8
sParticleChargedIceBeamTrailOAM_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20af
	.align	1, 0
	.type	 sParticleChargedIceBeamTrailOAM_Frame4,object
	.size	 sParticleChargedIceBeamTrailOAM_Frame4,8
sParticleChargedIceBeamTrailOAM_Frame4:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x208f
	.align	2, 0
	.type	 sIceBeamOAM_Horizontal,object
	.size	 sIceBeamOAM_Horizontal,24
sIceBeamOAM_Horizontal:
	.word	sIceBeamOAM_Horizontal_Frame0
	.byte	0x3
	.space	3
	.word	sIceBeamOAM_Horizontal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sIceBeamOAM_Diagonal,object
	.size	 sIceBeamOAM_Diagonal,24
sIceBeamOAM_Diagonal:
	.word	sIceBeamOAM_Diagonal_Frame0
	.byte	0x3
	.space	3
	.word	sIceBeamOAM_Diagonal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sIceBeamOAM_Vertical,object
	.size	 sIceBeamOAM_Vertical,24
sIceBeamOAM_Vertical:
	.word	sIceBeamOAM_Vertical_Frame0
	.byte	0x3
	.space	3
	.word	sIceBeamOAM_Vertical_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sIceBeamOAM_Horizontal_Unused,object
	.size	 sIceBeamOAM_Horizontal_Unused,24
sIceBeamOAM_Horizontal_Unused:
	.word	sIceBeamOAM_Horizontal_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sIceBeamOAM_Horizontal_Unused_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sIceBeamOAM_Diagonal_Unused,object
	.size	 sIceBeamOAM_Diagonal_Unused,24
sIceBeamOAM_Diagonal_Unused:
	.word	sIceBeamOAM_Diagonal_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sIceBeamOAM_Diagonal_Unused_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sIceBeamOAM_Vertical_Unused,object
	.size	 sIceBeamOAM_Vertical_Unused,24
sIceBeamOAM_Vertical_Unused:
	.word	sIceBeamOAM_Vertical_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sIceBeamOAM_Vertical_Unused_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedIceBeamOAM_Horizontal,object
	.size	 sChargedIceBeamOAM_Horizontal,24
sChargedIceBeamOAM_Horizontal:
	.word	sChargedIceBeamOAM_Horizontal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedIceBeamOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedIceBeamOAM_Diagonal,object
	.size	 sChargedIceBeamOAM_Diagonal,24
sChargedIceBeamOAM_Diagonal:
	.word	sChargedIceBeamOAM_Diagonal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedIceBeamOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedIceBeamOAM_Vertical,object
	.size	 sChargedIceBeamOAM_Vertical,24
sChargedIceBeamOAM_Vertical:
	.word	sChargedIceBeamOAM_Vertical_Frame0
	.byte	0x2
	.space	3
	.word	sChargedIceBeamOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleChargedIceBeamTrailOAM,object
	.size	 sParticleChargedIceBeamTrailOAM,48
sParticleChargedIceBeamTrailOAM:
	.word	sParticleChargedIceBeamTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleChargedIceBeamTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleChargedIceBeamTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleChargedIceBeamTrailOAM_Frame3
	.byte	0x4
	.space	3
	.word	sParticleChargedIceBeamTrailOAM_Frame4
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame0,object
	.size	 sWaveBeamOAM_Horizontal_Frame0,8
sWaveBeamOAM_Horizontal_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x1fb
	.short	0x2080
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame1,object
	.size	 sWaveBeamOAM_Horizontal_Frame1,20
sWaveBeamOAM_Horizontal_Frame1:
	.short	0x3
	.short	0x4000
	.short	0x1fb
	.short	0x2080
	.short	0x40f8
	.short	0x1fb
	.short	0x2080
	.short	0x40fc
	.short	0x5
	.short	0x20a0
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame2,object
	.size	 sWaveBeamOAM_Horizontal_Frame2,20
sWaveBeamOAM_Horizontal_Frame2:
	.short	0x3
	.short	0x4004
	.short	0x1fb
	.short	0x2080
	.short	0x40f4
	.short	0x1fb
	.short	0x2080
	.short	0x40fc
	.short	0xd
	.short	0x20a0
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame3,object
	.size	 sWaveBeamOAM_Horizontal_Frame3,14
sWaveBeamOAM_Horizontal_Frame3:
	.short	0x2
	.short	0x4008
	.short	0x1fb
	.short	0x2080
	.short	0x40f0
	.short	0x1fb
	.short	0x2080
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame4,object
	.size	 sWaveBeamOAM_Horizontal_Frame4,26
sWaveBeamOAM_Horizontal_Frame4:
	.short	0x4
	.short	0x40f3
	.short	0x1fb
	.short	0x2080
	.short	0x4005
	.short	0x1fb
	.short	0x2080
	.short	0x40ef
	.short	0x1fb
	.short	0x20a0
	.short	0x4009
	.short	0x1fb
	.short	0x20a0
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame5,object
	.size	 sWaveBeamOAM_Horizontal_Frame5,26
sWaveBeamOAM_Horizontal_Frame5:
	.short	0x4
	.short	0x40f8
	.short	0x1fb
	.short	0x2080
	.short	0x4000
	.short	0x1fb
	.short	0x2080
	.short	0x40f2
	.short	0x1fb
	.short	0x20a0
	.short	0x4006
	.short	0x1fb
	.short	0x20a0
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Frame6,object
	.size	 sWaveBeamOAM_Horizontal_Frame6,20
sWaveBeamOAM_Horizontal_Frame6:
	.short	0x3
	.short	0x40fc
	.short	0x1fb
	.short	0x2080
	.short	0x40f6
	.short	0x1fb
	.short	0x20a0
	.short	0x4002
	.short	0x1fb
	.short	0x20a0
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame0,object
	.size	 sWaveBeamOAM_Diagonal_Frame0,8
sWaveBeamOAM_Diagonal_Frame0:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x20c0
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame1,object
	.size	 sWaveBeamOAM_Diagonal_Frame1,20
sWaveBeamOAM_Diagonal_Frame1:
	.short	0x3
	.short	0xf6
	.short	0x41fd
	.short	0x20c0
	.short	0xfc
	.short	0x41f6
	.short	0x20c0
	.short	0x0
	.short	0x4001
	.short	0x20c2
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame2,object
	.size	 sWaveBeamOAM_Diagonal_Frame2,20
sWaveBeamOAM_Diagonal_Frame2:
	.short	0x3
	.short	0xf3
	.short	0x41ff
	.short	0x20c0
	.short	0xfe
	.short	0x41f4
	.short	0x20c0
	.short	0x5
	.short	0x4005
	.short	0x20c2
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame3,object
	.size	 sWaveBeamOAM_Diagonal_Frame3,14
sWaveBeamOAM_Diagonal_Frame3:
	.short	0x2
	.short	0xf0
	.short	0x4002
	.short	0x20c0
	.short	0x1
	.short	0x41f1
	.short	0x20c0
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame4,object
	.size	 sWaveBeamOAM_Diagonal_Frame4,26
sWaveBeamOAM_Diagonal_Frame4:
	.short	0x4
	.short	0xf2
	.short	0x41ff
	.short	0x20c0
	.short	0xff
	.short	0x41f3
	.short	0x20c0
	.short	0xef
	.short	0x4003
	.short	0x20c2
	.short	0x2
	.short	0x41f0
	.short	0x20c2
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame5,object
	.size	 sWaveBeamOAM_Diagonal_Frame5,26
sWaveBeamOAM_Diagonal_Frame5:
	.short	0x4
	.short	0xf6
	.short	0x41fc
	.short	0x20c0
	.short	0xfb
	.short	0x41f7
	.short	0x20c0
	.short	0xf2
	.short	0x4001
	.short	0x20c2
	.short	0x0
	.short	0x41f3
	.short	0x20c2
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Frame6,object
	.size	 sWaveBeamOAM_Diagonal_Frame6,20
sWaveBeamOAM_Diagonal_Frame6:
	.short	0x3
	.short	0xf9
	.short	0x41f9
	.short	0x20c0
	.short	0xf4
	.short	0x41fe
	.short	0x20c2
	.short	0xfe
	.short	0x41f4
	.short	0x20c2
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame0,object
	.size	 sWaveBeamOAM_Vertical_Frame0,8
sWaveBeamOAM_Vertical_Frame0:
	.short	0x1
	.short	0x80fb
	.short	0x1fc
	.short	0x2082
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame1,object
	.size	 sWaveBeamOAM_Vertical_Frame1,20
sWaveBeamOAM_Vertical_Frame1:
	.short	0x3
	.short	0x80fb
	.short	0x0
	.short	0x2082
	.short	0x80fb
	.short	0x1f8
	.short	0x2082
	.short	0x8005
	.short	0x1fc
	.short	0x20c6
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame2,object
	.size	 sWaveBeamOAM_Vertical_Frame2,20
sWaveBeamOAM_Vertical_Frame2:
	.short	0x3
	.short	0x80fb
	.short	0x4
	.short	0x2082
	.short	0x80fb
	.short	0x1f4
	.short	0x2082
	.short	0x800d
	.short	0x1fc
	.short	0x20c6
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame3,object
	.size	 sWaveBeamOAM_Vertical_Frame3,14
sWaveBeamOAM_Vertical_Frame3:
	.short	0x2
	.short	0x80fb
	.short	0x8
	.short	0x2082
	.short	0x80fb
	.short	0x1f0
	.short	0x2082
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame4,object
	.size	 sWaveBeamOAM_Vertical_Frame4,26
sWaveBeamOAM_Vertical_Frame4:
	.short	0x4
	.short	0x80fb
	.short	0x5
	.short	0x2082
	.short	0x80fb
	.short	0x1f3
	.short	0x2082
	.short	0x80fb
	.short	0x9
	.short	0x20c6
	.short	0x80fb
	.short	0x1ef
	.short	0x20c6
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame5,object
	.size	 sWaveBeamOAM_Vertical_Frame5,26
sWaveBeamOAM_Vertical_Frame5:
	.short	0x4
	.short	0x80fb
	.short	0x0
	.short	0x2082
	.short	0x80fb
	.short	0x1f8
	.short	0x2082
	.short	0x80fb
	.short	0x6
	.short	0x20c6
	.short	0x80fb
	.short	0x1f2
	.short	0x20c6
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Frame6,object
	.size	 sWaveBeamOAM_Vertical_Frame6,20
sWaveBeamOAM_Vertical_Frame6:
	.short	0x3
	.short	0x80fb
	.short	0x1fc
	.short	0x2082
	.short	0x80fb
	.short	0x2
	.short	0x20c6
	.short	0x80fb
	.short	0x1f6
	.short	0x20c6
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame0,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame0,8
sWaveBeamOAM_Horizontal_Unused_Frame0:
	.short	0x1
	.short	0x40f8
	.short	0x1f8
	.short	0x20ee
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame1,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame1,8
sWaveBeamOAM_Horizontal_Unused_Frame1:
	.short	0x1
	.short	0x40f8
	.short	0x1f8
	.short	0x20ee
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame2,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame2,26
sWaveBeamOAM_Horizontal_Unused_Frame2:
	.short	0x4
	.short	0x1
	.short	0x1fd
	.short	0x2084
	.short	0xf7
	.short	0x1fd
	.short	0x2084
	.short	0xfc
	.short	0x9
	.short	0x2085
	.short	0xfc
	.short	0x1fa
	.short	0x2084
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame3,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame3,26
sWaveBeamOAM_Horizontal_Unused_Frame3:
	.short	0x4
	.short	0x5
	.short	0x0
	.short	0x2084
	.short	0xf3
	.short	0x0
	.short	0x2084
	.short	0xf6
	.short	0x1fd
	.short	0x2084
	.short	0x2
	.short	0x1fd
	.short	0x2084
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame4,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame4,26
sWaveBeamOAM_Horizontal_Unused_Frame4:
	.short	0x4
	.short	0x7
	.short	0x4
	.short	0x2084
	.short	0xf1
	.short	0x4
	.short	0x2084
	.short	0xf2
	.short	0x0
	.short	0x2084
	.short	0x6
	.short	0x0
	.short	0x2084
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame5,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame5,26
sWaveBeamOAM_Horizontal_Unused_Frame5:
	.short	0x4
	.short	0xf3
	.short	0xd
	.short	0x2084
	.short	0x5
	.short	0xd
	.short	0x2084
	.short	0x7
	.short	0x8
	.short	0x2084
	.short	0xf1
	.short	0x8
	.short	0x2084
	.align	1, 0
	.type	 sWaveBeamOAM_Horizontal_Unused_Frame6,object
	.size	 sWaveBeamOAM_Horizontal_Unused_Frame6,26
sWaveBeamOAM_Horizontal_Unused_Frame6:
	.short	0x4
	.short	0xf5
	.short	0x10
	.short	0x2084
	.short	0x3
	.short	0x10
	.short	0x2084
	.short	0xf8
	.short	0x13
	.short	0x2085
	.short	0x0
	.short	0x13
	.short	0x2085
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame0,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame0,8
sWaveBeamOAM_Diagonal_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20a4
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame1,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame1,20
sWaveBeamOAM_Diagonal_Unused_Frame1:
	.short	0x3
	.short	0xfa
	.short	0x1fc
	.short	0x20a4
	.short	0xfc
	.short	0x1fa
	.short	0x20a4
	.short	0xff
	.short	0x1ff
	.short	0x20a5
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame2,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame2,26
sWaveBeamOAM_Diagonal_Unused_Frame2:
	.short	0x4
	.short	0xf8
	.short	0x1fd
	.short	0x20a4
	.short	0xfd
	.short	0x1f8
	.short	0x20a4
	.short	0x1
	.short	0x1
	.short	0x20a5
	.short	0xf9
	.short	0x1f9
	.short	0x20a4
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame3,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame3,26
sWaveBeamOAM_Diagonal_Unused_Frame3:
	.short	0x4
	.short	0xf8
	.short	0x3
	.short	0x20a4
	.short	0x3
	.short	0x1f8
	.short	0x20a4
	.short	0xf7
	.short	0x1fe
	.short	0x20a4
	.short	0xfe
	.short	0x1f7
	.short	0x20a4
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame4,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame4,26
sWaveBeamOAM_Diagonal_Unused_Frame4:
	.short	0x4
	.short	0xf9
	.short	0x7
	.short	0x20a4
	.short	0x7
	.short	0x1f9
	.short	0x20a4
	.short	0xf6
	.short	0x3
	.short	0x20a4
	.short	0x3
	.short	0x1f6
	.short	0x20a4
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame5,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame5,26
sWaveBeamOAM_Diagonal_Unused_Frame5:
	.short	0x4
	.short	0x1
	.short	0xc
	.short	0x20a4
	.short	0xc
	.short	0x1
	.short	0x20a4
	.short	0xfc
	.short	0xa
	.short	0x20a4
	.short	0xa
	.short	0x1fc
	.short	0x20a4
	.align	1, 0
	.type	 sWaveBeamOAM_Diagonal_Unused_Frame6,object
	.size	 sWaveBeamOAM_Diagonal_Unused_Frame6,26
sWaveBeamOAM_Diagonal_Unused_Frame6:
	.short	0x4
	.short	0x3
	.short	0xe
	.short	0x20a4
	.short	0xe
	.short	0x3
	.short	0x20a4
	.short	0xf
	.short	0x8
	.short	0x20a5
	.short	0x8
	.short	0xf
	.short	0x20a5
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame0,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame0,8
sWaveBeamOAM_Vertical_Unused_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20c4
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame1,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame1,20
sWaveBeamOAM_Vertical_Unused_Frame1:
	.short	0x3
	.short	0xfd
	.short	0x1fe
	.short	0x20c4
	.short	0xfd
	.short	0x1fa
	.short	0x20c4
	.short	0x3
	.short	0x1fc
	.short	0x20c5
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame2,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame2,26
sWaveBeamOAM_Vertical_Unused_Frame2:
	.short	0x4
	.short	0xfd
	.short	0x1
	.short	0x20c4
	.short	0xfd
	.short	0x1f7
	.short	0x20c4
	.short	0x9
	.short	0x1fc
	.short	0x20c5
	.short	0xfa
	.short	0x1fc
	.short	0x20c4
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame3,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame3,26
sWaveBeamOAM_Vertical_Unused_Frame3:
	.short	0x4
	.short	0x0
	.short	0x5
	.short	0x20c4
	.short	0x0
	.short	0x1f3
	.short	0x20c4
	.short	0xfd
	.short	0x2
	.short	0x20c4
	.short	0xfd
	.short	0x1f6
	.short	0x20c4
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame4,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame4,26
sWaveBeamOAM_Vertical_Unused_Frame4:
	.short	0x4
	.short	0x4
	.short	0x7
	.short	0x20c4
	.short	0x4
	.short	0x1f1
	.short	0x20c4
	.short	0x0
	.short	0x6
	.short	0x20c4
	.short	0x0
	.short	0x1f2
	.short	0x20c4
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame5,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame5,26
sWaveBeamOAM_Vertical_Unused_Frame5:
	.short	0x4
	.short	0xd
	.short	0x5
	.short	0x20c4
	.short	0xd
	.short	0x1f3
	.short	0x20c4
	.short	0x8
	.short	0x7
	.short	0x20c4
	.short	0x8
	.short	0x1f1
	.short	0x20c4
	.align	1, 0
	.type	 sWaveBeamOAM_Vertical_Unused_Frame6,object
	.size	 sWaveBeamOAM_Vertical_Unused_Frame6,26
sWaveBeamOAM_Vertical_Unused_Frame6:
	.short	0x4
	.short	0x10
	.short	0x3
	.short	0x20c4
	.short	0x10
	.short	0x1f5
	.short	0x20c4
	.short	0x13
	.short	0x1f8
	.short	0x20c5
	.short	0x13
	.short	0x0
	.short	0x20c5
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame0,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame0,8
sChargedWaveBeamOAM_Horizontal_Frame0:
	.short	0x1
	.short	0x40f8
	.short	0x81f9
	.short	0x2083
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame1,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame1,20
sChargedWaveBeamOAM_Horizontal_Frame1:
	.short	0x3
	.short	0x40f6
	.short	0x81f7
	.short	0x2083
	.short	0x40fa
	.short	0x81f7
	.short	0x2083
	.short	0x40f8
	.short	0x9004
	.short	0x2086
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame2,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame2,26
sChargedWaveBeamOAM_Horizontal_Frame2:
	.short	0x4
	.short	0x40f2
	.short	0x81f7
	.short	0x2083
	.short	0x40fe
	.short	0x81f7
	.short	0x2083
	.short	0x40f8
	.short	0x81f3
	.short	0x2083
	.short	0x40f8
	.short	0x9010
	.short	0x2086
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame3,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame3,14
sChargedWaveBeamOAM_Horizontal_Frame3:
	.short	0x2
	.short	0x40ed
	.short	0x81fb
	.short	0x2083
	.short	0x4003
	.short	0x81fb
	.short	0x2083
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame4,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame4,14
sChargedWaveBeamOAM_Horizontal_Frame4:
	.short	0x2
	.short	0x40ea
	.short	0x8001
	.short	0x2083
	.short	0x4006
	.short	0x8001
	.short	0x2083
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame5,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame5,14
sChargedWaveBeamOAM_Horizontal_Frame5:
	.short	0x2
	.short	0x40ed
	.short	0x8008
	.short	0x2083
	.short	0x4003
	.short	0x8008
	.short	0x2083
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Horizontal_Frame6,object
	.size	 sChargedWaveBeamOAM_Horizontal_Frame6,14
sChargedWaveBeamOAM_Horizontal_Frame6:
	.short	0x2
	.short	0x40f1
	.short	0x900c
	.short	0x2086
	.short	0x40ff
	.short	0x900c
	.short	0x2086
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame0,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame0,14
sChargedWaveBeamOAM_Diagonal_Frame0:
	.short	0x2
	.short	0xf9
	.short	0x41f9
	.short	0x20c4
	.short	0x4
	.short	0x4
	.short	0x20e7
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame1,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame1,38
sChargedWaveBeamOAM_Diagonal_Frame1:
	.short	0x6
	.short	0xf6
	.short	0x41f9
	.short	0x20c4
	.short	0x1
	.short	0x4
	.short	0x20e7
	.short	0xf9
	.short	0x41f6
	.short	0x20c4
	.short	0x4
	.short	0x1
	.short	0x20e7
	.short	0x1
	.short	0x4001
	.short	0x20c8
	.short	0xc
	.short	0xc
	.short	0x20e7
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame2,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame2,50
sChargedWaveBeamOAM_Diagonal_Frame2:
	.short	0x8
	.short	0xf3
	.short	0x41fc
	.short	0x20c4
	.short	0xfe
	.short	0x7
	.short	0x20e7
	.short	0xfc
	.short	0x41f3
	.short	0x20c4
	.short	0x7
	.short	0x1fe
	.short	0x20e7
	.short	0xf4
	.short	0x41f4
	.short	0x20c4
	.short	0xff
	.short	0x1ff
	.short	0x20e7
	.short	0x7
	.short	0x4007
	.short	0x20c8
	.short	0x12
	.short	0x12
	.short	0x20e7
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame3,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame3,26
sChargedWaveBeamOAM_Diagonal_Frame3:
	.short	0x4
	.short	0xf2
	.short	0x4002
	.short	0x20c4
	.short	0xfd
	.short	0xd
	.short	0x20e7
	.short	0x2
	.short	0x41f2
	.short	0x20c4
	.short	0xd
	.short	0x1fd
	.short	0x20e7
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame4,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame4,26
sChargedWaveBeamOAM_Diagonal_Frame4:
	.short	0x4
	.short	0xf3
	.short	0x4006
	.short	0x20c4
	.short	0xfe
	.short	0x11
	.short	0x20e7
	.short	0x6
	.short	0x41f3
	.short	0x20c4
	.short	0x11
	.short	0x1fe
	.short	0x20e7
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame5,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame5,26
sChargedWaveBeamOAM_Diagonal_Frame5:
	.short	0x4
	.short	0xfa
	.short	0x400b
	.short	0x20c4
	.short	0x5
	.short	0x16
	.short	0x20e7
	.short	0xa
	.short	0x41fb
	.short	0x20c4
	.short	0x15
	.short	0x6
	.short	0x20e7
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Diagonal_Frame6,object
	.size	 sChargedWaveBeamOAM_Diagonal_Frame6,38
sChargedWaveBeamOAM_Diagonal_Frame6:
	.short	0x4
	.short	0x2
	.short	0x400c
	.short	0x20c8
	.short	0xd
	.short	0x17
	.short	0x20e7
	.short	0xb
	.short	0x4003
	.short	0x20c8
	.short	0x16
	.short	0xe
	.short	0x20e7
	.space	12
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame0,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame0,8
sChargedWaveBeamOAM_Vertical_Frame0:
	.short	0x1
	.short	0x80f9
	.short	0x81f8
	.short	0x208a
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame1,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame1,20
sChargedWaveBeamOAM_Vertical_Frame1:
	.short	0x3
	.short	0x80f7
	.short	0x81fa
	.short	0x208a
	.short	0x80f7
	.short	0x81f6
	.short	0x208a
	.short	0x8004
	.short	0x81f8
	.short	0x208c
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame2,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame2,26
sChargedWaveBeamOAM_Vertical_Frame2:
	.short	0x4
	.short	0x80f7
	.short	0x81fe
	.short	0x208a
	.short	0x80f7
	.short	0x81f2
	.short	0x208a
	.short	0x80f3
	.short	0x81f8
	.short	0x208a
	.short	0x8010
	.short	0x81f8
	.short	0x208c
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame3,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame3,14
sChargedWaveBeamOAM_Vertical_Frame3:
	.short	0x2
	.short	0x80fb
	.short	0x8003
	.short	0x208a
	.short	0x80fb
	.short	0x81ed
	.short	0x208a
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame4,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame4,14
sChargedWaveBeamOAM_Vertical_Frame4:
	.short	0x2
	.short	0x8001
	.short	0x8006
	.short	0x208a
	.short	0x8001
	.short	0x81ea
	.short	0x208a
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame5,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame5,14
sChargedWaveBeamOAM_Vertical_Frame5:
	.short	0x2
	.short	0x8008
	.short	0x8003
	.short	0x208a
	.short	0x8008
	.short	0x81ed
	.short	0x208a
	.align	1, 0
	.type	 sChargedWaveBeamOAM_Vertical_Frame6,object
	.size	 sChargedWaveBeamOAM_Vertical_Frame6,14
sChargedWaveBeamOAM_Vertical_Frame6:
	.short	0x2
	.short	0x800c
	.short	0x81ff
	.short	0x208c
	.short	0x800c
	.short	0x81f1
	.short	0x208c
	.align	1, 0
	.type	 sParticleChargedWaveBeamTrailOAM_Frame0,object
	.size	 sParticleChargedWaveBeamTrailOAM_Frame0,8
sParticleChargedWaveBeamTrailOAM_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20c7
	.align	1, 0
	.type	 sParticleChargedWaveBeamTrailOAM_Frame1,object
	.size	 sParticleChargedWaveBeamTrailOAM_Frame1,14
sParticleChargedWaveBeamTrailOAM_Frame1:
	.short	0x2
	.short	0x40f8
	.short	0x1f8
	.short	0x208e
	.short	0x4000
	.short	0x21f8
	.short	0x208e
	.align	1, 0
	.type	 sParticleChargedWaveBeamTrailOAM_Frame2,object
	.size	 sParticleChargedWaveBeamTrailOAM_Frame2,8
sParticleChargedWaveBeamTrailOAM_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x20ae
	.align	1, 0
	.type	 sParticleChargedWaveBeamTrailOAM_Frame3,object
	.size	 sParticleChargedWaveBeamTrailOAM_Frame3,14
sParticleChargedWaveBeamTrailOAM_Frame3:
	.short	0x2
	.short	0x40f8
	.short	0x1f8
	.short	0x20ee
	.short	0x4000
	.short	0x21f8
	.short	0x20ee
	.align	2, 0
	.type	 sWaveBeamOAM_Horizontal,object
	.size	 sWaveBeamOAM_Horizontal,64
sWaveBeamOAM_Horizontal:
	.word	sWaveBeamOAM_Horizontal_Frame0
	.byte	0x3
	.space	3
	.word	sWaveBeamOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Horizontal_Frame2
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Horizontal_Frame3
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Horizontal_Frame4
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Horizontal_Frame5
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Horizontal_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sWaveBeamOAM_Diagonal,object
	.size	 sWaveBeamOAM_Diagonal,64
sWaveBeamOAM_Diagonal:
	.word	sWaveBeamOAM_Diagonal_Frame0
	.byte	0x3
	.space	3
	.word	sWaveBeamOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Diagonal_Frame2
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Diagonal_Frame3
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Diagonal_Frame4
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Diagonal_Frame5
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Diagonal_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sWaveBeamOAM_Vertical,object
	.size	 sWaveBeamOAM_Vertical,64
sWaveBeamOAM_Vertical:
	.word	sWaveBeamOAM_Vertical_Frame0
	.byte	0x3
	.space	3
	.word	sWaveBeamOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Vertical_Frame2
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Vertical_Frame3
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Vertical_Frame4
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Vertical_Frame5
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Vertical_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sWaveBeamOAM_Horizontal_Unused,object
	.size	 sWaveBeamOAM_Horizontal_Unused,64
sWaveBeamOAM_Horizontal_Unused:
	.word	sWaveBeamOAM_Horizontal_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sWaveBeamOAM_Horizontal_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Horizontal_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Horizontal_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Horizontal_Unused_Frame4
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Horizontal_Unused_Frame5
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Horizontal_Unused_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sWaveBeamOAM_Diagonal_Unused,object
	.size	 sWaveBeamOAM_Diagonal_Unused,64
sWaveBeamOAM_Diagonal_Unused:
	.word	sWaveBeamOAM_Diagonal_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sWaveBeamOAM_Diagonal_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Diagonal_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Diagonal_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Diagonal_Unused_Frame4
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Diagonal_Unused_Frame5
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Diagonal_Unused_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sWaveBeamOAM_Vertical_Unused,object
	.size	 sWaveBeamOAM_Vertical_Unused,64
sWaveBeamOAM_Vertical_Unused:
	.word	sWaveBeamOAM_Vertical_Unused_Frame0
	.byte	0x3
	.space	3
	.word	sWaveBeamOAM_Vertical_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Vertical_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sWaveBeamOAM_Vertical_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Vertical_Unused_Frame4
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Vertical_Unused_Frame5
	.byte	0x1
	.space	3
	.word	sWaveBeamOAM_Vertical_Unused_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedWaveBeamOAM_Horizontal,object
	.size	 sChargedWaveBeamOAM_Horizontal,64
sChargedWaveBeamOAM_Horizontal:
	.word	sChargedWaveBeamOAM_Horizontal_Frame0
	.byte	0x3
	.space	3
	.word	sChargedWaveBeamOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	sChargedWaveBeamOAM_Horizontal_Frame2
	.byte	0x2
	.space	3
	.word	sChargedWaveBeamOAM_Horizontal_Frame3
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Horizontal_Frame4
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Horizontal_Frame5
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Horizontal_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedWaveBeamOAM_Diagonal,object
	.size	 sChargedWaveBeamOAM_Diagonal,64
sChargedWaveBeamOAM_Diagonal:
	.word	sChargedWaveBeamOAM_Diagonal_Frame0
	.byte	0x3
	.space	3
	.word	sChargedWaveBeamOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	sChargedWaveBeamOAM_Diagonal_Frame2
	.byte	0x2
	.space	3
	.word	sChargedWaveBeamOAM_Diagonal_Frame3
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Diagonal_Frame4
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Diagonal_Frame5
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Diagonal_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedWaveBeamOAM_Vertical,object
	.size	 sChargedWaveBeamOAM_Vertical,64
sChargedWaveBeamOAM_Vertical:
	.word	sChargedWaveBeamOAM_Vertical_Frame0
	.byte	0x3
	.space	3
	.word	sChargedWaveBeamOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	sChargedWaveBeamOAM_Vertical_Frame2
	.byte	0x2
	.space	3
	.word	sChargedWaveBeamOAM_Vertical_Frame3
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Vertical_Frame4
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Vertical_Frame5
	.byte	0x1
	.space	3
	.word	sChargedWaveBeamOAM_Vertical_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleChargedWaveBeamTrailOAM,object
	.size	 sParticleChargedWaveBeamTrailOAM,40
sParticleChargedWaveBeamTrailOAM:
	.word	sParticleChargedWaveBeamTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleChargedWaveBeamTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleChargedWaveBeamTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleChargedWaveBeamTrailOAM_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_NoWave_Frame0,object
	.size	 sPlasmaBeamOAM_Horizontal_NoWave_Frame0,8
sPlasmaBeamOAM_Horizontal_NoWave_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x41f8
	.short	0x20e0
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_NoWave_Frame1,object
	.size	 sPlasmaBeamOAM_Horizontal_NoWave_Frame1,8
sPlasmaBeamOAM_Horizontal_NoWave_Frame1:
	.short	0x1
	.short	0x40fc
	.short	0x41f9
	.short	0x20e4
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_NoWave_Frame0,object
	.size	 sPlasmaBeamOAM_Diagonal_NoWave_Frame0,8
sPlasmaBeamOAM_Diagonal_NoWave_Frame0:
	.short	0x1
	.short	0xfb
	.short	0x41fb
	.short	0x208e
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_NoWave_Frame1,object
	.size	 sPlasmaBeamOAM_Diagonal_NoWave_Frame1,8
sPlasmaBeamOAM_Diagonal_NoWave_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x41fc
	.short	0x20ce
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_NoWave_Frame0,object
	.size	 sPlasmaBeamOAM_Vertical_NoWave_Frame0,8
sPlasmaBeamOAM_Vertical_NoWave_Frame0:
	.short	0x1
	.short	0x80f8
	.short	0x41fc
	.short	0x2083
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_NoWave_Frame1,object
	.size	 sPlasmaBeamOAM_Vertical_NoWave_Frame1,8
sPlasmaBeamOAM_Vertical_NoWave_Frame1:
	.short	0x1
	.short	0x80f9
	.short	0x41fc
	.short	0x2087
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame0,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame0,20
sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame0:
	.short	0x3
	.short	0x40f8
	.short	0x81f8
	.short	0x208a
	.short	0x40f8
	.short	0x4000
	.short	0x20ca
	.short	0x4000
	.short	0x6000
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame1,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame1,32
sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame1:
	.short	0x5
	.short	0x40f8
	.short	0x81f6
	.short	0x208a
	.short	0x40f8
	.short	0x4002
	.short	0x20ca
	.short	0x4000
	.short	0x6002
	.short	0x20ca
	.short	0x40f8
	.short	0x400c
	.short	0x20ca
	.short	0x4000
	.short	0x600c
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame0,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame0,26
sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame0:
	.short	0x4
	.short	0xfa
	.short	0x41fa
	.short	0x2080
	.short	0x2
	.short	0x4002
	.short	0x20a1
	.short	0xff
	.short	0x41ff
	.short	0x2084
	.short	0x7
	.short	0x4007
	.short	0x20a5
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame1,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame1,38
sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame1:
	.short	0x6
	.short	0xf8
	.short	0x41f8
	.short	0x2080
	.short	0x0
	.short	0x4000
	.short	0x20a1
	.short	0x0
	.short	0x4000
	.short	0x2084
	.short	0x8
	.short	0x4008
	.short	0x20a5
	.short	0x8
	.short	0x4008
	.short	0x2084
	.short	0x10
	.short	0x4010
	.short	0x20a5
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_NoWave_Frame0,object
	.size	 sChargedPlasmaBeamOAM_Vertical_NoWave_Frame0,26
sChargedPlasmaBeamOAM_Vertical_NoWave_Frame0:
	.short	0x4
	.short	0x80f8
	.short	0x4000
	.short	0x2088
	.short	0x80f8
	.short	0x51f8
	.short	0x2088
	.short	0x8000
	.short	0x4000
	.short	0x2089
	.short	0x8000
	.short	0x51f8
	.short	0x2089
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_NoWave_Frame1,object
	.size	 sChargedPlasmaBeamOAM_Vertical_NoWave_Frame1,38
sChargedPlasmaBeamOAM_Vertical_NoWave_Frame1:
	.short	0x6
	.short	0x80f6
	.short	0x4000
	.short	0x2088
	.short	0x80f6
	.short	0x51f8
	.short	0x2088
	.short	0x8002
	.short	0x4000
	.short	0x2089
	.short	0x8002
	.short	0x51f8
	.short	0x2089
	.short	0x800c
	.short	0x4000
	.short	0x2089
	.short	0x800c
	.short	0x51f8
	.short	0x2089
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Frame1,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Frame1,20
sPlasmaBeamOAM_Horizontal_Wave_Frame1:
	.short	0x3
	.short	0x40f8
	.short	0x41f8
	.short	0x20e0
	.short	0x4000
	.short	0x41f8
	.short	0x20e0
	.short	0x40fc
	.short	0x4006
	.short	0x20e4
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Frame2,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Frame2,26
sPlasmaBeamOAM_Horizontal_Wave_Frame2:
	.short	0x4
	.short	0x40f4
	.short	0x41f8
	.short	0x20e0
	.short	0x4004
	.short	0x41f8
	.short	0x20e0
	.short	0x40fc
	.short	0x4010
	.short	0x20e4
	.short	0x40fc
	.short	0x41f8
	.short	0x20e0
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Frame3,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Frame3,20
sPlasmaBeamOAM_Horizontal_Wave_Frame3:
	.short	0x3
	.short	0x40f0
	.short	0x41f8
	.short	0x20e0
	.short	0x4008
	.short	0x41f8
	.short	0x20e0
	.short	0x40fc
	.short	0x41f9
	.short	0x20e4
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Frame4,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Frame4,32
sPlasmaBeamOAM_Horizontal_Wave_Frame4:
	.short	0x5
	.short	0x40f3
	.short	0x41f8
	.short	0x20e0
	.short	0x4005
	.short	0x41f8
	.short	0x20e0
	.short	0x40ef
	.short	0x41f8
	.short	0x20e4
	.short	0x4009
	.short	0x41f8
	.short	0x20e4
	.short	0x40fc
	.short	0x41f8
	.short	0x20e0
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Frame5,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Frame5,26
sPlasmaBeamOAM_Horizontal_Wave_Frame5:
	.short	0x4
	.short	0x40f8
	.short	0x41f8
	.short	0x20e0
	.short	0x4000
	.short	0x41f8
	.short	0x20e0
	.short	0x40f3
	.short	0x41f8
	.short	0x20e4
	.short	0x4005
	.short	0x41f8
	.short	0x20e4
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Frame6,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Frame6,20
sPlasmaBeamOAM_Horizontal_Wave_Frame6:
	.short	0x3
	.short	0x40fc
	.short	0x41f8
	.short	0x20e0
	.short	0x40f6
	.short	0x41f8
	.short	0x20e4
	.short	0x4002
	.short	0x41f8
	.short	0x20e4
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Frame1,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Frame1,20
sPlasmaBeamOAM_Diagonal_Wave_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41fd
	.short	0x208e
	.short	0xfe
	.short	0x41f7
	.short	0x208e
	.short	0x5
	.short	0x4005
	.short	0x20ce
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Frame2,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Frame2,26
sPlasmaBeamOAM_Diagonal_Wave_Frame2:
	.short	0x4
	.short	0xf5
	.short	0x4001
	.short	0x208e
	.short	0x1
	.short	0x41f5
	.short	0x208e
	.short	0xc
	.short	0x400c
	.short	0x20ce
	.short	0xfb
	.short	0x41fb
	.short	0x208e
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Frame3,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Frame3,20
sPlasmaBeamOAM_Diagonal_Wave_Frame3:
	.short	0x3
	.short	0xf2
	.short	0x4004
	.short	0x208e
	.short	0x4
	.short	0x41f2
	.short	0x208e
	.short	0xfc
	.short	0x41fc
	.short	0x20ce
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Frame4,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Frame4,32
sPlasmaBeamOAM_Diagonal_Wave_Frame4:
	.short	0x5
	.short	0x2
	.short	0x41f4
	.short	0x208e
	.short	0xf4
	.short	0x4002
	.short	0x208e
	.short	0x5
	.short	0x41f0
	.short	0x20ce
	.short	0xf0
	.short	0x4006
	.short	0x20ce
	.short	0xfb
	.short	0x41fb
	.short	0x208e
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Frame5,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Frame5,26
sPlasmaBeamOAM_Diagonal_Wave_Frame5:
	.short	0x4
	.short	0xfe
	.short	0x41f7
	.short	0x208e
	.short	0xf8
	.short	0x41fd
	.short	0x208e
	.short	0x2
	.short	0x41f3
	.short	0x20ce
	.short	0xf3
	.short	0x4003
	.short	0x20ce
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Frame6,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Frame6,20
sPlasmaBeamOAM_Diagonal_Wave_Frame6:
	.short	0x3
	.short	0xfb
	.short	0x41fb
	.short	0x208e
	.short	0xff
	.short	0x41f7
	.short	0x20ce
	.short	0xf7
	.short	0x41ff
	.short	0x20ce
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Frame1,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Frame1,20
sPlasmaBeamOAM_Vertical_Wave_Frame1:
	.short	0x3
	.short	0x80f8
	.short	0x4000
	.short	0x2083
	.short	0x80f8
	.short	0x41f8
	.short	0x2083
	.short	0x8006
	.short	0x41fc
	.short	0x2087
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Frame2,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Frame2,26
sPlasmaBeamOAM_Vertical_Wave_Frame2:
	.short	0x4
	.short	0x80f8
	.short	0x4004
	.short	0x2083
	.short	0x80f8
	.short	0x41f4
	.short	0x2083
	.short	0x8010
	.short	0x41fc
	.short	0x2087
	.short	0x80f8
	.short	0x41fc
	.short	0x2083
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Frame3,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Frame3,20
sPlasmaBeamOAM_Vertical_Wave_Frame3:
	.short	0x3
	.short	0x80f8
	.short	0x4008
	.short	0x2083
	.short	0x80f8
	.short	0x41f0
	.short	0x2083
	.short	0x80f9
	.short	0x41fc
	.short	0x2087
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Frame4,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Frame4,32
sPlasmaBeamOAM_Vertical_Wave_Frame4:
	.short	0x5
	.short	0x80f8
	.short	0x4005
	.short	0x2083
	.short	0x80f8
	.short	0x41f3
	.short	0x2083
	.short	0x80f8
	.short	0x4009
	.short	0x2087
	.short	0x80f8
	.short	0x41ef
	.short	0x2087
	.short	0x80f8
	.short	0x41fc
	.short	0x2083
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Frame5,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Frame5,26
sPlasmaBeamOAM_Vertical_Wave_Frame5:
	.short	0x4
	.short	0x80f8
	.short	0x4000
	.short	0x2083
	.short	0x80f8
	.short	0x41f8
	.short	0x2083
	.short	0x80f8
	.short	0x4005
	.short	0x2087
	.short	0x80f8
	.short	0x41f3
	.short	0x2087
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Frame6,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Frame6,20
sPlasmaBeamOAM_Vertical_Wave_Frame6:
	.short	0x3
	.short	0x80f8
	.short	0x41fc
	.short	0x2083
	.short	0x80f8
	.short	0x4002
	.short	0x2087
	.short	0x80f8
	.short	0x41f6
	.short	0x2087
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame3,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame3,38
sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame3:
	.short	0x6
	.short	0xf7
	.short	0x3
	.short	0x208e
	.short	0x3
	.short	0x1f7
	.short	0x208e
	.short	0xf6
	.short	0x1fd
	.short	0x208f
	.short	0xfd
	.short	0x1f6
	.short	0x208f
	.short	0x4
	.short	0x4
	.short	0x208f
	.short	0x1
	.short	0x1
	.short	0x208e
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame4,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame4,26
sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame4:
	.short	0x4
	.short	0xfb
	.short	0x7
	.short	0x208f
	.short	0x7
	.short	0x1fb
	.short	0x208f
	.short	0x5
	.short	0x5
	.short	0x208f
	.short	0xff
	.short	0x1ff
	.short	0x208e
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame1,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame1,20
sPlasmaBeamOAM_Vertical_Wave_Unused_Frame1:
	.short	0x3
	.short	0xfc
	.short	0x1fe
	.short	0x20c4
	.short	0xfc
	.short	0x1fa
	.short	0x20c4
	.short	0x0
	.short	0x1fc
	.short	0x2086
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame2,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame2,32
sPlasmaBeamOAM_Vertical_Wave_Unused_Frame2:
	.short	0x5
	.short	0xf8
	.short	0x1ff
	.short	0x20c4
	.short	0xf8
	.short	0x1f9
	.short	0x20c4
	.short	0xfd
	.short	0x4
	.short	0x20c4
	.short	0xfd
	.short	0x1f4
	.short	0x20c4
	.short	0x1
	.short	0x1fc
	.short	0x20c4
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame3,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame3,32
sPlasmaBeamOAM_Vertical_Wave_Unused_Frame3:
	.short	0x5
	.short	0x1
	.short	0x6
	.short	0x20c4
	.short	0x1
	.short	0x1f2
	.short	0x20c4
	.short	0xfb
	.short	0x2
	.short	0x2086
	.short	0xfb
	.short	0x1f6
	.short	0x2086
	.short	0x7
	.short	0x1fc
	.short	0x2086
	.align	1, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame4,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Unused_Frame4,20
sPlasmaBeamOAM_Vertical_Wave_Unused_Frame4:
	.short	0x3
	.short	0x5
	.short	0x6
	.short	0x2086
	.short	0x5
	.short	0x1f2
	.short	0x2086
	.short	0xb
	.short	0x1fc
	.short	0x2086
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame0,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame0,8
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame0:
	.short	0x1
	.short	0x40f8
	.short	0x81f9
	.short	0x208a
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame1,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame1,26
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame1:
	.short	0x4
	.short	0x40f6
	.short	0x81f7
	.short	0x208a
	.short	0x40fb
	.short	0x81f7
	.short	0x208a
	.short	0x40f8
	.short	0x4004
	.short	0x20ca
	.short	0x4000
	.short	0x6004
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame2,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame2,32
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame2:
	.short	0x5
	.short	0x40f2
	.short	0x81f7
	.short	0x208a
	.short	0x40fe
	.short	0x81f7
	.short	0x208a
	.short	0x40f8
	.short	0x81f3
	.short	0x208a
	.short	0x40f8
	.short	0x4010
	.short	0x20ca
	.short	0x4000
	.short	0x6010
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame3,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame3,20
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame3:
	.short	0x3
	.short	0x40ed
	.short	0x81fb
	.short	0x208a
	.short	0x4003
	.short	0x81fb
	.short	0x208a
	.short	0x40f8
	.short	0x81f0
	.short	0x208a
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame4,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame4,26
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame4:
	.short	0x4
	.short	0x40ea
	.short	0x8001
	.short	0x208a
	.short	0x4006
	.short	0x8001
	.short	0x208a
	.short	0x40f8
	.short	0x4000
	.short	0x20ca
	.short	0x4000
	.short	0x6000
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame5,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame5,26
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame5:
	.short	0x4
	.short	0x40ed
	.short	0x8008
	.short	0x208a
	.short	0x4003
	.short	0x8008
	.short	0x208a
	.short	0x40f8
	.short	0x4010
	.short	0x20ca
	.short	0x4000
	.short	0x6010
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame6,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave_Frame6,26
sChargedPlasmaBeamOAM_Horizontal_Wave_Frame6:
	.short	0x4
	.short	0x40f1
	.short	0x400c
	.short	0x20ca
	.short	0x40f9
	.short	0x600c
	.short	0x20ca
	.short	0x40ff
	.short	0x400c
	.short	0x20ca
	.short	0x4007
	.short	0x600c
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame0,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame0,14
sChargedPlasmaBeamOAM_Diagonal_Wave_Frame0:
	.short	0x2
	.short	0xf9
	.short	0x41f9
	.short	0x2080
	.short	0x1
	.short	0x4001
	.short	0x20a1
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame1,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame1,38
sChargedPlasmaBeamOAM_Diagonal_Wave_Frame1:
	.short	0x6
	.short	0xf6
	.short	0x41f9
	.short	0x2080
	.short	0xfe
	.short	0x4001
	.short	0x20a1
	.short	0xf9
	.short	0x41f6
	.short	0x2080
	.short	0x1
	.short	0x41fe
	.short	0x20a1
	.short	0x1
	.short	0x4001
	.short	0x2084
	.short	0x9
	.short	0x4009
	.short	0x20a5
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame2,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame2,50
sChargedPlasmaBeamOAM_Diagonal_Wave_Frame2:
	.short	0x8
	.short	0xf3
	.short	0x41fc
	.short	0x2080
	.short	0xfb
	.short	0x4004
	.short	0x20a1
	.short	0xfc
	.short	0x41f3
	.short	0x2080
	.short	0x4
	.short	0x41fb
	.short	0x20a1
	.short	0xf4
	.short	0x41f4
	.short	0x2080
	.short	0xfc
	.short	0x41fc
	.short	0x20a1
	.short	0x7
	.short	0x4007
	.short	0x2084
	.short	0xf
	.short	0x400f
	.short	0x20a5
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame3,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame3,38
sChargedPlasmaBeamOAM_Diagonal_Wave_Frame3:
	.short	0x6
	.short	0xf2
	.short	0x4002
	.short	0x2080
	.short	0xfa
	.short	0x400a
	.short	0x20a1
	.short	0x2
	.short	0x41f2
	.short	0x2080
	.short	0xa
	.short	0x41fa
	.short	0x20a1
	.short	0xf0
	.short	0x41f0
	.short	0x2080
	.short	0xf8
	.short	0x41f8
	.short	0x20a1
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame4,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_Wave_Frame4,38
sChargedPlasmaBeamOAM_Diagonal_Wave_Frame4:
	.short	0x6
	.short	0xf3
	.short	0x4006
	.short	0x2080
	.short	0xfb
	.short	0x400e
	.short	0x20a1
	.short	0x6
	.short	0x41f3
	.short	0x2080
	.short	0xe
	.short	0x41fb
	.short	0x20a1
	.short	0xfc
	.short	0x41fc
	.short	0x2084
	.short	0x4
	.short	0x4004
	.short	0x20a5
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame3,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame3,38
sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame3:
	.short	0x6
	.short	0xfa
	.short	0x400a
	.short	0x2080
	.short	0x2
	.short	0x4012
	.short	0x20a1
	.short	0xa
	.short	0x41fa
	.short	0x2080
	.short	0x12
	.short	0x4002
	.short	0x20a1
	.short	0x8
	.short	0x4008
	.short	0x2084
	.short	0x10
	.short	0x4010
	.short	0x20a5
	.align	1, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame4,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame4,26
sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame4:
	.short	0x4
	.short	0x2
	.short	0x400c
	.short	0x2084
	.short	0xa
	.short	0x4014
	.short	0x20a5
	.short	0xc
	.short	0x4002
	.short	0x2084
	.short	0x14
	.short	0x400a
	.short	0x20a5
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame0,object
	.size	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame0,14
sChargedPlasmaBeamOAM_Vertical_Wave_Frame0:
	.short	0x2
	.short	0x80f9
	.short	0x4000
	.short	0x2088
	.short	0x80f9
	.short	0x51f8
	.short	0x2088
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame1,object
	.size	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame1,38
sChargedPlasmaBeamOAM_Vertical_Wave_Frame1:
	.short	0x6
	.short	0x80f7
	.short	0x4002
	.short	0x2088
	.short	0x80f7
	.short	0x51fa
	.short	0x2088
	.short	0x80f7
	.short	0x41fd
	.short	0x2088
	.short	0x80f7
	.short	0x51f5
	.short	0x2088
	.short	0x8004
	.short	0x4000
	.short	0x2089
	.short	0x8004
	.short	0x51f8
	.short	0x2089
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame2,object
	.size	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame2,50
sChargedPlasmaBeamOAM_Vertical_Wave_Frame2:
	.short	0x8
	.short	0x80f7
	.short	0x4006
	.short	0x2088
	.short	0x80f7
	.short	0x51fe
	.short	0x2088
	.short	0x80f7
	.short	0x41fa
	.short	0x2088
	.short	0x80f7
	.short	0x51f2
	.short	0x2088
	.short	0x80f4
	.short	0x4000
	.short	0x2088
	.short	0x80f4
	.short	0x51f8
	.short	0x2088
	.short	0x8010
	.short	0x4000
	.short	0x2089
	.short	0x8010
	.short	0x51f8
	.short	0x2089
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame3,object
	.size	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame3,38
sChargedPlasmaBeamOAM_Vertical_Wave_Frame3:
	.short	0x6
	.short	0x80fd
	.short	0x400b
	.short	0x2088
	.short	0x80fd
	.short	0x5003
	.short	0x2088
	.short	0x80fd
	.short	0x41f5
	.short	0x2088
	.short	0x80fd
	.short	0x51ed
	.short	0x2088
	.short	0x80f0
	.short	0x4000
	.short	0x2088
	.short	0x80f0
	.short	0x51f8
	.short	0x2088
	.align	1, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame4,object
	.size	 sChargedPlasmaBeamOAM_Vertical_Wave_Frame4,38
sChargedPlasmaBeamOAM_Vertical_Wave_Frame4:
	.short	0x6
	.short	0x8001
	.short	0x400e
	.short	0x2088
	.short	0x8001
	.short	0x5006
	.short	0x2088
	.short	0x8001
	.short	0x41f2
	.short	0x2088
	.short	0x8001
	.short	0x51ea
	.short	0x2088
	.short	0x8000
	.short	0x4000
	.short	0x2089
	.short	0x8000
	.short	0x51f8
	.short	0x2089
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame1,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame1,38
sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame1:
	.short	0x6
	.short	0x8008
	.short	0x400b
	.short	0x2088
	.short	0x8008
	.short	0x5003
	.short	0x2088
	.short	0x8008
	.short	0x41f5
	.short	0x2088
	.short	0x8008
	.short	0x51ed
	.short	0x2088
	.short	0x8010
	.short	0x4000
	.short	0x2089
	.short	0x8010
	.short	0x51f8
	.short	0x2089
	.align	1, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame2,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame2,26
sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame2:
	.short	0x4
	.short	0x800c
	.short	0x41f9
	.short	0x2089
	.short	0x800c
	.short	0x51f1
	.short	0x2089
	.short	0x800c
	.short	0x4007
	.short	0x2089
	.short	0x800c
	.short	0x51ff
	.short	0x2089
	.align	1, 0
	.type	 sParticleChargedPlasmaBeamTrailOAM_Frame1,object
	.size	 sParticleChargedPlasmaBeamTrailOAM_Frame1,26
sParticleChargedPlasmaBeamTrailOAM_Frame1:
	.short	0x4
	.short	0xf8
	.short	0x1f8
	.short	0x20ea
	.short	0xf8
	.short	0x1000
	.short	0x20ea
	.short	0x0
	.short	0x21f8
	.short	0x20ea
	.short	0x0
	.short	0x3000
	.short	0x20ea
	.align	1, 0
	.type	 sParticleChargedFullBeamTrailOAM_Frame1,object
	.size	 sParticleChargedFullBeamTrailOAM_Frame1,26
sParticleChargedFullBeamTrailOAM_Frame1:
	.short	0x4
	.short	0xf9
	.short	0x1f9
	.short	0x20ea
	.short	0xf9
	.short	0x11ff
	.short	0x20ea
	.short	0xff
	.short	0x21f9
	.short	0x20ea
	.short	0xff
	.short	0x31ff
	.short	0x20ea
	.align	1, 0
	.type	 sParticleChargedPlasmaBeamTrailOAM_Frame2,object
	.size	 sParticleChargedPlasmaBeamTrailOAM_Frame2,26
sParticleChargedPlasmaBeamTrailOAM_Frame2:
	.short	0x4
	.short	0xf8
	.short	0x1f8
	.short	0x20eb
	.short	0xf8
	.short	0x1000
	.short	0x20eb
	.short	0x0
	.short	0x21f8
	.short	0x20eb
	.short	0x0
	.short	0x3000
	.short	0x20eb
	.align	1, 0
	.type	 sParticleChargedFullBeamTrailOAM_Frame3,object
	.size	 sParticleChargedFullBeamTrailOAM_Frame3,26
sParticleChargedFullBeamTrailOAM_Frame3:
	.short	0x4
	.short	0xf9
	.short	0x1f9
	.short	0x20eb
	.short	0xf9
	.short	0x11ff
	.short	0x20eb
	.short	0xff
	.short	0x21f9
	.short	0x20eb
	.short	0xff
	.short	0x31ff
	.short	0x20eb
	.align	1, 0
	.type	 sParticleChargedPlasmaBeamTrailOAM_Frame0,object
	.size	 sParticleChargedPlasmaBeamTrailOAM_Frame0,8
sParticleChargedPlasmaBeamTrailOAM_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20c0
	.align	1, 0
	.type	 sParticleChargedFullBeamTrailOAM_Frame5,object
	.size	 sParticleChargedFullBeamTrailOAM_Frame5,8
sParticleChargedFullBeamTrailOAM_Frame5:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x2082
	.align	1, 0
	.type	 sParticleChargedFullBeamTrailOAM_Frame6,object
	.size	 sParticleChargedFullBeamTrailOAM_Frame6,8
sParticleChargedFullBeamTrailOAM_Frame6:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20c4
	.align	1, 0
	.type	 sParticleChargedPlasmaBeamTrailOAM_Frame3,object
	.size	 sParticleChargedPlasmaBeamTrailOAM_Frame3,8
sParticleChargedPlasmaBeamTrailOAM_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x2086
	.align	2, 0
	.type	 sPlasmaBeamOAM_Horizontal_NoWave,object
	.size	 sPlasmaBeamOAM_Horizontal_NoWave,24
sPlasmaBeamOAM_Horizontal_NoWave:
	.word	sPlasmaBeamOAM_Horizontal_NoWave_Frame0
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_NoWave_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Diagonal_NoWave,object
	.size	 sPlasmaBeamOAM_Diagonal_NoWave,24
sPlasmaBeamOAM_Diagonal_NoWave:
	.word	sPlasmaBeamOAM_Diagonal_NoWave_Frame0
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_NoWave_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Vertical_NoWave,object
	.size	 sPlasmaBeamOAM_Vertical_NoWave,24
sPlasmaBeamOAM_Vertical_NoWave:
	.word	sPlasmaBeamOAM_Vertical_NoWave_Frame0
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Vertical_NoWave_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Horizontal_NoWave_Unused,object
	.size	 sPlasmaBeamOAM_Horizontal_NoWave_Unused,24
sPlasmaBeamOAM_Horizontal_NoWave_Unused:
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame5
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame6
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Diagonal_NoWave_Unused,object
	.size	 sPlasmaBeamOAM_Diagonal_NoWave_Unused,24
sPlasmaBeamOAM_Diagonal_NoWave_Unused:
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame5
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame6
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Vertical_NoWave_Unused,object
	.size	 sPlasmaBeamOAM_Vertical_NoWave_Unused,24
sPlasmaBeamOAM_Vertical_NoWave_Unused:
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame5
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame6
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_NoWave,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_NoWave,24
sChargedPlasmaBeamOAM_Horizontal_NoWave:
	.word	sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame0
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_NoWave_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_NoWave,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_NoWave,24
sChargedPlasmaBeamOAM_Diagonal_NoWave:
	.word	sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame0
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Diagonal_NoWave_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_NoWave,object
	.size	 sChargedPlasmaBeamOAM_Vertical_NoWave,24
sChargedPlasmaBeamOAM_Vertical_NoWave:
	.word	sChargedPlasmaBeamOAM_Vertical_NoWave_Frame0
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Vertical_NoWave_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave,64
sPlasmaBeamOAM_Horizontal_Wave:
	.word	sPlasmaBeamOAM_Horizontal_NoWave_Frame0
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame1
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame2
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame4
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame5
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave,64
sPlasmaBeamOAM_Diagonal_Wave:
	.word	sPlasmaBeamOAM_Diagonal_NoWave_Frame0
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame1
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame2
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame4
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame5
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave,object
	.size	 sPlasmaBeamOAM_Vertical_Wave,64
sPlasmaBeamOAM_Vertical_Wave:
	.word	sPlasmaBeamOAM_Vertical_NoWave_Frame0
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame1
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame2
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame4
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame5
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Horizontal_Wave_Unused,object
	.size	 sPlasmaBeamOAM_Horizontal_Wave_Unused,48
sPlasmaBeamOAM_Horizontal_Wave_Unused:
	.word	sPlasmaBeamOAM_Horizontal_Wave_Frame5
	.byte	0x3
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame5
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame6
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame4
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Diagonal_Wave_Unused,object
	.size	 sPlasmaBeamOAM_Diagonal_Wave_Unused,48
sPlasmaBeamOAM_Diagonal_Wave_Unused:
	.word	sPlasmaBeamOAM_Diagonal_Wave_Frame5
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame4
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPlasmaBeamOAM_Vertical_Wave_Unused,object
	.size	 sPlasmaBeamOAM_Vertical_Wave_Unused,48
sPlasmaBeamOAM_Vertical_Wave_Unused:
	.word	sPlasmaBeamOAM_Vertical_Wave_Frame5
	.byte	0x3
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Vertical_Wave_Unused_Frame4
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPlasmaBeamOAM_Horizontal_Wave,object
	.size	 sChargedPlasmaBeamOAM_Horizontal_Wave,64
sChargedPlasmaBeamOAM_Horizontal_Wave:
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame0
	.byte	0x3
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame1
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame2
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame3
	.byte	0x1
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame4
	.byte	0x1
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame5
	.byte	0x1
	.space	3
	.word	sChargedPlasmaBeamOAM_Horizontal_Wave_Frame6
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPlasmaBeamOAM_Diagonal_Wave,object
	.size	 sChargedPlasmaBeamOAM_Diagonal_Wave,64
sChargedPlasmaBeamOAM_Diagonal_Wave:
	.word	sChargedPlasmaBeamOAM_Diagonal_Wave_Frame0
	.byte	0x3
	.space	3
	.word	sChargedPlasmaBeamOAM_Diagonal_Wave_Frame1
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Diagonal_Wave_Frame2
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Diagonal_Wave_Frame3
	.byte	0x1
	.space	3
	.word	sChargedPlasmaBeamOAM_Diagonal_Wave_Frame4
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame3
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Horizontal_Wave_Unused_Frame4
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPlasmaBeamOAM_Vertical_Wave,object
	.size	 sChargedPlasmaBeamOAM_Vertical_Wave,64
sChargedPlasmaBeamOAM_Vertical_Wave:
	.word	sChargedPlasmaBeamOAM_Vertical_Wave_Frame0
	.byte	0x3
	.space	3
	.word	sChargedPlasmaBeamOAM_Vertical_Wave_Frame1
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Vertical_Wave_Frame2
	.byte	0x2
	.space	3
	.word	sChargedPlasmaBeamOAM_Vertical_Wave_Frame3
	.byte	0x1
	.space	3
	.word	sChargedPlasmaBeamOAM_Vertical_Wave_Frame4
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame1
	.byte	0x1
	.space	3
	.word	sPlasmaBeamOAM_Diagonal_Wave_Unused_Frame2
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleChargedPlasmaBeamTrailOAM,object
	.size	 sParticleChargedPlasmaBeamTrailOAM,40
sParticleChargedPlasmaBeamTrailOAM:
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleChargedFullBeamTrailOAM,object
	.size	 sParticleChargedFullBeamTrailOAM,72
sParticleChargedFullBeamTrailOAM:
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame1
	.byte	0x3
	.space	3
	.word	sParticleChargedFullBeamTrailOAM_Frame1
	.byte	0x3
	.space	3
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame2
	.byte	0x3
	.space	3
	.word	sParticleChargedFullBeamTrailOAM_Frame3
	.byte	0x3
	.space	3
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleChargedFullBeamTrailOAM_Frame5
	.byte	0x4
	.space	3
	.word	sParticleChargedFullBeamTrailOAM_Frame6
	.byte	0x4
	.space	3
	.word	sParticleChargedPlasmaBeamTrailOAM_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sPistolOAM_Horizontal_Frame0,object
	.size	 sPistolOAM_Horizontal_Frame0,8
sPistolOAM_Horizontal_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x1fa
	.short	0x2080
	.align	1, 0
	.type	 sPistolOAM_Horizontal_Frame1,object
	.size	 sPistolOAM_Horizontal_Frame1,8
sPistolOAM_Horizontal_Frame1:
	.short	0x1
	.short	0x40fc
	.short	0x1fa
	.short	0x20a0
	.align	1, 0
	.type	 sPistolOAM_Diagonal_Frame0,object
	.size	 sPistolOAM_Diagonal_Frame0,8
sPistolOAM_Diagonal_Frame0:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x2082
	.align	1, 0
	.type	 sPistolOAM_Diagonal_Frame1,object
	.size	 sPistolOAM_Diagonal_Frame1,8
sPistolOAM_Diagonal_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x41f9
	.short	0x2084
	.align	1, 0
	.type	 sPitsolOAM_Vertical_Frame0,object
	.size	 sPitsolOAM_Vertical_Frame0,8
sPitsolOAM_Vertical_Frame0:
	.short	0x1
	.short	0x80fa
	.short	0x1fc
	.short	0x2086
	.align	1, 0
	.type	 sPitsolOAM_Vertical_Frame1,object
	.size	 sPitsolOAM_Vertical_Frame1,8
sPitsolOAM_Vertical_Frame1:
	.short	0x1
	.short	0x80fa
	.short	0x1fc
	.short	0x2087
	.align	1, 0
	.type	 sChargedPistolOAM_Horizontal_Frame0,object
	.size	 sChargedPistolOAM_Horizontal_Frame0,14
sChargedPistolOAM_Horizontal_Frame0:
	.short	0x2
	.short	0xf8
	.short	0x41fa
	.short	0x20c0
	.short	0xf8
	.short	0x41ff
	.short	0x20c2
	.align	1, 0
	.type	 sChargedPistolOAM_Horizontal_Frame1,object
	.size	 sChargedPistolOAM_Horizontal_Frame1,20
sChargedPistolOAM_Horizontal_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x20c2
	.short	0xf8
	.short	0x4001
	.short	0x20c0
	.short	0xf8
	.short	0x4009
	.short	0x20c2
	.align	1, 0
	.type	 sChargedPistolOAM_Diagonal_Frame0,object
	.size	 sChargedPistolOAM_Diagonal_Frame0,14
sChargedPistolOAM_Diagonal_Frame0:
	.short	0x2
	.short	0xfb
	.short	0x41fb
	.short	0x20c4
	.short	0xfe
	.short	0x41fe
	.short	0x20c6
	.align	1, 0
	.type	 sChargedPistolOAM_Diagonal_Frame1,object
	.size	 sChargedPistolOAM_Diagonal_Frame1,20
sChargedPistolOAM_Diagonal_Frame1:
	.short	0x3
	.short	0xfa
	.short	0x41fa
	.short	0x20c6
	.short	0xff
	.short	0x41ff
	.short	0x20c4
	.short	0x4
	.short	0x4004
	.short	0x20c6
	.align	1, 0
	.type	 sChargedPistolOAM_Vertical_Frame0,object
	.size	 sChargedPistolOAM_Vertical_Frame0,14
sChargedPistolOAM_Vertical_Frame0:
	.short	0x2
	.short	0xfa
	.short	0x41f8
	.short	0x20c8
	.short	0xff
	.short	0x41f8
	.short	0x20ca
	.align	1, 0
	.type	 sChargedPistolOAM_Vertical_Frame1,object
	.size	 sChargedPistolOAM_Vertical_Frame1,20
sChargedPistolOAM_Vertical_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x20ca
	.short	0x1
	.short	0x41f8
	.short	0x20c8
	.short	0x9
	.short	0x41f8
	.short	0x20ca
	.align	1, 0
	.type	 sParticleChargedPistolTrailOAM_Frame0,object
	.size	 sParticleChargedPistolTrailOAM_Frame0,8
sParticleChargedPistolTrailOAM_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ce
	.align	1, 0
	.type	 sParticleChargedPistolTrailOAM_Frame1,object
	.size	 sParticleChargedPistolTrailOAM_Frame1,8
sParticleChargedPistolTrailOAM_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20cf
	.align	1, 0
	.type	 sParticleChargedPistolTrailOAM_Frame2,object
	.size	 sParticleChargedPistolTrailOAM_Frame2,8
sParticleChargedPistolTrailOAM_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ee
	.align	1, 0
	.type	 sParticleChargedPistolTrailOAM_Frame3,object
	.size	 sParticleChargedPistolTrailOAM_Frame3,8
sParticleChargedPistolTrailOAM_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x20ef
	.align	2, 0
	.type	 sPistolOAM_Horizontal,object
	.size	 sPistolOAM_Horizontal,24
sPistolOAM_Horizontal:
	.word	sPistolOAM_Horizontal_Frame0
	.byte	0x3
	.space	3
	.word	sPistolOAM_Horizontal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPistolOAM_Diagonal,object
	.size	 sPistolOAM_Diagonal,24
sPistolOAM_Diagonal:
	.word	sPistolOAM_Diagonal_Frame0
	.byte	0x3
	.space	3
	.word	sPistolOAM_Diagonal_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPistolOAM_Vertical,object
	.size	 sPistolOAM_Vertical,24
sPistolOAM_Vertical:
	.word	sPitsolOAM_Vertical_Frame0
	.byte	0x3
	.space	3
	.word	sPitsolOAM_Vertical_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPistolOAM_Horizontal,object
	.size	 sChargedPistolOAM_Horizontal,24
sChargedPistolOAM_Horizontal:
	.word	sChargedPistolOAM_Horizontal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedPistolOAM_Horizontal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPistolOAM_Diagonal,object
	.size	 sChargedPistolOAM_Diagonal,24
sChargedPistolOAM_Diagonal:
	.word	sChargedPistolOAM_Diagonal_Frame0
	.byte	0x2
	.space	3
	.word	sChargedPistolOAM_Diagonal_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sChargedPistolOAM_Vertical,object
	.size	 sChargedPistolOAM_Vertical,24
sChargedPistolOAM_Vertical:
	.word	sChargedPistolOAM_Vertical_Frame0
	.byte	0x2
	.space	3
	.word	sChargedPistolOAM_Vertical_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleChargedPistolTrailOAM,object
	.size	 sParticleChargedPistolTrailOAM,40
sParticleChargedPistolTrailOAM:
	.word	sParticleChargedPistolTrailOAM_Frame0
	.byte	0x4
	.space	3
	.word	sParticleChargedPistolTrailOAM_Frame1
	.byte	0x4
	.space	3
	.word	sParticleChargedPistolTrailOAM_Frame2
	.byte	0x4
	.space	3
	.word	sParticleChargedPistolTrailOAM_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleEscapeOAM_Unused,object
	.size	 sParticleEscapeOAM_Unused,16
sParticleEscapeOAM_Unused:
	.word	gParticleEscapeOAMFrames
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParticleSamusReflectionOAM_Unused,object
	.size	 sParticleSamusReflectionOAM_Unused,16
sParticleSamusReflectionOAM_Unused:
	.word	gParticleSamusReflectionOAMFrames
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
