@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.data
	.align	2, 0
	.type	 sVisitedMinimapTilesPointer,object
	.size	 sVisitedMinimapTilesPointer,4
sVisitedMinimapTilesPointer:
	.word	gVisitedMinimapTiles
	.section .rodata
	.align	2, 0
	.type	 sExploredMinimapBitFlags,object
	.size	 sExploredMinimapBitFlags,128
sExploredMinimapBitFlags:
	.word	0x1
	.word	0x2
	.word	0x4
	.word	0x8
	.word	0x10
	.word	0x20
	.word	0x40
	.word	0x80
	.word	0x100
	.word	0x200
	.word	0x400
	.word	0x800
	.word	0x1000
	.word	0x2000
	.word	0x4000
	.word	0x8000
	.word	0x10000
	.word	0x20000
	.word	0x40000
	.word	0x80000
	.word	0x100000
	.word	0x200000
	.word	0x400000
	.word	0x800000
	.word	0x1000000
	.word	0x2000000
	.word	0x4000000
	.word	0x8000000
	.word	0x10000000
	.word	0x20000000
	.word	0x40000000
	.word	-0x80000000
	.align	2, 0
	.type	 sMinimapTilesCopyGFXFunctionPointers,object
	.size	 sMinimapTilesCopyGFXFunctionPointers,16
sMinimapTilesCopyGFXFunctionPointers:
	.word	MinimapCopyTileGFX
	.word	MinimapCopyTileXFlippedGFX
	.word	MinimapCopyTileYFlippedGFX
	.word	MinimapCopyTileXYFlippedGFX
	.align 2, 0 @ dont insert nops
