#ifndef ITEM_BANNER_AI_H
#define ITEM_BANNER_AI_H

#include "types.h"

// Item banner

#define ITEM_BANNER_POSE_GFX_INIT 0x8
#define ITEM_BANNER_POSE_POP_UP 0x9
#define ITEM_BANNER_POSE_STATIC 0x23
#define ITEM_BANNER_POSE_REMOVAL_INIT 0x24
#define ITEM_BANNER_POSE_REMOVAL_ANIMATION 0x25

// Save yes no cursor

#define SAVE_YES_NO_CURSOR_POSE_INPUT 0x9
#define SAVE_YES_NO_CURSOR_POSE_SAVING 0x43

#define SAVE_YES_NO_CURSOR_LEFT_POSITION 0x36
#define SAVE_YES_NO_CURSOR_RIGHT_POSITION 0x96

// Temporary place
#define MESSAGE_DUMMY 0x0
#define MESSAGE_ENERGY_TANK_ACQUIRED 0x1
#define MESSAGE_MISSILE_TANK_ACQUIRED 0x2
#define MESSAGE_FIRST_MISSILE_TANK 0x3
#define MESSAGE_SUPER_MISSILE_TANK_ACQUIRED 0x4
#define MESSAGE_FIRST_SUPER_MISSILE_TANK 0x5
#define MESSAGE_POWER_BOMB_TANK_ACQUIRED 0x6
#define MESSAGE_FIRST_POWER_BOMB_TANK 0x7
#define MESSAGE_LONG_BEAM 0x8
#define MESSAGE_CHARGE_BEAM 0x9
#define MESSAGE_ICE_BEAM 0xA
#define MESSAGE_WAVE_BEAM 0xB
#define MESSAGE_UKNOWN_ITEM_PLASMA 0xC
#define MESSAGE_BOMB 0xD
#define MESSAGE_VARIA_SUIT 0xE
#define MESSAGE_UNKNOWN_ITEM_GRAVITY 0xF
#define MESSAGE_MORPH_BALL 0x10
#define MESSAGE_SPEED_BOOSTER 0x11
#define MESSAGE_HIGH_JUMP 0x12
#define MESSAGE_SCREW_ATTACK 0x13
#define MESSAGE_UNKNOWN_ITEM_SPACE_JUMP 0x14
#define MESSAGE_POWER_GRIP 0x15
#define MESSAGE_SAVE_PROMPT 0x16
#define MESSAGE_SAVE_COMPLETE 0x17
#define MESSAGE_WEAPON_RESUPPLY_COMPLETE 0x18
#define MESSAGE_ENERGY_TANK_RECHARGE_COMPLETE 0x19
#define MESSAGE_WEAPONS_AND_ENERGY_RESTORED 0x1A
#define MESSAGE_BRINSTAR_MAP_ACQUIRED 0x1B
#define MESSAGE_KRAID_MAP_ACQUIRED 0x1C
#define MESSAGE_NORFAIR_MAP_ACQUIRED 0x1D
#define MESSAGE_RIDLEY_MAP_ACQUIRED 0x1E
#define MESSAGE_MOTHER_SHIP_MAP_ACQUIRED 0x1F
#define MESSAGE_FULLY_POWERED_SUIT 0x20
#define MESSAGE_ZEBES_ESCAPE 0x21
#define MESSAGE_CHOZODIA_ESCAPE 0x22
#define MESSAGE_ENEMY_LOCATION_ABNORMAL 0x23
#define MESSAGE_ACTIVATE_EASY_SLEEP 0x24
#define MESSAGE_PRESS_SELECT_L_AND_R 0x25
#define MESSAGE_EASY_SLEEP_PROMPT 0x26
#define MESSAGE_NONE -1

void ItemBannerInit(void);
void ItemBannerGFXInit(void);
void ItemBannerPopUp(void);
void ItemBannerStatic(void);
void ItemBannerRemovalInit(void);
void ItemBannerRemovalAnimation(void);
void ItemBanner(void);
void SaveYesNoCursor(void);

#endif /* ITEM_BANNER_AI_H* */