#ifndef SPACE_PIRATE_CARRYING_POWER_BOMB_AI
#define SPACE_PIRATE_CARRYING_POWER_BOMB_AI

#define SPACE_PIRATE_CARRYING_POWER_BOMB_POSE_SPAWNING 0x9
#define SPACE_PIRATE_CARRYING_POWER_BOMB_POSE_MOVING 0x23

void SpacePirateCarryingPowerBomb(void);
void FakePowerBomb(void);
void FakePowerBombEventTrigger(void);

#endif /* SPACE_PIRATE_CARRYING_POWER_BOMB_AI */