#ifndef GBA_DISPLAY_H
#define GBA_DISPLAY_H

#include "../types.h"

#define REG_DISPCNT (REG_BASE + 0x000)
#define REG_DISPSTAT (REG_BASE + 0x004)
#define REG_BLDCNT (REG_BASE + 0x050)
#define REG_BLDALPHA (REG_BASE + 0x052)
#define REG_BLDY (REG_BASE + 0x054)

#define PLTT_BASE 0x05000000
#define PLTT_BG ((vu16 *)(PLTT_BASE + 0x00))

#define DCNT_MODE_1 1,
#define DCNT_MODE_2 2,
#define DCNT_MODE_3 3,
#define DCNT_MODE_4 4,
#define DCNT_MODE_5 5,

#define DCNT_CGB (1 << 3)
#define DCNT_PAGE (1 << 4)
#define DCNT_OAM_HBL (1 << 5)
#define DCNT_OBJ_1D (1 << 6)
#define DCNT_BLANK (1 << 7)

#define DCNT_BG0 (1 << 8)
#define DCNT_BG1 (1 << 9)
#define DCNT_BG2 (1 << 10)
#define DCNT_BG3 (1 << 11)
#define DCNT_OBJ (1 << 12)
#define DCNT_WIN0 (1 << 13)
#define DCNT_WIN1 (1 << 14)
#define DCNT_WINOBJ (1 << 15)

#define DSTAT_IN_VBLANK (1 << 0)
#define DSTAT_IN_HBLANK (1 << 1)
#define DSTAT_VCOUNT_MATCH (1 << 2)
#define DSTAT_IF_VBLANK (1 << 3)
#define DSTAT_IF_HBLANK (1 << 4)
#define DSTAT_IF_VCOUNT (1 << 5)

#define BLDCNT_BG0_FIRST_TARGET_PIXEL 0x1
#define BLDCNT_BG1_FIRST_TARGET_PIXEL 0x2
#define BLDCNT_BG2_FIRST_TARGET_PIXEL 0x4
#define BLDCNT_BG3_FIRST_TARGET_PIXEL 0x8
#define BLDCNT_OBJ_FIRST_TARGET_PIXEL 0x10
#define BLDCNT_BACKDROP_FIRST_TARGET_PIXEL 0x20
#define BLDCNT_ALPHA_BLENDING_EFFECT 0x40
#define BLDCNT_BRIGHTNESS_INCREASE_EFFECT 0x80
#define BLDCNT_BG0_SECOND_TARGET_PIXEL 0x100
#define BLDCNT_BG1_SECOND_TARGET_PIXEL 0x200
#define BLDCNT_BG2_SECOND_TARGET_PIXEL 0x400
#define BLDCNT_BG3_SECOND_TARGET_PIXEL 0x800
#define BLDCNT_OBJ_SECOND_TARGET_PIXEL 0x1000
#define BLDCNT_BACKDROP_SECOND_TARGET_PIXEL 0x2000

#endif /* GBA_DISPLAY_H */
