@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sAtomicIdleYMovement,object
	.size	 sAtomicIdleYMovement,130
sAtomicIdleYMovement:
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x2
	.short	0x2
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x7fff
	.align	1, 0
	.type	 sAtomicIdleXMovement,object
	.size	 sAtomicIdleXMovement,162
sAtomicIdleXMovement:
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x2
	.short	0x2
	.short	0x2
	.short	0x2
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x7fff
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame0,object
	.size	 sAtomicOAM_Idle_Frame0,26
sAtomicOAM_Idle_Frame0:
	.short	0x4
	.short	0xf4
	.short	0x1fc
	.short	0x8292
	.short	0xfc
	.short	0x4
	.short	0x8291
	.short	0xf8
	.short	0x41f8
	.short	0x821a
	.short	0x1
	.short	0x1f7
	.short	0x8293
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame1,object
	.size	 sAtomicOAM_Idle_Frame1,20
sAtomicOAM_Idle_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x1f6
	.short	0x8293
	.short	0x0
	.short	0x1
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x821c
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame2,object
	.size	 sAtomicOAM_Idle_Frame2,26
sAtomicOAM_Idle_Frame2:
	.short	0x4
	.short	0xfc
	.short	0x1f4
	.short	0x8291
	.short	0x3
	.short	0x1fe
	.short	0x8292
	.short	0xf8
	.short	0x41f8
	.short	0x821e
	.short	0xf7
	.short	0x3001
	.short	0x8293
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame3,object
	.size	 sAtomicOAM_Idle_Frame3,26
sAtomicOAM_Idle_Frame3:
	.short	0x4
	.short	0xf8
	.short	0x0
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x821c
	.short	0xfb
	.short	0x1f5
	.short	0x8291
	.short	0x3
	.short	0x1fc
	.short	0x8292
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame4,object
	.size	 sAtomicOAM_Idle_Frame4,26
sAtomicOAM_Idle_Frame4:
	.short	0x4
	.short	0xfd
	.short	0x1fe
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x821a
	.short	0xf8
	.short	0x1f6
	.short	0x8291
	.short	0x3
	.short	0x1fa
	.short	0x8292
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame5,object
	.size	 sAtomicOAM_Idle_Frame5,26
sAtomicOAM_Idle_Frame5:
	.short	0x4
	.short	0x1
	.short	0x1001
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x8218
	.short	0xf5
	.short	0x11f9
	.short	0x8292
	.short	0xff
	.short	0x11f6
	.short	0x8291
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame6,object
	.size	 sAtomicOAM_Idle_Frame6,26
sAtomicOAM_Idle_Frame6:
	.short	0x4
	.short	0xf4
	.short	0x11fc
	.short	0x8292
	.short	0xfc
	.short	0x11f4
	.short	0x8291
	.short	0xf8
	.short	0x41f8
	.short	0x821a
	.short	0x1
	.short	0x1001
	.short	0x8293
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame7,object
	.size	 sAtomicOAM_Idle_Frame7,20
sAtomicOAM_Idle_Frame7:
	.short	0x3
	.short	0xf8
	.short	0x1002
	.short	0x8293
	.short	0x0
	.short	0x11f7
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x821c
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame8,object
	.size	 sAtomicOAM_Idle_Frame8,26
sAtomicOAM_Idle_Frame8:
	.short	0x4
	.short	0xfc
	.short	0x1004
	.short	0x8291
	.short	0x3
	.short	0x11fa
	.short	0x8292
	.short	0xf8
	.short	0x41f8
	.short	0x821e
	.short	0xf7
	.short	0x21f7
	.short	0x8293
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame9,object
	.size	 sAtomicOAM_Idle_Frame9,26
sAtomicOAM_Idle_Frame9:
	.short	0x4
	.short	0xf8
	.short	0x11f8
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x821c
	.short	0xfb
	.short	0x1003
	.short	0x8291
	.short	0x3
	.short	0x11fc
	.short	0x8292
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame10,object
	.size	 sAtomicOAM_Idle_Frame10,26
sAtomicOAM_Idle_Frame10:
	.short	0x4
	.short	0xfd
	.short	0x11fa
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x821a
	.short	0xf8
	.short	0x1002
	.short	0x8291
	.short	0x3
	.short	0x11fe
	.short	0x8292
	.align	1, 0
	.type	 sAtomicOAM_Idle_Frame11,object
	.size	 sAtomicOAM_Idle_Frame11,26
sAtomicOAM_Idle_Frame11:
	.short	0x4
	.short	0x1
	.short	0x1f7
	.short	0x8293
	.short	0xf8
	.short	0x41f8
	.short	0x8218
	.short	0xf5
	.short	0x1ff
	.short	0x8292
	.short	0xff
	.short	0x2
	.short	0x8291
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame0,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame0,14
sAtomicElectricityOAM_MovingVertical_Frame0:
	.short	0x2
	.short	0x8000
	.short	0x81f8
	.short	0x9215
	.short	0x4020
	.short	0x1f8
	.short	0x9295
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame1,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame1,14
sAtomicElectricityOAM_MovingVertical_Frame1:
	.short	0x2
	.short	0x8000
	.short	0x41fc
	.short	0x9217
	.short	0x20
	.short	0x1fc
	.short	0x9297
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame3,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame3,14
sAtomicElectricityOAM_MovingVertical_Frame3:
	.short	0x2
	.short	0x8008
	.short	0xb1fb
	.short	0x9215
	.short	0x4000
	.short	0x31fb
	.short	0x9295
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame5,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame5,14
sAtomicElectricityOAM_MovingVertical_Frame5:
	.short	0x2
	.short	0x8008
	.short	0x71fc
	.short	0x9217
	.short	0x0
	.short	0x31fc
	.short	0x9297
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame6,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame6,14
sAtomicElectricityOAM_MovingVertical_Frame6:
	.short	0x2
	.short	0x8000
	.short	0x91f8
	.short	0x9215
	.short	0x4020
	.short	0x11f8
	.short	0x9295
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame7,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame7,14
sAtomicElectricityOAM_MovingVertical_Frame7:
	.short	0x2
	.short	0x8000
	.short	0x51fc
	.short	0x9217
	.short	0x20
	.short	0x11fc
	.short	0x9297
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame9,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame9,14
sAtomicElectricityOAM_MovingVertical_Frame9:
	.short	0x2
	.short	0x8008
	.short	0xa1f8
	.short	0x9215
	.short	0x4000
	.short	0x21f8
	.short	0x9295
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame10,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame10,14
sAtomicElectricityOAM_MovingVertical_Frame10:
	.short	0x2
	.short	0x8008
	.short	0x61fc
	.short	0x9217
	.short	0x0
	.short	0x21fc
	.short	0x9297
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Unused_Frame0,object
	.size	 sAtomicElectricityOAM_MovingVertical_Unused_Frame0,8
sAtomicElectricityOAM_MovingVertical_Unused_Frame0:
	.short	0x1
	.short	0x8010
	.short	0x41fc
	.short	0x9258
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Unused_Frame1,object
	.size	 sAtomicElectricityOAM_MovingVertical_Unused_Frame1,8
sAtomicElectricityOAM_MovingVertical_Unused_Frame1:
	.short	0x1
	.short	0x8008
	.short	0x71fc
	.short	0x9258
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Unused_Frame2,object
	.size	 sAtomicElectricityOAM_MovingVertical_Unused_Frame2,8
sAtomicElectricityOAM_MovingVertical_Unused_Frame2:
	.short	0x1
	.short	0x8010
	.short	0x41fc
	.short	0x9279
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Unused_Frame3,object
	.size	 sAtomicElectricityOAM_MovingVertical_Unused_Frame3,8
sAtomicElectricityOAM_MovingVertical_Unused_Frame3:
	.short	0x1
	.short	0x8008
	.short	0x71fc
	.short	0x9279
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame0,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame0,8
sAtomicElectricityOAM_MovingDiagonal_Frame0:
	.short	0x1
	.short	0x0
	.short	0x81e0
	.short	0x9280
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame1,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame1,8
sAtomicElectricityOAM_MovingDiagonal_Frame1:
	.short	0x1
	.short	0x0
	.short	0x81e0
	.short	0x9284
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame3,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame3,8
sAtomicElectricityOAM_MovingDiagonal_Frame3:
	.short	0x1
	.short	0x0
	.short	0xb1e0
	.short	0x9280
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame5,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame5,8
sAtomicElectricityOAM_MovingDiagonal_Frame5:
	.short	0x1
	.short	0x0
	.short	0xb1e0
	.short	0x9284
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame6,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame6,8
sAtomicElectricityOAM_MovingDiagonal_Frame6:
	.short	0x1
	.short	0x0
	.short	0x81e0
	.short	0x9288
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame7,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame7,8
sAtomicElectricityOAM_MovingDiagonal_Frame7:
	.short	0x1
	.short	0x0
	.short	0x81e0
	.short	0x928c
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame9,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame9,8
sAtomicElectricityOAM_MovingDiagonal_Frame9:
	.short	0x1
	.short	0x0
	.short	0xb1e0
	.short	0x9288
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Frame10,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Frame10,8
sAtomicElectricityOAM_MovingDiagonal_Frame10:
	.short	0x1
	.short	0x0
	.short	0xb1e0
	.short	0x928c
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame0,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame0,8
sAtomicElectricityOAM_MovingDiagonal_Unused_Frame0:
	.short	0x1
	.short	0x10
	.short	0x41e0
	.short	0x929a
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame1,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame1,8
sAtomicElectricityOAM_MovingDiagonal_Unused_Frame1:
	.short	0x1
	.short	0x10
	.short	0x71e0
	.short	0x929a
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame2,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame2,8
sAtomicElectricityOAM_MovingDiagonal_Unused_Frame2:
	.short	0x1
	.short	0x10
	.short	0x41e0
	.short	0x92da
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame3,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Unused_Frame3,8
sAtomicElectricityOAM_MovingDiagonal_Unused_Frame3:
	.short	0x1
	.short	0x10
	.short	0x71e0
	.short	0x92da
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame0,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame0,14
sAtomicElectricityOAM_MovingHorizontal_Frame0:
	.short	0x2
	.short	0x40f8
	.short	0x81d8
	.short	0x92b0
	.short	0x80f8
	.short	0x1f8
	.short	0x92b4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame1,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame1,14
sAtomicElectricityOAM_MovingHorizontal_Frame1:
	.short	0x2
	.short	0x40fc
	.short	0x41d8
	.short	0x92f0
	.short	0xfc
	.short	0x1f8
	.short	0x92f4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame3,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame3,14
sAtomicElectricityOAM_MovingHorizontal_Frame3:
	.short	0x2
	.short	0x40fb
	.short	0xb1e0
	.short	0x92b0
	.short	0x80fb
	.short	0x31d8
	.short	0x92b4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame5,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame5,14
sAtomicElectricityOAM_MovingHorizontal_Frame5:
	.short	0x2
	.short	0x40fc
	.short	0x71e0
	.short	0x92f0
	.short	0xfc
	.short	0x31d8
	.short	0x92f4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame6,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame6,14
sAtomicElectricityOAM_MovingHorizontal_Frame6:
	.short	0x2
	.short	0x40f8
	.short	0xa1d8
	.short	0x92b0
	.short	0x80f8
	.short	0x21f8
	.short	0x92b4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame7,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame7,14
sAtomicElectricityOAM_MovingHorizontal_Frame7:
	.short	0x2
	.short	0x40fc
	.short	0x61d8
	.short	0x92f0
	.short	0xfc
	.short	0x21f8
	.short	0x92f4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame9,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame9,14
sAtomicElectricityOAM_MovingHorizontal_Frame9:
	.short	0x2
	.short	0x40f8
	.short	0x91e0
	.short	0x92b0
	.short	0x80f8
	.short	0x11d8
	.short	0x92b4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Frame10,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Frame10,14
sAtomicElectricityOAM_MovingHorizontal_Frame10:
	.short	0x2
	.short	0x40fc
	.short	0x51e0
	.short	0x92f0
	.short	0xfc
	.short	0x11d8
	.short	0x92f4
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame0,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame0,8
sAtomicElectricityOAM_MovingHorizontal_Unused_Frame0:
	.short	0x1
	.short	0x40fc
	.short	0x41d8
	.short	0x92b5
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame1,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame1,8
sAtomicElectricityOAM_MovingHorizontal_Unused_Frame1:
	.short	0x1
	.short	0x40fc
	.short	0x71d0
	.short	0x92b5
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame2,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame2,8
sAtomicElectricityOAM_MovingHorizontal_Unused_Frame2:
	.short	0x1
	.short	0x40fc
	.short	0x41d8
	.short	0x92d6
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame3,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Unused_Frame3,8
sAtomicElectricityOAM_MovingHorizontal_Unused_Frame3:
	.short	0x1
	.short	0x40fc
	.short	0x71d0
	.short	0x92d6
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame0,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame0,8
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x9290
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame1,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame1,8
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x92dc
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame2,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame2,8
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame2:
	.short	0x1
	.short	0xf0
	.short	0x81f0
	.short	0x9210
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame3,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame3,8
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame3:
	.short	0x1
	.short	0xf0
	.short	0x81f0
	.short	0x920c
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame4,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame4,26
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame4:
	.short	0x4
	.short	0xe0
	.short	0x81e0
	.short	0x9208
	.short	0xe0
	.short	0x9000
	.short	0x9208
	.short	0x0
	.short	0xa1e0
	.short	0x9208
	.short	0x0
	.short	0xb000
	.short	0x9208
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame5,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame5,50
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame5:
	.short	0x8
	.short	0xdf
	.short	0x4011
	.short	0x929a
	.short	0xdf
	.short	0x51df
	.short	0x929a
	.short	0x11
	.short	0x6011
	.short	0x929a
	.short	0x11
	.short	0x71df
	.short	0x929a
	.short	0xe0
	.short	0x81e0
	.short	0x9204
	.short	0xe0
	.short	0x9000
	.short	0x9204
	.short	0x0
	.short	0xa1e0
	.short	0x9204
	.short	0x0
	.short	0xb000
	.short	0x9204
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame6,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal_Frame6,50
sAtomicElectricityOAM_ExplodingNonDiagonal_Frame6:
	.short	0x8
	.short	0xdb
	.short	0x4015
	.short	0x92da
	.short	0xdb
	.short	0x51db
	.short	0x92da
	.short	0x15
	.short	0x6015
	.short	0x92da
	.short	0x15
	.short	0x71db
	.short	0x92da
	.short	0xe0
	.short	0x81e0
	.short	0x9200
	.short	0xe0
	.short	0x9000
	.short	0x9200
	.short	0x0
	.short	0xa1e0
	.short	0x9200
	.short	0x0
	.short	0xb000
	.short	0x9200
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingDiagonal_Frame3,object
	.size	 sAtomicElectricityOAM_ExplodingDiagonal_Frame3,8
sAtomicElectricityOAM_ExplodingDiagonal_Frame3:
	.short	0x1
	.short	0xf0
	.short	0x81f0
	.short	0x920c
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingDiagonal_Frame4,object
	.size	 sAtomicElectricityOAM_ExplodingDiagonal_Frame4,26
sAtomicElectricityOAM_ExplodingDiagonal_Frame4:
	.short	0x4
	.short	0xe0
	.short	0x81e0
	.short	0x9208
	.short	0xe0
	.short	0x9000
	.short	0x9208
	.short	0x0
	.short	0xa1e0
	.short	0x9208
	.short	0x0
	.short	0xb000
	.short	0x9208
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingDiagonal_Frame5,object
	.size	 sAtomicElectricityOAM_ExplodingDiagonal_Frame5,74
sAtomicElectricityOAM_ExplodingDiagonal_Frame5:
	.short	0xc
	.short	0xe0
	.short	0x81e0
	.short	0x9204
	.short	0xe0
	.short	0x9000
	.short	0x9204
	.short	0x0
	.short	0xa1e0
	.short	0x9204
	.short	0x0
	.short	0xb000
	.short	0x9204
	.short	0x80d8
	.short	0x1fc
	.short	0x9258
	.short	0xe8
	.short	0x1fc
	.short	0x9298
	.short	0x40fc
	.short	0x1d8
	.short	0x92b5
	.short	0xfc
	.short	0x1e8
	.short	0x92b7
	.short	0x8018
	.short	0x31fc
	.short	0x9258
	.short	0x10
	.short	0x31fc
	.short	0x9298
	.short	0x40fc
	.short	0x3018
	.short	0x92b5
	.short	0xfc
	.short	0x3010
	.short	0x92b7
	.align	1, 0
	.type	 sAtomicElectricityOAM_ExplodingDiagonal_Frame6,object
	.size	 sAtomicElectricityOAM_ExplodingDiagonal_Frame6,74
sAtomicElectricityOAM_ExplodingDiagonal_Frame6:
	.short	0xc
	.short	0xe0
	.short	0x81e0
	.short	0x9200
	.short	0xe0
	.short	0x9000
	.short	0x9200
	.short	0x0
	.short	0xa1e0
	.short	0x9200
	.short	0x0
	.short	0xb000
	.short	0x9200
	.short	0x80d0
	.short	0x1fc
	.short	0x9279
	.short	0xe0
	.short	0x1fc
	.short	0x92b9
	.short	0x40fc
	.short	0x1d0
	.short	0x92d6
	.short	0xfc
	.short	0x1e0
	.short	0x92d8
	.short	0x8020
	.short	0x31fc
	.short	0x9279
	.short	0x18
	.short	0x31fc
	.short	0x92b9
	.short	0x40fc
	.short	0x3020
	.short	0x92d6
	.short	0xfc
	.short	0x3018
	.short	0x92d8
	.align	1, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Frame2,object
	.size	 sAtomicElectricityOAM_MovingVertical_Frame2,8
sAtomicElectricityOAM_MovingVertical_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x9204
	.align	1, 0
	.type	 sAtomicElectricityOAM_Charging_Frame0,object
	.size	 sAtomicElectricityOAM_Charging_Frame0,8
sAtomicElectricityOAM_Charging_Frame0:
	.short	0x1
	.short	0x80f0
	.short	0x41f8
	.short	0x925f
	.align	1, 0
	.type	 sAtomicElectricityOAM_Charging_Frame1,object
	.size	 sAtomicElectricityOAM_Charging_Frame1,8
sAtomicElectricityOAM_Charging_Frame1:
	.short	0x1
	.short	0xfb
	.short	0x41f8
	.short	0x92de
	.align	1, 0
	.type	 sAtomicElectricityOAM_Charging_Frame2,object
	.size	 sAtomicElectricityOAM_Charging_Frame2,8
sAtomicElectricityOAM_Charging_Frame2:
	.short	0x1
	.short	0x4001
	.short	0x41f0
	.short	0x925b
	.align	1, 0
	.type	 sAtomicElectricityOAM_Charging_Frame4,object
	.size	 sAtomicElectricityOAM_Charging_Frame4,8
sAtomicElectricityOAM_Charging_Frame4:
	.short	0x1
	.short	0x80f0
	.short	0x7000
	.short	0x925f
	.align	1, 0
	.type	 sAtomicElectricityOAM_Charging_Frame5,object
	.size	 sAtomicElectricityOAM_Charging_Frame5,8
sAtomicElectricityOAM_Charging_Frame5:
	.short	0x1
	.short	0xf5
	.short	0x71f8
	.short	0x92de
	.align	1, 0
	.type	 sAtomicElectricityOAM_Charging_Frame7,object
	.size	 sAtomicElectricityOAM_Charging_Frame7,8
sAtomicElectricityOAM_Charging_Frame7:
	.short	0x1
	.short	0x40f7
	.short	0x71f0
	.short	0x925b
	.align	2, 0
	.type	 sAtomicOAM_Idle,object
	.size	 sAtomicOAM_Idle,104
sAtomicOAM_Idle:
	.word	sAtomicOAM_Idle_Frame0
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame2
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame3
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame4
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame5
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame6
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame7
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame8
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame9
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame10
	.byte	0x8
	.space	3
	.word	sAtomicOAM_Idle_Frame11
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_MovingVertical,object
	.size	 sAtomicElectricityOAM_MovingVertical,104
sAtomicElectricityOAM_MovingVertical:
	.word	sAtomicElectricityOAM_MovingVertical_Frame0
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame1
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame3
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame5
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame6
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame7
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame9
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame10
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_MovingVertical_Unused,object
	.size	 sAtomicElectricityOAM_MovingVertical_Unused,40
sAtomicElectricityOAM_MovingVertical_Unused:
	.word	sAtomicElectricityOAM_MovingVertical_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Unused_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal,object
	.size	 sAtomicElectricityOAM_MovingDiagonal,104
sAtomicElectricityOAM_MovingDiagonal:
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame0
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame1
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame3
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame5
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame6
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame7
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame9
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Frame10
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_MovingDiagonal_Unused,object
	.size	 sAtomicElectricityOAM_MovingDiagonal_Unused,40
sAtomicElectricityOAM_MovingDiagonal_Unused:
	.word	sAtomicElectricityOAM_MovingDiagonal_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingDiagonal_Unused_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal,object
	.size	 sAtomicElectricityOAM_MovingHorizontal,104
sAtomicElectricityOAM_MovingHorizontal:
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame0
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame1
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame3
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame5
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame6
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame7
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame9
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Frame10
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_MovingHorizontal_Unused,object
	.size	 sAtomicElectricityOAM_MovingHorizontal_Unused,40
sAtomicElectricityOAM_MovingHorizontal_Unused:
	.word	sAtomicElectricityOAM_MovingHorizontal_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sAtomicElectricityOAM_MovingHorizontal_Unused_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_ExplodingNonDiagonal,object
	.size	 sAtomicElectricityOAM_ExplodingNonDiagonal,64
sAtomicElectricityOAM_ExplodingNonDiagonal:
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame0
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame1
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame2
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame3
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame5
	.byte	0x4
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame6
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.space	8
	.align	2, 0
	.type	 sAtomicElectricityOAM_ExplodingDiagonal,object
	.size	 sAtomicElectricityOAM_ExplodingDiagonal,64
sAtomicElectricityOAM_ExplodingDiagonal:
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame0
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame1
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingNonDiagonal_Frame2
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingDiagonal_Frame3
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingDiagonal_Frame4
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_ExplodingDiagonal_Frame5
	.byte	0x4
	.space	3
	.word	sAtomicElectricityOAM_ExplodingDiagonal_Frame6
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sAtomicElectricityOAM_Charging,object
	.size	 sAtomicElectricityOAM_Charging,96
sAtomicElectricityOAM_Charging:
	.word	sAtomicElectricityOAM_Charging_Frame0
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame1
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame2
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1e
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame4
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame5
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1e
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame7
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_MovingVertical_Frame2
	.byte	0x1e
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame0
	.byte	0x3
	.space	3
	.word	sAtomicElectricityOAM_Charging_Frame4
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
