@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sElevatorPadOAM_Moving_Frame0,object
	.size	 sElevatorPadOAM_Moving_Frame0,8
sElevatorPadOAM_Moving_Frame0:
	.short	0x1
	.short	0x4000
	.short	0x41f0
	.short	0x8200
	.align	1, 0
	.type	 sElevatorPadOAM_Moving_Frame1,object
	.size	 sElevatorPadOAM_Moving_Frame1,8
sElevatorPadOAM_Moving_Frame1:
	.short	0x1
	.short	0x4000
	.short	0x41f0
	.short	0x8208
	.align	1, 0
	.type	 sElevatorPadOAM_Moving_Frame2,object
	.size	 sElevatorPadOAM_Moving_Frame2,8
sElevatorPadOAM_Moving_Frame2:
	.short	0x1
	.short	0x4000
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sElevatorPadOAM_Moving_Frame3,object
	.size	 sElevatorPadOAM_Moving_Frame3,8
sElevatorPadOAM_Moving_Frame3:
	.short	0x1
	.short	0x4000
	.short	0x1f8
	.short	0x822a
	.align	1, 0
	.type	 sElevatorPadOAM_Idle_Frame1,object
	.size	 sElevatorPadOAM_Idle_Frame1,8
sElevatorPadOAM_Idle_Frame1:
	.short	0x1
	.short	0x4000
	.short	0x41f0
	.short	0x8220
	.align	1, 0
	.type	 sElevatorPadOAM_Idle_Frame2,object
	.size	 sElevatorPadOAM_Idle_Frame2,8
sElevatorPadOAM_Idle_Frame2:
	.short	0x1
	.short	0x4000
	.short	0x41f0
	.short	0x8204
	.align	1, 0
	.type	 sElevatorPadOAM_Idle_Frame3,object
	.size	 sElevatorPadOAM_Idle_Frame3,8
sElevatorPadOAM_Idle_Frame3:
	.short	0x1
	.short	0x4000
	.short	0x41f0
	.short	0x8224
	.align	2, 0
	.type	 sElevatorPadOAM_Moving,object
	.size	 sElevatorPadOAM_Moving,40
sElevatorPadOAM_Moving:
	.word	sElevatorPadOAM_Moving_Frame0
	.byte	0x1
	.space	3
	.word	sElevatorPadOAM_Moving_Frame1
	.byte	0x2
	.space	3
	.word	sElevatorPadOAM_Moving_Frame2
	.byte	0x1
	.space	3
	.word	sElevatorPadOAM_Moving_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sElevatorPadOAM_Idle,object
	.size	 sElevatorPadOAM_Idle,56
sElevatorPadOAM_Idle:
	.word	sElevatorPadOAM_Moving_Frame0
	.byte	0x8
	.space	3
	.word	sElevatorPadOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	sElevatorPadOAM_Idle_Frame2
	.byte	0x8
	.space	3
	.word	sElevatorPadOAM_Idle_Frame3
	.byte	0x8
	.space	3
	.word	sElevatorPadOAM_Idle_Frame2
	.byte	0x8
	.space	3
	.word	sElevatorPadOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
