@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sEnemyDropOAM_SmallEnergy_Frame0,object
	.size	 sEnemyDropOAM_SmallEnergy_Frame0,8
sEnemyDropOAM_SmallEnergy_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x4183
	.align	1, 0
	.type	 sEnemyDropOAM_SmallEnergy_Frame1,object
	.size	 sEnemyDropOAM_SmallEnergy_Frame1,8
sEnemyDropOAM_SmallEnergy_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x41a3
	.align	1, 0
	.type	 sEnemyDropOAM_SmallEnergy_Frame2,object
	.size	 sEnemyDropOAM_SmallEnergy_Frame2,8
sEnemyDropOAM_SmallEnergy_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x4184
	.align	1, 0
	.type	 sEnemyDropOAM_SmallEnergy_Frame3,object
	.size	 sEnemyDropOAM_SmallEnergy_Frame3,8
sEnemyDropOAM_SmallEnergy_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x41a4
	.align	1, 0
	.type	 sEnemyDropOAM_LargeEnergy_Frame0,object
	.size	 sEnemyDropOAM_LargeEnergy_Frame0,8
sEnemyDropOAM_LargeEnergy_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x41c0
	.align	1, 0
	.type	 sEnemyDropOAM_LargeEnergy_Frame1,object
	.size	 sEnemyDropOAM_LargeEnergy_Frame1,8
sEnemyDropOAM_LargeEnergy_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x41c2
	.align	1, 0
	.type	 sEnemyDropOAM_LargeEnergy_Frame2,object
	.size	 sEnemyDropOAM_LargeEnergy_Frame2,8
sEnemyDropOAM_LargeEnergy_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x41c4
	.align	1, 0
	.type	 sEnemyDropOAM_LargeEnergy_Frame3,object
	.size	 sEnemyDropOAM_LargeEnergy_Frame3,8
sEnemyDropOAM_LargeEnergy_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x41c6
	.align	1, 0
	.type	 sEnemyDropOAM_Missile_Frame0,object
	.size	 sEnemyDropOAM_Missile_Frame0,8
sEnemyDropOAM_Missile_Frame0:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x4185
	.align	1, 0
	.type	 sEnemyDropOAM_Missile_Frame1,object
	.size	 sEnemyDropOAM_Missile_Frame1,8
sEnemyDropOAM_Missile_Frame1:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x4190
	.align	1, 0
	.type	 sEnemyDropOAM_SuperMissile_Frame0,object
	.size	 sEnemyDropOAM_SuperMissile_Frame0,8
sEnemyDropOAM_SuperMissile_Frame0:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x4186
	.align	1, 0
	.type	 sEnemyDropOAM_SuperMissile_Frame1,object
	.size	 sEnemyDropOAM_SuperMissile_Frame1,8
sEnemyDropOAM_SuperMissile_Frame1:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x4191
	.align	1, 0
	.type	 sEnemyDropOAM_PowerBomb_Frame0,object
	.size	 sEnemyDropOAM_PowerBomb_Frame0,8
sEnemyDropOAM_PowerBomb_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x414b
	.align	1, 0
	.type	 sEnemyDropOAM_PowerBomb_Frame1,object
	.size	 sEnemyDropOAM_PowerBomb_Frame1,8
sEnemyDropOAM_PowerBomb_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x416c
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame0,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame0,20
sEnemyDropOAM_MultipleLargeEnergySlot1_Frame0:
	.short	0x3
	.short	0xf3
	.short	0x41f1
	.short	0x41c0
	.short	0xf8
	.short	0x4000
	.short	0x41c0
	.short	0x0
	.short	0x41f8
	.short	0x41c0
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame1,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame1,20
sEnemyDropOAM_MultipleLargeEnergySlot1_Frame1:
	.short	0x3
	.short	0xf3
	.short	0x41f1
	.short	0x41c2
	.short	0xf8
	.short	0x4000
	.short	0x41c2
	.short	0x0
	.short	0x41f8
	.short	0x41c2
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame2,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame2,20
sEnemyDropOAM_MultipleLargeEnergySlot1_Frame2:
	.short	0x3
	.short	0xf3
	.short	0x41f1
	.short	0x41c4
	.short	0xf8
	.short	0x4000
	.short	0x41c4
	.short	0x0
	.short	0x41f8
	.short	0x41c4
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame3,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot1_Frame3,20
sEnemyDropOAM_MultipleLargeEnergySlot1_Frame3:
	.short	0x3
	.short	0xf3
	.short	0x41f1
	.short	0x41c6
	.short	0xf8
	.short	0x4000
	.short	0x41c6
	.short	0x0
	.short	0x41f8
	.short	0x41c6
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame0,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame0,20
sEnemyDropOAM_MultipleLargeEnergySlot3_Frame0:
	.short	0x3
	.short	0xf2
	.short	0x41f7
	.short	0x41c0
	.short	0xff
	.short	0x41f1
	.short	0x41c0
	.short	0xfc
	.short	0x41fc
	.short	0x41c0
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame1,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame1,20
sEnemyDropOAM_MultipleLargeEnergySlot3_Frame1:
	.short	0x3
	.short	0xf2
	.short	0x41f7
	.short	0x41c2
	.short	0xff
	.short	0x41f1
	.short	0x41c2
	.short	0xfc
	.short	0x41fc
	.short	0x41c2
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame2,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame2,20
sEnemyDropOAM_MultipleLargeEnergySlot3_Frame2:
	.short	0x3
	.short	0xf2
	.short	0x41f7
	.short	0x41c4
	.short	0xff
	.short	0x41f1
	.short	0x41c4
	.short	0xfc
	.short	0x41fc
	.short	0x41c4
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame3,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot3_Frame3,20
sEnemyDropOAM_MultipleLargeEnergySlot3_Frame3:
	.short	0x3
	.short	0xf2
	.short	0x41f7
	.short	0x41c6
	.short	0xff
	.short	0x41f1
	.short	0x41c6
	.short	0xfc
	.short	0x41fc
	.short	0x41c6
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame0,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame0,20
sEnemyDropOAM_MultipleLargeEnergySlot2_Frame0:
	.short	0x3
	.short	0xf4
	.short	0x41fb
	.short	0x41c0
	.short	0xff
	.short	0x41f3
	.short	0x41c0
	.short	0xf0
	.short	0x41f4
	.short	0x41c0
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame1,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame1,20
sEnemyDropOAM_MultipleLargeEnergySlot2_Frame1:
	.short	0x3
	.short	0xf4
	.short	0x41fb
	.short	0x41c2
	.short	0xff
	.short	0x41f3
	.short	0x41c2
	.short	0xf0
	.short	0x41f4
	.short	0x41c2
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame2,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame2,20
sEnemyDropOAM_MultipleLargeEnergySlot2_Frame2:
	.short	0x3
	.short	0xf4
	.short	0x41fb
	.short	0x41c4
	.short	0xff
	.short	0x41f3
	.short	0x41c4
	.short	0xf0
	.short	0x41f4
	.short	0x41c4
	.align	1, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame3,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot2_Frame3,20
sEnemyDropOAM_MultipleLargeEnergySlot2_Frame3:
	.short	0x3
	.short	0xf4
	.short	0x41fb
	.short	0x41c6
	.short	0xff
	.short	0x41f3
	.short	0x41c6
	.short	0xf0
	.short	0x41f4
	.short	0x41c6
	.align	2, 0
	.type	 sEnemyDropOAM_SmallEnergy,object
	.size	 sEnemyDropOAM_SmallEnergy,40
sEnemyDropOAM_SmallEnergy:
	.word	sEnemyDropOAM_SmallEnergy_Frame0
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_SmallEnergy_Frame1
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_SmallEnergy_Frame2
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_SmallEnergy_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_LargeEnergy,object
	.size	 sEnemyDropOAM_LargeEnergy,40
sEnemyDropOAM_LargeEnergy:
	.word	sEnemyDropOAM_LargeEnergy_Frame0
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_LargeEnergy_Frame1
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_LargeEnergy_Frame2
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_LargeEnergy_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_Missile,object
	.size	 sEnemyDropOAM_Missile,24
sEnemyDropOAM_Missile:
	.word	sEnemyDropOAM_Missile_Frame0
	.byte	0x4
	.space	3
	.word	sEnemyDropOAM_Missile_Frame1
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_SuperMissile,object
	.size	 sEnemyDropOAM_SuperMissile,24
sEnemyDropOAM_SuperMissile:
	.word	sEnemyDropOAM_SuperMissile_Frame0
	.byte	0x4
	.space	3
	.word	sEnemyDropOAM_SuperMissile_Frame1
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_PowerBomb,object
	.size	 sEnemyDropOAM_PowerBomb,24
sEnemyDropOAM_PowerBomb:
	.word	sEnemyDropOAM_PowerBomb_Frame0
	.byte	0x4
	.space	3
	.word	sEnemyDropOAM_PowerBomb_Frame1
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot1,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot1,40
sEnemyDropOAM_MultipleLargeEnergySlot1:
	.word	sEnemyDropOAM_MultipleLargeEnergySlot1_Frame0
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot1_Frame1
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot1_Frame2
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot1_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot3,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot3,40
sEnemyDropOAM_MultipleLargeEnergySlot3:
	.word	sEnemyDropOAM_MultipleLargeEnergySlot3_Frame0
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot3_Frame1
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot3_Frame2
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot3_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEnemyDropOAM_MultipleLargeEnergySlot2,object
	.size	 sEnemyDropOAM_MultipleLargeEnergySlot2,40
sEnemyDropOAM_MultipleLargeEnergySlot2:
	.word	sEnemyDropOAM_MultipleLargeEnergySlot2_Frame0
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot2_Frame1
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot2_Frame2
	.byte	0x8
	.space	3
	.word	sEnemyDropOAM_MultipleLargeEnergySlot2_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
