@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sEscapeGateOAM_Closed_Frame0,object
	.size	 sEscapeGateOAM_Closed_Frame0,32
sEscapeGateOAM_Closed_Frame0:
	.short	0x5
	.short	0x40c0
	.short	0x81f0
	.short	0xf3cb
	.short	0x40d0
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e0
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f0
	.short	0x81f0
	.short	0xf3d7
	.short	0x40da
	.short	0x41f0
	.short	0xf3db
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame1,object
	.size	 sEscapeGateOAM_Opening_Frame1,32
sEscapeGateOAM_Opening_Frame1:
	.short	0x5
	.short	0x40c0
	.short	0x81f0
	.short	0xf3cb
	.short	0x40d0
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e0
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f0
	.short	0x81f0
	.short	0xf3d7
	.short	0x40da
	.short	0x41f0
	.short	0xf3fb
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame2,object
	.size	 sEscapeGateOAM_Opening_Frame2,26
sEscapeGateOAM_Opening_Frame2:
	.short	0x4
	.short	0x40c0
	.short	0x81f0
	.short	0xf3cb
	.short	0x40d0
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e0
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f0
	.short	0x81f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame4,object
	.size	 sEscapeGateOAM_Opening_Frame4,26
sEscapeGateOAM_Opening_Frame4:
	.short	0x4
	.short	0x40be
	.short	0x81f0
	.short	0xf3cb
	.short	0x40ce
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e2
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f2
	.short	0x81f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame3,object
	.size	 sEscapeGateOAM_Opening_Frame3,26
sEscapeGateOAM_Opening_Frame3:
	.short	0x4
	.short	0x40bd
	.short	0x81f0
	.short	0xf3cb
	.short	0x40cd
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e3
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f3
	.short	0x81f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame5,object
	.size	 sEscapeGateOAM_Opening_Frame5,26
sEscapeGateOAM_Opening_Frame5:
	.short	0x4
	.short	0x40bc
	.short	0x81f0
	.short	0xf3cb
	.short	0x40cc
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e4
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f4
	.short	0x81f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame6,object
	.size	 sEscapeGateOAM_Opening_Frame6,26
sEscapeGateOAM_Opening_Frame6:
	.short	0x4
	.short	0x40ba
	.short	0x81f0
	.short	0xf3cb
	.short	0x40ca
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e6
	.short	0x81f0
	.short	0xf3d3
	.short	0x40f6
	.short	0x81f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame7,object
	.size	 sEscapeGateOAM_Opening_Frame7,26
sEscapeGateOAM_Opening_Frame7:
	.short	0x4
	.short	0x40c8
	.short	0x81f0
	.short	0xf3cf
	.short	0x40e8
	.short	0x81f0
	.short	0xf3d3
	.short	0x40c0
	.short	0x41f0
	.short	0xf3eb
	.short	0x40f8
	.short	0x41f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame8,object
	.size	 sEscapeGateOAM_Opening_Frame8,26
sEscapeGateOAM_Opening_Frame8:
	.short	0x4
	.short	0x40c6
	.short	0x81f0
	.short	0xf3cf
	.short	0x40ea
	.short	0x81f0
	.short	0xf3d3
	.short	0x40fa
	.short	0x41f0
	.short	0xf3d7
	.short	0x40be
	.short	0x41f0
	.short	0xf3eb
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame9,object
	.size	 sEscapeGateOAM_Opening_Frame9,26
sEscapeGateOAM_Opening_Frame9:
	.short	0x4
	.short	0x40c4
	.short	0x81f0
	.short	0xf3cf
	.short	0x40ec
	.short	0x81f0
	.short	0xf3d3
	.short	0x40bc
	.short	0x41f0
	.short	0xf3eb
	.short	0x40fc
	.short	0x41f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame10,object
	.size	 sEscapeGateOAM_Opening_Frame10,26
sEscapeGateOAM_Opening_Frame10:
	.short	0x4
	.short	0x40c2
	.short	0x81f0
	.short	0xf3cf
	.short	0x40ee
	.short	0x81f0
	.short	0xf3d3
	.short	0x40ba
	.short	0x41f0
	.short	0xf3eb
	.short	0x40fe
	.short	0x41f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame11,object
	.size	 sEscapeGateOAM_Opening_Frame11,26
sEscapeGateOAM_Opening_Frame11:
	.short	0x4
	.short	0x40c0
	.short	0x81f0
	.short	0xf3cf
	.short	0x40f0
	.short	0x81f0
	.short	0xf3d3
	.short	0x40b8
	.short	0x41f0
	.short	0xf3eb
	.short	0x4000
	.short	0x41f0
	.short	0xf3d7
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame12,object
	.size	 sEscapeGateOAM_Opening_Frame12,14
sEscapeGateOAM_Opening_Frame12:
	.short	0x2
	.short	0x40be
	.short	0x81f0
	.short	0xf3cf
	.short	0x40f2
	.short	0x81f0
	.short	0xf3d3
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame13,object
	.size	 sEscapeGateOAM_Opening_Frame13,14
sEscapeGateOAM_Opening_Frame13:
	.short	0x2
	.short	0x40bc
	.short	0x81f0
	.short	0xf3cf
	.short	0x40f4
	.short	0x81f0
	.short	0xf3d3
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame14,object
	.size	 sEscapeGateOAM_Opening_Frame14,14
sEscapeGateOAM_Opening_Frame14:
	.short	0x2
	.short	0x40ba
	.short	0x81f0
	.short	0xf3cf
	.short	0x40f6
	.short	0x81f0
	.short	0xf3d3
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame15,object
	.size	 sEscapeGateOAM_Opening_Frame15,14
sEscapeGateOAM_Opening_Frame15:
	.short	0x2
	.short	0x40b8
	.short	0x81f0
	.short	0xf3cf
	.short	0x40f8
	.short	0x81f0
	.short	0xf3d3
	.align	1, 0
	.type	 sEscapeGateOAM_Opening_Frame16,object
	.size	 sEscapeGateOAM_Opening_Frame16,14
sEscapeGateOAM_Opening_Frame16:
	.short	0x2
	.short	0x40be
	.short	0x41f0
	.short	0xf3ef
	.short	0x40fa
	.short	0x41f0
	.short	0xf3d3
	.align	2, 0
	.type	 sEscapeGateOAM_Closed,object
	.size	 sEscapeGateOAM_Closed,16
sEscapeGateOAM_Closed:
	.word	sEscapeGateOAM_Closed_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEscapeGateOAM_Opening,object
	.size	 sEscapeGateOAM_Opening,144
sEscapeGateOAM_Opening:
	.word	sEscapeGateOAM_Closed_Frame0
	.byte	0x32
	.space	3
	.word	sEscapeGateOAM_Opening_Frame1
	.byte	0xc
	.space	3
	.word	sEscapeGateOAM_Opening_Frame2
	.byte	0x32
	.space	3
	.word	sEscapeGateOAM_Opening_Frame3
	.byte	0x4
	.space	3
	.word	sEscapeGateOAM_Opening_Frame4
	.byte	0xa
	.space	3
	.word	sEscapeGateOAM_Opening_Frame5
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame6
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame7
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame8
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame9
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame10
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame11
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame12
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame13
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame14
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame15
	.byte	0x1
	.space	3
	.word	sEscapeGateOAM_Opening_Frame16
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sEscapeGateOAM_Opened,object
	.size	 sEscapeGateOAM_Opened,16
sEscapeGateOAM_Opened:
	.word	sEscapeGateOAM_Opening_Frame16
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
