@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sFallingChozoPillarOAM_Falling_Frame0,object
	.size	 sFallingChozoPillarOAM_Falling_Frame0,50
sFallingChozoPillarOAM_Falling_Frame0:
	.short	0x8
	.short	0x40f0
	.short	0x81e0
	.short	0x8208
	.short	0x40f0
	.short	0x8000
	.short	0x820c
	.short	0x40e0
	.short	0x81e0
	.short	0x8200
	.short	0x40e0
	.short	0x8000
	.short	0x8204
	.short	0x40d0
	.short	0x81e0
	.short	0x8208
	.short	0x40d0
	.short	0x8000
	.short	0x820c
	.short	0x40c0
	.short	0x81e0
	.short	0x8200
	.short	0x40c0
	.short	0x8000
	.short	0x8204
	.align	2, 0
	.type	 sFallingChozoPillarOAM_Falling,object
	.size	 sFallingChozoPillarOAM_Falling,16
sFallingChozoPillarOAM_Falling:
	.word	sFallingChozoPillarOAM_Falling_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
