@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sGametOAM_Idle_Frame0,object
	.size	 sGametOAM_Idle_Frame0,20
sGametOAM_Idle_Frame0:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x8201
	.short	0xf8
	.short	0x41f8
	.short	0x8207
	.short	0x80f8
	.short	0x1f0
	.short	0x8200
	.align	1, 0
	.type	 sGametOAM_Idle_Frame1,object
	.size	 sGametOAM_Idle_Frame1,20
sGametOAM_Idle_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x8203
	.short	0xf9
	.short	0x41f8
	.short	0x8207
	.short	0x80f8
	.short	0x1f0
	.short	0x8200
	.align	1, 0
	.type	 sGametOAM_Idle_Frame2,object
	.size	 sGametOAM_Idle_Frame2,20
sGametOAM_Idle_Frame2:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x8205
	.short	0xf8
	.short	0x41f8
	.short	0x8207
	.short	0x80f8
	.short	0x1f0
	.short	0x8200
	.align	1, 0
	.type	 sGametOAM_Moving_Frame2,object
	.size	 sGametOAM_Moving_Frame2,20
sGametOAM_Moving_Frame2:
	.short	0x3
	.short	0x80f7
	.short	0x1f0
	.short	0x8200
	.short	0xf7
	.short	0x41f8
	.short	0x8201
	.short	0xf9
	.short	0x41f8
	.short	0x8209
	.align	1, 0
	.type	 sGametOAM_Moving_Frame1,object
	.size	 sGametOAM_Moving_Frame1,20
sGametOAM_Moving_Frame1:
	.short	0x3
	.short	0x80f7
	.short	0x1f0
	.short	0x8200
	.short	0xf7
	.short	0x41f8
	.short	0x8203
	.short	0xf8
	.short	0x41f8
	.short	0x8209
	.align	1, 0
	.type	 sGametOAM_Moving_Frame0,object
	.size	 sGametOAM_Moving_Frame0,20
sGametOAM_Moving_Frame0:
	.short	0x3
	.short	0xf8
	.short	0x41f8
	.short	0x8205
	.short	0xf8
	.short	0x41f8
	.short	0x8209
	.short	0x80f8
	.short	0x1f0
	.short	0x8200
	.align	2, 0
	.type	 sGametOAM_Idle,object
	.size	 sGametOAM_Idle,40
sGametOAM_Idle:
	.word	sGametOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sGametOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	sGametOAM_Idle_Frame2
	.byte	0x4
	.space	3
	.word	sGametOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sGametOAM_Moving,object
	.size	 sGametOAM_Moving,40
sGametOAM_Moving:
	.word	sGametOAM_Moving_Frame0
	.byte	0x2
	.space	3
	.word	sGametOAM_Moving_Frame1
	.byte	0x1
	.space	3
	.word	sGametOAM_Moving_Frame2
	.byte	0x3
	.space	3
	.word	sGametOAM_Moving_Frame1
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
