@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sGeegaOAM_Idle_Frame0,object
	.size	 sGeegaOAM_Idle_Frame0,8
sGeegaOAM_Idle_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sGeegaOAM_Idle_Frame1,object
	.size	 sGeegaOAM_Idle_Frame1,8
sGeegaOAM_Idle_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sGeegaOAM_Idle_Frame2,object
	.size	 sGeegaOAM_Idle_Frame2,8
sGeegaOAM_Idle_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sGeegaOAM_Moving_Frame4,object
	.size	 sGeegaOAM_Moving_Frame4,8
sGeegaOAM_Moving_Frame4:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sGeegaOAM_Moving_Frame5,object
	.size	 sGeegaOAM_Moving_Frame5,8
sGeegaOAM_Moving_Frame5:
	.short	0x1
	.short	0xf7
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sGeegaOAM_Moving_Frame6,object
	.size	 sGeegaOAM_Moving_Frame6,8
sGeegaOAM_Moving_Frame6:
	.short	0x1
	.short	0xf7
	.short	0x41f8
	.short	0x820a
	.align	2, 0
	.type	 sGeegaOAM_Idle,object
	.size	 sGeegaOAM_Idle,40
sGeegaOAM_Idle:
	.word	sGeegaOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sGeegaOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	sGeegaOAM_Idle_Frame2
	.byte	0x4
	.space	3
	.word	sGeegaOAM_Idle_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sGeegaOAM_Moving,object
	.size	 sGeegaOAM_Moving,72
sGeegaOAM_Moving:
	.word	sGeegaOAM_Idle_Frame0
	.byte	0x3
	.space	3
	.word	sGeegaOAM_Idle_Frame1
	.byte	0x2
	.space	3
	.word	sGeegaOAM_Idle_Frame2
	.byte	0x3
	.space	3
	.word	sGeegaOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sGeegaOAM_Moving_Frame4
	.byte	0x2
	.space	3
	.word	sGeegaOAM_Moving_Frame5
	.byte	0x2
	.space	3
	.word	sGeegaOAM_Moving_Frame6
	.byte	0x3
	.space	3
	.word	sGeegaOAM_Moving_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
