@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sMellaIdleYMovement,object
	.size	 sMellaIdleYMovement,130
sMellaIdleYMovement:
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x2
	.short	0x2
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x7fff
	.align	1, 0
	.type	 sMellaIdleXMovement,object
	.size	 sMellaIdleXMovement,98
sMellaIdleXMovement:
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x2
	.short	0x2
	.short	0x1
	.short	0x1
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x0
	.short	-0x1
	.short	0x7fff
	.align	1, 0
	.type	 sMellaGoingDownYMovement,object
	.size	 sMellaGoingDownYMovement,12
sMellaGoingDownYMovement:
	.short	0x1
	.short	0x2
	.short	0x3
	.short	0x4
	.short	0x5
	.short	0x6
	.align	1, 0
	.type	 sMellaGoingUpYMovement,object
	.size	 sMellaGoingUpYMovement,14
sMellaGoingUpYMovement:
	.short	0x0
	.short	0x1
	.short	0x2
	.short	0x3
	.short	0x4
	.short	0x5
	.short	0x6
	.align	1, 0
	.type	 sMellaMovingXMovement,object
	.size	 sMellaMovingXMovement,14
sMellaMovingXMovement:
	.short	0x0
	.short	0x1
	.short	0x2
	.short	0x3
	.short	0x4
	.short	0x5
	.short	0x6
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame0,object
	.size	 sMellaOAM_Idle_Frame0,8
sMellaOAM_Idle_Frame0:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8200
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame1,object
	.size	 sMellaOAM_Idle_Frame1,8
sMellaOAM_Idle_Frame1:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8204
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame2,object
	.size	 sMellaOAM_Idle_Frame2,8
sMellaOAM_Idle_Frame2:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8208
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame3,object
	.size	 sMellaOAM_Idle_Frame3,8
sMellaOAM_Idle_Frame3:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x820c
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame4,object
	.size	 sMellaOAM_Idle_Frame4,8
sMellaOAM_Idle_Frame4:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8210
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame5,object
	.size	 sMellaOAM_Idle_Frame5,8
sMellaOAM_Idle_Frame5:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8214
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame6,object
	.size	 sMellaOAM_Idle_Frame6,8
sMellaOAM_Idle_Frame6:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8218
	.align	1, 0
	.type	 sMellaOAM_Idle_Frame7,object
	.size	 sMellaOAM_Idle_Frame7,8
sMellaOAM_Idle_Frame7:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x821c
	.align	1, 0
	.type	 sMellaOAM_Moving_Frame1,object
	.size	 sMellaOAM_Moving_Frame1,14
sMellaOAM_Moving_Frame1:
	.short	0x2
	.short	0x4000
	.short	0x41f0
	.short	0x8224
	.short	0x40f8
	.short	0x41f0
	.short	0x8200
	.align	1, 0
	.type	 sMellaOAM_Moving_Frame2,object
	.size	 sMellaOAM_Moving_Frame2,14
sMellaOAM_Moving_Frame2:
	.short	0x2
	.short	0x4000
	.short	0x41f0
	.short	0x8228
	.short	0x40f8
	.short	0x41f0
	.short	0x8204
	.align	1, 0
	.type	 sMellaOAM_Moving_Frame3,object
	.size	 sMellaOAM_Moving_Frame3,14
sMellaOAM_Moving_Frame3:
	.short	0x2
	.short	0x4000
	.short	0x41f0
	.short	0x822c
	.short	0x40f8
	.short	0x41f0
	.short	0x8204
	.align	1, 0
	.type	 sMellaOAM_Moving_Frame4,object
	.size	 sMellaOAM_Moving_Frame4,14
sMellaOAM_Moving_Frame4:
	.short	0x2
	.short	0x4000
	.short	0x41f0
	.short	0x8230
	.short	0x40f8
	.short	0x41f0
	.short	0x8208
	.align	1, 0
	.type	 sMellaOAM_Moving_Frame5,object
	.size	 sMellaOAM_Moving_Frame5,14
sMellaOAM_Moving_Frame5:
	.short	0x2
	.short	0x4000
	.short	0x41f0
	.short	0x8234
	.short	0x40f8
	.short	0x41f0
	.short	0x8208
	.align	1, 0
	.type	 sMellaOAM_Moving_Frame6,object
	.size	 sMellaOAM_Moving_Frame6,14
sMellaOAM_Moving_Frame6:
	.short	0x2
	.short	0x4000
	.short	0x41f0
	.short	0x8238
	.short	0x40f8
	.short	0x41f0
	.short	0x820c
	.align	2, 0
	.type	 sMellaOAM_Idle,object
	.size	 sMellaOAM_Idle,72
sMellaOAM_Idle:
	.word	sMellaOAM_Idle_Frame0
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame1
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame2
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame3
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame4
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame5
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame6
	.byte	0x6
	.space	3
	.word	sMellaOAM_Idle_Frame7
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sMelloOAM_Moving,object
	.size	 sMelloOAM_Moving,72
sMelloOAM_Moving:
	.word	sMellaOAM_Idle_Frame0
	.byte	0x2
	.space	3
	.word	sMellaOAM_Moving_Frame1
	.byte	0x2
	.space	3
	.word	sMellaOAM_Moving_Frame2
	.byte	0x2
	.space	3
	.word	sMellaOAM_Moving_Frame3
	.byte	0x2
	.space	3
	.word	sMellaOAM_Moving_Frame4
	.byte	0x2
	.space	3
	.word	sMellaOAM_Moving_Frame5
	.byte	0x2
	.space	3
	.word	sMellaOAM_Moving_Frame6
	.byte	0x2
	.space	3
	.word	sMellaOAM_Idle_Frame7
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
