@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sMorphBallOAM_Idle_Frame0,object
	.size	 sMorphBallOAM_Idle_Frame0,8
sMorphBallOAM_Idle_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sMorphBallOAM_Idle_Frame1,object
	.size	 sMorphBallOAM_Idle_Frame1,8
sMorphBallOAM_Idle_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sMorphBallOAM_Idle_Frame2,object
	.size	 sMorphBallOAM_Idle_Frame2,8
sMorphBallOAM_Idle_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sMorphBallOutsideOAM_Idle_Frame0,object
	.size	 sMorphBallOutsideOAM_Idle_Frame0,8
sMorphBallOutsideOAM_Idle_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sMorphBallOutsideOAM_Idle_Frame1,object
	.size	 sMorphBallOutsideOAM_Idle_Frame1,8
sMorphBallOutsideOAM_Idle_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sMorphBallOutsideOAM_Idle_Frame2,object
	.size	 sMorphBallOutsideOAM_Idle_Frame2,8
sMorphBallOutsideOAM_Idle_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820a
	.align	1, 0
	.type	 sMorphBallOutsideOAM_Idle_Frame3,object
	.size	 sMorphBallOutsideOAM_Idle_Frame3,8
sMorphBallOutsideOAM_Idle_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820c
	.align	1, 0
	.type	 sMorphBallOutsideOAM_Idle_Frame4,object
	.size	 sMorphBallOutsideOAM_Idle_Frame4,8
sMorphBallOutsideOAM_Idle_Frame4:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820e
	.align	2, 0
	.type	 sMorphBallOAM_Idle,object
	.size	 sMorphBallOAM_Idle,40
sMorphBallOAM_Idle:
	.word	sMorphBallOAM_Idle_Frame0
	.byte	0x10
	.space	3
	.word	sMorphBallOAM_Idle_Frame1
	.byte	0x10
	.space	3
	.word	sMorphBallOAM_Idle_Frame2
	.byte	0x10
	.space	3
	.word	sMorphBallOAM_Idle_Frame1
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sMorphBallOutsideOAM_Idle,object
	.size	 sMorphBallOutsideOAM_Idle,48
sMorphBallOutsideOAM_Idle:
	.word	sMorphBallOutsideOAM_Idle_Frame0
	.byte	0x64
	.space	3
	.word	sMorphBallOutsideOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	sMorphBallOutsideOAM_Idle_Frame2
	.byte	0x6
	.space	3
	.word	sMorphBallOutsideOAM_Idle_Frame3
	.byte	0x4
	.space	3
	.word	sMorphBallOutsideOAM_Idle_Frame4
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
