@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sParasiteOAM_Idle_Frame0,object
	.size	 sParasiteOAM_Idle_Frame0,8
sParasiteOAM_Idle_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sParasiteOAM_Idle_Frame1,object
	.size	 sParasiteOAM_Idle_Frame1,8
sParasiteOAM_Idle_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8201
	.align	1, 0
	.type	 sParasiteOAM_Idle_Frame2,object
	.size	 sParasiteOAM_Idle_Frame2,8
sParasiteOAM_Idle_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8202
	.align	1, 0
	.type	 sParasiteOAM_Idle_Frame5,object
	.size	 sParasiteOAM_Idle_Frame5,8
sParasiteOAM_Idle_Frame5:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8203
	.align	1, 0
	.type	 sParasiteOAM_LandingAfterFalling_Frame1,object
	.size	 sParasiteOAM_LandingAfterFalling_Frame1,8
sParasiteOAM_LandingAfterFalling_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8220
	.align	1, 0
	.type	 sParasiteOAM_LandingAfterFalling_Frame2,object
	.size	 sParasiteOAM_LandingAfterFalling_Frame2,8
sParasiteOAM_LandingAfterFalling_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8221
	.align	1, 0
	.type	 sParasiteOAM_Landing_Frame0,object
	.size	 sParasiteOAM_Landing_Frame0,8
sParasiteOAM_Landing_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8222
	.align	1, 0
	.type	 sParasiteOAM_Landing_Frame2,object
	.size	 sParasiteOAM_Landing_Frame2,8
sParasiteOAM_Landing_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8223
	.align	1, 0
	.type	 sParasiteOAM_Tumbling_Frame0,object
	.size	 sParasiteOAM_Tumbling_Frame0,8
sParasiteOAM_Tumbling_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x1fb
	.short	0x8204
	.align	1, 0
	.type	 sParasiteOAM_Tumbling_Frame1,object
	.size	 sParasiteOAM_Tumbling_Frame1,8
sParasiteOAM_Tumbling_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x21fc
	.short	0x8200
	.align	1, 0
	.type	 sParasiteOAM_Tumbling_Frame2,object
	.size	 sParasiteOAM_Tumbling_Frame2,8
sParasiteOAM_Tumbling_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8205
	.align	1, 0
	.type	 sParasiteOAM_TurningBackOnFeet_Frame1,object
	.size	 sParasiteOAM_TurningBackOnFeet_Frame1,8
sParasiteOAM_TurningBackOnFeet_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x1fc
	.short	0x8224
	.align	1, 0
	.type	 sParasiteOAM_TurningBackOnFeet_Frame2,object
	.size	 sParasiteOAM_TurningBackOnFeet_Frame2,8
sParasiteOAM_TurningBackOnFeet_Frame2:
	.short	0x1
	.short	0xf9
	.short	0x1fc
	.short	0x8225
	.align	1, 0
	.type	 sParasiteOAM_TurningBackOnFeet_Frame3,object
	.size	 sParasiteOAM_TurningBackOnFeet_Frame3,8
sParasiteOAM_TurningBackOnFeet_Frame3:
	.short	0x1
	.short	0xfa
	.short	0x21fc
	.short	0x8224
	.align	1, 0
	.type	 sParasiteOAM_TurningAround_Frame0,object
	.size	 sParasiteOAM_TurningAround_Frame0,8
sParasiteOAM_TurningAround_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x1fc
	.short	0x8206
	.align	1, 0
	.type	 sParasiteOAM_JumpingUp_Unused_Frame0,object
	.size	 sParasiteOAM_JumpingUp_Unused_Frame0,8
sParasiteOAM_JumpingUp_Unused_Frame0:
	.short	0x1
	.short	0xf9
	.short	0x1fd
	.short	0x8207
	.align	1, 0
	.type	 sParasiteOAM_JumpingUp_Unused_Frame1,object
	.size	 sParasiteOAM_JumpingUp_Unused_Frame1,8
sParasiteOAM_JumpingUp_Unused_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x1fd
	.short	0x8208
	.align	1, 0
	.type	 sParasiteOAM_JumpingUp_Unused_Frame2,object
	.size	 sParasiteOAM_JumpingUp_Unused_Frame2,8
sParasiteOAM_JumpingUp_Unused_Frame2:
	.short	0x1
	.short	0xf9
	.short	0x1fd
	.short	0x8209
	.align	1, 0
	.type	 sParasiteOAM_JumpingUp_Unused_Frame5,object
	.size	 sParasiteOAM_JumpingUp_Unused_Frame5,8
sParasiteOAM_JumpingUp_Unused_Frame5:
	.short	0x1
	.short	0xf9
	.short	0x1fe
	.short	0x820a
	.align	1, 0
	.type	 sParasiteOAM_JumpingUp_Frame1,object
	.size	 sParasiteOAM_JumpingUp_Frame1,8
sParasiteOAM_JumpingUp_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x1fc
	.short	0x8207
	.align	1, 0
	.type	 sParasiteOAM_JumpingDown_Unused_Frame0,object
	.size	 sParasiteOAM_JumpingDown_Unused_Frame0,8
sParasiteOAM_JumpingDown_Unused_Frame0:
	.short	0x1
	.short	0xf9
	.short	0x1fb
	.short	0x8227
	.align	1, 0
	.type	 sParasiteOAM_JumpingDown_Unused_Frame1,object
	.size	 sParasiteOAM_JumpingDown_Unused_Frame1,8
sParasiteOAM_JumpingDown_Unused_Frame1:
	.short	0x1
	.short	0xf9
	.short	0x1fb
	.short	0x8228
	.align	1, 0
	.type	 sParasiteOAM_JumpingDown_Unused_Frame2,object
	.size	 sParasiteOAM_JumpingDown_Unused_Frame2,8
sParasiteOAM_JumpingDown_Unused_Frame2:
	.short	0x1
	.short	0xf9
	.short	0x1fb
	.short	0x8229
	.align	1, 0
	.type	 sParasiteOAM_JumpingDown_Unused_Frame5,object
	.size	 sParasiteOAM_JumpingDown_Unused_Frame5,8
sParasiteOAM_JumpingDown_Unused_Frame5:
	.short	0x1
	.short	0xf9
	.short	0x1fb
	.short	0x822a
	.align	1, 0
	.type	 sParasiteOAM_Attached_Unused_Frame0,object
	.size	 sParasiteOAM_Attached_Unused_Frame0,8
sParasiteOAM_Attached_Unused_Frame0:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x820b
	.align	1, 0
	.type	 sParasiteOAM_Attached_Unused_Frame1,object
	.size	 sParasiteOAM_Attached_Unused_Frame1,8
sParasiteOAM_Attached_Unused_Frame1:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x820c
	.align	1, 0
	.type	 sParasiteOAM_Attached_Unused_Frame2,object
	.size	 sParasiteOAM_Attached_Unused_Frame2,8
sParasiteOAM_Attached_Unused_Frame2:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x820d
	.align	1, 0
	.type	 sParasiteOAM_Attached_Unused_Frame5,object
	.size	 sParasiteOAM_Attached_Unused_Frame5,8
sParasiteOAM_Attached_Unused_Frame5:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x820e
	.align	1, 0
	.type	 sParasiteOAM_Attached_Unused_Frame6,object
	.size	 sParasiteOAM_Attached_Unused_Frame6,8
sParasiteOAM_Attached_Unused_Frame6:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x820f
	.align	1, 0
	.type	 sParasiteOAM_Attached_Frame0,object
	.size	 sParasiteOAM_Attached_Frame0,8
sParasiteOAM_Attached_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x822b
	.align	1, 0
	.type	 sParasiteOAM_Attached_Frame1,object
	.size	 sParasiteOAM_Attached_Frame1,8
sParasiteOAM_Attached_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x822c
	.align	1, 0
	.type	 sParasiteOAM_Attached_Frame2,object
	.size	 sParasiteOAM_Attached_Frame2,8
sParasiteOAM_Attached_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x822d
	.align	1, 0
	.type	 sParasiteOAM_Attached_Frame5,object
	.size	 sParasiteOAM_Attached_Frame5,8
sParasiteOAM_Attached_Frame5:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x822e
	.align	1, 0
	.type	 sParasiteOAM_Attached_Frame6,object
	.size	 sParasiteOAM_Attached_Frame6,8
sParasiteOAM_Attached_Frame6:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x822f
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame1,object
	.size	 sParasiteOAM_Expulsed_Frame1,8
sParasiteOAM_Expulsed_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8210
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame2,object
	.size	 sParasiteOAM_Expulsed_Frame2,8
sParasiteOAM_Expulsed_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8211
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame3,object
	.size	 sParasiteOAM_Expulsed_Frame3,8
sParasiteOAM_Expulsed_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8212
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame4,object
	.size	 sParasiteOAM_Expulsed_Frame4,8
sParasiteOAM_Expulsed_Frame4:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8213
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame5,object
	.size	 sParasiteOAM_Expulsed_Frame5,8
sParasiteOAM_Expulsed_Frame5:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8214
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame6,object
	.size	 sParasiteOAM_Expulsed_Frame6,8
sParasiteOAM_Expulsed_Frame6:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8215
	.align	1, 0
	.type	 sParasiteOAM_Expulsed_Frame7,object
	.size	 sParasiteOAM_Expulsed_Frame7,8
sParasiteOAM_Expulsed_Frame7:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8216
	.align	1, 0
	.type	 sParasiteOAM_Dying_Unused_Frame0,object
	.size	 sParasiteOAM_Dying_Unused_Frame0,8
sParasiteOAM_Dying_Unused_Frame0:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x8230
	.align	1, 0
	.type	 sParasiteOAM_Dying_Unused_Frame1,object
	.size	 sParasiteOAM_Dying_Unused_Frame1,8
sParasiteOAM_Dying_Unused_Frame1:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x8231
	.align	1, 0
	.type	 sParasiteOAM_Dying_Unused_Frame2,object
	.size	 sParasiteOAM_Dying_Unused_Frame2,8
sParasiteOAM_Dying_Unused_Frame2:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x8232
	.align	1, 0
	.type	 sParasiteOAM_Dying_Unused_Frame3,object
	.size	 sParasiteOAM_Dying_Unused_Frame3,8
sParasiteOAM_Dying_Unused_Frame3:
	.short	0x1
	.short	0xfa
	.short	0x1fc
	.short	0x8233
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame0,object
	.size	 sParasiteOAM_Dying_Frame0,8
sParasiteOAM_Dying_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x8217
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame1,object
	.size	 sParasiteOAM_Dying_Frame1,8
sParasiteOAM_Dying_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x31fc
	.short	0x8217
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame2,object
	.size	 sParasiteOAM_Dying_Frame2,8
sParasiteOAM_Dying_Frame2:
	.short	0x1
	.short	0xfb
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame3,object
	.size	 sParasiteOAM_Dying_Frame3,8
sParasiteOAM_Dying_Frame3:
	.short	0x1
	.short	0xfa
	.short	0x31fc
	.short	0x8218
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame4,object
	.size	 sParasiteOAM_Dying_Frame4,14
sParasiteOAM_Dying_Frame4:
	.short	0x2
	.short	0xf9
	.short	0x1fc
	.short	0x8219
	.short	0xf4
	.short	0x1fc
	.short	0x8237
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame5,object
	.size	 sParasiteOAM_Dying_Frame5,14
sParasiteOAM_Dying_Frame5:
	.short	0x2
	.short	0xf8
	.short	0x1fc
	.short	0x821a
	.short	0xf4
	.short	0x1fc
	.short	0x8238
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame6,object
	.size	 sParasiteOAM_Dying_Frame6,14
sParasiteOAM_Dying_Frame6:
	.short	0x2
	.short	0xf7
	.short	0x1fc
	.short	0x821b
	.short	0xf3
	.short	0x1fc
	.short	0x8239
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame7,object
	.size	 sParasiteOAM_Dying_Frame7,14
sParasiteOAM_Dying_Frame7:
	.short	0x2
	.short	0xf6
	.short	0x11fc
	.short	0x821b
	.short	0xf2
	.short	0x1fc
	.short	0x823a
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame8,object
	.size	 sParasiteOAM_Dying_Frame8,8
sParasiteOAM_Dying_Frame8:
	.short	0x1
	.short	0xf1
	.short	0x1fc
	.short	0x823b
	.align	1, 0
	.type	 sParasiteOAM_Dying_Frame9,object
	.size	 sParasiteOAM_Dying_Frame9,8
sParasiteOAM_Dying_Frame9:
	.short	0x1
	.short	0xf1
	.short	0x11fc
	.short	0x823b
	.align	2, 0
	.type	 sParasiteOAM_Idle,object
	.size	 sParasiteOAM_Idle,56
sParasiteOAM_Idle:
	.word	sParasiteOAM_Idle_Frame0
	.byte	0x6
	.space	3
	.word	sParasiteOAM_Idle_Frame1
	.byte	0x6
	.space	3
	.word	sParasiteOAM_Idle_Frame2
	.byte	0x6
	.space	3
	.word	sParasiteOAM_Idle_Frame1
	.byte	0x6
	.space	3
	.word	sParasiteOAM_Idle_Frame0
	.byte	0x6
	.space	3
	.word	sParasiteOAM_Idle_Frame5
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_LandingAfterFalling,object
	.size	 sParasiteOAM_LandingAfterFalling,40
sParasiteOAM_LandingAfterFalling:
	.word	sParasiteOAM_Idle_Frame0
	.byte	0x10
	.space	3
	.word	sParasiteOAM_LandingAfterFalling_Frame1
	.byte	0x10
	.space	3
	.word	sParasiteOAM_LandingAfterFalling_Frame2
	.byte	0x10
	.space	3
	.word	sParasiteOAM_LandingAfterFalling_Frame1
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Landing,object
	.size	 sParasiteOAM_Landing,32
sParasiteOAM_Landing:
	.word	sParasiteOAM_Landing_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Landing_Frame2
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Tumbling,object
	.size	 sParasiteOAM_Tumbling,40
sParasiteOAM_Tumbling:
	.word	sParasiteOAM_Tumbling_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Tumbling_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Tumbling_Frame2
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Tumbling_Frame1
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_TurningBackOnFeet,object
	.size	 sParasiteOAM_TurningBackOnFeet,64
sParasiteOAM_TurningBackOnFeet:
	.word	sParasiteOAM_Tumbling_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_TurningBackOnFeet_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_TurningBackOnFeet_Frame2
	.byte	0x4
	.space	3
	.word	sParasiteOAM_TurningBackOnFeet_Frame3
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Landing_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Landing_Frame2
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_TurningAround,object
	.size	 sParasiteOAM_TurningAround,16
sParasiteOAM_TurningAround:
	.word	sParasiteOAM_TurningAround_Frame0
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_JumpingUp_Unused,object
	.size	 sParasiteOAM_JumpingUp_Unused,56
sParasiteOAM_JumpingUp_Unused:
	.word	sParasiteOAM_JumpingUp_Unused_Frame0
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingUp_Unused_Frame1
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingUp_Unused_Frame2
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingUp_Unused_Frame1
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingUp_Unused_Frame0
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingUp_Unused_Frame5
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_JumpingDown_Unused,object
	.size	 sParasiteOAM_JumpingDown_Unused,56
sParasiteOAM_JumpingDown_Unused:
	.word	sParasiteOAM_JumpingDown_Unused_Frame0
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingDown_Unused_Frame1
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingDown_Unused_Frame2
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingDown_Unused_Frame1
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingDown_Unused_Frame0
	.byte	0x6
	.space	3
	.word	sParasiteOAM_JumpingDown_Unused_Frame5
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_JumpingUp,object
	.size	 sParasiteOAM_JumpingUp,24
sParasiteOAM_JumpingUp:
	.word	sParasiteOAM_JumpingUp_Unused_Frame0
	.byte	0x8
	.space	3
	.word	sParasiteOAM_JumpingUp_Frame1
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Attached_Unused,object
	.size	 sParasiteOAM_Attached_Unused,72
sParasiteOAM_Attached_Unused:
	.word	sParasiteOAM_Attached_Unused_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame2
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame5
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame6
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Unused_Frame5
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Attached,object
	.size	 sParasiteOAM_Attached,72
sParasiteOAM_Attached:
	.word	sParasiteOAM_Attached_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame2
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame5
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame6
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Attached_Frame5
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Expulsed,object
	.size	 sParasiteOAM_Expulsed,72
sParasiteOAM_Expulsed:
	.word	sParasiteOAM_Attached_Frame0
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame1
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame2
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame3
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame4
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame5
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame6
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Expulsed_Frame7
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Dying_Unused,object
	.size	 sParasiteOAM_Dying_Unused,40
sParasiteOAM_Dying_Unused:
	.word	sParasiteOAM_Dying_Unused_Frame0
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Dying_Unused_Frame1
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Dying_Unused_Frame2
	.byte	0x4
	.space	3
	.word	sParasiteOAM_Dying_Unused_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sParasiteOAM_Dying,object
	.size	 sParasiteOAM_Dying,88
sParasiteOAM_Dying:
	.word	sParasiteOAM_Dying_Frame0
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame1
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame2
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame3
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame4
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame5
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame6
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame7
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame8
	.byte	0x2
	.space	3
	.word	sParasiteOAM_Dying_Frame9
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
