@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sPolypProjectileYVelocity,object
	.size	 sPolypProjectileYVelocity,88
sPolypProjectileYVelocity:
	.short	-0x10
	.short	-0x10
	.short	-0xe
	.short	-0xe
	.short	-0xc
	.short	-0xc
	.short	-0xa
	.short	-0xa
	.short	-0x8
	.short	-0x8
	.short	-0x8
	.short	-0x8
	.short	-0x6
	.short	-0x6
	.short	-0x6
	.short	-0x6
	.short	-0x5
	.short	-0x5
	.short	-0x4
	.short	-0x4
	.short	-0x3
	.short	-0x2
	.short	-0x1
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x1
	.short	0x2
	.short	0x3
	.short	0x4
	.short	0x5
	.short	0x6
	.short	0x7
	.short	0x8
	.short	0x9
	.short	0xa
	.short	0xb
	.short	0xc
	.short	0xe
	.short	0x10
	.short	0x12
	.short	0x7fff
	.align	1, 0
	.type	 sPolypOAM_Idle_Frame0,object
	.size	 sPolypOAM_Idle_Frame0,26
sPolypOAM_Idle_Frame0:
	.short	0x4
	.short	0x40f7
	.short	0x41f0
	.short	0x8200
	.short	0x40f7
	.short	0x41f0
	.short	0x8204
	.short	0x40f3
	.short	0x41f0
	.short	0x8224
	.short	0x40ff
	.short	0x41f0
	.short	0x8220
	.align	1, 0
	.type	 sPolypOAM_Idle_Frame1,object
	.size	 sPolypOAM_Idle_Frame1,26
sPolypOAM_Idle_Frame1:
	.short	0x4
	.short	0x40f7
	.short	0x41f0
	.short	0x8200
	.short	0x40f7
	.short	0x41f0
	.short	0x8204
	.short	0x40f4
	.short	0x41f0
	.short	0x8224
	.short	0x40ff
	.short	0x41f0
	.short	0x8220
	.align	1, 0
	.type	 sPolypOAM_Idle_Frame2,object
	.size	 sPolypOAM_Idle_Frame2,26
sPolypOAM_Idle_Frame2:
	.short	0x4
	.short	0x40f7
	.short	0x41f0
	.short	0x8200
	.short	0x40ff
	.short	0x41f0
	.short	0x8220
	.short	0x40f8
	.short	0x41f0
	.short	0x8204
	.short	0x40f5
	.short	0x41f0
	.short	0x8224
	.align	1, 0
	.type	 sPolypOAM_Warning_Frame3,object
	.size	 sPolypOAM_Warning_Frame3,26
sPolypOAM_Warning_Frame3:
	.short	0x4
	.short	0x40f9
	.short	0x41f0
	.short	0x8200
	.short	0x4001
	.short	0x41f0
	.short	0x8220
	.short	0x40f9
	.short	0x41f0
	.short	0x8204
	.short	0x40f8
	.short	0x41f0
	.short	0x8224
	.align	1, 0
	.type	 sPolypOAM_Warning_Frame2,object
	.size	 sPolypOAM_Warning_Frame2,26
sPolypOAM_Warning_Frame2:
	.short	0x4
	.short	0x40f9
	.short	0x41f0
	.short	0x8200
	.short	0x4001
	.short	0x41f0
	.short	0x8220
	.short	0x40f9
	.short	0x41f0
	.short	0x8204
	.short	0x40f7
	.short	0x41f0
	.short	0x8224
	.align	1, 0
	.type	 sPolypOAM_Warning_Frame1,object
	.size	 sPolypOAM_Warning_Frame1,26
sPolypOAM_Warning_Frame1:
	.short	0x4
	.short	0x40f8
	.short	0x41f0
	.short	0x8200
	.short	0x4000
	.short	0x41f0
	.short	0x8220
	.short	0x40f8
	.short	0x41f0
	.short	0x8204
	.short	0x40f5
	.short	0x41f0
	.short	0x8224
	.align	1, 0
	.type	 sPolypOAM_Warning_Frame0,object
	.size	 sPolypOAM_Warning_Frame0,26
sPolypOAM_Warning_Frame0:
	.short	0x4
	.short	0x40f8
	.short	0x41f0
	.short	0x8200
	.short	0x4000
	.short	0x41f0
	.short	0x8220
	.short	0x40f8
	.short	0x41f0
	.short	0x8204
	.short	0x40f4
	.short	0x41f0
	.short	0x8224
	.align	1, 0
	.type	 sPolypOAM_AfterSpitting_Frame2,object
	.size	 sPolypOAM_AfterSpitting_Frame2,32
sPolypOAM_AfterSpitting_Frame2:
	.short	0x5
	.short	0x40f8
	.short	0x41f0
	.short	0x8200
	.short	0x4000
	.short	0x41f0
	.short	0x8220
	.short	0x40f8
	.short	0x81f0
	.short	0x8208
	.short	0x40f7
	.short	0x41f0
	.short	0x8204
	.short	0x40f2
	.short	0x41f0
	.short	0x8224
	.align	1, 0
	.type	 sPolypProjectileOAM_Right_Frame0,object
	.size	 sPolypProjectileOAM_Right_Frame0,8
sPolypProjectileOAM_Right_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8210
	.align	1, 0
	.type	 sPolypProjectileOAM_Right_Frame1,object
	.size	 sPolypProjectileOAM_Right_Frame1,8
sPolypProjectileOAM_Right_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8212
	.align	1, 0
	.type	 sPolypProjectileOAM_Right_Frame2,object
	.size	 sPolypProjectileOAM_Right_Frame2,8
sPolypProjectileOAM_Right_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8214
	.align	1, 0
	.type	 sPolypProjectileOAM_Right_Frame3,object
	.size	 sPolypProjectileOAM_Right_Frame3,8
sPolypProjectileOAM_Right_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8216
	.align	1, 0
	.type	 sPolypProjectileOAM_Left_Frame0,object
	.size	 sPolypProjectileOAM_Left_Frame0,8
sPolypProjectileOAM_Left_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x51f8
	.short	0x8210
	.align	1, 0
	.type	 sPolypProjectileOAM_Left_Frame1,object
	.size	 sPolypProjectileOAM_Left_Frame1,8
sPolypProjectileOAM_Left_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x51f8
	.short	0x8212
	.align	1, 0
	.type	 sPolypProjectileOAM_Left_Frame2,object
	.size	 sPolypProjectileOAM_Left_Frame2,8
sPolypProjectileOAM_Left_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x51f8
	.short	0x8214
	.align	1, 0
	.type	 sPolypProjectileOAM_Left_Frame3,object
	.size	 sPolypProjectileOAM_Left_Frame3,8
sPolypProjectileOAM_Left_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x51f8
	.short	0x8216
	.align	1, 0
	.type	 sPolypProjectileOAM_Exploding_Frame0,object
	.size	 sPolypProjectileOAM_Exploding_Frame0,8
sPolypProjectileOAM_Exploding_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8218
	.align	1, 0
	.type	 sPolypProjectileOAM_Exploding_Frame1,object
	.size	 sPolypProjectileOAM_Exploding_Frame1,8
sPolypProjectileOAM_Exploding_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x821a
	.align	1, 0
	.type	 sPolypProjectileOAM_Exploding_Frame2,object
	.size	 sPolypProjectileOAM_Exploding_Frame2,8
sPolypProjectileOAM_Exploding_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x821c
	.align	1, 0
	.type	 sPolypProjectileOAM_Exploding_Frame3,object
	.size	 sPolypProjectileOAM_Exploding_Frame3,8
sPolypProjectileOAM_Exploding_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x821e
	.align	2, 0
	.type	 sPolypOAM_Idle,object
	.size	 sPolypOAM_Idle,40
sPolypOAM_Idle:
	.word	sPolypOAM_Idle_Frame0
	.byte	0x10
	.space	3
	.word	sPolypOAM_Idle_Frame1
	.byte	0x10
	.space	3
	.word	sPolypOAM_Idle_Frame2
	.byte	0x10
	.space	3
	.word	sPolypOAM_Idle_Frame1
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypOAM_Warning,object
	.size	 sPolypOAM_Warning,40
sPolypOAM_Warning:
	.word	sPolypOAM_Warning_Frame0
	.byte	0x2
	.space	3
	.word	sPolypOAM_Warning_Frame1
	.byte	0x2
	.space	3
	.word	sPolypOAM_Warning_Frame2
	.byte	0x2
	.space	3
	.word	sPolypOAM_Warning_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypOAM_Spitting,object
	.size	 sPolypOAM_Spitting,16
sPolypOAM_Spitting:
	.word	sPolypOAM_Warning_Frame2
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypOAM_AfterSpitting,object
	.size	 sPolypOAM_AfterSpitting,32
sPolypOAM_AfterSpitting:
	.word	sPolypOAM_Warning_Frame1
	.byte	0x2
	.space	3
	.word	sPolypOAM_Warning_Frame0
	.byte	0x2
	.space	3
	.word	sPolypOAM_AfterSpitting_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypOAM_Retracting,object
	.size	 sPolypOAM_Retracting,24
sPolypOAM_Retracting:
	.word	sPolypOAM_Warning_Frame0
	.byte	0x2
	.space	3
	.word	sPolypOAM_Warning_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypProjectileOAM_Right,object
	.size	 sPolypProjectileOAM_Right,40
sPolypProjectileOAM_Right:
	.word	sPolypProjectileOAM_Right_Frame0
	.byte	0x6
	.space	3
	.word	sPolypProjectileOAM_Right_Frame1
	.byte	0x6
	.space	3
	.word	sPolypProjectileOAM_Right_Frame2
	.byte	0x6
	.space	3
	.word	sPolypProjectileOAM_Right_Frame3
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypProjectileOAM_Left,object
	.size	 sPolypProjectileOAM_Left,40
sPolypProjectileOAM_Left:
	.word	sPolypProjectileOAM_Left_Frame0
	.byte	0x6
	.space	3
	.word	sPolypProjectileOAM_Left_Frame1
	.byte	0x6
	.space	3
	.word	sPolypProjectileOAM_Left_Frame2
	.byte	0x6
	.space	3
	.word	sPolypProjectileOAM_Left_Frame3
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPolypProjectileOAM_Exploding,object
	.size	 sPolypProjectileOAM_Exploding,40
sPolypProjectileOAM_Exploding:
	.word	sPolypProjectileOAM_Exploding_Frame0
	.byte	0x4
	.space	3
	.word	sPolypProjectileOAM_Exploding_Frame1
	.byte	0x4
	.space	3
	.word	sPolypProjectileOAM_Exploding_Frame2
	.byte	0x4
	.space	3
	.word	sPolypProjectileOAM_Exploding_Frame3
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
