@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sPowerGripOAM_Idle_Frame0,object
	.size	 sPowerGripOAM_Idle_Frame0,8
sPowerGripOAM_Idle_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sPowerGripOAM_Idle_Frame1,object
	.size	 sPowerGripOAM_Idle_Frame1,8
sPowerGripOAM_Idle_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sPowerGripOAM_Idle_Frame2,object
	.size	 sPowerGripOAM_Idle_Frame2,8
sPowerGripOAM_Idle_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sPowerGripGlowOAM_Idle_Frame0,object
	.size	 sPowerGripGlowOAM_Idle_Frame0,20
sPowerGripGlowOAM_Idle_Frame0:
	.short	0x3
	.short	0x40f0
	.short	0x81f0
	.short	0x9206
	.short	0x0
	.short	0x71f0
	.short	0x9208
	.short	0x0
	.short	0x6000
	.short	0x9208
	.align	1, 0
	.type	 sPowerGripGlowOAM_Idle_Frame2,object
	.size	 sPowerGripGlowOAM_Idle_Frame2,20
sPowerGripGlowOAM_Idle_Frame2:
	.short	0x3
	.short	0x40f0
	.short	0x81f0
	.short	0x920a
	.short	0x0
	.short	0x71f0
	.short	0x920c
	.short	0x0
	.short	0x6000
	.short	0x920c
	.align	1, 0
	.type	 sPowerGripGlowOAM_Idle_Frame4,object
	.size	 sPowerGripGlowOAM_Idle_Frame4,20
sPowerGripGlowOAM_Idle_Frame4:
	.short	0x3
	.short	0x40f0
	.short	0x81f0
	.short	0x920e
	.short	0x0
	.short	0x71f0
	.short	0x9210
	.short	0x0
	.short	0x6000
	.short	0x9210
	.align	1, 0
	.type	 sPowerGripGlowOAM_Idle_Frame6,object
	.size	 sPowerGripGlowOAM_Idle_Frame6,20
sPowerGripGlowOAM_Idle_Frame6:
	.short	0x3
	.short	0x40f0
	.short	0x81f0
	.short	0x9212
	.short	0x0
	.short	0x71f0
	.short	0x9214
	.short	0x0
	.short	0x6000
	.short	0x9214
	.align	1, 0
	.type	 sPowerGripGlowOAM_Idle_Frame1,object
	.size	 sPowerGripGlowOAM_Idle_Frame1,8
sPowerGripGlowOAM_Idle_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x9216
	.align	2, 0
	.type	 sPowerGripOAM_Idle,object
	.size	 sPowerGripOAM_Idle,40
sPowerGripOAM_Idle:
	.word	sPowerGripOAM_Idle_Frame0
	.byte	0xa
	.space	3
	.word	sPowerGripOAM_Idle_Frame1
	.byte	0xa
	.space	3
	.word	sPowerGripOAM_Idle_Frame2
	.byte	0xa
	.space	3
	.word	sPowerGripOAM_Idle_Frame1
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sPowerGripGlowOAM_Idle,object
	.size	 sPowerGripGlowOAM_Idle,120
sPowerGripGlowOAM_Idle:
	.word	sPowerGripGlowOAM_Idle_Frame0
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame2
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame4
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame6
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame4
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame2
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame0
	.byte	0x2
	.space	3
	.word	sPowerGripGlowOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
