@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sRinkaOrangeOAM_Moving_Frame0,object
	.size	 sRinkaOrangeOAM_Moving_Frame0,8
sRinkaOrangeOAM_Moving_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sRinkaOrangeOAM_Moving_Frame1,object
	.size	 sRinkaOrangeOAM_Moving_Frame1,8
sRinkaOrangeOAM_Moving_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sRinkaOrangeOAM_Moving_Frame2,object
	.size	 sRinkaOrangeOAM_Moving_Frame2,8
sRinkaOrangeOAM_Moving_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sRinkaOrangeOAM_Spawning_Frame0,object
	.size	 sRinkaOrangeOAM_Spawning_Frame0,8
sRinkaOrangeOAM_Spawning_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820b
	.align	1, 0
	.type	 sRinkaOrangeOAM_Spawning_Frame1,object
	.size	 sRinkaOrangeOAM_Spawning_Frame1,8
sRinkaOrangeOAM_Spawning_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820d
	.align	1, 0
	.type	 sRinkaOrangeOAM_Spawning_Frame2,object
	.size	 sRinkaOrangeOAM_Spawning_Frame2,8
sRinkaOrangeOAM_Spawning_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820f
	.align	1, 0
	.type	 sRinkaOrangeOAM_Spawning_Frame3,object
	.size	 sRinkaOrangeOAM_Spawning_Frame3,8
sRinkaOrangeOAM_Spawning_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8211
	.align	1, 0
	.type	 sRinkaOrangeOAM_Spawning_Frame4,object
	.size	 sRinkaOrangeOAM_Spawning_Frame4,20
sRinkaOrangeOAM_Spawning_Frame4:
	.short	0x3
	.short	0xf7
	.short	0x41f7
	.short	0x8206
	.short	0x80f7
	.short	0x7
	.short	0x8215
	.short	0x4007
	.short	0x1f7
	.short	0x8233
	.align	1, 0
	.type	 sRinkaOrangeOAM_Spawning_Frame5,object
	.size	 sRinkaOrangeOAM_Spawning_Frame5,20
sRinkaOrangeOAM_Spawning_Frame5:
	.short	0x3
	.short	0xf7
	.short	0x41f7
	.short	0x8208
	.short	0x80f7
	.short	0x7
	.short	0x820a
	.short	0x4007
	.short	0x1f7
	.short	0x8213
	.align	2, 0
	.type	 sRinkaOrangeOAM_Spawning,object
	.size	 sRinkaOrangeOAM_Spawning,128
sRinkaOrangeOAM_Spawning:
	.word	sRinkaOrangeOAM_Spawning_Frame0
	.byte	0x4
	.space	3
	.word	sRinkaOrangeOAM_Spawning_Frame1
	.byte	0x4
	.space	3
	.word	sRinkaOrangeOAM_Spawning_Frame2
	.byte	0x4
	.space	3
	.word	sRinkaOrangeOAM_Spawning_Frame3
	.byte	0x4
	.space	3
	.word	sRinkaOrangeOAM_Spawning_Frame4
	.byte	0x4
	.space	3
	.word	sRinkaOrangeOAM_Spawning_Frame5
	.byte	0x4
	.space	3
	.word	sRinkaOrangeOAM_Spawning_Frame3
	.byte	0x8
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame0
	.byte	0x6
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame1
	.byte	0x6
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame2
	.byte	0x6
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame1
	.byte	0x8
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame0
	.byte	0x7
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame1
	.byte	0x7
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame2
	.byte	0x7
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame1
	.byte	0x7
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRinkaOrangeOAM_Moving,object
	.size	 sRinkaOrangeOAM_Moving,40
sRinkaOrangeOAM_Moving:
	.word	sRinkaOrangeOAM_Moving_Frame0
	.byte	0xc
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame1
	.byte	0xc
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame2
	.byte	0xc
	.space	3
	.word	sRinkaOrangeOAM_Moving_Frame1
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sRinkaGreenOAM_Moving_Frame0,object
	.size	 sRinkaGreenOAM_Moving_Frame0,8
sRinkaGreenOAM_Moving_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sRinkaGreenOAM_Moving_Frame1,object
	.size	 sRinkaGreenOAM_Moving_Frame1,8
sRinkaGreenOAM_Moving_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sRinkaGreenOAM_Moving_Frame2,object
	.size	 sRinkaGreenOAM_Moving_Frame2,8
sRinkaGreenOAM_Moving_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sRinkaGreenOAM_Spawning_Frame0,object
	.size	 sRinkaGreenOAM_Spawning_Frame0,8
sRinkaGreenOAM_Spawning_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820b
	.align	1, 0
	.type	 sRinkaGreenOAM_Spawning_Frame1,object
	.size	 sRinkaGreenOAM_Spawning_Frame1,8
sRinkaGreenOAM_Spawning_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820d
	.align	1, 0
	.type	 sRinkaGreenOAM_Spawning_Frame2,object
	.size	 sRinkaGreenOAM_Spawning_Frame2,8
sRinkaGreenOAM_Spawning_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820f
	.align	1, 0
	.type	 sRinkaGreenOAM_Spawning_Frame3,object
	.size	 sRinkaGreenOAM_Spawning_Frame3,8
sRinkaGreenOAM_Spawning_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8211
	.align	1, 0
	.type	 sRinkaGreenOAM_Spawning_Frame4,object
	.size	 sRinkaGreenOAM_Spawning_Frame4,20
sRinkaGreenOAM_Spawning_Frame4:
	.short	0x3
	.short	0xf7
	.short	0x41f7
	.short	0x8206
	.short	0x80f7
	.short	0x7
	.short	0x8215
	.short	0x4007
	.short	0x1f7
	.short	0x8233
	.align	1, 0
	.type	 sRinkaGreenOAM_Spawning_Frame5,object
	.size	 sRinkaGreenOAM_Spawning_Frame5,20
sRinkaGreenOAM_Spawning_Frame5:
	.short	0x3
	.short	0xf7
	.short	0x41f7
	.short	0x8208
	.short	0x80f7
	.short	0x7
	.short	0x820a
	.short	0x4007
	.short	0x1f7
	.short	0x8213
	.align	2, 0
	.type	 sRinkaGreenOAM_Spawning,object
	.size	 sRinkaGreenOAM_Spawning,128
sRinkaGreenOAM_Spawning:
	.word	sRinkaGreenOAM_Spawning_Frame0
	.byte	0x2
	.space	3
	.word	sRinkaGreenOAM_Spawning_Frame1
	.byte	0x2
	.space	3
	.word	sRinkaGreenOAM_Spawning_Frame2
	.byte	0x2
	.space	3
	.word	sRinkaGreenOAM_Spawning_Frame3
	.byte	0x2
	.space	3
	.word	sRinkaGreenOAM_Spawning_Frame4
	.byte	0x2
	.space	3
	.word	sRinkaGreenOAM_Spawning_Frame5
	.byte	0x2
	.space	3
	.word	sRinkaGreenOAM_Spawning_Frame3
	.byte	0x5
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame0
	.byte	0x3
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame1
	.byte	0x3
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame2
	.byte	0x3
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame1
	.byte	0x3
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame0
	.byte	0x4
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame1
	.byte	0x4
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame2
	.byte	0x4
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame1
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRinkaGreenOAM_Moving,object
	.size	 sRinkaGreenOAM_Moving,40
sRinkaGreenOAM_Moving:
	.word	sRinkaGreenOAM_Moving_Frame0
	.byte	0x8
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame1
	.byte	0x8
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame2
	.byte	0x8
	.space	3
	.word	sRinkaGreenOAM_Moving_Frame1
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
