@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sRipperOAM_Moving_Frame0,object
	.size	 sRipperOAM_Moving_Frame0,8
sRipperOAM_Moving_Frame0:
	.short	0x1
	.short	0x40f3
	.short	0x81f0
	.short	0x8200
	.align	1, 0
	.type	 sRipperOAM_Moving_Frame1,object
	.size	 sRipperOAM_Moving_Frame1,14
sRipperOAM_Moving_Frame1:
	.short	0x2
	.short	0xf3
	.short	0x41f0
	.short	0x8204
	.short	0xf3
	.short	0x4000
	.short	0x8202
	.align	1, 0
	.type	 sRipperOAM_Moving_Frame2,object
	.size	 sRipperOAM_Moving_Frame2,14
sRipperOAM_Moving_Frame2:
	.short	0x2
	.short	0xf3
	.short	0x41f0
	.short	0x8206
	.short	0xf3
	.short	0x4000
	.short	0x8202
	.align	1, 0
	.type	 sRipperOAM_TurningAround_Frame0,object
	.size	 sRipperOAM_TurningAround_Frame0,8
sRipperOAM_TurningAround_Frame0:
	.short	0x1
	.short	0x40f3
	.short	0x81f0
	.short	0x8208
	.align	1, 0
	.type	 sRipperOAM_TurningAround_Frame1,object
	.size	 sRipperOAM_TurningAround_Frame1,8
sRipperOAM_TurningAround_Frame1:
	.short	0x1
	.short	0xf3
	.short	0x41f8
	.short	0x820c
	.align	2, 0
	.type	 sRipperOAM_Moving,object
	.size	 sRipperOAM_Moving,40
sRipperOAM_Moving:
	.word	sRipperOAM_Moving_Frame0
	.byte	0x10
	.space	3
	.word	sRipperOAM_Moving_Frame1
	.byte	0x10
	.space	3
	.word	sRipperOAM_Moving_Frame2
	.byte	0x10
	.space	3
	.word	sRipperOAM_Moving_Frame1
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRipperOAM_TurningAround,object
	.size	 sRipperOAM_TurningAround,24
sRipperOAM_TurningAround:
	.word	sRipperOAM_TurningAround_Frame0
	.byte	0x3
	.space	3
	.word	sRipperOAM_TurningAround_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRipperOAM_TurningAroundPart2,object
	.size	 sRipperOAM_TurningAroundPart2,24
sRipperOAM_TurningAroundPart2:
	.word	sRipperOAM_TurningAround_Frame1
	.byte	0x3
	.space	3
	.word	sRipperOAM_TurningAround_Frame0
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
