@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sRipper2OAM_Moving_Frame0,object
	.size	 sRipper2OAM_Moving_Frame0,14
sRipper2OAM_Moving_Frame0:
	.short	0x2
	.short	0x40f3
	.short	0x81ec
	.short	0x8200
	.short	0xf5
	.short	0x400c
	.short	0x8212
	.align	1, 0
	.type	 sRipper2OAM_Moving_Frame1,object
	.size	 sRipper2OAM_Moving_Frame1,14
sRipper2OAM_Moving_Frame1:
	.short	0x2
	.short	0x40f3
	.short	0x81ec
	.short	0x8200
	.short	0x40f5
	.short	0x800c
	.short	0x820e
	.align	1, 0
	.type	 sRipper2OAM_Moving_Frame2,object
	.size	 sRipper2OAM_Moving_Frame2,14
sRipper2OAM_Moving_Frame2:
	.short	0x2
	.short	0x40f3
	.short	0x81ec
	.short	0x8200
	.short	0x40f4
	.short	0x800c
	.short	0x820a
	.align	1, 0
	.type	 sRipper2OAM_TurningAround_Frame0,object
	.size	 sRipper2OAM_TurningAround_Frame0,14
sRipper2OAM_TurningAround_Frame0:
	.short	0x2
	.short	0x40f3
	.short	0x81ec
	.short	0x8204
	.short	0xf4
	.short	0x4008
	.short	0x8212
	.align	1, 0
	.type	 sRipper2OAM_TurningAround_Frame1,object
	.size	 sRipper2OAM_TurningAround_Frame1,14
sRipper2OAM_TurningAround_Frame1:
	.short	0x2
	.short	0xf3
	.short	0x41f8
	.short	0x8208
	.short	0xf5
	.short	0x6000
	.short	0x8212
	.align	2, 0
	.type	 sRipper2OAM_Moving,object
	.size	 sRipper2OAM_Moving,40
sRipper2OAM_Moving:
	.word	sRipper2OAM_Moving_Frame0
	.byte	0x3
	.space	3
	.word	sRipper2OAM_Moving_Frame1
	.byte	0x3
	.space	3
	.word	sRipper2OAM_Moving_Frame2
	.byte	0x3
	.space	3
	.word	sRipper2OAM_Moving_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRipper2OAM_TurningAround,object
	.size	 sRipper2OAM_TurningAround,24
sRipper2OAM_TurningAround:
	.word	sRipper2OAM_TurningAround_Frame0
	.byte	0x3
	.space	3
	.word	sRipper2OAM_TurningAround_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRipper2OAM_TurningAroundPart2,object
	.size	 sRipper2OAM_TurningAroundPart2,24
sRipper2OAM_TurningAroundPart2:
	.word	sRipper2OAM_TurningAround_Frame1
	.byte	0x3
	.space	3
	.word	sRipper2OAM_TurningAround_Frame0
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
