@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame0,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame0,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame0:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8200
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame1,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame1,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame1:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8204
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame2,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame2,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame2:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8208
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame3,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame3,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame3:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x820c
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame4,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame4,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame4:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8210
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame5,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame5,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame5:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x9200
	.short	0x40f8
	.short	0x81f0
	.short	0x8214
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame6,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame6,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame6:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x9204
	.short	0x40f8
	.short	0x81f0
	.short	0x8218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame7,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame7,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame7:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x9208
	.short	0x40f8
	.short	0x81f0
	.short	0x8218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame8,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame8,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame8:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x920c
	.short	0x40f8
	.short	0x81f0
	.short	0x8218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame9,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame9,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame9:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x9210
	.short	0x40f8
	.short	0x81f0
	.short	0x8218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame10,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame10,26
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame10:
	.short	0x4
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xa200
	.short	0x40f8
	.short	0x81f0
	.short	0x9214
	.short	0x40f8
	.short	0x81f0
	.short	0x8218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame11,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame11,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame11:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xa204
	.short	0x40f8
	.short	0x81f0
	.short	0x9218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame12,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame12,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame12:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xa208
	.short	0x40f8
	.short	0x81f0
	.short	0x9218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame13,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame13,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame13:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xa20c
	.short	0x40f8
	.short	0x81f0
	.short	0x9218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame14,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame14,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame14:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xa210
	.short	0x40f8
	.short	0x81f0
	.short	0x9218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame15,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame15,26
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame15:
	.short	0x4
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb200
	.short	0x40f8
	.short	0x81f0
	.short	0xa214
	.short	0x40f8
	.short	0x81f0
	.short	0x9218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame16,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame16,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame16:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb204
	.short	0x40f8
	.short	0x81f0
	.short	0xa218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame17,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame17,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame17:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb208
	.short	0x40f8
	.short	0x81f0
	.short	0xa218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame18,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame18,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame18:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb20c
	.short	0x40f8
	.short	0x81f0
	.short	0xa218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame19,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame19,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame19:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb210
	.short	0x40f8
	.short	0x81f0
	.short	0xa218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame20,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame20,20
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame20:
	.short	0x3
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb214
	.short	0x40f8
	.short	0x81f0
	.short	0xa218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame21,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame21,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame21:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0xb218
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame22,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame22,38
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame22:
	.short	0x6
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x821c
	.short	0x80f0
	.short	0x41e8
	.short	0x8298
	.short	0x80f0
	.short	0x5010
	.short	0x8298
	.short	0x40f0
	.short	0x41f0
	.short	0x82f4
	.short	0x4008
	.short	0x61f0
	.short	0x82f4
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame23,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame23,38
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame23:
	.short	0x6
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8280
	.short	0x80f0
	.short	0x41e8
	.short	0x8299
	.short	0x80f0
	.short	0x5010
	.short	0x8299
	.short	0x40ef
	.short	0x41f0
	.short	0x82d4
	.short	0x4009
	.short	0x61f0
	.short	0x82d4
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame24,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame24,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame24:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8280
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame25,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame25,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame25:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8284
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame26,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame26,14
sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame26:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x8288
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawned_Frame0,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawned_Frame0,14
sRisingChozoPillarPlatformOAM_Slot0Spawned_Frame0:
	.short	0x2
	.short	0x80f8
	.short	0x1fc
	.short	0x82d0
	.short	0x40f8
	.short	0x81f0
	.short	0x828c
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame0,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame0,8
sRisingChozoPillarPlatformOAM_Spawning_Frame0:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8200
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame1,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame1,8
sRisingChozoPillarPlatformOAM_Spawning_Frame1:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8244
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame2,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame2,8
sRisingChozoPillarPlatformOAM_Spawning_Frame2:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8248
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame3,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame3,8
sRisingChozoPillarPlatformOAM_Spawning_Frame3:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x824c
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame4,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame4,8
sRisingChozoPillarPlatformOAM_Spawning_Frame4:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x8250
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame5,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame5,14
sRisingChozoPillarPlatformOAM_Spawning_Frame5:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0x9240
	.short	0x40f8
	.short	0x81f0
	.short	0x8254
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame6,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame6,14
sRisingChozoPillarPlatformOAM_Spawning_Frame6:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0x9244
	.short	0x40f8
	.short	0x81f0
	.short	0x8258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame7,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame7,14
sRisingChozoPillarPlatformOAM_Spawning_Frame7:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0x9248
	.short	0x40f8
	.short	0x81f0
	.short	0x8258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame8,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame8,14
sRisingChozoPillarPlatformOAM_Spawning_Frame8:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0x924c
	.short	0x40f8
	.short	0x81f0
	.short	0x8258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame9,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame9,14
sRisingChozoPillarPlatformOAM_Spawning_Frame9:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0x9250
	.short	0x40f8
	.short	0x81f0
	.short	0x8258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame10,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame10,20
sRisingChozoPillarPlatformOAM_Spawning_Frame10:
	.short	0x3
	.short	0x40f8
	.short	0x81f0
	.short	0xa240
	.short	0x40f8
	.short	0x81f0
	.short	0x9254
	.short	0x40f8
	.short	0x81f0
	.short	0x8258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame11,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame11,14
sRisingChozoPillarPlatformOAM_Spawning_Frame11:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xa244
	.short	0x40f8
	.short	0x81f0
	.short	0x9258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame12,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame12,14
sRisingChozoPillarPlatformOAM_Spawning_Frame12:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xa248
	.short	0x40f8
	.short	0x81f0
	.short	0x9258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame13,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame13,14
sRisingChozoPillarPlatformOAM_Spawning_Frame13:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xa24c
	.short	0x40f8
	.short	0x81f0
	.short	0x9258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame14,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame14,14
sRisingChozoPillarPlatformOAM_Spawning_Frame14:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xa250
	.short	0x40f8
	.short	0x81f0
	.short	0x9258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame15,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame15,20
sRisingChozoPillarPlatformOAM_Spawning_Frame15:
	.short	0x3
	.short	0x40f8
	.short	0x81f0
	.short	0xb240
	.short	0x40f8
	.short	0x81f0
	.short	0xa254
	.short	0x40f8
	.short	0x81f0
	.short	0x9258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame16,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame16,14
sRisingChozoPillarPlatformOAM_Spawning_Frame16:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xb244
	.short	0x40f8
	.short	0x81f0
	.short	0xa258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame17,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame17,14
sRisingChozoPillarPlatformOAM_Spawning_Frame17:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xb248
	.short	0x40f8
	.short	0x81f0
	.short	0xa258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame18,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame18,14
sRisingChozoPillarPlatformOAM_Spawning_Frame18:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xb24c
	.short	0x40f8
	.short	0x81f0
	.short	0xa258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame19,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame19,14
sRisingChozoPillarPlatformOAM_Spawning_Frame19:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xb250
	.short	0x40f8
	.short	0x81f0
	.short	0xa258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame20,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame20,14
sRisingChozoPillarPlatformOAM_Spawning_Frame20:
	.short	0x2
	.short	0x40f8
	.short	0x81f0
	.short	0xb254
	.short	0x40f8
	.short	0x81f0
	.short	0xa258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame21,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame21,8
sRisingChozoPillarPlatformOAM_Spawning_Frame21:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0xb258
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame22,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame22,32
sRisingChozoPillarPlatformOAM_Spawning_Frame22:
	.short	0x5
	.short	0x40f8
	.short	0x81f0
	.short	0x825c
	.short	0x80f0
	.short	0x41e8
	.short	0x8298
	.short	0x80f0
	.short	0x5010
	.short	0x8298
	.short	0x40f0
	.short	0x41f0
	.short	0x82f4
	.short	0x4008
	.short	0x61f0
	.short	0x82f4
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame23,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame23,32
sRisingChozoPillarPlatformOAM_Spawning_Frame23:
	.short	0x5
	.short	0x40f8
	.short	0x81f0
	.short	0x82c0
	.short	0x80f0
	.short	0x41e8
	.short	0x8299
	.short	0x80f0
	.short	0x5010
	.short	0x8299
	.short	0x40ef
	.short	0x41f0
	.short	0x82d4
	.short	0x4009
	.short	0x61f0
	.short	0x82d4
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame24,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame24,8
sRisingChozoPillarPlatformOAM_Spawning_Frame24:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x82c0
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame25,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame25,8
sRisingChozoPillarPlatformOAM_Spawning_Frame25:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x82c4
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning_Frame26,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning_Frame26,8
sRisingChozoPillarPlatformOAM_Spawning_Frame26:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x82c8
	.align	1, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawned_Frame0,object
	.size	 sRisingChozoPillarPlatformOAM_Spawned_Frame0,8
sRisingChozoPillarPlatformOAM_Spawned_Frame0:
	.short	0x1
	.short	0x40f8
	.short	0x81f0
	.short	0x82cc
	.align	1, 0
	.type	 sRisingChozoPillarPlatformShadowOAM_Frame0,object
	.size	 sRisingChozoPillarPlatformShadowOAM_Frame0,8
sRisingChozoPillarPlatformShadowOAM_Frame0:
	.short	0x1
	.short	0x4008
	.short	0x41f0
	.short	0x8290
	.align	1, 0
	.type	 sRisingChozoPillarPlatformShadowOAM_Frame1,object
	.size	 sRisingChozoPillarPlatformShadowOAM_Frame1,8
sRisingChozoPillarPlatformShadowOAM_Frame1:
	.short	0x1
	.short	0x4008
	.short	0x41f0
	.short	0x8294
	.align	1, 0
	.type	 sRisingChozoPillarPlatformShadowOAM_Frame2,object
	.size	 sRisingChozoPillarPlatformShadowOAM_Frame2,8
sRisingChozoPillarPlatformShadowOAM_Frame2:
	.short	0x1
	.short	0x4008
	.short	0x41f0
	.short	0x82b4
	.align	2, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawning,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawning,224
sRisingChozoPillarPlatformOAM_Slot0Spawning:
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame0
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame1
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame2
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame3
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame4
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame5
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame6
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame7
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame8
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame9
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame10
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame11
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame12
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame13
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame14
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame15
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame16
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame17
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame18
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame19
	.byte	0x0
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame20
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame21
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame22
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame23
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame24
	.byte	0x8
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame25
	.byte	0x8
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawning_Frame26
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRisingChozoPillarPlatformOAM_Slot0Spawned,object
	.size	 sRisingChozoPillarPlatformOAM_Slot0Spawned,16
sRisingChozoPillarPlatformOAM_Slot0Spawned:
	.word	sRisingChozoPillarPlatformOAM_Slot0Spawned_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawning,object
	.size	 sRisingChozoPillarPlatformOAM_Spawning,224
sRisingChozoPillarPlatformOAM_Spawning:
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame0
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame1
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame2
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame3
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame4
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame5
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame6
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame7
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame8
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame9
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame10
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame11
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame12
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame13
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame14
	.byte	0x2
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame15
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame16
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame17
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame18
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame19
	.byte	0x0
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame20
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame21
	.byte	0x1
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame22
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame23
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame24
	.byte	0x8
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame25
	.byte	0x8
	.space	3
	.word	sRisingChozoPillarPlatformOAM_Spawning_Frame26
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRisingChozoPillarPlatformOAM_Spawned,object
	.size	 sRisingChozoPillarPlatformOAM_Spawned,16
sRisingChozoPillarPlatformOAM_Spawned:
	.word	sRisingChozoPillarPlatformOAM_Spawned_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRisingChozoPillarPlatformShadowOAM,object
	.size	 sRisingChozoPillarPlatformShadowOAM,32
sRisingChozoPillarPlatformShadowOAM:
	.word	sRisingChozoPillarPlatformShadowOAM_Frame0
	.byte	0x4
	.space	3
	.word	sRisingChozoPillarPlatformShadowOAM_Frame1
	.byte	0x3
	.space	3
	.word	sRisingChozoPillarPlatformShadowOAM_Frame2
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
