@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sSearchlightEyeOAM_Idle_Frame0,object
	.size	 sSearchlightEyeOAM_Idle_Frame0,20
sSearchlightEyeOAM_Idle_Frame0:
	.short	0x3
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.short	0x0
	.short	0x41f8
	.short	0x8202
	.short	0x80f8
	.short	0x8
	.short	0x8204
	.align	1, 0
	.type	 sSearchlightEyeOAM_Idle_Frame1,object
	.size	 sSearchlightEyeOAM_Idle_Frame1,20
sSearchlightEyeOAM_Idle_Frame1:
	.short	0x3
	.short	0x0
	.short	0x41f8
	.short	0x8207
	.short	0x80f8
	.short	0x8
	.short	0x8204
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sSearchlightEyeOAM_Idle_Frame2,object
	.size	 sSearchlightEyeOAM_Idle_Frame2,20
sSearchlightEyeOAM_Idle_Frame2:
	.short	0x3
	.short	0xf0
	.short	0x41f8
	.short	0x8205
	.short	0x0
	.short	0x41f8
	.short	0x8207
	.short	0x80f8
	.short	0x8
	.short	0x8204
	.align	1, 0
	.type	 sSearchlightEyeOAM_Idle_Frame10,object
	.size	 sSearchlightEyeOAM_Idle_Frame10,20
sSearchlightEyeOAM_Idle_Frame10:
	.short	0x3
	.short	0x80f8
	.short	0x8
	.short	0x8204
	.short	0xf0
	.short	0x41f8
	.short	0x8209
	.short	0x0
	.short	0x41f8
	.short	0x820b
	.align	1, 0
	.type	 sSearchlightEyeBeamOAM_Idle_Frame0,object
	.size	 sSearchlightEyeBeamOAM_Idle_Frame0,44
sSearchlightEyeBeamOAM_Idle_Frame0:
	.short	0x7
	.short	0x40f8
	.short	0x81f0
	.short	0x821c
	.short	0x40f8
	.short	0x81d0
	.short	0x821c
	.short	0x40f8
	.short	0x81b0
	.short	0x821c
	.short	0x40f8
	.short	0x8190
	.short	0x821c
	.short	0x40f8
	.short	0x8010
	.short	0x821c
	.short	0x40f8
	.short	0x8030
	.short	0x821c
	.short	0x40f8
	.short	0x8050
	.short	0x821c
	.align	1, 0
	.type	 sSearchlightEyeBeamOAM_Idle_Frame2,object
	.size	 sSearchlightEyeBeamOAM_Idle_Frame2,44
sSearchlightEyeBeamOAM_Idle_Frame2:
	.short	0x7
	.short	0x40f8
	.short	0xa1f0
	.short	0x821c
	.short	0x40f8
	.short	0xa1d0
	.short	0x821c
	.short	0x40f8
	.short	0xa1b0
	.short	0x821c
	.short	0x40f8
	.short	0xa190
	.short	0x821c
	.short	0x40f8
	.short	0xa010
	.short	0x821c
	.short	0x40f8
	.short	0xa030
	.short	0x821c
	.short	0x40f8
	.short	0xa050
	.short	0x821c
	.align	1, 0
	.type	 sSearchlightEyeBeamOAM_Idle_Frame1,object
	.size	 sSearchlightEyeBeamOAM_Idle_Frame1,8
sSearchlightEyeBeamOAM_Idle_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x1f8
	.short	0x8200
	.align	1, 0
	.type	 sSearchlightEyeBeamOAM_Unused_Frame0,object
	.size	 sSearchlightEyeBeamOAM_Unused_Frame0,8
sSearchlightEyeBeamOAM_Unused_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x821c
	.align	1, 0
	.type	 sSearchlightEyeProjectileOAM_Moving_Frame0,object
	.size	 sSearchlightEyeProjectileOAM_Moving_Frame0,50
sSearchlightEyeProjectileOAM_Moving_Frame0:
	.short	0x8
	.short	0x40f8
	.short	0x1f6
	.short	0x8219
	.short	0x4000
	.short	0x21f6
	.short	0x8219
	.short	0xf8
	.short	0x0
	.short	0x8239
	.short	0x0
	.short	0x2000
	.short	0x8239
	.short	0xf8
	.short	0x8
	.short	0x823a
	.short	0x0
	.short	0x2008
	.short	0x823a
	.short	0xf8
	.short	0x1fc
	.short	0x823b
	.short	0x0
	.short	0x21fc
	.short	0x823b
	.align	1, 0
	.type	 sSearchlightEyeProjectileOAM_Moving_Frame2,object
	.size	 sSearchlightEyeProjectileOAM_Moving_Frame2,50
sSearchlightEyeProjectileOAM_Moving_Frame2:
	.short	0x8
	.short	0x40f8
	.short	0x1f7
	.short	0x8219
	.short	0x4000
	.short	0x21f7
	.short	0x8219
	.short	0xf8
	.short	0x3
	.short	0x8239
	.short	0x0
	.short	0x2003
	.short	0x8239
	.short	0xf8
	.short	0xb
	.short	0x823a
	.short	0x0
	.short	0x200b
	.short	0x823a
	.short	0xf8
	.short	0x1fe
	.short	0x823b
	.short	0x0
	.short	0x21fe
	.short	0x823b
	.align	1, 0
	.type	 sSearchlightEyeProjectileOAM_Moving_Frame4,object
	.size	 sSearchlightEyeProjectileOAM_Moving_Frame4,50
sSearchlightEyeProjectileOAM_Moving_Frame4:
	.short	0x8
	.short	0x40f8
	.short	0x1f6
	.short	0x8219
	.short	0x4000
	.short	0x21f6
	.short	0x8219
	.short	0xf8
	.short	0x7
	.short	0x8239
	.short	0x0
	.short	0x2007
	.short	0x8239
	.short	0xf8
	.short	0x1fd
	.short	0x823a
	.short	0x0
	.short	0x21fd
	.short	0x823a
	.short	0xf8
	.short	0x0
	.short	0x823b
	.short	0x0
	.short	0x2000
	.short	0x823b
	.align	1, 0
	.type	 sSearchlightEyeProjectileOAM_Moving_Frame6,object
	.size	 sSearchlightEyeProjectileOAM_Moving_Frame6,50
sSearchlightEyeProjectileOAM_Moving_Frame6:
	.short	0x8
	.short	0x40f8
	.short	0x1f7
	.short	0x8219
	.short	0x4000
	.short	0x21f7
	.short	0x8219
	.short	0xf8
	.short	0x1fe
	.short	0x8239
	.short	0x0
	.short	0x21fe
	.short	0x8239
	.short	0xf8
	.short	0x3
	.short	0x823a
	.short	0x0
	.short	0x2003
	.short	0x823a
	.short	0xf8
	.short	0xd
	.short	0x823b
	.short	0x0
	.short	0x200d
	.short	0x823b
	.align	1, 0
	.type	 sSearchlightEyeOAM_Shooting_Frame1,object
	.size	 sSearchlightEyeOAM_Shooting_Frame1,20
sSearchlightEyeOAM_Shooting_Frame1:
	.short	0x3
	.short	0x80f8
	.short	0x8
	.short	0x8204
	.short	0xf0
	.short	0x41f8
	.short	0x820d
	.short	0x0
	.short	0x41f8
	.short	0x820f
	.align	1, 0
	.type	 sSearchlightEyeOAM_Shooting_Frame2,object
	.size	 sSearchlightEyeOAM_Shooting_Frame2,20
sSearchlightEyeOAM_Shooting_Frame2:
	.short	0x3
	.short	0xf0
	.short	0x41f8
	.short	0x8215
	.short	0x0
	.short	0x41f8
	.short	0x8217
	.short	0x80f8
	.short	0x8
	.short	0x8204
	.align	2, 0
	.type	 sSearchlightEyeOAM_Idle,object
	.size	 sSearchlightEyeOAM_Idle,104
sSearchlightEyeOAM_Idle:
	.word	sSearchlightEyeOAM_Idle_Frame0
	.byte	0x14
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame1
	.byte	0x10
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame2
	.byte	0x14
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame1
	.byte	0x10
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame0
	.byte	0x10
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame2
	.byte	0x10
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame0
	.byte	0x14
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame2
	.byte	0x10
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame10
	.byte	0xc
	.space	3
	.word	sSearchlightEyeOAM_Idle_Frame2
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSearchlightEyeBeamOAM_Idle,object
	.size	 sSearchlightEyeBeamOAM_Idle,40
sSearchlightEyeBeamOAM_Idle:
	.word	sSearchlightEyeBeamOAM_Idle_Frame0
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame2
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSearchlightEyeBeamOAM_Unused,object
	.size	 sSearchlightEyeBeamOAM_Unused,16
sSearchlightEyeBeamOAM_Unused:
	.word	sSearchlightEyeBeamOAM_Unused_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSearchlightEyeProjectileOAM_Moving,object
	.size	 sSearchlightEyeProjectileOAM_Moving,72
sSearchlightEyeProjectileOAM_Moving:
	.word	sSearchlightEyeProjectileOAM_Moving_Frame0
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sSearchlightEyeProjectileOAM_Moving_Frame2
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sSearchlightEyeProjectileOAM_Moving_Frame4
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sSearchlightEyeProjectileOAM_Moving_Frame6
	.byte	0x1
	.space	3
	.word	sSearchlightEyeBeamOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSearchlightEyeOAM_Shooting,object
	.size	 sSearchlightEyeOAM_Shooting,32
sSearchlightEyeOAM_Shooting:
	.word	sSearchlightEyeOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sSearchlightEyeOAM_Shooting_Frame1
	.byte	0x5
	.space	3
	.word	sSearchlightEyeOAM_Shooting_Frame2
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
