@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sSecurityGateOAM_Opened_Frame0,object
	.size	 sSecurityGateOAM_Opened_Frame0,8
sSecurityGateOAM_Opened_Frame0:
	.short	0x1
	.short	0xc0
	.short	0x1f8
	.short	0x822c
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame0,object
	.size	 sSecurityGateOAM_Closing_Frame0,8
sSecurityGateOAM_Closing_Frame0:
	.short	0x1
	.short	0x40c0
	.short	0x1f8
	.short	0x8222
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame1,object
	.size	 sSecurityGateOAM_Closing_Frame1,8
sSecurityGateOAM_Closing_Frame1:
	.short	0x1
	.short	0x40c0
	.short	0x1f8
	.short	0x8226
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame2,object
	.size	 sSecurityGateOAM_Closing_Frame2,8
sSecurityGateOAM_Closing_Frame2:
	.short	0x1
	.short	0xc0
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame3,object
	.size	 sSecurityGateOAM_Closing_Frame3,8
sSecurityGateOAM_Closing_Frame3:
	.short	0x1
	.short	0xc0
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame4,object
	.size	 sSecurityGateOAM_Closing_Frame4,14
sSecurityGateOAM_Closing_Frame4:
	.short	0x2
	.short	0xc8
	.short	0x41f8
	.short	0x8202
	.short	0x40c0
	.short	0x1f8
	.short	0x8220
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame5,object
	.size	 sSecurityGateOAM_Closing_Frame5,14
sSecurityGateOAM_Closing_Frame5:
	.short	0x2
	.short	0xc8
	.short	0x41f8
	.short	0x8206
	.short	0x40c0
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame6,object
	.size	 sSecurityGateOAM_Closing_Frame6,14
sSecurityGateOAM_Closing_Frame6:
	.short	0x2
	.short	0xd0
	.short	0x41f8
	.short	0x8202
	.short	0xc0
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame7,object
	.size	 sSecurityGateOAM_Closing_Frame7,14
sSecurityGateOAM_Closing_Frame7:
	.short	0x2
	.short	0xd0
	.short	0x41f8
	.short	0x8206
	.short	0xc0
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame8,object
	.size	 sSecurityGateOAM_Closing_Frame8,20
sSecurityGateOAM_Closing_Frame8:
	.short	0x3
	.short	0xd8
	.short	0x41f8
	.short	0x8202
	.short	0xc8
	.short	0x41f8
	.short	0x8200
	.short	0x40c0
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame9,object
	.size	 sSecurityGateOAM_Closing_Frame9,20
sSecurityGateOAM_Closing_Frame9:
	.short	0x3
	.short	0xd8
	.short	0x41f8
	.short	0x8206
	.short	0xc8
	.short	0x41f8
	.short	0x8208
	.short	0x40c0
	.short	0x1f8
	.short	0x8200
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame10,object
	.size	 sSecurityGateOAM_Closing_Frame10,20
sSecurityGateOAM_Closing_Frame10:
	.short	0x3
	.short	0xe0
	.short	0x41f8
	.short	0x8202
	.short	0xd0
	.short	0x41f8
	.short	0x8200
	.short	0xc0
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame11,object
	.size	 sSecurityGateOAM_Closing_Frame11,20
sSecurityGateOAM_Closing_Frame11:
	.short	0x3
	.short	0xe0
	.short	0x41f8
	.short	0x8206
	.short	0xd0
	.short	0x41f8
	.short	0x8208
	.short	0xc0
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame12,object
	.size	 sSecurityGateOAM_Closing_Frame12,26
sSecurityGateOAM_Closing_Frame12:
	.short	0x4
	.short	0xe8
	.short	0x41f8
	.short	0x8202
	.short	0xd8
	.short	0x41f8
	.short	0x8200
	.short	0xc8
	.short	0x41f8
	.short	0x8208
	.short	0x40c0
	.short	0x1f8
	.short	0x8200
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame13,object
	.size	 sSecurityGateOAM_Closing_Frame13,26
sSecurityGateOAM_Closing_Frame13:
	.short	0x4
	.short	0xe8
	.short	0x41f8
	.short	0x8206
	.short	0xd8
	.short	0x41f8
	.short	0x8208
	.short	0xc8
	.short	0x41f8
	.short	0x8204
	.short	0x40c0
	.short	0x1f8
	.short	0x8220
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame14,object
	.size	 sSecurityGateOAM_Closing_Frame14,26
sSecurityGateOAM_Closing_Frame14:
	.short	0x4
	.short	0xf0
	.short	0x41f8
	.short	0x8202
	.short	0xe0
	.short	0x41f8
	.short	0x8200
	.short	0xd0
	.short	0x41f8
	.short	0x8208
	.short	0xc0
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame15,object
	.size	 sSecurityGateOAM_Closing_Frame15,32
sSecurityGateOAM_Closing_Frame15:
	.short	0x5
	.short	0xf0
	.short	0x41f8
	.short	0x8206
	.short	0xe0
	.short	0x41f8
	.short	0x8208
	.short	0xd0
	.short	0x41f8
	.short	0x8204
	.short	0x40c0
	.short	0x1f8
	.short	0x820c
	.short	0x40c8
	.short	0x1f8
	.short	0x8220
	.align	1, 0
	.type	 sSecurityGateOAM_Closing_Frame16,object
	.size	 sSecurityGateOAM_Closing_Frame16,32
sSecurityGateOAM_Closing_Frame16:
	.short	0x5
	.short	0xfb
	.short	0x41f8
	.short	0x8202
	.short	0xeb
	.short	0x41f8
	.short	0x8200
	.short	0xdb
	.short	0x41f8
	.short	0x8208
	.short	0xcb
	.short	0x41f8
	.short	0x8204
	.short	0xbb
	.short	0x41f8
	.short	0x820a
	.align	1, 0
	.type	 sSecurityGateOAM_Closed_Frame0,object
	.size	 sSecurityGateOAM_Closed_Frame0,32
sSecurityGateOAM_Closed_Frame0:
	.short	0x5
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.short	0xe8
	.short	0x41f8
	.short	0x8200
	.short	0xd8
	.short	0x41f8
	.short	0x8208
	.short	0xc8
	.short	0x41f8
	.short	0x8204
	.short	0x40c0
	.short	0x1f8
	.short	0x822a
	.align	1, 0
	.type	 sSecurityGateOAM_Closed_Frame1,object
	.size	 sSecurityGateOAM_Closed_Frame1,32
sSecurityGateOAM_Closed_Frame1:
	.short	0x5
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.short	0xe8
	.short	0x41f8
	.short	0x820e
	.short	0xd8
	.short	0x41f8
	.short	0x8210
	.short	0xc8
	.short	0x41f8
	.short	0x8212
	.short	0x40c0
	.short	0x1f8
	.short	0x822a
	.align	1, 0
	.type	 sSecurityGateOAM_Closed_Frame2,object
	.size	 sSecurityGateOAM_Closed_Frame2,32
sSecurityGateOAM_Closed_Frame2:
	.short	0x5
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.short	0xe8
	.short	0x41f8
	.short	0x8214
	.short	0xd8
	.short	0x41f8
	.short	0x8216
	.short	0xc8
	.short	0x41f8
	.short	0x8218
	.short	0x40c0
	.short	0x1f8
	.short	0x822a
	.align	2, 0
	.type	 sSecurityGateOAM_Opened,object
	.size	 sSecurityGateOAM_Opened,16
sSecurityGateOAM_Opened:
	.word	sSecurityGateOAM_Opened_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityGateOAM_Closing,object
	.size	 sSecurityGateOAM_Closing,144
sSecurityGateOAM_Closing:
	.word	sSecurityGateOAM_Closing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame5
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame6
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame7
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame8
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame9
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame10
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame11
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame12
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame13
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame14
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame15
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame16
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityGateOAM_Closed,object
	.size	 sSecurityGateOAM_Closed,32
sSecurityGateOAM_Closed:
	.word	sSecurityGateOAM_Closed_Frame0
	.byte	0x4
	.space	3
	.word	sSecurityGateOAM_Closed_Frame1
	.byte	0x4
	.space	3
	.word	sSecurityGateOAM_Closed_Frame2
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSceurityGateOAM_Opened,object
	.size	 sSceurityGateOAM_Opened,144
sSceurityGateOAM_Opened:
	.word	sSecurityGateOAM_Closing_Frame16
	.byte	0x2
	.space	3
	.word	sSecurityGateOAM_Closing_Frame15
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame14
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame13
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame12
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame11
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame10
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame9
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame8
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame7
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame6
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame5
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityGateOAM_Closing_Frame0
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
