@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmall_Frame0,object
	.size	 sSecurityLaserOAM_VerticalSmall_Frame0,20
sSecurityLaserOAM_VerticalSmall_Frame0:
	.short	0x3
	.short	0x80e5
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmall_Frame1,object
	.size	 sSecurityLaserOAM_VerticalSmall_Frame1,20
sSecurityLaserOAM_VerticalSmall_Frame1:
	.short	0x3
	.short	0x80e6
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmall_Frame2,object
	.size	 sSecurityLaserOAM_VerticalSmall_Frame2,20
sSecurityLaserOAM_VerticalSmall_Frame2:
	.short	0x3
	.short	0x80e7
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmall_Frame3,object
	.size	 sSecurityLaserOAM_VerticalSmall_Frame3,20
sSecurityLaserOAM_VerticalSmall_Frame3:
	.short	0x3
	.short	0x80e8
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmall_Frame4,object
	.size	 sSecurityLaserOAM_VerticalSmall_Frame4,20
sSecurityLaserOAM_VerticalSmall_Frame4:
	.short	0x3
	.short	0x80e9
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmall_Frame5,object
	.size	 sSecurityLaserOAM_VerticalSmall_Frame5,20
sSecurityLaserOAM_VerticalSmall_Frame5:
	.short	0x3
	.short	0x80ea
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMedium_Frame0,object
	.size	 sSecurityLaserOAM_VerticalMedium_Frame0,26
sSecurityLaserOAM_VerticalMedium_Frame0:
	.short	0x4
	.short	0x80dd
	.short	0x1fc
	.short	0x8201
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMedium_Frame1,object
	.size	 sSecurityLaserOAM_VerticalMedium_Frame1,26
sSecurityLaserOAM_VerticalMedium_Frame1:
	.short	0x4
	.short	0x80de
	.short	0x1fc
	.short	0x8201
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMedium_Frame2,object
	.size	 sSecurityLaserOAM_VerticalMedium_Frame2,26
sSecurityLaserOAM_VerticalMedium_Frame2:
	.short	0x4
	.short	0x80df
	.short	0x1fc
	.short	0x8201
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMedium_Frame3,object
	.size	 sSecurityLaserOAM_VerticalMedium_Frame3,26
sSecurityLaserOAM_VerticalMedium_Frame3:
	.short	0x4
	.short	0x80e0
	.short	0x1fc
	.short	0x8201
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMedium_Frame4,object
	.size	 sSecurityLaserOAM_VerticalMedium_Frame4,26
sSecurityLaserOAM_VerticalMedium_Frame4:
	.short	0x4
	.short	0x80e1
	.short	0x1fc
	.short	0x8201
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMedium_Frame5,object
	.size	 sSecurityLaserOAM_VerticalMedium_Frame5,26
sSecurityLaserOAM_VerticalMedium_Frame5:
	.short	0x4
	.short	0x80e2
	.short	0x1fc
	.short	0x8201
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLarge_Frame0,object
	.size	 sSecurityLaserOAM_VerticalLarge_Frame0,38
sSecurityLaserOAM_VerticalLarge_Frame0:
	.short	0x6
	.short	0x80e5
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c5
	.short	0x1fc
	.short	0x8201
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLarge_Frame1,object
	.size	 sSecurityLaserOAM_VerticalLarge_Frame1,38
sSecurityLaserOAM_VerticalLarge_Frame1:
	.short	0x6
	.short	0x80e6
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c6
	.short	0x1fc
	.short	0x8201
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLarge_Frame2,object
	.size	 sSecurityLaserOAM_VerticalLarge_Frame2,38
sSecurityLaserOAM_VerticalLarge_Frame2:
	.short	0x6
	.short	0x80e7
	.short	0x1fc
	.short	0x8201
	.short	0x80c7
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLarge_Frame3,object
	.size	 sSecurityLaserOAM_VerticalLarge_Frame3,38
sSecurityLaserOAM_VerticalLarge_Frame3:
	.short	0x6
	.short	0x80e8
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c8
	.short	0x1fc
	.short	0x8201
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLarge_Frame4,object
	.size	 sSecurityLaserOAM_VerticalLarge_Frame4,38
sSecurityLaserOAM_VerticalLarge_Frame4:
	.short	0x6
	.short	0x80e9
	.short	0x1fc
	.short	0x8201
	.short	0x80c9
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLarge_Frame5,object
	.size	 sSecurityLaserOAM_VerticalLarge_Frame5,38
sSecurityLaserOAM_VerticalLarge_Frame5:
	.short	0x6
	.short	0x80ea
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80ca
	.short	0x1fc
	.short	0x8201
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge_Frame0,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge_Frame0,44
sSecurityLaserOAM_VerticalVeryLarge_Frame0:
	.short	0x7
	.short	0x80e5
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80bd
	.short	0x1fc
	.short	0x8201
	.short	0x80b0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge_Frame1,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge_Frame1,44
sSecurityLaserOAM_VerticalVeryLarge_Frame1:
	.short	0x7
	.short	0x80e6
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80be
	.short	0x1fc
	.short	0x8201
	.short	0x80b0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge_Frame2,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge_Frame2,44
sSecurityLaserOAM_VerticalVeryLarge_Frame2:
	.short	0x7
	.short	0x80e7
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80bf
	.short	0x1fc
	.short	0x8201
	.short	0x80b0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge_Frame3,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge_Frame3,44
sSecurityLaserOAM_VerticalVeryLarge_Frame3:
	.short	0x7
	.short	0x80e8
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8201
	.short	0x80b0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge_Frame4,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge_Frame4,44
sSecurityLaserOAM_VerticalVeryLarge_Frame4:
	.short	0x7
	.short	0x80e9
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c1
	.short	0x1fc
	.short	0x8201
	.short	0x80b0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge_Frame5,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge_Frame5,44
sSecurityLaserOAM_VerticalVeryLarge_Frame5:
	.short	0x7
	.short	0x80ea
	.short	0x1fc
	.short	0x8201
	.short	0x80e0
	.short	0x1fc
	.short	0x8200
	.short	0x80f0
	.short	0x1fc
	.short	0x8200
	.short	0x80c2
	.short	0x1fc
	.short	0x8201
	.short	0x80b0
	.short	0x1fc
	.short	0x8200
	.short	0x80c0
	.short	0x1fc
	.short	0x8200
	.short	0x80d0
	.short	0x1fc
	.short	0x8200
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmall_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalSmall_Frame0,14
sSecurityLaserOAM_HorizontalSmall_Frame0:
	.short	0x2
	.short	0x40f4
	.short	0x3
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmall_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalSmall_Frame1,14
sSecurityLaserOAM_HorizontalSmall_Frame1:
	.short	0x2
	.short	0x40f4
	.short	0x2
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmall_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalSmall_Frame2,14
sSecurityLaserOAM_HorizontalSmall_Frame2:
	.short	0x2
	.short	0x40f4
	.short	0x1
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmall_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalSmall_Frame3,14
sSecurityLaserOAM_HorizontalSmall_Frame3:
	.short	0x2
	.short	0x40f4
	.short	0x0
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmall_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalSmall_Frame4,14
sSecurityLaserOAM_HorizontalSmall_Frame4:
	.short	0x2
	.short	0x40f4
	.short	0x1ff
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmall_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalSmall_Frame5,14
sSecurityLaserOAM_HorizontalSmall_Frame5:
	.short	0x2
	.short	0x40f4
	.short	0x1fe
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMedium_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalMedium_Frame0,20
sSecurityLaserOAM_HorizontalMedium_Frame0:
	.short	0x3
	.short	0x40f4
	.short	0xb
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x18
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMedium_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalMedium_Frame1,20
sSecurityLaserOAM_HorizontalMedium_Frame1:
	.short	0x3
	.short	0x40f4
	.short	0xa
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x18
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMedium_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalMedium_Frame2,20
sSecurityLaserOAM_HorizontalMedium_Frame2:
	.short	0x3
	.short	0x40f4
	.short	0x9
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x18
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMedium_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalMedium_Frame3,20
sSecurityLaserOAM_HorizontalMedium_Frame3:
	.short	0x3
	.short	0x40f4
	.short	0x8
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x18
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMedium_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalMedium_Frame4,20
sSecurityLaserOAM_HorizontalMedium_Frame4:
	.short	0x3
	.short	0x40f4
	.short	0x7
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x18
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMedium_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalMedium_Frame5,20
sSecurityLaserOAM_HorizontalMedium_Frame5:
	.short	0x3
	.short	0x40f4
	.short	0x6
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x18
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLarge_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalLarge_Frame0,26
sSecurityLaserOAM_HorizontalLarge_Frame0:
	.short	0x4
	.short	0x40f4
	.short	0x3
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x23
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLarge_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalLarge_Frame1,26
sSecurityLaserOAM_HorizontalLarge_Frame1:
	.short	0x4
	.short	0x40f4
	.short	0x2
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x22
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLarge_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalLarge_Frame2,26
sSecurityLaserOAM_HorizontalLarge_Frame2:
	.short	0x4
	.short	0x40f4
	.short	0x1
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x21
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLarge_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalLarge_Frame3,26
sSecurityLaserOAM_HorizontalLarge_Frame3:
	.short	0x4
	.short	0x40f4
	.short	0x0
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x20
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLarge_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalLarge_Frame4,26
sSecurityLaserOAM_HorizontalLarge_Frame4:
	.short	0x4
	.short	0x40f4
	.short	0x1ff
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x1f
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLarge_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalLarge_Frame5,26
sSecurityLaserOAM_HorizontalLarge_Frame5:
	.short	0x4
	.short	0x40f4
	.short	0x1fe
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x1e
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge_Frame0,32
sSecurityLaserOAM_HorizontalVeryLarge_Frame0:
	.short	0x5
	.short	0x40f4
	.short	0x3
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x2b
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.short	0x40f4
	.short	0x38
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge_Frame1,32
sSecurityLaserOAM_HorizontalVeryLarge_Frame1:
	.short	0x5
	.short	0x40f4
	.short	0x2
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x2a
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.short	0x40f4
	.short	0x38
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge_Frame2,32
sSecurityLaserOAM_HorizontalVeryLarge_Frame2:
	.short	0x5
	.short	0x40f4
	.short	0x1
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x29
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.short	0x40f4
	.short	0x38
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge_Frame3,32
sSecurityLaserOAM_HorizontalVeryLarge_Frame3:
	.short	0x5
	.short	0x40f4
	.short	0x0
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x28
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.short	0x40f4
	.short	0x38
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge_Frame4,32
sSecurityLaserOAM_HorizontalVeryLarge_Frame4:
	.short	0x5
	.short	0x40f4
	.short	0x1ff
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x27
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.short	0x40f4
	.short	0x38
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge_Frame5,32
sSecurityLaserOAM_HorizontalVeryLarge_Frame5:
	.short	0x5
	.short	0x40f4
	.short	0x1fe
	.short	0x8222
	.short	0x40f4
	.short	0x41f8
	.short	0x8202
	.short	0x40f4
	.short	0x26
	.short	0x8222
	.short	0x40f4
	.short	0x4018
	.short	0x8202
	.short	0x40f4
	.short	0x38
	.short	0x8204
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame0,14
sSecurityLaserOAM_VerticalSmallDisappearing_Frame0:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8206
	.short	0x80e0
	.short	0x1fc
	.short	0x8206
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame1,14
sSecurityLaserOAM_VerticalSmallDisappearing_Frame1:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8207
	.short	0x80e0
	.short	0x1fc
	.short	0x8207
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame2,14
sSecurityLaserOAM_VerticalSmallDisappearing_Frame2:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8208
	.short	0x80e0
	.short	0x1fc
	.short	0x8208
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame3,14
sSecurityLaserOAM_VerticalSmallDisappearing_Frame3:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8209
	.short	0x80e0
	.short	0x1fc
	.short	0x8209
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame4,14
sSecurityLaserOAM_VerticalSmallDisappearing_Frame4:
	.short	0x2
	.short	0x80ec
	.short	0x1fc
	.short	0x820a
	.short	0xe4
	.short	0x1fc
	.short	0x820a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Frame5,14
sSecurityLaserOAM_VerticalSmallDisappearing_Frame5:
	.short	0x2
	.short	0xea
	.short	0x1fc
	.short	0x820b
	.short	0xee
	.short	0x1fc
	.short	0x820b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame0,20
sSecurityLaserOAM_VerticalMediumDisappearing_Frame0:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x8206
	.short	0x80e0
	.short	0x1fc
	.short	0x8206
	.short	0x80d0
	.short	0x1fc
	.short	0x8206
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame1,20
sSecurityLaserOAM_VerticalMediumDisappearing_Frame1:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x8207
	.short	0x80e0
	.short	0x1fc
	.short	0x8207
	.short	0x80d0
	.short	0x1fc
	.short	0x8207
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame2,20
sSecurityLaserOAM_VerticalMediumDisappearing_Frame2:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x8208
	.short	0x80e0
	.short	0x1fc
	.short	0x8208
	.short	0x80d0
	.short	0x1fc
	.short	0x8208
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame3,20
sSecurityLaserOAM_VerticalMediumDisappearing_Frame3:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x8209
	.short	0x80e0
	.short	0x1fc
	.short	0x8209
	.short	0x80d0
	.short	0x1fc
	.short	0x8209
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame4,14
sSecurityLaserOAM_VerticalMediumDisappearing_Frame4:
	.short	0x2
	.short	0x80e8
	.short	0x1fc
	.short	0x820a
	.short	0x80d8
	.short	0x1fc
	.short	0x820a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Frame5,14
sSecurityLaserOAM_VerticalMediumDisappearing_Frame5:
	.short	0x2
	.short	0x80de
	.short	0x1fc
	.short	0x820b
	.short	0xea
	.short	0x1fc
	.short	0x820b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame0,26
sSecurityLaserOAM_VerticalLargeDisappearing_Frame0:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8206
	.short	0x80e0
	.short	0x1fc
	.short	0x8206
	.short	0x80d0
	.short	0x1fc
	.short	0x8206
	.short	0x80c0
	.short	0x1fc
	.short	0x8206
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame1,26
sSecurityLaserOAM_VerticalLargeDisappearing_Frame1:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8207
	.short	0x80e0
	.short	0x1fc
	.short	0x8207
	.short	0x80d0
	.short	0x1fc
	.short	0x8207
	.short	0x80c0
	.short	0x1fc
	.short	0x8207
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame2,26
sSecurityLaserOAM_VerticalLargeDisappearing_Frame2:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8208
	.short	0x80e0
	.short	0x1fc
	.short	0x8208
	.short	0x80d0
	.short	0x1fc
	.short	0x8208
	.short	0x80c0
	.short	0x1fc
	.short	0x8208
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame3,26
sSecurityLaserOAM_VerticalLargeDisappearing_Frame3:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8209
	.short	0x80e0
	.short	0x1fc
	.short	0x8209
	.short	0x80d0
	.short	0x1fc
	.short	0x8209
	.short	0x80c0
	.short	0x1fc
	.short	0x8209
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame4,20
sSecurityLaserOAM_VerticalLargeDisappearing_Frame4:
	.short	0x3
	.short	0x80cc
	.short	0x1fc
	.short	0x820a
	.short	0x80e4
	.short	0x1fc
	.short	0x820a
	.short	0xdc
	.short	0x1fc
	.short	0x820a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Frame5,14
sSecurityLaserOAM_VerticalLargeDisappearing_Frame5:
	.short	0x2
	.short	0x80d2
	.short	0x1fc
	.short	0x820b
	.short	0x80de
	.short	0x1fc
	.short	0x820b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame0,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame0:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x8206
	.short	0x80e0
	.short	0x1fc
	.short	0x8206
	.short	0x80d0
	.short	0x1fc
	.short	0x8206
	.short	0x80c0
	.short	0x1fc
	.short	0x8206
	.short	0x80b0
	.short	0x1fc
	.short	0x8206
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame1,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame1:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x8207
	.short	0x80e0
	.short	0x1fc
	.short	0x8207
	.short	0x80d0
	.short	0x1fc
	.short	0x8207
	.short	0x80c0
	.short	0x1fc
	.short	0x8207
	.short	0x80b0
	.short	0x1fc
	.short	0x8207
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame2,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame2:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x8208
	.short	0x80e0
	.short	0x1fc
	.short	0x8208
	.short	0x80d0
	.short	0x1fc
	.short	0x8208
	.short	0x80c0
	.short	0x1fc
	.short	0x8208
	.short	0x80b0
	.short	0x1fc
	.short	0x8208
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame3,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame3:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x8209
	.short	0x80e0
	.short	0x1fc
	.short	0x8209
	.short	0x80d0
	.short	0x1fc
	.short	0x8209
	.short	0x80c0
	.short	0x1fc
	.short	0x8209
	.short	0x80b0
	.short	0x1fc
	.short	0x8209
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame4,26
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame4:
	.short	0x4
	.short	0x80e4
	.short	0x1fc
	.short	0x820a
	.short	0x80cc
	.short	0x1fc
	.short	0x820a
	.short	0x80bc
	.short	0x1fc
	.short	0x820a
	.short	0xdc
	.short	0x1fc
	.short	0x820a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame5,20
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame5:
	.short	0x3
	.short	0x80de
	.short	0x1fc
	.short	0x820b
	.short	0x80c2
	.short	0x1fc
	.short	0x820b
	.short	0x80d0
	.short	0x1fc
	.short	0x820b
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame0,8
sSecurityLaserOAM_HorizontalSmallDisappearing_Frame0:
	.short	0x1
	.short	0x40f4
	.short	0x41f8
	.short	0x820c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame1,8
sSecurityLaserOAM_HorizontalSmallDisappearing_Frame1:
	.short	0x1
	.short	0x40f4
	.short	0x41f8
	.short	0x822c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame2,8
sSecurityLaserOAM_HorizontalSmallDisappearing_Frame2:
	.short	0x1
	.short	0x40f4
	.short	0x41f8
	.short	0x8210
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame3,8
sSecurityLaserOAM_HorizontalSmallDisappearing_Frame3:
	.short	0x1
	.short	0x40f4
	.short	0x41f8
	.short	0x8230
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame4,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Frame4:
	.short	0x2
	.short	0x40f4
	.short	0x1fc
	.short	0x8214
	.short	0xf4
	.short	0xc
	.short	0x8216
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Frame5,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Frame5:
	.short	0x2
	.short	0xf4
	.short	0x2
	.short	0x8234
	.short	0xf4
	.short	0x6
	.short	0x8234
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame0,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Frame0:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x820c
	.short	0x40f4
	.short	0x18
	.short	0x820c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame1,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Frame1:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x822c
	.short	0x40f4
	.short	0x18
	.short	0x822c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame2,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Frame2:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x8210
	.short	0x40f4
	.short	0x18
	.short	0x8210
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame3,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Frame3:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x8230
	.short	0x40f4
	.short	0x18
	.short	0x8230
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame4,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Frame4:
	.short	0x2
	.short	0x40f4
	.short	0x0
	.short	0x8215
	.short	0x40f4
	.short	0x10
	.short	0x8215
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Frame5,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Frame5:
	.short	0x2
	.short	0x40f4
	.short	0x6
	.short	0x8234
	.short	0xf4
	.short	0x12
	.short	0x8236
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame0,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Frame0:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x820c
	.short	0x40f4
	.short	0x4018
	.short	0x820c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame1,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Frame1:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x822c
	.short	0x40f4
	.short	0x4018
	.short	0x822c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame2,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Frame2:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x8210
	.short	0x40f4
	.short	0x4018
	.short	0x8210
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame3,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Frame3:
	.short	0x2
	.short	0x40f4
	.short	0x41f8
	.short	0x8230
	.short	0x40f4
	.short	0x4018
	.short	0x8230
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame4,20
sSecurityLaserOAM_HorizontalLargeDisappearing_Frame4:
	.short	0x3
	.short	0x40f4
	.short	0x4
	.short	0x8214
	.short	0xf4
	.short	0x14
	.short	0x8216
	.short	0x40f4
	.short	0x1c
	.short	0x8214
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Frame5,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Frame5:
	.short	0x2
	.short	0x40f4
	.short	0xa
	.short	0x8234
	.short	0x40f4
	.short	0x16
	.short	0x8234
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame0,20
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame0:
	.short	0x3
	.short	0x40f4
	.short	0x41f8
	.short	0x820c
	.short	0x40f4
	.short	0x18
	.short	0x820c
	.short	0x40f4
	.short	0x4028
	.short	0x820c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame1,20
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame1:
	.short	0x3
	.short	0x40f4
	.short	0x41f8
	.short	0x822c
	.short	0x40f4
	.short	0x18
	.short	0x822c
	.short	0x40f4
	.short	0x4028
	.short	0x822c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame2,20
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame2:
	.short	0x3
	.short	0x40f4
	.short	0x41f8
	.short	0x8210
	.short	0x40f4
	.short	0x18
	.short	0x8210
	.short	0x40f4
	.short	0x4028
	.short	0x8210
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame3,20
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame3:
	.short	0x3
	.short	0x40f4
	.short	0x41f8
	.short	0x8230
	.short	0x40f4
	.short	0x18
	.short	0x8230
	.short	0x40f4
	.short	0x4028
	.short	0x8230
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame4,26
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame4:
	.short	0x4
	.short	0x40f4
	.short	0x4
	.short	0x8215
	.short	0x40f4
	.short	0x14
	.short	0x8215
	.short	0xf4
	.short	0x24
	.short	0x8214
	.short	0x40f4
	.short	0x2c
	.short	0x8215
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame5,20
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame5:
	.short	0x3
	.short	0x40f4
	.short	0xa
	.short	0x8234
	.short	0x40f4
	.short	0x18
	.short	0x8234
	.short	0x40f4
	.short	0x26
	.short	0x8234
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame0,14
sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xf8
	.short	0x1fc
	.short	0x821b
	.short	0xe0
	.short	0x21fc
	.short	0x821b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame1,14
sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame1:
	.short	0x2
	.short	0xf8
	.short	0x1fc
	.short	0x8238
	.short	0xe0
	.short	0x1fc
	.short	0x8238
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame2,26
sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame2:
	.short	0x4
	.short	0xf0
	.short	0x1fc
	.short	0x821b
	.short	0xf8
	.short	0x1fc
	.short	0x8238
	.short	0xe8
	.short	0x21fc
	.short	0x821b
	.short	0xe0
	.short	0x21fc
	.short	0x8238
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame3,14
sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame3:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80e0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame4,14
sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame4:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8219
	.short	0x80e0
	.short	0x1fc
	.short	0x8219
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame5,14
sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame5:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x821a
	.short	0x80e0
	.short	0x1fc
	.short	0x821a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame0,14
sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xf8
	.short	0x1fc
	.short	0x821b
	.short	0xd0
	.short	0x21fc
	.short	0x821b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame1,26
sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame1:
	.short	0x4
	.short	0xf8
	.short	0x1fc
	.short	0x8238
	.short	0xd0
	.short	0x1fc
	.short	0x8238
	.short	0xf0
	.short	0x1fc
	.short	0x821b
	.short	0xd8
	.short	0x21fc
	.short	0x821b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame2,26
sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame2:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80d0
	.short	0x1fc
	.short	0x8218
	.short	0xe8
	.short	0x1fc
	.short	0x821b
	.short	0xe0
	.short	0x21fc
	.short	0x821b
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame3,20
sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame3:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80e0
	.short	0x1fc
	.short	0x8218
	.short	0x80d0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame4,20
sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame4:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x8219
	.short	0x80e0
	.short	0x1fc
	.short	0x8219
	.short	0x80d0
	.short	0x1fc
	.short	0x8219
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame5,20
sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame5:
	.short	0x3
	.short	0x80f0
	.short	0x1fc
	.short	0x821a
	.short	0x80e0
	.short	0x1fc
	.short	0x821a
	.short	0x80d0
	.short	0x1fc
	.short	0x821a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame0,14
sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xc0
	.short	0x1fc
	.short	0x8218
	.short	0xf8
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame1,14
sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame1:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80c0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame2,26
sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame2:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80c0
	.short	0x1fc
	.short	0x8218
	.short	0xd0
	.short	0x1fc
	.short	0x8218
	.short	0xe8
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame3,26
sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame3:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80e0
	.short	0x1fc
	.short	0x8218
	.short	0x80d0
	.short	0x1fc
	.short	0x8218
	.short	0x80c0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame4,26
sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame4:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8219
	.short	0x80e0
	.short	0x1fc
	.short	0x8219
	.short	0x80d0
	.short	0x1fc
	.short	0x8219
	.short	0x80c0
	.short	0x1fc
	.short	0x8219
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame5,26
sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame5:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x821a
	.short	0x80e0
	.short	0x1fc
	.short	0x821a
	.short	0x80d0
	.short	0x1fc
	.short	0x821a
	.short	0x80c0
	.short	0x1fc
	.short	0x821a
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame0,14
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xb0
	.short	0x1fc
	.short	0x8218
	.short	0xf8
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame1,14
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame1:
	.short	0x2
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80b0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame2,26
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame2:
	.short	0x4
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80b0
	.short	0x1fc
	.short	0x8218
	.short	0x80e0
	.short	0x1fc
	.short	0x8218
	.short	0x80c0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame3,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame3:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x8218
	.short	0x80e0
	.short	0x1fc
	.short	0x8218
	.short	0x80d0
	.short	0x1fc
	.short	0x8218
	.short	0x80c0
	.short	0x1fc
	.short	0x8218
	.short	0x80b0
	.short	0x1fc
	.short	0x8218
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame4,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame4:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x8219
	.short	0x80e0
	.short	0x1fc
	.short	0x8219
	.short	0x80d0
	.short	0x1fc
	.short	0x8219
	.short	0x80c0
	.short	0x1fc
	.short	0x8219
	.short	0x80b0
	.short	0x1fc
	.short	0x8219
	.align	1, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame5,32
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame5:
	.short	0x5
	.short	0x80f0
	.short	0x1fc
	.short	0x821a
	.short	0x80e0
	.short	0x1fc
	.short	0x821a
	.short	0x80d0
	.short	0x1fc
	.short	0x821a
	.short	0x80c0
	.short	0x1fc
	.short	0x821a
	.short	0x80b0
	.short	0x1fc
	.short	0x821a
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame0,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xf4
	.short	0x1f8
	.short	0x823b
	.short	0xf4
	.short	0x1010
	.short	0x823b
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame1,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame1:
	.short	0x2
	.short	0xf4
	.short	0x1f8
	.short	0x821c
	.short	0xf4
	.short	0x10
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame2,26
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame2:
	.short	0x4
	.short	0xf4
	.short	0x1f8
	.short	0x821c
	.short	0xf4
	.short	0x10
	.short	0x821c
	.short	0xf4
	.short	0x0
	.short	0x823b
	.short	0xf4
	.short	0x1008
	.short	0x823b
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame3,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame3:
	.short	0x2
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x8
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame4,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame4:
	.short	0x2
	.short	0x40f4
	.short	0x1f8
	.short	0x823c
	.short	0x40f4
	.short	0x8
	.short	0x823c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame5,14
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame5:
	.short	0x2
	.short	0x40f4
	.short	0x1f8
	.short	0x821e
	.short	0x40f4
	.short	0x8
	.short	0x821e
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame0,14
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xf4
	.short	0x1f8
	.short	0x823b
	.short	0xf4
	.short	0x1020
	.short	0x823b
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame1,26
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame1:
	.short	0x4
	.short	0xf4
	.short	0x1f8
	.short	0x821c
	.short	0xf4
	.short	0x20
	.short	0x821c
	.short	0xf4
	.short	0x0
	.short	0x823b
	.short	0xf4
	.short	0x1018
	.short	0x823b
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame2,26
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame2:
	.short	0x4
	.short	0xf4
	.short	0x8
	.short	0x823b
	.short	0xf4
	.short	0x1010
	.short	0x823b
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x18
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame3,20
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame3:
	.short	0x3
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x8
	.short	0x821c
	.short	0x40f4
	.short	0x18
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame4,20
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame4:
	.short	0x3
	.short	0x40f4
	.short	0x1f8
	.short	0x823c
	.short	0x40f4
	.short	0x8
	.short	0x823c
	.short	0x40f4
	.short	0x18
	.short	0x823c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame5,20
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame5:
	.short	0x3
	.short	0x40f4
	.short	0x1f8
	.short	0x821e
	.short	0x40f4
	.short	0x8
	.short	0x821e
	.short	0x40f4
	.short	0x18
	.short	0x821e
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame0,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xf4
	.short	0x1f8
	.short	0x821c
	.short	0xf4
	.short	0x30
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame1,14
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame1:
	.short	0x2
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x28
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame2,26
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame2:
	.short	0x4
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x28
	.short	0x821c
	.short	0xf4
	.short	0x8
	.short	0x821c
	.short	0xf4
	.short	0x20
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame3,26
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame3:
	.short	0x4
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x28
	.short	0x821c
	.short	0x40f4
	.short	0x8
	.short	0x821c
	.short	0x40f4
	.short	0x18
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame4,26
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame4:
	.short	0x4
	.short	0x40f4
	.short	0x1f8
	.short	0x823c
	.short	0x40f4
	.short	0x8
	.short	0x823c
	.short	0x40f4
	.short	0x18
	.short	0x823c
	.short	0x40f4
	.short	0x28
	.short	0x823c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame5,26
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame5:
	.short	0x4
	.short	0x40f4
	.short	0x1f8
	.short	0x821e
	.short	0x40f4
	.short	0x8
	.short	0x821e
	.short	0x40f4
	.short	0x18
	.short	0x821e
	.short	0x40f4
	.short	0x28
	.short	0x821e
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame0,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame0,14
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame0:
	.short	0x2
	.short	0xf4
	.short	0x1f8
	.short	0x821c
	.short	0xf4
	.short	0x40
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame1,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame1,14
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame1:
	.short	0x2
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x38
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame2,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame2,26
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame2:
	.short	0x4
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x38
	.short	0x821c
	.short	0x40f4
	.short	0x8
	.short	0x821c
	.short	0x40f4
	.short	0x28
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame3,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame3,32
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame3:
	.short	0x5
	.short	0x40f4
	.short	0x1f8
	.short	0x821c
	.short	0x40f4
	.short	0x38
	.short	0x821c
	.short	0x40f4
	.short	0x8
	.short	0x821c
	.short	0x40f4
	.short	0x28
	.short	0x821c
	.short	0x40f4
	.short	0x18
	.short	0x821c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame4,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame4,32
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame4:
	.short	0x5
	.short	0x40f4
	.short	0x1f8
	.short	0x823c
	.short	0x40f4
	.short	0x8
	.short	0x823c
	.short	0x40f4
	.short	0x18
	.short	0x823c
	.short	0x40f4
	.short	0x28
	.short	0x823c
	.short	0x40f4
	.short	0x38
	.short	0x823c
	.align	1, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame5,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame5,32
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame5:
	.short	0x5
	.short	0x40f4
	.short	0x1f8
	.short	0x821e
	.short	0x40f4
	.short	0x8
	.short	0x821e
	.short	0x40f4
	.short	0x18
	.short	0x821e
	.short	0x40f4
	.short	0x28
	.short	0x821e
	.short	0x40f4
	.short	0x38
	.short	0x821e
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalSmall,object
	.size	 sSecurityLaserOAM_VerticalSmall,88
sSecurityLaserOAM_VerticalSmall:
	.word	sSecurityLaserOAM_VerticalSmall_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmall_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalMedium,object
	.size	 sSecurityLaserOAM_VerticalMedium,88
sSecurityLaserOAM_VerticalMedium:
	.word	sSecurityLaserOAM_VerticalMedium_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMedium_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalLarge,object
	.size	 sSecurityLaserOAM_VerticalLarge,88
sSecurityLaserOAM_VerticalLarge:
	.word	sSecurityLaserOAM_VerticalLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLarge_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalVeryLarge,object
	.size	 sSecurityLaserOAM_VerticalVeryLarge,88
sSecurityLaserOAM_VerticalVeryLarge:
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLarge_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalSmall,object
	.size	 sSecurityLaserOAM_HorizontalSmall,88
sSecurityLaserOAM_HorizontalSmall:
	.word	sSecurityLaserOAM_HorizontalSmall_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmall_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalMedium,object
	.size	 sSecurityLaserOAM_HorizontalMedium,88
sSecurityLaserOAM_HorizontalMedium:
	.word	sSecurityLaserOAM_HorizontalMedium_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMedium_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalLarge,object
	.size	 sSecurityLaserOAM_HorizontalLarge,88
sSecurityLaserOAM_HorizontalLarge:
	.word	sSecurityLaserOAM_HorizontalLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLarge_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLarge,object
	.size	 sSecurityLaserOAM_HorizontalVeryLarge,88
sSecurityLaserOAM_HorizontalVeryLarge:
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame5
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLarge_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing,56
sSecurityLaserOAM_VerticalSmallDisappearing:
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing,56
sSecurityLaserOAM_VerticalMediumDisappearing:
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing,56
sSecurityLaserOAM_VerticalLargeDisappearing:
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing,56
sSecurityLaserOAM_VerticalVeryLargeDisappearing:
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing,56
sSecurityLaserOAM_HorizontalSmallDisappearing:
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing,56
sSecurityLaserOAM_HorizontalMediumDisappearing:
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing,56
sSecurityLaserOAM_HorizontalLargeDisappearing:
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing,56
sSecurityLaserOAM_HorizontalVeryLargeDisappearing:
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame0
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame1
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame2
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame3
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame4
	.byte	0x1
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Frame5
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused,object
	.size	 sSecurityLaserOAM_VerticalSmallDisappearing_Unused,56
sSecurityLaserOAM_VerticalSmallDisappearing_Unused:
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalSmallDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused,object
	.size	 sSecurityLaserOAM_VerticalMediumDisappearing_Unused,56
sSecurityLaserOAM_VerticalMediumDisappearing_Unused:
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalMediumDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused,object
	.size	 sSecurityLaserOAM_VerticalLargeDisappearing_Unused,56
sSecurityLaserOAM_VerticalLargeDisappearing_Unused:
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalLargeDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused,object
	.size	 sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused,56
sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused:
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_VerticalVeryLargeDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused,object
	.size	 sSecurityLaserOAM_HorizontalSmallDisappearing_Unused,56
sSecurityLaserOAM_HorizontalSmallDisappearing_Unused:
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalSmallDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused,object
	.size	 sSecurityLaserOAM_HorizontalMediumDisappearing_Unused,56
sSecurityLaserOAM_HorizontalMediumDisappearing_Unused:
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalMediumDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused,object
	.size	 sSecurityLaserOAM_HorizontalLargeDisappearing_Unused,56
sSecurityLaserOAM_HorizontalLargeDisappearing_Unused:
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalLargeDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused,object
	.size	 sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused,56
sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused:
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame0
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame1
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame2
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame3
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame4
	.byte	0x2
	.space	3
	.word	sSecurityLaserOAM_HorizontalVeryLargeDisappearing_Unused_Frame5
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
