@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sSkreeFallingSpeed,object
	.size	 sSkreeFallingSpeed,16
sSkreeFallingSpeed:
	.short	0x2
	.short	0x4
	.short	0x6
	.short	0x7
	.short	0xc
	.short	0xe
	.short	0x10
	.short	0x7fff
	.align	1, 0
	.type	 sSkreeOAM_Idle_Frame0,object
	.size	 sSkreeOAM_Idle_Frame0,26
sSkreeOAM_Idle_Frame0:
	.short	0x4
	.short	0x0
	.short	0x41f0
	.short	0x8200
	.short	0x10
	.short	0x41f0
	.short	0x8202
	.short	0x0
	.short	0x5000
	.short	0x8200
	.short	0x10
	.short	0x5000
	.short	0x8202
	.align	1, 0
	.type	 sSkreeOAM_Idle_Frame1,object
	.size	 sSkreeOAM_Idle_Frame1,14
sSkreeOAM_Idle_Frame1:
	.short	0x2
	.short	0x0
	.short	0x41f8
	.short	0x820c
	.short	0x10
	.short	0x41f8
	.short	0x820e
	.align	1, 0
	.type	 sSkreeOAM_Idle_Frame2,object
	.size	 sSkreeOAM_Idle_Frame2,26
sSkreeOAM_Idle_Frame2:
	.short	0x4
	.short	0x8000
	.short	0x1fc
	.short	0x8210
	.short	0x8010
	.short	0x1fc
	.short	0x8212
	.short	0x0
	.short	0x4
	.short	0x8211
	.short	0x0
	.short	0x11f4
	.short	0x8211
	.align	1, 0
	.type	 sSkreeOAM_Idle_Frame3,object
	.size	 sSkreeOAM_Idle_Frame3,14
sSkreeOAM_Idle_Frame3:
	.short	0x2
	.short	0x0
	.short	0x41f8
	.short	0x8213
	.short	0x10
	.short	0x41f8
	.short	0x8215
	.align	1, 0
	.type	 sSkreeOAM_Spinning_Frame1,object
	.size	 sSkreeOAM_Spinning_Frame1,26
sSkreeOAM_Spinning_Frame1:
	.short	0x4
	.short	0x0
	.short	0x41f0
	.short	0x8208
	.short	0x4010
	.short	0x1f0
	.short	0x820a
	.short	0x0
	.short	0x5000
	.short	0x8208
	.short	0x4010
	.short	0x1000
	.short	0x820a
	.align	1, 0
	.type	 sSkreeOAM_Spinning_Frame2,object
	.size	 sSkreeOAM_Spinning_Frame2,26
sSkreeOAM_Spinning_Frame2:
	.short	0x4
	.short	0x0
	.short	0x41f0
	.short	0x8204
	.short	0x4010
	.short	0x1f0
	.short	0x8206
	.short	0x0
	.short	0x5000
	.short	0x8204
	.short	0x4010
	.short	0x1000
	.short	0x8206
	.align	1, 0
	.type	 sSkreeOAM_CrashingUnused_Frame0,object
	.size	 sSkreeOAM_CrashingUnused_Frame0,26
sSkreeOAM_CrashingUnused_Frame0:
	.short	0x4
	.short	0xf0
	.short	0x61f0
	.short	0x8200
	.short	0xe0
	.short	0x61f0
	.short	0x8202
	.short	0xf0
	.short	0x7000
	.short	0x8200
	.short	0xe0
	.short	0x7000
	.short	0x8202
	.align	1, 0
	.type	 sSkreeOAM_CrashingUnused_Frame1,object
	.size	 sSkreeOAM_CrashingUnused_Frame1,14
sSkreeOAM_CrashingUnused_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x61f8
	.short	0x820c
	.short	0xe0
	.short	0x61f8
	.short	0x820e
	.align	1, 0
	.type	 sSkreeOAM_CrashingUnused_Frame2,object
	.size	 sSkreeOAM_CrashingUnused_Frame2,26
sSkreeOAM_CrashingUnused_Frame2:
	.short	0x4
	.short	0x80f0
	.short	0x21fc
	.short	0x8210
	.short	0x80e0
	.short	0x21fc
	.short	0x8212
	.short	0xf8
	.short	0x2004
	.short	0x8211
	.short	0xf8
	.short	0x31f4
	.short	0x8211
	.align	1, 0
	.type	 sSkreeOAM_CrashingUnused_Frame3,object
	.size	 sSkreeOAM_CrashingUnused_Frame3,14
sSkreeOAM_CrashingUnused_Frame3:
	.short	0x2
	.short	0xf0
	.short	0x61f8
	.short	0x8213
	.short	0xe0
	.short	0x61f8
	.short	0x8215
	.align	1, 0
	.type	 sSkreeOAM_CrashingUnused2_Frame1,object
	.size	 sSkreeOAM_CrashingUnused2_Frame1,26
sSkreeOAM_CrashingUnused2_Frame1:
	.short	0x4
	.short	0xf0
	.short	0x61f0
	.short	0x8208
	.short	0x40e8
	.short	0x21f0
	.short	0x820a
	.short	0xf0
	.short	0x7000
	.short	0x8208
	.short	0x40e8
	.short	0x3000
	.short	0x820a
	.align	1, 0
	.type	 sSkreeOAM_CrashingUnused2_Frame2,object
	.size	 sSkreeOAM_CrashingUnused2_Frame2,26
sSkreeOAM_CrashingUnused2_Frame2:
	.short	0x4
	.short	0xf0
	.short	0x61f0
	.short	0x8204
	.short	0x40e8
	.short	0x21f0
	.short	0x8206
	.short	0xf0
	.short	0x7000
	.short	0x8204
	.short	0x40e8
	.short	0x3000
	.short	0x8206
	.align	1, 0
	.type	 sSkreeExplosionOAM_GoingUp_Frame0,object
	.size	 sSkreeExplosionOAM_GoingUp_Frame0,20
sSkreeExplosionOAM_GoingUp_Frame0:
	.short	0x3
	.short	0x6
	.short	0x1fb
	.short	0x8238
	.short	0xf6
	.short	0x1fb
	.short	0x8217
	.short	0xfe
	.short	0x1fb
	.short	0x8218
	.align	1, 0
	.type	 sSkreeExplosionOAM_GoingUp_Frame1,object
	.size	 sSkreeExplosionOAM_GoingUp_Frame1,20
sSkreeExplosionOAM_GoingUp_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x1fb
	.short	0x8217
	.short	0xfd
	.short	0x1fb
	.short	0x8218
	.short	0x2
	.short	0x1fb
	.short	0x8238
	.align	1, 0
	.type	 sSkreeExplosionOAM_GoingUp_Frame2,object
	.size	 sSkreeExplosionOAM_GoingUp_Frame2,14
sSkreeExplosionOAM_GoingUp_Frame2:
	.short	0x2
	.short	0xff
	.short	0x1f9
	.short	0x8238
	.short	0xf9
	.short	0x21f9
	.short	0x8238
	.align	1, 0
	.type	 sSkreeExplosionOAM_GoingDown_Frame0,object
	.size	 sSkreeExplosionOAM_GoingDown_Frame0,20
sSkreeExplosionOAM_GoingDown_Frame0:
	.short	0x3
	.short	0x80f6
	.short	0x1fa
	.short	0x8219
	.short	0x6
	.short	0x1fa
	.short	0x823a
	.short	0xfe
	.short	0x1fa
	.short	0x821a
	.align	1, 0
	.type	 sSkreeExplosionOAM_GoingDown_Frame1,object
	.size	 sSkreeExplosionOAM_GoingDown_Frame1,14
sSkreeExplosionOAM_GoingDown_Frame1:
	.short	0x2
	.short	0xfa
	.short	0x1fa
	.short	0x8219
	.short	0xfe
	.short	0x1fa
	.short	0x821a
	.align	1, 0
	.type	 sSkreeExplosionOAM_GoingDown_Frame2,object
	.size	 sSkreeExplosionOAM_GoingDown_Frame2,8
sSkreeExplosionOAM_GoingDown_Frame2:
	.short	0x1
	.short	0xfc
	.short	0x1fa
	.short	0x8219
	.align	2, 0
	.type	 sSkreeOAM_Idle,object
	.size	 sSkreeOAM_Idle,40
sSkreeOAM_Idle:
	.word	sSkreeOAM_Idle_Frame0
	.byte	0x8
	.space	3
	.word	sSkreeOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	sSkreeOAM_Idle_Frame2
	.byte	0x8
	.space	3
	.word	sSkreeOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_Spinning,object
	.size	 sSkreeOAM_Spinning,48
sSkreeOAM_Spinning:
	.word	sSkreeOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sSkreeOAM_Spinning_Frame1
	.byte	0x2
	.space	3
	.word	sSkreeOAM_Spinning_Frame2
	.byte	0x2
	.space	3
	.word	sSkreeOAM_Spinning_Frame1
	.byte	0x2
	.space	3
	.word	sSkreeOAM_Spinning_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_GoingDown,object
	.size	 sSkreeOAM_GoingDown,40
sSkreeOAM_GoingDown:
	.word	sSkreeOAM_Idle_Frame0
	.byte	0x2
	.space	3
	.word	sSkreeOAM_Idle_Frame1
	.byte	0x2
	.space	3
	.word	sSkreeOAM_Idle_Frame2
	.byte	0x2
	.space	3
	.word	sSkreeOAM_Idle_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_Crashing,object
	.size	 sSkreeOAM_Crashing,40
sSkreeOAM_Crashing:
	.word	sSkreeOAM_Idle_Frame0
	.byte	0x1
	.space	3
	.word	sSkreeOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sSkreeOAM_Idle_Frame2
	.byte	0x1
	.space	3
	.word	sSkreeOAM_Idle_Frame3
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_CrashingUnused,object
	.size	 sSkreeOAM_CrashingUnused,40
sSkreeOAM_CrashingUnused:
	.word	sSkreeOAM_CrashingUnused_Frame0
	.byte	0x8
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame1
	.byte	0x8
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame2
	.byte	0x8
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_CrashingUnused2,object
	.size	 sSkreeOAM_CrashingUnused2,48
sSkreeOAM_CrashingUnused2:
	.word	sSkreeOAM_CrashingUnused_Frame0
	.byte	0x4
	.space	3
	.word	sSkreeOAM_CrashingUnused2_Frame1
	.byte	0x2
	.space	3
	.word	sSkreeOAM_CrashingUnused2_Frame2
	.byte	0x4
	.space	3
	.word	sSkreeOAM_CrashingUnused2_Frame1
	.byte	0x1
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame2
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_CrashingUnused3,object
	.size	 sSkreeOAM_CrashingUnused3,40
sSkreeOAM_CrashingUnused3:
	.word	sSkreeOAM_CrashingUnused_Frame0
	.byte	0x2
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame1
	.byte	0x2
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame2
	.byte	0x2
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeOAM_CrashingUnused4,object
	.size	 sSkreeOAM_CrashingUnused4,40
sSkreeOAM_CrashingUnused4:
	.word	sSkreeOAM_CrashingUnused_Frame0
	.byte	0x1
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame1
	.byte	0x1
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame2
	.byte	0x1
	.space	3
	.word	sSkreeOAM_CrashingUnused_Frame3
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeExplosionOAM_GoingDown,object
	.size	 sSkreeExplosionOAM_GoingDown,32
sSkreeExplosionOAM_GoingDown:
	.word	sSkreeExplosionOAM_GoingDown_Frame0
	.byte	0x8
	.space	3
	.word	sSkreeExplosionOAM_GoingDown_Frame1
	.byte	0x6
	.space	3
	.word	sSkreeExplosionOAM_GoingDown_Frame2
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkreeExplosionOAM_GoingUp,object
	.size	 sSkreeExplosionOAM_GoingUp,32
sSkreeExplosionOAM_GoingUp:
	.word	sSkreeExplosionOAM_GoingUp_Frame0
	.byte	0x8
	.space	3
	.word	sSkreeExplosionOAM_GoingUp_Frame1
	.byte	0x6
	.space	3
	.word	sSkreeExplosionOAM_GoingUp_Frame2
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
