@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sSkulteraOAM_Idle_Frame0,object
	.size	 sSkulteraOAM_Idle_Frame0,38
sSkulteraOAM_Idle_Frame0:
	.short	0x6
	.short	0x40e1
	.short	0x81ef
	.short	0x8207
	.short	0x40f1
	.short	0x41ef
	.short	0x8213
	.short	0x40f9
	.short	0x41f0
	.short	0x8233
	.short	0xf1
	.short	0x1
	.short	0x8200
	.short	0xf4
	.short	0x2005
	.short	0x8201
	.short	0x80ef
	.short	0xb
	.short	0x8206
	.align	1, 0
	.type	 sSkulteraOAM_Idle_Frame1,object
	.size	 sSkulteraOAM_Idle_Frame1,38
sSkulteraOAM_Idle_Frame1:
	.short	0x6
	.short	0x40e1
	.short	0x81e6
	.short	0x820a
	.short	0x40f9
	.short	0x41e7
	.short	0x8236
	.short	0x40f1
	.short	0x41e6
	.short	0x8216
	.short	0xf2
	.short	0x1ff
	.short	0x8201
	.short	0xf5
	.short	0x6
	.short	0x8202
	.short	0xf3
	.short	0xa
	.short	0x8225
	.align	1, 0
	.type	 sSkulteraOAM_Idle_Frame2,object
	.size	 sSkulteraOAM_Idle_Frame2,32
sSkulteraOAM_Idle_Frame2:
	.short	0x5
	.short	0x40e1
	.short	0x81e6
	.short	0x820a
	.short	0x40f1
	.short	0x81e6
	.short	0x8216
	.short	0xf5
	.short	0x2000
	.short	0x8201
	.short	0xf3
	.short	0x7
	.short	0x8200
	.short	0xf3
	.short	0xb
	.short	0x8205
	.align	1, 0
	.type	 sSkulteraOAM_Idle_Frame3,object
	.size	 sSkulteraOAM_Idle_Frame3,32
sSkulteraOAM_Idle_Frame3:
	.short	0x5
	.short	0x40e2
	.short	0x81ee
	.short	0x8207
	.short	0x40f2
	.short	0x81ee
	.short	0x8213
	.short	0xf5
	.short	0x1
	.short	0x8202
	.short	0xf3
	.short	0x5
	.short	0x8201
	.short	0xf2
	.short	0x200a
	.short	0x8225
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame0,object
	.size	 sSkulteraOAM_TurningAround_Frame0,38
sSkulteraOAM_TurningAround_Frame0:
	.short	0x6
	.short	0x40e1
	.short	0x81e6
	.short	0x820a
	.short	0x40f9
	.short	0x41e7
	.short	0x8236
	.short	0x40f1
	.short	0x41e6
	.short	0x8216
	.short	0xf1
	.short	0x0
	.short	0x8201
	.short	0xf3
	.short	0x6
	.short	0x8202
	.short	0xf4
	.short	0x200b
	.short	0x8225
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame1,object
	.size	 sSkulteraOAM_TurningAround_Frame1,38
sSkulteraOAM_TurningAround_Frame1:
	.short	0x6
	.short	0xe1
	.short	0x41f2
	.short	0x820e
	.short	0xf1
	.short	0x41f2
	.short	0x821a
	.short	0xf9
	.short	0x2
	.short	0x8232
	.short	0xf2
	.short	0x1fc
	.short	0x8201
	.short	0xf4
	.short	0x1
	.short	0x8202
	.short	0xf2
	.short	0x6
	.short	0x8204
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame2,object
	.size	 sSkulteraOAM_TurningAround_Frame2,32
sSkulteraOAM_TurningAround_Frame2:
	.short	0x5
	.short	0xe1
	.short	0x41f0
	.short	0x8210
	.short	0xf1
	.short	0x41f0
	.short	0x821c
	.short	0x80f1
	.short	0x0
	.short	0x821e
	.short	0xf1
	.short	0x1fe
	.short	0x8200
	.short	0xf2
	.short	0x3
	.short	0x8205
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame3,object
	.size	 sSkulteraOAM_TurningAround_Frame3,26
sSkulteraOAM_TurningAround_Frame3:
	.short	0x4
	.short	0xe1
	.short	0x51f0
	.short	0x820e
	.short	0xf1
	.short	0x51f0
	.short	0x821a
	.short	0xf1
	.short	0x11ed
	.short	0x8200
	.short	0xf3
	.short	0x1fd
	.short	0x8203
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame4,object
	.size	 sSkulteraOAM_TurningAround_Frame4,20
sSkulteraOAM_TurningAround_Frame4:
	.short	0x3
	.short	0x40e1
	.short	0x91f0
	.short	0x820a
	.short	0x40f1
	.short	0x91f0
	.short	0x8216
	.short	0xf1
	.short	0x11ee
	.short	0x8201
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame5,object
	.size	 sSkulteraOAM_TurningAround_Frame5,26
sSkulteraOAM_TurningAround_Frame5:
	.short	0x4
	.short	0x40e2
	.short	0x91eb
	.short	0x8207
	.short	0x40f2
	.short	0x91eb
	.short	0x8213
	.short	0xf4
	.short	0x11f1
	.short	0x8202
	.short	0xf1
	.short	0x11ee
	.short	0x8200
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame6,object
	.size	 sSkulteraOAM_TurningAround_Frame6,38
sSkulteraOAM_TurningAround_Frame6:
	.short	0x6
	.short	0x40e1
	.short	0x91ee
	.short	0x8207
	.short	0x40f1
	.short	0x51ee
	.short	0x8213
	.short	0x40f9
	.short	0x51ed
	.short	0x8233
	.short	0xf1
	.short	0x11f4
	.short	0x8200
	.short	0xf4
	.short	0x11ef
	.short	0x8202
	.short	0xf2
	.short	0x11ed
	.short	0x8204
	.align	1, 0
	.type	 sSkulteraOAM_TurningAround_Frame7,object
	.size	 sSkulteraOAM_TurningAround_Frame7,38
sSkulteraOAM_TurningAround_Frame7:
	.short	0x6
	.short	0x40e1
	.short	0x91fa
	.short	0x820a
	.short	0x40f9
	.short	0x51f9
	.short	0x8236
	.short	0x40f1
	.short	0x51fa
	.short	0x8216
	.short	0xf4
	.short	0x11f8
	.short	0x8202
	.short	0xf1
	.short	0x11f3
	.short	0x8200
	.short	0xf2
	.short	0x11ee
	.short	0x8205
	.align	2, 0
	.type	 sSkulteraOAM_Idle,object
	.size	 sSkulteraOAM_Idle,40
sSkulteraOAM_Idle:
	.word	sSkulteraOAM_Idle_Frame0
	.byte	0x8
	.space	3
	.word	sSkulteraOAM_Idle_Frame1
	.byte	0x8
	.space	3
	.word	sSkulteraOAM_Idle_Frame2
	.byte	0x8
	.space	3
	.word	sSkulteraOAM_Idle_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkulteraOAM_TurningAround,object
	.size	 sSkulteraOAM_TurningAround,72
sSkulteraOAM_TurningAround:
	.word	sSkulteraOAM_TurningAround_Frame0
	.byte	0xd
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame1
	.byte	0xa
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame2
	.byte	0x8
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame3
	.byte	0x6
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame4
	.byte	0x6
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame5
	.byte	0x8
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame6
	.byte	0xa
	.space	3
	.word	sSkulteraOAM_TurningAround_Frame7
	.byte	0xd
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSkulteraOAM_ChasingSamus,object
	.size	 sSkulteraOAM_ChasingSamus,40
sSkulteraOAM_ChasingSamus:
	.word	sSkulteraOAM_Idle_Frame0
	.byte	0x3
	.space	3
	.word	sSkulteraOAM_Idle_Frame3
	.byte	0x3
	.space	3
	.word	sSkulteraOAM_Idle_Frame2
	.byte	0x3
	.space	3
	.word	sSkulteraOAM_Idle_Frame3
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
