@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sFakePowerBombOAM_Idle_Frame0,object
	.size	 sFakePowerBombOAM_Idle_Frame0,8
sFakePowerBombOAM_Idle_Frame0:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sFakePowerBombOAM_Idle_Frame1,object
	.size	 sFakePowerBombOAM_Idle_Frame1,8
sFakePowerBombOAM_Idle_Frame1:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sFakePowerBombOAM_Idle_Frame2,object
	.size	 sFakePowerBombOAM_Idle_Frame2,8
sFakePowerBombOAM_Idle_Frame2:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sFakePowerBombOAM_Idle_Frame3,object
	.size	 sFakePowerBombOAM_Idle_Frame3,8
sFakePowerBombOAM_Idle_Frame3:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8206
	.align	2, 0
	.type	 sFakePowerBombOAM_Idle,object
	.size	 sFakePowerBombOAM_Idle,40
sFakePowerBombOAM_Idle:
	.word	sFakePowerBombOAM_Idle_Frame0
	.byte	0x6
	.space	3
	.word	sFakePowerBombOAM_Idle_Frame1
	.byte	0x6
	.space	3
	.word	sFakePowerBombOAM_Idle_Frame2
	.byte	0x6
	.space	3
	.word	sFakePowerBombOAM_Idle_Frame3
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
