@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame0,object
	.size	 sSteamOAM_HorizontalLarge_Frame0,8
sSteamOAM_HorizontalLarge_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame1,object
	.size	 sSteamOAM_HorizontalLarge_Frame1,14
sSteamOAM_HorizontalLarge_Frame1:
	.short	0x2
	.short	0xf8
	.short	0x5000
	.short	0x8200
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame2,object
	.size	 sSteamOAM_HorizontalLarge_Frame2,20
sSteamOAM_HorizontalLarge_Frame2:
	.short	0x3
	.short	0xf8
	.short	0x700b
	.short	0x8200
	.short	0xf8
	.short	0x5002
	.short	0x8202
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame3,object
	.size	 sSteamOAM_HorizontalLarge_Frame3,26
sSteamOAM_HorizontalLarge_Frame3:
	.short	0x4
	.short	0xf8
	.short	0x6018
	.short	0x8200
	.short	0xf8
	.short	0x700c
	.short	0x8202
	.short	0xf8
	.short	0x4000
	.short	0x8204
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame4,object
	.size	 sSteamOAM_HorizontalLarge_Frame4,44
sSteamOAM_HorizontalLarge_Frame4:
	.short	0x7
	.short	0xf8
	.short	0x1f8
	.short	0x8207
	.short	0xfc
	.short	0x1000
	.short	0x8207
	.short	0x0
	.short	0x31f8
	.short	0x8207
	.short	0xf8
	.short	0x6025
	.short	0x8200
	.short	0xf8
	.short	0x701b
	.short	0x8202
	.short	0xf8
	.short	0x400e
	.short	0x8204
	.short	0xf8
	.short	0x4003
	.short	0x8206
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame5,object
	.size	 sSteamOAM_HorizontalLarge_Frame5,50
sSteamOAM_HorizontalLarge_Frame5:
	.short	0x8
	.short	0xf8
	.short	0x21fb
	.short	0x8208
	.short	0x0
	.short	0x1fd
	.short	0x8208
	.short	0xf8
	.short	0x7030
	.short	0x8202
	.short	0xf8
	.short	0x4020
	.short	0x8204
	.short	0xf8
	.short	0x4010
	.short	0x8206
	.short	0xf8
	.short	0x1008
	.short	0x8207
	.short	0xfc
	.short	0x0
	.short	0x8207
	.short	0x0
	.short	0x2008
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame6,object
	.size	 sSteamOAM_HorizontalLarge_Frame6,44
sSteamOAM_HorizontalLarge_Frame6:
	.short	0x7
	.short	0xf8
	.short	0x3003
	.short	0x8208
	.short	0x0
	.short	0x1001
	.short	0x8208
	.short	0xf8
	.short	0x4033
	.short	0x8204
	.short	0xf8
	.short	0x4020
	.short	0x8206
	.short	0x0
	.short	0x200d
	.short	0x8207
	.short	0xfc
	.short	0x3015
	.short	0x8207
	.short	0xf8
	.short	0x100d
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame7,object
	.size	 sSteamOAM_HorizontalLarge_Frame7,38
sSteamOAM_HorizontalLarge_Frame7:
	.short	0x6
	.short	0xf8
	.short	0x300f
	.short	0x8208
	.short	0x0
	.short	0x100d
	.short	0x8208
	.short	0xf8
	.short	0x4038
	.short	0x8206
	.short	0xf8
	.short	0x102d
	.short	0x8207
	.short	0xfc
	.short	0x25
	.short	0x8207
	.short	0x0
	.short	0x202d
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame8,object
	.size	 sSteamOAM_HorizontalLarge_Frame8,32
sSteamOAM_HorizontalLarge_Frame8:
	.short	0x5
	.short	0xf7
	.short	0x301a
	.short	0x8208
	.short	0xff
	.short	0x1018
	.short	0x8208
	.short	0x0
	.short	0x2038
	.short	0x8207
	.short	0xfc
	.short	0x3040
	.short	0x8207
	.short	0xf8
	.short	0x1038
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame9,object
	.size	 sSteamOAM_HorizontalLarge_Frame9,14
sSteamOAM_HorizontalLarge_Frame9:
	.short	0x2
	.short	0xf8
	.short	0x3032
	.short	0x8208
	.short	0x0
	.short	0x1030
	.short	0x8208
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame1,object
	.size	 sSteamOAM_VerticalLarge_Frame1,14
sSteamOAM_VerticalLarge_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x51f8
	.short	0x8200
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame2,object
	.size	 sSteamOAM_VerticalLarge_Frame2,20
sSteamOAM_VerticalLarge_Frame2:
	.short	0x3
	.short	0xe2
	.short	0x71f8
	.short	0x8200
	.short	0xed
	.short	0x51f8
	.short	0x8202
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame3,object
	.size	 sSteamOAM_VerticalLarge_Frame3,26
sSteamOAM_VerticalLarge_Frame3:
	.short	0x4
	.short	0xd3
	.short	0x61f8
	.short	0x8200
	.short	0xe0
	.short	0x71f8
	.short	0x8202
	.short	0xec
	.short	0x41f8
	.short	0x8204
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame4,object
	.size	 sSteamOAM_VerticalLarge_Frame4,44
sSteamOAM_VerticalLarge_Frame4:
	.short	0x7
	.short	0xf8
	.short	0x1f8
	.short	0x8207
	.short	0xfc
	.short	0x1000
	.short	0x8207
	.short	0x0
	.short	0x31f8
	.short	0x8207
	.short	0xc8
	.short	0x41f8
	.short	0x8200
	.short	0xd5
	.short	0x71f8
	.short	0x8202
	.short	0xdf
	.short	0x41f8
	.short	0x8204
	.short	0xef
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame5,object
	.size	 sSteamOAM_VerticalLarge_Frame5,50
sSteamOAM_VerticalLarge_Frame5:
	.short	0x8
	.short	0xf8
	.short	0x21fb
	.short	0x8208
	.short	0x0
	.short	0x1fd
	.short	0x8208
	.short	0xc0
	.short	0x71f8
	.short	0x8202
	.short	0xd0
	.short	0x41f8
	.short	0x8204
	.short	0xd8
	.short	0x41f8
	.short	0x8206
	.short	0xe8
	.short	0x1000
	.short	0x8207
	.short	0xec
	.short	0x1f8
	.short	0x8207
	.short	0xf0
	.short	0x2000
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame6,object
	.size	 sSteamOAM_VerticalLarge_Frame6,44
sSteamOAM_VerticalLarge_Frame6:
	.short	0x7
	.short	0xed
	.short	0x31fc
	.short	0x8208
	.short	0xf5
	.short	0x11fa
	.short	0x8208
	.short	0xbe
	.short	0x41f8
	.short	0x8204
	.short	0xcc
	.short	0x41f8
	.short	0x8206
	.short	0xe4
	.short	0x21f8
	.short	0x8207
	.short	0xe0
	.short	0x3000
	.short	0x8207
	.short	0xdc
	.short	0x11f8
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame7,object
	.size	 sSteamOAM_VerticalLarge_Frame7,38
sSteamOAM_VerticalLarge_Frame7:
	.short	0x6
	.short	0xe5
	.short	0x31fd
	.short	0x8208
	.short	0xed
	.short	0x11fb
	.short	0x8208
	.short	0xbb
	.short	0x41f8
	.short	0x8206
	.short	0xd8
	.short	0x3000
	.short	0x8207
	.short	0xd4
	.short	0x21f8
	.short	0x8207
	.short	0xd0
	.short	0x0
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame8,object
	.size	 sSteamOAM_VerticalLarge_Frame8,32
sSteamOAM_VerticalLarge_Frame8:
	.short	0x5
	.short	0xda
	.short	0x21fb
	.short	0x8208
	.short	0xe2
	.short	0x1fd
	.short	0x8208
	.short	0xc8
	.short	0x21f8
	.short	0x8207
	.short	0xc4
	.short	0x3000
	.short	0x8207
	.short	0xc0
	.short	0x11f8
	.short	0x8207
	.align	1, 0
	.type	 sSteamOAM_VerticalLarge_Frame9,object
	.size	 sSteamOAM_VerticalLarge_Frame9,14
sSteamOAM_VerticalLarge_Frame9:
	.short	0x2
	.short	0xcc
	.short	0x31fd
	.short	0x8208
	.short	0xd4
	.short	0x11fb
	.short	0x8208
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame0,object
	.size	 sSteamOAM_HorizontalSmall_Frame0,8
sSteamOAM_HorizontalSmall_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x11fd
	.short	0x8209
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame1,object
	.size	 sSteamOAM_HorizontalSmall_Frame1,14
sSteamOAM_HorizontalSmall_Frame1:
	.short	0x2
	.short	0xf8
	.short	0x1004
	.short	0x8209
	.short	0xf8
	.short	0x1ff
	.short	0x8209
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame2,object
	.size	 sSteamOAM_HorizontalSmall_Frame2,20
sSteamOAM_HorizontalSmall_Frame2:
	.short	0x3
	.short	0xf8
	.short	0xb
	.short	0x8209
	.short	0xfa
	.short	0x11fc
	.short	0x820b
	.short	0xf8
	.short	0x3
	.short	0x8209
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame3,object
	.size	 sSteamOAM_HorizontalSmall_Frame3,26
sSteamOAM_HorizontalSmall_Frame3:
	.short	0x4
	.short	0xf8
	.short	0x1011
	.short	0x8209
	.short	0xfa
	.short	0x1000
	.short	0x820b
	.short	0xf8
	.short	0x8
	.short	0x8209
	.short	0xf8
	.short	0x11fc
	.short	0x820c
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame4,object
	.size	 sSteamOAM_HorizontalSmall_Frame4,32
sSteamOAM_HorizontalSmall_Frame4:
	.short	0x5
	.short	0xf9
	.short	0x1000
	.short	0x820d
	.short	0xf8
	.short	0x100c
	.short	0x820b
	.short	0xf8
	.short	0x1008
	.short	0x820c
	.short	0xf8
	.short	0x101a
	.short	0x8209
	.short	0xf8
	.short	0x1013
	.short	0x8209
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame5,object
	.size	 sSteamOAM_HorizontalSmall_Frame5,32
sSteamOAM_HorizontalSmall_Frame5:
	.short	0x5
	.short	0xf8
	.short	0x1003
	.short	0x820d
	.short	0xf8
	.short	0x1016
	.short	0x820b
	.short	0xf7
	.short	0x100f
	.short	0x820c
	.short	0xf7
	.short	0x100a
	.short	0x820d
	.short	0xf8
	.short	0x101e
	.short	0x820b
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame6,object
	.size	 sSteamOAM_HorizontalSmall_Frame6,26
sSteamOAM_HorizontalSmall_Frame6:
	.short	0x4
	.short	0xf8
	.short	0x1024
	.short	0x820c
	.short	0xf8
	.short	0x201a
	.short	0x820c
	.short	0xf8
	.short	0x100c
	.short	0x820d
	.short	0xf7
	.short	0x11
	.short	0x820d
	.align	1, 0
	.type	 sSteamOAM_HorizontalSmall_Frame7,object
	.size	 sSteamOAM_HorizontalSmall_Frame7,20
sSteamOAM_HorizontalSmall_Frame7:
	.short	0x3
	.short	0xf8
	.short	0x201e
	.short	0x820d
	.short	0xf8
	.short	0x1028
	.short	0x820d
	.short	0xf7
	.short	0x1013
	.short	0x820d
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame1,object
	.size	 sSteamOAM_VerticalSmall_Frame1,14
sSteamOAM_VerticalSmall_Frame1:
	.short	0x2
	.short	0xf1
	.short	0x11fc
	.short	0x8209
	.short	0xf8
	.short	0x1fc
	.short	0x8209
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame2,object
	.size	 sSteamOAM_VerticalSmall_Frame2,20
sSteamOAM_VerticalSmall_Frame2:
	.short	0x3
	.short	0xec
	.short	0x1fb
	.short	0x8209
	.short	0xfa
	.short	0x11fc
	.short	0x820b
	.short	0xf2
	.short	0x1fb
	.short	0x8209
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame3,object
	.size	 sSteamOAM_VerticalSmall_Frame3,26
sSteamOAM_VerticalSmall_Frame3:
	.short	0x4
	.short	0xe7
	.short	0x11fc
	.short	0x8209
	.short	0xee
	.short	0x1fc
	.short	0x8209
	.short	0xf4
	.short	0x11fc
	.short	0x820b
	.short	0xf8
	.short	0x11fc
	.short	0x820c
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame4,object
	.size	 sSteamOAM_VerticalSmall_Frame4,32
sSteamOAM_VerticalSmall_Frame4:
	.short	0x5
	.short	0xe1
	.short	0x11fc
	.short	0x8209
	.short	0xe8
	.short	0x11fc
	.short	0x8209
	.short	0xf7
	.short	0x11fc
	.short	0x820d
	.short	0xec
	.short	0x11fc
	.short	0x820b
	.short	0xf1
	.short	0x11fc
	.short	0x820c
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame5,object
	.size	 sSteamOAM_VerticalSmall_Frame5,32
sSteamOAM_VerticalSmall_Frame5:
	.short	0x5
	.short	0xf6
	.short	0x1fc
	.short	0x820d
	.short	0xe4
	.short	0x11fc
	.short	0x820b
	.short	0xea
	.short	0x11fc
	.short	0x820c
	.short	0xf0
	.short	0x11fc
	.short	0x820d
	.short	0xdd
	.short	0x11fc
	.short	0x820b
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame6,object
	.size	 sSteamOAM_VerticalSmall_Frame6,26
sSteamOAM_VerticalSmall_Frame6:
	.short	0x4
	.short	0xda
	.short	0x11fc
	.short	0x820c
	.short	0xe2
	.short	0x1fc
	.short	0x820c
	.short	0xf2
	.short	0x11fc
	.short	0x820d
	.short	0xe7
	.short	0x1fc
	.short	0x820d
	.align	1, 0
	.type	 sSteamOAM_VerticalSmall_Frame7,object
	.size	 sSteamOAM_VerticalSmall_Frame7,20
sSteamOAM_VerticalSmall_Frame7:
	.short	0x3
	.short	0xe4
	.short	0x11fc
	.short	0x820d
	.short	0xd7
	.short	0x11fc
	.short	0x820d
	.short	0xef
	.short	0x1fc
	.short	0x820d
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame1,object
	.size	 sSteamDiagonalOAM_Large_Frame1,14
sSteamDiagonalOAM_Large_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x5000
	.short	0x8200
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame2,object
	.size	 sSteamDiagonalOAM_Large_Frame2,20
sSteamDiagonalOAM_Large_Frame2:
	.short	0x3
	.short	0xe8
	.short	0x700b
	.short	0x8200
	.short	0xf0
	.short	0x5002
	.short	0x8202
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame3,object
	.size	 sSteamDiagonalOAM_Large_Frame3,26
sSteamDiagonalOAM_Large_Frame3:
	.short	0x4
	.short	0xe0
	.short	0x6018
	.short	0x8200
	.short	0xe8
	.short	0x700c
	.short	0x8202
	.short	0xf0
	.short	0x4000
	.short	0x8204
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame4,object
	.size	 sSteamDiagonalOAM_Large_Frame4,44
sSteamDiagonalOAM_Large_Frame4:
	.short	0x7
	.short	0xf8
	.short	0x1f8
	.short	0x8207
	.short	0xfc
	.short	0x1000
	.short	0x8207
	.short	0x0
	.short	0x31f8
	.short	0x8207
	.short	0xd8
	.short	0x6025
	.short	0x8200
	.short	0xe0
	.short	0x7019
	.short	0x8202
	.short	0xe8
	.short	0x400e
	.short	0x8204
	.short	0xf0
	.short	0x4003
	.short	0x8206
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame5,object
	.size	 sSteamDiagonalOAM_Large_Frame5,50
sSteamDiagonalOAM_Large_Frame5:
	.short	0x8
	.short	0xf8
	.short	0x21fb
	.short	0x8208
	.short	0x0
	.short	0x1fd
	.short	0x8208
	.short	0xd0
	.short	0x7030
	.short	0x8202
	.short	0xd8
	.short	0x4020
	.short	0x8204
	.short	0xe4
	.short	0x4010
	.short	0x8206
	.short	0xf0
	.short	0x1008
	.short	0x8207
	.short	0xf4
	.short	0x0
	.short	0x8207
	.short	0xf8
	.short	0x2008
	.short	0x8207
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame6,object
	.size	 sSteamDiagonalOAM_Large_Frame6,44
sSteamDiagonalOAM_Large_Frame6:
	.short	0x7
	.short	0xf0
	.short	0x3003
	.short	0x8208
	.short	0xf8
	.short	0x1001
	.short	0x8208
	.short	0xcc
	.short	0x5033
	.short	0x8204
	.short	0xd8
	.short	0x401f
	.short	0x8206
	.short	0xed
	.short	0x200d
	.short	0x8207
	.short	0xe9
	.short	0x3015
	.short	0x8207
	.short	0xe5
	.short	0x100d
	.short	0x8207
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame7,object
	.size	 sSteamDiagonalOAM_Large_Frame7,38
sSteamDiagonalOAM_Large_Frame7:
	.short	0x6
	.short	0xe8
	.short	0x300f
	.short	0x8208
	.short	0xf0
	.short	0x100d
	.short	0x8208
	.short	0xc8
	.short	0x4038
	.short	0x8206
	.short	0xd5
	.short	0x102b
	.short	0x8207
	.short	0xd9
	.short	0x23
	.short	0x8207
	.short	0xdd
	.short	0x202b
	.short	0x8207
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame8,object
	.size	 sSteamDiagonalOAM_Large_Frame8,32
sSteamDiagonalOAM_Large_Frame8:
	.short	0x5
	.short	0xd8
	.short	0x301a
	.short	0x8208
	.short	0xe0
	.short	0x1018
	.short	0x8208
	.short	0xca
	.short	0x203e
	.short	0x8207
	.short	0xc6
	.short	0x3046
	.short	0x8207
	.short	0xc2
	.short	0x103e
	.short	0x8207
	.align	1, 0
	.type	 sSteamDiagonalOAM_Large_Frame9,object
	.size	 sSteamDiagonalOAM_Large_Frame9,14
sSteamDiagonalOAM_Large_Frame9:
	.short	0x2
	.short	0xc8
	.short	0x3032
	.short	0x8208
	.short	0xd0
	.short	0x1030
	.short	0x8208
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame1,object
	.size	 sSteamDiagonalOAM_Small_Frame1,14
sSteamDiagonalOAM_Small_Frame1:
	.short	0x2
	.short	0xf4
	.short	0x1004
	.short	0x8209
	.short	0xf8
	.short	0x1ff
	.short	0x8209
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame2,object
	.size	 sSteamDiagonalOAM_Small_Frame2,20
sSteamDiagonalOAM_Small_Frame2:
	.short	0x3
	.short	0xee
	.short	0xb
	.short	0x8209
	.short	0xfa
	.short	0x11fc
	.short	0x820b
	.short	0xf4
	.short	0x3
	.short	0x8209
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame3,object
	.size	 sSteamDiagonalOAM_Small_Frame3,26
sSteamDiagonalOAM_Small_Frame3:
	.short	0x4
	.short	0xea
	.short	0x1011
	.short	0x8209
	.short	0xf6
	.short	0x1000
	.short	0x820b
	.short	0xf0
	.short	0x8
	.short	0x8209
	.short	0xf8
	.short	0x11fc
	.short	0x820c
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame4,object
	.size	 sSteamDiagonalOAM_Small_Frame4,32
sSteamDiagonalOAM_Small_Frame4:
	.short	0x5
	.short	0xf9
	.short	0x1000
	.short	0x820d
	.short	0xf2
	.short	0x1007
	.short	0x820b
	.short	0xf5
	.short	0x1004
	.short	0x820c
	.short	0xe5
	.short	0x1017
	.short	0x8209
	.short	0xeb
	.short	0x100e
	.short	0x8209
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame5,object
	.size	 sSteamDiagonalOAM_Small_Frame5,32
sSteamDiagonalOAM_Small_Frame5:
	.short	0x5
	.short	0xf8
	.short	0x1003
	.short	0x820d
	.short	0xe9
	.short	0x1013
	.short	0x820b
	.short	0xee
	.short	0x100e
	.short	0x820c
	.short	0xf3
	.short	0x100a
	.short	0x820d
	.short	0xe2
	.short	0x101c
	.short	0x820b
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame6,object
	.size	 sSteamDiagonalOAM_Small_Frame6,26
sSteamDiagonalOAM_Small_Frame6:
	.short	0x4
	.short	0xdc
	.short	0x1022
	.short	0x820c
	.short	0xe4
	.short	0x2019
	.short	0x820c
	.short	0xf0
	.short	0x100c
	.short	0x820d
	.short	0xeb
	.short	0x11
	.short	0x820d
	.align	1, 0
	.type	 sSteamDiagonalOAM_Small_Frame7,object
	.size	 sSteamDiagonalOAM_Small_Frame7,20
sSteamDiagonalOAM_Small_Frame7:
	.short	0x3
	.short	0xe0
	.short	0x201c
	.short	0x820d
	.short	0xd9
	.short	0x1026
	.short	0x820d
	.short	0xe5
	.short	0x1013
	.short	0x820d
	.align	1, 0
	.type	 sSteamOAM_HorizontalLarge_Frame10,object
	.size	 sSteamOAM_HorizontalLarge_Frame10,8
sSteamOAM_HorizontalLarge_Frame10:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x820e
	.align	2, 0
	.type	 sSteamOAM_HorizontalLarge,object
	.size	 sSteamOAM_HorizontalLarge,96
sSteamOAM_HorizontalLarge:
	.word	sSteamOAM_HorizontalLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame1
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame5
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame6
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame7
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame8
	.byte	0x4
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame9
	.byte	0x4
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame10
	.byte	0x28
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSteamOAM_VerticalLarge,object
	.size	 sSteamOAM_VerticalLarge,96
sSteamOAM_VerticalLarge:
	.word	sSteamOAM_HorizontalLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame1
	.byte	0x2
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame2
	.byte	0x2
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame3
	.byte	0x2
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame4
	.byte	0x2
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame5
	.byte	0x2
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame6
	.byte	0x3
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame7
	.byte	0x3
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame8
	.byte	0x4
	.space	3
	.word	sSteamOAM_VerticalLarge_Frame9
	.byte	0x4
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame10
	.byte	0x1e
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSteamOAM_HorizontalSmall,object
	.size	 sSteamOAM_HorizontalSmall,80
sSteamOAM_HorizontalSmall:
	.word	sSteamOAM_HorizontalSmall_Frame0
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame1
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame2
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame3
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame4
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame5
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame6
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame7
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame10
	.byte	0x14
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSteamOAM_VerticalSmall,object
	.size	 sSteamOAM_VerticalSmall,80
sSteamOAM_VerticalSmall:
	.word	sSteamOAM_HorizontalSmall_Frame0
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame1
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame2
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame3
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame4
	.byte	0x2
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame5
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame6
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalSmall_Frame7
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame10
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSteamDiagonalOAM_Large,object
	.size	 sSteamDiagonalOAM_Large,96
sSteamDiagonalOAM_Large:
	.word	sSteamOAM_HorizontalLarge_Frame0
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame1
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame2
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame3
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame4
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame5
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame6
	.byte	0x3
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame7
	.byte	0x3
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame8
	.byte	0x4
	.space	3
	.word	sSteamDiagonalOAM_Large_Frame9
	.byte	0x4
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame10
	.byte	0x23
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sSteamDiagonalOAM_Small,object
	.size	 sSteamDiagonalOAM_Small,80
sSteamDiagonalOAM_Small:
	.word	sSteamOAM_HorizontalSmall_Frame0
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame1
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame2
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame3
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame4
	.byte	0x2
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame5
	.byte	0x3
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame6
	.byte	0x3
	.space	3
	.word	sSteamDiagonalOAM_Small_Frame7
	.byte	0x3
	.space	3
	.word	sSteamOAM_HorizontalLarge_Frame10
	.byte	0xf
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
