@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sTangleVineGerutaMultiSpriteData_Idle_Frame0,object
	.size	 sTangleVineGerutaMultiSpriteData_Idle_Frame0,18
sTangleVineGerutaMultiSpriteData_Idle_Frame0:
	.short	0x8
	.short	0x0
	.short	-0x8
	.short	0xc
	.short	-0xc8
	.short	0x20
	.short	0x9
	.short	0x0
	.short	0x0
	.align	1, 0
	.type	 sTangleVineGerutaMultiSpriteData_Idle_Frame1,object
	.size	 sTangleVineGerutaMultiSpriteData_Idle_Frame1,18
sTangleVineGerutaMultiSpriteData_Idle_Frame1:
	.short	0x8
	.short	0x0
	.short	0x0
	.short	0xc
	.short	-0xc4
	.short	0x1c
	.short	0x9
	.short	0x0
	.short	0x0
	.align	1, 0
	.type	 sTangleVineGerutaMultiSpriteData_Idle_Frame2,object
	.size	 sTangleVineGerutaMultiSpriteData_Idle_Frame2,18
sTangleVineGerutaMultiSpriteData_Idle_Frame2:
	.short	0x8
	.short	0x0
	.short	0x0
	.short	0xc
	.short	-0xc0
	.short	0x1c
	.short	0x9
	.short	0x0
	.short	0x0
	.align	1, 0
	.type	 sTangleVineGerutaMultiSpriteData_Idle_Frame3,object
	.size	 sTangleVineGerutaMultiSpriteData_Idle_Frame3,18
sTangleVineGerutaMultiSpriteData_Idle_Frame3:
	.short	0x8
	.short	0x0
	.short	0x8
	.short	0xc
	.short	-0xbc
	.short	0x28
	.short	0x9
	.short	0x0
	.short	0x0
	.align	2, 0
	.type	 sTangleVineGerutaMultiSpriteData_Idle,object
	.size	 sTangleVineGerutaMultiSpriteData_Idle,40
sTangleVineGerutaMultiSpriteData_Idle:
	.word	sTangleVineGerutaMultiSpriteData_Idle_Frame0
	.byte	0xa
	.space	3
	.word	sTangleVineGerutaMultiSpriteData_Idle_Frame1
	.byte	0xa
	.space	3
	.word	sTangleVineGerutaMultiSpriteData_Idle_Frame2
	.byte	0xa
	.space	3
	.word	sTangleVineGerutaMultiSpriteData_Idle_Frame3
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	1, 0
	.type	 sTangleVineTallOAM_OnGround_Frame3,object
	.size	 sTangleVineTallOAM_OnGround_Frame3,26
sTangleVineTallOAM_OnGround_Frame3:
	.short	0x4
	.short	0x80c0
	.short	0x81fa
	.short	0x9248
	.short	0x80e0
	.short	0x81fa
	.short	0x92c8
	.short	0x80e0
	.short	0x41f6
	.short	0x9258
	.short	0xdc
	.short	0x1f5
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnGround_Frame2,object
	.size	 sTangleVineTallOAM_OnGround_Frame2,26
sTangleVineTallOAM_OnGround_Frame2:
	.short	0x4
	.short	0x80c0
	.short	0x81fb
	.short	0x924a
	.short	0x80e0
	.short	0x81fb
	.short	0x92ca
	.short	0x80e0
	.short	0x41f6
	.short	0x9259
	.short	0xdb
	.short	0x1f4
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnGround_Frame1,object
	.size	 sTangleVineTallOAM_OnGround_Frame1,26
sTangleVineTallOAM_OnGround_Frame1:
	.short	0x4
	.short	0x80c0
	.short	0x81fc
	.short	0x924c
	.short	0x80e0
	.short	0x81fc
	.short	0x92cc
	.short	0x80e0
	.short	0x41f6
	.short	0x925a
	.short	0xdc
	.short	0x1f4
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnGround_Frame0,object
	.size	 sTangleVineTallOAM_OnGround_Frame0,26
sTangleVineTallOAM_OnGround_Frame0:
	.short	0x4
	.short	0x80c0
	.short	0x81f8
	.short	0x924e
	.short	0x80e0
	.short	0x81f8
	.short	0x92ce
	.short	0x80e0
	.short	0x41f5
	.short	0x925b
	.short	0xdc
	.short	0x1f3
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnCeiling_Frame0,object
	.size	 sTangleVineTallOAM_OnCeiling_Frame0,26
sTangleVineTallOAM_OnCeiling_Frame0:
	.short	0x4
	.short	0x8020
	.short	0xa1fc
	.short	0x924c
	.short	0x8000
	.short	0xa1fc
	.short	0x92cc
	.short	0x8000
	.short	0x61f6
	.short	0x925a
	.short	0x1c
	.short	0x21f4
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnCeiling_Frame1,object
	.size	 sTangleVineTallOAM_OnCeiling_Frame1,26
sTangleVineTallOAM_OnCeiling_Frame1:
	.short	0x4
	.short	0x8020
	.short	0xa1f8
	.short	0x924e
	.short	0x8000
	.short	0xa1f8
	.short	0x92ce
	.short	0x8000
	.short	0x61f5
	.short	0x925b
	.short	0x1c
	.short	0x21f3
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnCeiling_Frame2,object
	.size	 sTangleVineTallOAM_OnCeiling_Frame2,26
sTangleVineTallOAM_OnCeiling_Frame2:
	.short	0x4
	.short	0x8020
	.short	0xa1f9
	.short	0x9248
	.short	0x8000
	.short	0xa1f9
	.short	0x92c8
	.short	0x8000
	.short	0x61f5
	.short	0x9258
	.short	0x1c
	.short	0x21f4
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineTallOAM_OnCeiling_Frame3,object
	.size	 sTangleVineTallOAM_OnCeiling_Frame3,26
sTangleVineTallOAM_OnCeiling_Frame3:
	.short	0x4
	.short	0x8020
	.short	0xa1fb
	.short	0x924a
	.short	0x8000
	.short	0xa1fb
	.short	0x92ca
	.short	0x8000
	.short	0x61f6
	.short	0x9259
	.short	0x1d
	.short	0x21f4
	.short	0x9310
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnGround_Frame3,object
	.size	 sTangleVineMediumOAM_OnGround_Frame3,20
sTangleVineMediumOAM_OnGround_Frame3:
	.short	0x3
	.short	0x80d0
	.short	0x81f8
	.short	0x9250
	.short	0xf0
	.short	0x41f8
	.short	0x92d0
	.short	0x80e0
	.short	0x41f8
	.short	0x925e
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnGround_Frame2,object
	.size	 sTangleVineMediumOAM_OnGround_Frame2,20
sTangleVineMediumOAM_OnGround_Frame2:
	.short	0x3
	.short	0x80d0
	.short	0x81f8
	.short	0x9252
	.short	0xf0
	.short	0x41f8
	.short	0x92d2
	.short	0x80e0
	.short	0x41f8
	.short	0x925f
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnGround_Frame1,object
	.size	 sTangleVineMediumOAM_OnGround_Frame1,20
sTangleVineMediumOAM_OnGround_Frame1:
	.short	0x3
	.short	0x80d0
	.short	0x81f8
	.short	0x9254
	.short	0xf0
	.short	0x41f8
	.short	0x92d4
	.short	0x80e0
	.short	0x41f8
	.short	0x925c
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnGround_Frame0,object
	.size	 sTangleVineMediumOAM_OnGround_Frame0,20
sTangleVineMediumOAM_OnGround_Frame0:
	.short	0x3
	.short	0x80d0
	.short	0x81fb
	.short	0x9256
	.short	0xf0
	.short	0x41fb
	.short	0x92d6
	.short	0x80e0
	.short	0x41f8
	.short	0x925d
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnCeiling_Frame0,object
	.size	 sTangleVineMediumOAM_OnCeiling_Frame0,20
sTangleVineMediumOAM_OnCeiling_Frame0:
	.short	0x3
	.short	0x8010
	.short	0xa1f8
	.short	0x9252
	.short	0x0
	.short	0x61f8
	.short	0x92d2
	.short	0x8000
	.short	0x71f5
	.short	0x925c
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnCeiling_Frame1,object
	.size	 sTangleVineMediumOAM_OnCeiling_Frame1,20
sTangleVineMediumOAM_OnCeiling_Frame1:
	.short	0x3
	.short	0x8010
	.short	0xa1f8
	.short	0x9254
	.short	0x0
	.short	0x61f8
	.short	0x92d4
	.short	0x8000
	.short	0x71f7
	.short	0x925d
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnCeiling_Frame2,object
	.size	 sTangleVineMediumOAM_OnCeiling_Frame2,20
sTangleVineMediumOAM_OnCeiling_Frame2:
	.short	0x3
	.short	0x8010
	.short	0xa1fc
	.short	0x9256
	.short	0x0
	.short	0x61fc
	.short	0x92d6
	.short	0x8000
	.short	0x71fa
	.short	0x925c
	.align	1, 0
	.type	 sTangleVineMediumOAM_OnCeiling_Frame3,object
	.size	 sTangleVineMediumOAM_OnCeiling_Frame3,20
sTangleVineMediumOAM_OnCeiling_Frame3:
	.short	0x3
	.short	0x8010
	.short	0xa1f8
	.short	0x9250
	.short	0x0
	.short	0x61f8
	.short	0x92d0
	.short	0x8000
	.short	0x71f8
	.short	0x925d
	.align	1, 0
	.type	 sTangleVineShortOAM_OnGround_Frame3,object
	.size	 sTangleVineShortOAM_OnGround_Frame3,20
sTangleVineShortOAM_OnGround_Frame3:
	.short	0x3
	.short	0x80e0
	.short	0x41fc
	.short	0x9258
	.short	0xdd
	.short	0x1fb
	.short	0x9310
	.short	0x80e0
	.short	0x5000
	.short	0x925c
	.align	1, 0
	.type	 sTangleVineShortOAM_OnGround_Frame2,object
	.size	 sTangleVineShortOAM_OnGround_Frame2,20
sTangleVineShortOAM_OnGround_Frame2:
	.short	0x3
	.short	0x80e0
	.short	0x41fc
	.short	0x9259
	.short	0xdc
	.short	0x1fb
	.short	0x9310
	.short	0x80e0
	.short	0x5000
	.short	0x925d
	.align	1, 0
	.type	 sTangleVineShortOAM_OnGround_Frame1,object
	.size	 sTangleVineShortOAM_OnGround_Frame1,20
sTangleVineShortOAM_OnGround_Frame1:
	.short	0x3
	.short	0x80e0
	.short	0x41fc
	.short	0x925a
	.short	0xde
	.short	0x1fa
	.short	0x9310
	.short	0x80e0
	.short	0x5000
	.short	0x925e
	.align	1, 0
	.type	 sTangleVineShortOAM_OnGround_Frame0,object
	.size	 sTangleVineShortOAM_OnGround_Frame0,20
sTangleVineShortOAM_OnGround_Frame0:
	.short	0x3
	.short	0x80e0
	.short	0x41fd
	.short	0x925b
	.short	0xdd
	.short	0x1fa
	.short	0x9310
	.short	0x80e0
	.short	0x5000
	.short	0x925f
	.align	1, 0
	.type	 sTangleVineShortOAM_OnCeiling_Frame0,object
	.size	 sTangleVineShortOAM_OnCeiling_Frame0,20
sTangleVineShortOAM_OnCeiling_Frame0:
	.short	0x3
	.short	0x8000
	.short	0x61fc
	.short	0x9258
	.short	0x14
	.short	0x0
	.short	0x9311
	.short	0x1b
	.short	0x1fd
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineShortOAM_OnCeiling_Frame1,object
	.size	 sTangleVineShortOAM_OnCeiling_Frame1,20
sTangleVineShortOAM_OnCeiling_Frame1:
	.short	0x3
	.short	0x8000
	.short	0x61fc
	.short	0x9259
	.short	0x14
	.short	0x1
	.short	0x9311
	.short	0x1b
	.short	0x1fa
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineShortOAM_OnCeiling_Frame2,object
	.size	 sTangleVineShortOAM_OnCeiling_Frame2,20
sTangleVineShortOAM_OnCeiling_Frame2:
	.short	0x3
	.short	0x8000
	.short	0x61fc
	.short	0x925a
	.short	0x15
	.short	0x0
	.short	0x9311
	.short	0x1a
	.short	0x1fb
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineShortOAM_OnCeiling_Frame3,object
	.size	 sTangleVineShortOAM_OnCeiling_Frame3,20
sTangleVineShortOAM_OnCeiling_Frame3:
	.short	0x3
	.short	0x8000
	.short	0x61fc
	.short	0x925b
	.short	0x14
	.short	0x1ff
	.short	0x9311
	.short	0x1c
	.short	0x1fb
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnGround_Frame0,object
	.size	 sTangleVineCurvedOAM_OnGround_Frame0,20
sTangleVineCurvedOAM_OnGround_Frame0:
	.short	0x3
	.short	0x80e0
	.short	0x51fc
	.short	0x925c
	.short	0x80e0
	.short	0x51f8
	.short	0x925e
	.short	0xdf
	.short	0x1001
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnGround_Frame1,object
	.size	 sTangleVineCurvedOAM_OnGround_Frame1,20
sTangleVineCurvedOAM_OnGround_Frame1:
	.short	0x3
	.short	0x80e0
	.short	0x51fc
	.short	0x925d
	.short	0x80e0
	.short	0x51f8
	.short	0x925f
	.short	0xdd
	.short	0x1000
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnGround_Frame2,object
	.size	 sTangleVineCurvedOAM_OnGround_Frame2,20
sTangleVineCurvedOAM_OnGround_Frame2:
	.short	0x3
	.short	0x80e0
	.short	0x51fc
	.short	0x925e
	.short	0x80e0
	.short	0x51f8
	.short	0x925c
	.short	0xdc
	.short	0x11fe
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnGround_Frame3,object
	.size	 sTangleVineCurvedOAM_OnGround_Frame3,20
sTangleVineCurvedOAM_OnGround_Frame3:
	.short	0x3
	.short	0x80e0
	.short	0x51fc
	.short	0x925f
	.short	0x80e0
	.short	0x51f8
	.short	0x925d
	.short	0xdb
	.short	0x11fb
	.short	0x9312
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnCeiling_Frame0,object
	.size	 sTangleVineCurvedOAM_OnCeiling_Frame0,20
sTangleVineCurvedOAM_OnCeiling_Frame0:
	.short	0x3
	.short	0x8000
	.short	0x61fa
	.short	0x925c
	.short	0x8000
	.short	0x61fe
	.short	0x925e
	.short	0x1c
	.short	0x1f7
	.short	0x9311
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnCeiling_Frame1,object
	.size	 sTangleVineCurvedOAM_OnCeiling_Frame1,20
sTangleVineCurvedOAM_OnCeiling_Frame1:
	.short	0x3
	.short	0x8000
	.short	0x61fa
	.short	0x925d
	.short	0x8000
	.short	0x61fe
	.short	0x925f
	.short	0x1d
	.short	0x1f8
	.short	0x9311
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnCeiling_Frame2,object
	.size	 sTangleVineCurvedOAM_OnCeiling_Frame2,20
sTangleVineCurvedOAM_OnCeiling_Frame2:
	.short	0x3
	.short	0x8000
	.short	0x61fa
	.short	0x925e
	.short	0x8000
	.short	0x61fe
	.short	0x925c
	.short	0x1d
	.short	0x1fa
	.short	0x9311
	.align	1, 0
	.type	 sTangleVineCurvedOAM_OnCeiling_Frame3,object
	.size	 sTangleVineCurvedOAM_OnCeiling_Frame3,20
sTangleVineCurvedOAM_OnCeiling_Frame3:
	.short	0x3
	.short	0x8000
	.short	0x61fa
	.short	0x925f
	.short	0x8000
	.short	0x61fe
	.short	0x925d
	.short	0x1d
	.short	0x1fc
	.short	0x9311
	.align	1, 0
	.type	 sTangleVineOAM_Unused_Frame,object
	.size	 sTangleVineOAM_Unused_Frame,8
sTangleVineOAM_Unused_Frame:
	.short	0x1
	.short	0x80c0
	.short	0x8000
	.short	0x9240
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame2,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame2,8
sTangleVineGerutaPartOAM_Grip_Frame2:
	.short	0x1
	.short	0x80bf
	.short	0x81fd
	.short	0x9242
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame4,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame4,8
sTangleVineGerutaPartOAM_Grip_Frame4:
	.short	0x1
	.short	0x80c1
	.short	0x81fc
	.short	0x9244
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame0,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame0,8
sTangleVineGerutaPartOAM_Grip_Frame0:
	.short	0x1
	.short	0x80c3
	.short	0x8001
	.short	0x9246
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame1,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame1,8
sTangleVineGerutaPartOAM_Grip_Frame1:
	.short	0x1
	.short	0x80c0
	.short	0x8000
	.short	0x9240
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame3,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame3,8
sTangleVineGerutaPartOAM_Grip_Frame3:
	.short	0x1
	.short	0x80bf
	.short	0x81fd
	.short	0x9242
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame5,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame5,8
sTangleVineGerutaPartOAM_Grip_Frame5:
	.short	0x1
	.short	0x80c1
	.short	0x81fc
	.short	0x9244
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Grip_Frame7,object
	.size	 sTangleVineGerutaPartOAM_Grip_Frame7,8
sTangleVineGerutaPartOAM_Grip_Frame7:
	.short	0x1
	.short	0x80c3
	.short	0x8001
	.short	0x9246
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Full_Frame0,object
	.size	 sTangleVineGerutaOAM_Full_Frame0,26
sTangleVineGerutaOAM_Full_Frame0:
	.short	0x4
	.short	0xd0
	.short	0x41f9
	.short	0x9288
	.short	0x80c1
	.short	0x81fd
	.short	0x9240
	.short	0x80e0
	.short	0x81f9
	.short	0x92c8
	.short	0xc8
	.short	0x1ff
	.short	0x9261
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Full_Frame1,object
	.size	 sTangleVineGerutaOAM_Full_Frame1,20
sTangleVineGerutaOAM_Full_Frame1:
	.short	0x3
	.short	0x80bf
	.short	0x81fc
	.short	0x9242
	.short	0x80c0
	.short	0x81fa
	.short	0x924a
	.short	0x80e0
	.short	0x81fa
	.short	0x92ca
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Full_Frame2,object
	.size	 sTangleVineGerutaOAM_Full_Frame2,20
sTangleVineGerutaOAM_Full_Frame2:
	.short	0x3
	.short	0x80c1
	.short	0x81fc
	.short	0x9244
	.short	0x80c0
	.short	0x81fc
	.short	0x924c
	.short	0x80e0
	.short	0x81fc
	.short	0x92cc
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Full_Frame3,object
	.size	 sTangleVineGerutaOAM_Full_Frame3,26
sTangleVineGerutaOAM_Full_Frame3:
	.short	0x4
	.short	0xd0
	.short	0x41f8
	.short	0x928e
	.short	0x80c1
	.short	0x81fd
	.short	0x9246
	.short	0x80e0
	.short	0x81f8
	.short	0x92ce
	.short	0x40c8
	.short	0x1f8
	.short	0x926e
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame0,object
	.size	 sTangleVineGerutaOAM_Root_Frame0,20
sTangleVineGerutaOAM_Root_Frame0:
	.short	0x3
	.short	0xc7
	.short	0x1ff
	.short	0x9261
	.short	0x80e0
	.short	0x81f9
	.short	0x92c8
	.short	0xd0
	.short	0x41f9
	.short	0x9288
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame2,object
	.size	 sTangleVineGerutaOAM_Root_Frame2,14
sTangleVineGerutaOAM_Root_Frame2:
	.short	0x2
	.short	0x80c0
	.short	0x81fb
	.short	0x924a
	.short	0x80e0
	.short	0x81fb
	.short	0x92ca
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame4,object
	.size	 sTangleVineGerutaOAM_Root_Frame4,14
sTangleVineGerutaOAM_Root_Frame4:
	.short	0x2
	.short	0x80c0
	.short	0x81fc
	.short	0x924c
	.short	0x80e0
	.short	0x81fc
	.short	0x92cc
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame6,object
	.size	 sTangleVineGerutaOAM_Root_Frame6,14
sTangleVineGerutaOAM_Root_Frame6:
	.short	0x2
	.short	0x80e0
	.short	0x81f8
	.short	0x92ce
	.short	0xd0
	.short	0x41f8
	.short	0x928e
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame1,object
	.size	 sTangleVineGerutaOAM_Root_Frame1,20
sTangleVineGerutaOAM_Root_Frame1:
	.short	0x3
	.short	0xc7
	.short	0x1ff
	.short	0x9261
	.short	0x80e0
	.short	0x81f9
	.short	0x92c8
	.short	0xd0
	.short	0x41f9
	.short	0x9288
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame3,object
	.size	 sTangleVineGerutaOAM_Root_Frame3,14
sTangleVineGerutaOAM_Root_Frame3:
	.short	0x2
	.short	0x80c0
	.short	0x81fb
	.short	0x924a
	.short	0x80e0
	.short	0x81fb
	.short	0x92ca
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame5,object
	.size	 sTangleVineGerutaOAM_Root_Frame5,14
sTangleVineGerutaOAM_Root_Frame5:
	.short	0x2
	.short	0x80c0
	.short	0x81fc
	.short	0x924c
	.short	0x80e0
	.short	0x81fc
	.short	0x92cc
	.align	1, 0
	.type	 sTangleVineGerutaOAM_Root_Frame7,object
	.size	 sTangleVineGerutaOAM_Root_Frame7,14
sTangleVineGerutaOAM_Root_Frame7:
	.short	0x2
	.short	0x80e0
	.short	0x81f8
	.short	0x92ce
	.short	0xd0
	.short	0x41f8
	.short	0x928e
	.align	1, 0
	.type	 sTangleVineRedGerutaOAM_Frame0,object
	.size	 sTangleVineRedGerutaOAM_Frame0,56
sTangleVineRedGerutaOAM_Frame0:
	.short	0x9
	.short	0x80bb
	.short	0x91f5
	.short	0xa2c2
	.short	0x40d5
	.short	0x1fa
	.short	0xa316
	.short	0x80ce
	.short	0x81f7
	.short	0xa2d8
	.short	0xd5
	.short	0x41fa
	.short	0xa202
	.short	0xd3
	.short	0x5008
	.short	0xa208
	.short	0xd4
	.short	0x41eb
	.short	0xa208
	.short	0xd9
	.short	0x5004
	.short	0xa212
	.short	0xd9
	.short	0x41ef
	.short	0xa212
	.short	0x80e0
	.short	0x81fb
	.short	0xa2c0
	.align	1, 0
	.type	 sTangleVineRedGerutaOAM_Frame1,object
	.size	 sTangleVineRedGerutaOAM_Frame1,56
sTangleVineRedGerutaOAM_Frame1:
	.short	0x9
	.short	0x40d5
	.short	0x1fb
	.short	0xa316
	.short	0x80bb
	.short	0x91f4
	.short	0xa2c4
	.short	0x80cf
	.short	0x81f9
	.short	0xa2da
	.short	0xd5
	.short	0x41fb
	.short	0xa202
	.short	0xd3
	.short	0x5009
	.short	0xa208
	.short	0xd4
	.short	0x41ec
	.short	0xa208
	.short	0xd9
	.short	0x5005
	.short	0xa212
	.short	0xd9
	.short	0x41f0
	.short	0xa212
	.short	0x80e0
	.short	0x81fc
	.short	0xa2c2
	.align	1, 0
	.type	 sTangleVineRedGerutaOAM_Frame2,object
	.size	 sTangleVineRedGerutaOAM_Frame2,56
sTangleVineRedGerutaOAM_Frame2:
	.short	0x9
	.short	0x40d7
	.short	0x1fa
	.short	0xa316
	.short	0x80bc
	.short	0x91f3
	.short	0xa2c6
	.short	0x80d0
	.short	0x81f7
	.short	0xa2dc
	.short	0xd7
	.short	0x41fb
	.short	0xa202
	.short	0xd5
	.short	0x5009
	.short	0xa208
	.short	0xd6
	.short	0x41ec
	.short	0xa208
	.short	0xdb
	.short	0x5005
	.short	0xa212
	.short	0xdb
	.short	0x41f0
	.short	0xa212
	.short	0x80e0
	.short	0x81fb
	.short	0xa2c4
	.align	1, 0
	.type	 sTangleVineRedGerutaOAM_Frame3,object
	.size	 sTangleVineRedGerutaOAM_Frame3,56
sTangleVineRedGerutaOAM_Frame3:
	.short	0x9
	.short	0x80bb
	.short	0x91f5
	.short	0xa2c0
	.short	0x40d6
	.short	0x1fa
	.short	0xa316
	.short	0x80cf
	.short	0x81f7
	.short	0xa2da
	.short	0xd6
	.short	0x41fa
	.short	0xa202
	.short	0xd4
	.short	0x5008
	.short	0xa208
	.short	0xd5
	.short	0x41eb
	.short	0xa208
	.short	0xda
	.short	0x5004
	.short	0xa212
	.short	0xda
	.short	0x41ef
	.short	0xa212
	.short	0x80e0
	.short	0x81fc
	.short	0xa2c6
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame0,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame0,32
sTangleVineGerutaPartOAM_Geruta_Frame0:
	.short	0x5
	.short	0xf7
	.short	0x41f8
	.short	0x8200
	.short	0xf4
	.short	0x5006
	.short	0x8208
	.short	0xf6
	.short	0x41e9
	.short	0x8208
	.short	0xfa
	.short	0x5000
	.short	0x8212
	.short	0xfb
	.short	0x41f0
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame2,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame2,32
sTangleVineGerutaPartOAM_Geruta_Frame2:
	.short	0x5
	.short	0xf8
	.short	0x41ec
	.short	0x820c
	.short	0xf8
	.short	0x5005
	.short	0x820c
	.short	0xf8
	.short	0x41f9
	.short	0x8204
	.short	0xfd
	.short	0x51ff
	.short	0x8212
	.short	0xfc
	.short	0x41f2
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame4,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame4,32
sTangleVineGerutaPartOAM_Geruta_Frame4:
	.short	0x5
	.short	0xf5
	.short	0x41eb
	.short	0x820a
	.short	0xf6
	.short	0x5006
	.short	0x820a
	.short	0xf8
	.short	0x41f9
	.short	0x8204
	.short	0xfd
	.short	0x41ec
	.short	0x8210
	.short	0xfc
	.short	0x5006
	.short	0x8210
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame6,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame6,32
sTangleVineGerutaPartOAM_Geruta_Frame6:
	.short	0x5
	.short	0xf8
	.short	0x41ec
	.short	0x820c
	.short	0xf8
	.short	0x5005
	.short	0x820c
	.short	0xf8
	.short	0x41f9
	.short	0x8204
	.short	0xfd
	.short	0x51ff
	.short	0x8212
	.short	0xfc
	.short	0x41f2
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame1,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame1,32
sTangleVineGerutaPartOAM_Geruta_Frame1:
	.short	0x5
	.short	0xf8
	.short	0x41ea
	.short	0x820a
	.short	0xf8
	.short	0x5007
	.short	0x820a
	.short	0xf8
	.short	0x41f9
	.short	0x8202
	.short	0xfd
	.short	0x5000
	.short	0x8212
	.short	0xfc
	.short	0x41f0
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame3,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame3,32
sTangleVineGerutaPartOAM_Geruta_Frame3:
	.short	0x5
	.short	0xf8
	.short	0x41ea
	.short	0x820a
	.short	0xf8
	.short	0x5007
	.short	0x820a
	.short	0xf8
	.short	0x41f9
	.short	0x8202
	.short	0xfd
	.short	0x5000
	.short	0x8212
	.short	0xfc
	.short	0x41f0
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame5,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame5,32
sTangleVineGerutaPartOAM_Geruta_Frame5:
	.short	0x5
	.short	0xf8
	.short	0x41f9
	.short	0x8202
	.short	0xf6
	.short	0x5007
	.short	0x8208
	.short	0xf7
	.short	0x41ea
	.short	0x8208
	.short	0xfc
	.short	0x5003
	.short	0x8212
	.short	0xfc
	.short	0x41ee
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineGerutaPartOAM_Geruta_Frame7,object
	.size	 sTangleVineGerutaPartOAM_Geruta_Frame7,32
sTangleVineGerutaPartOAM_Geruta_Frame7:
	.short	0x5
	.short	0xf8
	.short	0x41f9
	.short	0x8200
	.short	0xf9
	.short	0x41ea
	.short	0x8208
	.short	0xf7
	.short	0x5006
	.short	0x8208
	.short	0xfc
	.short	0x5002
	.short	0x8212
	.short	0xfd
	.short	0x41f0
	.short	0x8212
	.align	1, 0
	.type	 sTangleVineLarvaRightOAM_Frame0,object
	.size	 sTangleVineLarvaRightOAM_Frame0,20
sTangleVineLarvaRightOAM_Frame0:
	.short	0x3
	.short	0x80d8
	.short	0x81fc
	.short	0xa2c0
	.short	0x80f8
	.short	0x1fb
	.short	0xa313
	.short	0x80c8
	.short	0x2003
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaRightOAM_Frame1,object
	.size	 sTangleVineLarvaRightOAM_Frame1,20
sTangleVineLarvaRightOAM_Frame1:
	.short	0x3
	.short	0x80d8
	.short	0x81fb
	.short	0xa2c2
	.short	0x80f8
	.short	0x1fb
	.short	0xa313
	.short	0x80c9
	.short	0x2001
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaRightOAM_Frame2,object
	.size	 sTangleVineLarvaRightOAM_Frame2,20
sTangleVineLarvaRightOAM_Frame2:
	.short	0x3
	.short	0x80d8
	.short	0x81fb
	.short	0xa2c4
	.short	0x80f8
	.short	0x1fb
	.short	0xa313
	.short	0x80c9
	.short	0x2000
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaRightOAM_Frame3,object
	.size	 sTangleVineLarvaRightOAM_Frame3,20
sTangleVineLarvaRightOAM_Frame3:
	.short	0x3
	.short	0x80d8
	.short	0x81fc
	.short	0xa2c6
	.short	0x80f8
	.short	0x1fb
	.short	0xa313
	.short	0x80c8
	.short	0x2000
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaLeftOAM_Frame0,object
	.size	 sTangleVineLarvaLeftOAM_Frame0,20
sTangleVineLarvaLeftOAM_Frame0:
	.short	0x3
	.short	0x80d9
	.short	0x91f4
	.short	0xa2c0
	.short	0x80f8
	.short	0x11fd
	.short	0xa313
	.short	0x80c9
	.short	0x31f5
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaLeftOAM_Frame1,object
	.size	 sTangleVineLarvaLeftOAM_Frame1,20
sTangleVineLarvaLeftOAM_Frame1:
	.short	0x3
	.short	0x80da
	.short	0x91f6
	.short	0xa2c2
	.short	0x80f8
	.short	0x11fd
	.short	0xa313
	.short	0x80cb
	.short	0x31f8
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaLeftOAM_Frame2,object
	.size	 sTangleVineLarvaLeftOAM_Frame2,20
sTangleVineLarvaLeftOAM_Frame2:
	.short	0x3
	.short	0x80da
	.short	0x91f5
	.short	0xa2c4
	.short	0x80f8
	.short	0x11fd
	.short	0xa313
	.short	0x80cb
	.short	0x31f8
	.short	0xa313
	.align	1, 0
	.type	 sTangleVineLarvaLeftOAM_Frame3,object
	.size	 sTangleVineLarvaLeftOAM_Frame3,20
sTangleVineLarvaLeftOAM_Frame3:
	.short	0x3
	.short	0x80d9
	.short	0x91f5
	.short	0xa2c6
	.short	0x80f8
	.short	0x11fd
	.short	0xa313
	.short	0x80c9
	.short	0x31f9
	.short	0xa313
	.align	2, 0
	.type	 sTangleVineTallOAM_OnGround,object
	.size	 sTangleVineTallOAM_OnGround,40
sTangleVineTallOAM_OnGround:
	.word	sTangleVineTallOAM_OnGround_Frame0
	.byte	0xc
	.space	3
	.word	sTangleVineTallOAM_OnGround_Frame1
	.byte	0xc
	.space	3
	.word	sTangleVineTallOAM_OnGround_Frame2
	.byte	0xc
	.space	3
	.word	sTangleVineTallOAM_OnGround_Frame3
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineMediumOAM_OnGround,object
	.size	 sTangleVineMediumOAM_OnGround,40
sTangleVineMediumOAM_OnGround:
	.word	sTangleVineMediumOAM_OnGround_Frame0
	.byte	0xa
	.space	3
	.word	sTangleVineMediumOAM_OnGround_Frame1
	.byte	0xa
	.space	3
	.word	sTangleVineMediumOAM_OnGround_Frame2
	.byte	0xa
	.space	3
	.word	sTangleVineMediumOAM_OnGround_Frame3
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineShortOAM_OnGround,object
	.size	 sTangleVineShortOAM_OnGround,40
sTangleVineShortOAM_OnGround:
	.word	sTangleVineTallOAM_OnGround_Frame0
	.byte	0x8
	.space	3
	.word	sTangleVineTallOAM_OnGround_Frame1
	.byte	0x8
	.space	3
	.word	sTangleVineTallOAM_OnGround_Frame2
	.byte	0x8
	.space	3
	.word	sTangleVineTallOAM_OnGround_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineCurvedOAM_OnGround,object
	.size	 sTangleVineCurvedOAM_OnGround,56
sTangleVineCurvedOAM_OnGround:
	.word	sTangleVineCurvedOAM_OnGround_Frame0
	.byte	0xa
	.space	3
	.word	sTangleVineCurvedOAM_OnGround_Frame1
	.byte	0xa
	.space	3
	.word	sTangleVineCurvedOAM_OnGround_Frame2
	.byte	0xa
	.space	3
	.word	sTangleVineCurvedOAM_OnGround_Frame3
	.byte	0xa
	.space	3
	.word	sTangleVineCurvedOAM_OnGround_Frame2
	.byte	0xa
	.space	3
	.word	sTangleVineCurvedOAM_OnGround_Frame1
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineTallOAM_OnCeiling,object
	.size	 sTangleVineTallOAM_OnCeiling,40
sTangleVineTallOAM_OnCeiling:
	.word	sTangleVineTallOAM_OnCeiling_Frame0
	.byte	0xd
	.space	3
	.word	sTangleVineTallOAM_OnCeiling_Frame1
	.byte	0xd
	.space	3
	.word	sTangleVineTallOAM_OnCeiling_Frame2
	.byte	0xd
	.space	3
	.word	sTangleVineTallOAM_OnCeiling_Frame3
	.byte	0xd
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineMediumOAM_OnCeiling,object
	.size	 sTangleVineMediumOAM_OnCeiling,40
sTangleVineMediumOAM_OnCeiling:
	.word	sTangleVineMediumOAM_OnCeiling_Frame0
	.byte	0xb
	.space	3
	.word	sTangleVineMediumOAM_OnCeiling_Frame1
	.byte	0xb
	.space	3
	.word	sTangleVineMediumOAM_OnCeiling_Frame2
	.byte	0xb
	.space	3
	.word	sTangleVineMediumOAM_OnCeiling_Frame3
	.byte	0xb
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineShortOAM_OnCeiling,object
	.size	 sTangleVineShortOAM_OnCeiling,40
sTangleVineShortOAM_OnCeiling:
	.word	sTangleVineShortOAM_OnCeiling_Frame0
	.byte	0x7
	.space	3
	.word	sTangleVineShortOAM_OnCeiling_Frame1
	.byte	0x7
	.space	3
	.word	sTangleVineShortOAM_OnCeiling_Frame2
	.byte	0x7
	.space	3
	.word	sTangleVineShortOAM_OnCeiling_Frame3
	.byte	0x7
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineCurvedOAM_OnCeiling,object
	.size	 sTangleVineCurvedOAM_OnCeiling,40
sTangleVineCurvedOAM_OnCeiling:
	.word	sTangleVineCurvedOAM_OnCeiling_Frame0
	.byte	0x5
	.space	3
	.word	sTangleVineCurvedOAM_OnCeiling_Frame1
	.byte	0x5
	.space	3
	.word	sTangleVineCurvedOAM_OnCeiling_Frame2
	.byte	0x5
	.space	3
	.word	sTangleVineCurvedOAM_OnCeiling_Frame3
	.byte	0x5
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineGerutaPartOAM_Grip,object
	.size	 sTangleVineGerutaPartOAM_Grip,72
sTangleVineGerutaPartOAM_Grip:
	.word	sTangleVineGerutaPartOAM_Grip_Frame0
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame1
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame2
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame3
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame4
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame5
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame0
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Grip_Frame7
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineGerutaOAM_Root,object
	.size	 sTangleVineGerutaOAM_Root,72
sTangleVineGerutaOAM_Root:
	.word	sTangleVineGerutaOAM_Root_Frame0
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame1
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame2
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame3
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame4
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame5
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame6
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaOAM_Root_Frame7
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineGerutaOAM_Full,object
	.size	 sTangleVineGerutaOAM_Full,40
sTangleVineGerutaOAM_Full:
	.word	sTangleVineGerutaOAM_Full_Frame0
	.byte	0xc
	.space	3
	.word	sTangleVineGerutaOAM_Full_Frame1
	.byte	0xc
	.space	3
	.word	sTangleVineGerutaOAM_Full_Frame2
	.byte	0xc
	.space	3
	.word	sTangleVineGerutaOAM_Full_Frame3
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineRedGerutaOAM,object
	.size	 sTangleVineRedGerutaOAM,40
sTangleVineRedGerutaOAM:
	.word	sTangleVineRedGerutaOAM_Frame0
	.byte	0xc
	.space	3
	.word	sTangleVineRedGerutaOAM_Frame1
	.byte	0xc
	.space	3
	.word	sTangleVineRedGerutaOAM_Frame2
	.byte	0xc
	.space	3
	.word	sTangleVineRedGerutaOAM_Frame3
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineGerutaPartOAM_Geruta,object
	.size	 sTangleVineGerutaPartOAM_Geruta,72
sTangleVineGerutaPartOAM_Geruta:
	.word	sTangleVineGerutaPartOAM_Geruta_Frame0
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame1
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame2
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame3
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame4
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame5
	.byte	0x6
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame6
	.byte	0x4
	.space	3
	.word	sTangleVineGerutaPartOAM_Geruta_Frame7
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineLarvaRightOAM,object
	.size	 sTangleVineLarvaRightOAM,40
sTangleVineLarvaRightOAM:
	.word	sTangleVineLarvaRightOAM_Frame0
	.byte	0xc
	.space	3
	.word	sTangleVineLarvaRightOAM_Frame1
	.byte	0xc
	.space	3
	.word	sTangleVineLarvaRightOAM_Frame2
	.byte	0xc
	.space	3
	.word	sTangleVineLarvaRightOAM_Frame3
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sTangleVineLarvaLeftOAM,object
	.size	 sTangleVineLarvaLeftOAM,40
sTangleVineLarvaLeftOAM:
	.word	sTangleVineLarvaLeftOAM_Frame0
	.byte	0x8
	.space	3
	.word	sTangleVineLarvaLeftOAM_Frame1
	.byte	0x8
	.space	3
	.word	sTangleVineLarvaLeftOAM_Frame2
	.byte	0x8
	.space	3
	.word	sTangleVineLarvaLeftOAM_Frame3
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
