@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sUnusedSpritesOAM_Idle_Frame0,object
	.size	 sUnusedSpritesOAM_Idle_Frame0,8
sUnusedSpritesOAM_Idle_Frame0:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x3151
	.align	1, 0
	.type	 sUnusedSpritesOAM_Idle_Frame1,object
	.size	 sUnusedSpritesOAM_Idle_Frame1,8
sUnusedSpritesOAM_Idle_Frame1:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x3150
	.align	2, 0
	.type	 sUnusedSpritesOAM_Idle,object
	.size	 sUnusedSpritesOAM_Idle,24
sUnusedSpritesOAM_Idle:
	.word	sUnusedSpritesOAM_Idle_Frame0
	.byte	0x1e
	.space	3
	.word	sUnusedSpritesOAM_Idle_Frame1
	.byte	0x1e
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sUnusedSpritesOAM_Unused,object
	.size	 sUnusedSpritesOAM_Unused,24
sUnusedSpritesOAM_Unused:
	.word	sUnusedSpritesOAM_Idle_Frame0
	.byte	0x1e
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.space	8
	.align 2, 0 @ dont insert nops
