@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame0,object
	.size	 sViolaOAM_Moving_Frame0,8
sViolaOAM_Moving_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame1,object
	.size	 sViolaOAM_Moving_Frame1,8
sViolaOAM_Moving_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame2,object
	.size	 sViolaOAM_Moving_Frame2,8
sViolaOAM_Moving_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame3,object
	.size	 sViolaOAM_Moving_Frame3,8
sViolaOAM_Moving_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame4,object
	.size	 sViolaOAM_Moving_Frame4,8
sViolaOAM_Moving_Frame4:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame5,object
	.size	 sViolaOAM_Moving_Frame5,8
sViolaOAM_Moving_Frame5:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820a
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame6,object
	.size	 sViolaOAM_Moving_Frame6,8
sViolaOAM_Moving_Frame6:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820c
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame7,object
	.size	 sViolaOAM_Moving_Frame7,8
sViolaOAM_Moving_Frame7:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820e
	.align	1, 0
	.type	 sViolaOAM_Moving_Frame8,object
	.size	 sViolaOAM_Moving_Frame8,8
sViolaOAM_Moving_Frame8:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8210
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame0,object
	.size	 sViolaOAM_MovingOffsetUp_Frame0,8
sViolaOAM_MovingOffsetUp_Frame0:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame1,object
	.size	 sViolaOAM_MovingOffsetUp_Frame1,8
sViolaOAM_MovingOffsetUp_Frame1:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame2,object
	.size	 sViolaOAM_MovingOffsetUp_Frame2,8
sViolaOAM_MovingOffsetUp_Frame2:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame3,object
	.size	 sViolaOAM_MovingOffsetUp_Frame3,8
sViolaOAM_MovingOffsetUp_Frame3:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame4,object
	.size	 sViolaOAM_MovingOffsetUp_Frame4,8
sViolaOAM_MovingOffsetUp_Frame4:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame5,object
	.size	 sViolaOAM_MovingOffsetUp_Frame5,8
sViolaOAM_MovingOffsetUp_Frame5:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x820a
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame6,object
	.size	 sViolaOAM_MovingOffsetUp_Frame6,8
sViolaOAM_MovingOffsetUp_Frame6:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x820c
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame7,object
	.size	 sViolaOAM_MovingOffsetUp_Frame7,8
sViolaOAM_MovingOffsetUp_Frame7:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x820e
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetUp_Frame8,object
	.size	 sViolaOAM_MovingOffsetUp_Frame8,8
sViolaOAM_MovingOffsetUp_Frame8:
	.short	0x1
	.short	0xf0
	.short	0x41f8
	.short	0x8210
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame0,object
	.size	 sViolaOAM_MovingOffsetRight_Frame0,8
sViolaOAM_MovingOffsetRight_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x8200
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame1,object
	.size	 sViolaOAM_MovingOffsetRight_Frame1,8
sViolaOAM_MovingOffsetRight_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x8202
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame2,object
	.size	 sViolaOAM_MovingOffsetRight_Frame2,8
sViolaOAM_MovingOffsetRight_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x8204
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame3,object
	.size	 sViolaOAM_MovingOffsetRight_Frame3,8
sViolaOAM_MovingOffsetRight_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x8206
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame4,object
	.size	 sViolaOAM_MovingOffsetRight_Frame4,8
sViolaOAM_MovingOffsetRight_Frame4:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x8208
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame5,object
	.size	 sViolaOAM_MovingOffsetRight_Frame5,8
sViolaOAM_MovingOffsetRight_Frame5:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x820a
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame6,object
	.size	 sViolaOAM_MovingOffsetRight_Frame6,8
sViolaOAM_MovingOffsetRight_Frame6:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x820c
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame7,object
	.size	 sViolaOAM_MovingOffsetRight_Frame7,8
sViolaOAM_MovingOffsetRight_Frame7:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x820e
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetRight_Frame8,object
	.size	 sViolaOAM_MovingOffsetRight_Frame8,8
sViolaOAM_MovingOffsetRight_Frame8:
	.short	0x1
	.short	0xf8
	.short	0x40f8
	.short	0x8210
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame0,object
	.size	 sViolaOAM_MovingOffsetDown_Frame0,8
sViolaOAM_MovingOffsetDown_Frame0:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame1,object
	.size	 sViolaOAM_MovingOffsetDown_Frame1,8
sViolaOAM_MovingOffsetDown_Frame1:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame2,object
	.size	 sViolaOAM_MovingOffsetDown_Frame2,8
sViolaOAM_MovingOffsetDown_Frame2:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame3,object
	.size	 sViolaOAM_MovingOffsetDown_Frame3,8
sViolaOAM_MovingOffsetDown_Frame3:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame4,object
	.size	 sViolaOAM_MovingOffsetDown_Frame4,8
sViolaOAM_MovingOffsetDown_Frame4:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame5,object
	.size	 sViolaOAM_MovingOffsetDown_Frame5,8
sViolaOAM_MovingOffsetDown_Frame5:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x820a
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame6,object
	.size	 sViolaOAM_MovingOffsetDown_Frame6,8
sViolaOAM_MovingOffsetDown_Frame6:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x820c
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame7,object
	.size	 sViolaOAM_MovingOffsetDown_Frame7,8
sViolaOAM_MovingOffsetDown_Frame7:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x820e
	.align	1, 0
	.type	 sViolaOAM_MovingOffsetDown_Frame8,object
	.size	 sViolaOAM_MovingOffsetDown_Frame8,8
sViolaOAM_MovingOffsetDown_Frame8:
	.short	0x1
	.short	0x0
	.short	0x41f8
	.short	0x8210
	.align	2, 0
	.type	 sViolaOAM_Moving,object
	.size	 sViolaOAM_Moving,136
sViolaOAM_Moving:
	.word	sViolaOAM_Moving_Frame0
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame1
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame8
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_Moving_Frame1
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sViolaOAM_MovingOffsetUp,object
	.size	 sViolaOAM_MovingOffsetUp,136
sViolaOAM_MovingOffsetUp:
	.word	sViolaOAM_MovingOffsetUp_Frame0
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame1
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame8
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetUp_Frame1
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sViolaOAM_MovingOffsetRight,object
	.size	 sViolaOAM_MovingOffsetRight,136
sViolaOAM_MovingOffsetRight:
	.word	sViolaOAM_MovingOffsetRight_Frame0
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame1
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame8
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetRight_Frame1
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sViolaOAM_MovingOffsetDown,object
	.size	 sViolaOAM_MovingOffsetDown,136
sViolaOAM_MovingOffsetDown:
	.word	sViolaOAM_MovingOffsetDown_Frame0
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame1
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame8
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame7
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame6
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame5
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame4
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame3
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame2
	.byte	0xa
	.space	3
	.word	sViolaOAM_MovingOffsetDown_Frame1
	.byte	0xa
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
