@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sWaverOAM_Frame0,object
	.size	 sWaverOAM_Frame0,14
sWaverOAM_Frame0:
	.short	0x2
	.short	0x40f5
	.short	0x81ec
	.short	0x8200
	.short	0x4005
	.short	0x41ec
	.short	0x8216
	.align	1, 0
	.type	 sWaverOAM_Frame1,object
	.size	 sWaverOAM_Frame1,8
sWaverOAM_Frame1:
	.short	0x1
	.short	0x40f8
	.short	0x81f4
	.short	0x8204
	.align	1, 0
	.type	 sWaverOAM_Frame2,object
	.size	 sWaverOAM_Frame2,8
sWaverOAM_Frame2:
	.short	0x1
	.short	0x40f8
	.short	0x81ec
	.short	0x8207
	.align	1, 0
	.type	 sWaverOAM_Frame3,object
	.size	 sWaverOAM_Frame3,8
sWaverOAM_Frame3:
	.short	0x1
	.short	0x40f8
	.short	0x81f4
	.short	0x820b
	.align	1, 0
	.type	 sWaverOAM_Frame4,object
	.size	 sWaverOAM_Frame4,14
sWaverOAM_Frame4:
	.short	0x2
	.short	0x40f5
	.short	0x81ec
	.short	0x820e
	.short	0x4005
	.short	0x41ec
	.short	0x8236
	.align	1, 0
	.type	 sWaverOAM_Frame5,object
	.size	 sWaverOAM_Frame5,14
sWaverOAM_Frame5:
	.short	0x2
	.short	0x40f4
	.short	0x81ec
	.short	0x8212
	.short	0x4004
	.short	0x41ec
	.short	0x821a
	.align	2, 0
	.type	 sWaverOAM,object
	.size	 sWaverOAM,56
sWaverOAM:
	.word	sWaverOAM_Frame0
	.byte	0x6
	.space	3
	.word	sWaverOAM_Frame1
	.byte	0x6
	.space	3
	.word	sWaverOAM_Frame2
	.byte	0x6
	.space	3
	.word	sWaverOAM_Frame3
	.byte	0x6
	.space	3
	.word	sWaverOAM_Frame4
	.byte	0x6
	.space	3
	.word	sWaverOAM_Frame5
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
