@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sZebOAM_Idle_Frame0,object
	.size	 sZebOAM_Idle_Frame0,14
sZebOAM_Idle_Frame0:
	.short	0x2
	.short	0xf9
	.short	0x41f4
	.short	0x820a
	.short	0xf8
	.short	0x41fa
	.short	0x8200
	.align	1, 0
	.type	 sZebOAM_Idle_Frame1,object
	.size	 sZebOAM_Idle_Frame1,14
sZebOAM_Idle_Frame1:
	.short	0x2
	.short	0xf9
	.short	0x41f5
	.short	0x820a
	.short	0xf8
	.short	0x41fa
	.short	0x8204
	.align	1, 0
	.type	 sZebOAM_Idle_Frame2,object
	.size	 sZebOAM_Idle_Frame2,14
sZebOAM_Idle_Frame2:
	.short	0x2
	.short	0xf8
	.short	0x41f5
	.short	0x820a
	.short	0xf7
	.short	0x41fa
	.short	0x8208
	.align	2, 0
	.type	 sZebOAM_Idle,object
	.size	 sZebOAM_Idle,40
sZebOAM_Idle:
	.word	sZebOAM_Idle_Frame0
	.byte	0x4
	.space	3
	.word	sZebOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	sZebOAM_Idle_Frame2
	.byte	0x4
	.space	3
	.word	sZebOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZebOAM_Moving,object
	.size	 sZebOAM_Moving,40
sZebOAM_Moving:
	.word	sZebOAM_Idle_Frame0
	.byte	0x3
	.space	3
	.word	sZebOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	sZebOAM_Idle_Frame2
	.byte	0x2
	.space	3
	.word	sZebOAM_Idle_Frame1
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
