@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sZebboOAM_Idle_Frame0,object
	.size	 sZebboOAM_Idle_Frame0,8
sZebboOAM_Idle_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8200
	.align	1, 0
	.type	 sZebboOAM_Idle_Frame1,object
	.size	 sZebboOAM_Idle_Frame1,8
sZebboOAM_Idle_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8202
	.align	1, 0
	.type	 sZebboOAM_Idle_Frame2,object
	.size	 sZebboOAM_Idle_Frame2,8
sZebboOAM_Idle_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8204
	.align	1, 0
	.type	 sZebboOAM_Moving_Frame0,object
	.size	 sZebboOAM_Moving_Frame0,8
sZebboOAM_Moving_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8206
	.align	1, 0
	.type	 sZebboOAM_Moving_Frame1,object
	.size	 sZebboOAM_Moving_Frame1,8
sZebboOAM_Moving_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8208
	.align	1, 0
	.type	 sZebboOAM_Moving_Frame2,object
	.size	 sZebboOAM_Moving_Frame2,8
sZebboOAM_Moving_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x820a
	.align	2, 0
	.type	 sZebboOAM_Idle,object
	.size	 sZebboOAM_Idle,40
sZebboOAM_Idle:
	.word	sZebboOAM_Idle_Frame0
	.byte	0x3
	.space	3
	.word	sZebboOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	sZebboOAM_Idle_Frame2
	.byte	0x3
	.space	3
	.word	sZebboOAM_Idle_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZebboOAM_Moving,object
	.size	 sZebboOAM_Moving,40
sZebboOAM_Moving:
	.word	sZebboOAM_Moving_Frame0
	.byte	0x2
	.space	3
	.word	sZebboOAM_Moving_Frame1
	.byte	0x1
	.space	3
	.word	sZebboOAM_Moving_Frame2
	.byte	0x2
	.space	3
	.word	sZebboOAM_Moving_Frame1
	.byte	0x1
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
