@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Moving_Frame0,object
	.size	 sRinkaMotherBrainOAM_Moving_Frame0,14
sRinkaMotherBrainOAM_Moving_Frame0:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9200
	.short	0x80f8
	.short	0x1000
	.short	0x9200
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Moving_Frame1,object
	.size	 sRinkaMotherBrainOAM_Moving_Frame1,14
sRinkaMotherBrainOAM_Moving_Frame1:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9201
	.short	0x80f8
	.short	0x1000
	.short	0x9201
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Moving_Frame2,object
	.size	 sRinkaMotherBrainOAM_Moving_Frame2,14
sRinkaMotherBrainOAM_Moving_Frame2:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9202
	.short	0x80f8
	.short	0x1000
	.short	0x9202
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Spawning_Frame0,object
	.size	 sRinkaMotherBrainOAM_Spawning_Frame0,14
sRinkaMotherBrainOAM_Spawning_Frame0:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9203
	.short	0x80f8
	.short	0x1000
	.short	0x9203
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Spawning_Frame1,object
	.size	 sRinkaMotherBrainOAM_Spawning_Frame1,14
sRinkaMotherBrainOAM_Spawning_Frame1:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9204
	.short	0x80f8
	.short	0x1000
	.short	0x9204
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Spawning_Frame2,object
	.size	 sRinkaMotherBrainOAM_Spawning_Frame2,14
sRinkaMotherBrainOAM_Spawning_Frame2:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9205
	.short	0x80f8
	.short	0x1000
	.short	0x9205
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Spawning_Frame3,object
	.size	 sRinkaMotherBrainOAM_Spawning_Frame3,14
sRinkaMotherBrainOAM_Spawning_Frame3:
	.short	0x2
	.short	0x80f8
	.short	0x1f8
	.short	0x9206
	.short	0x80f8
	.short	0x1000
	.short	0x9206
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Spawning_Frame4,object
	.size	 sRinkaMotherBrainOAM_Spawning_Frame4,38
sRinkaMotherBrainOAM_Spawning_Frame4:
	.short	0x6
	.short	0x80f8
	.short	0x1f8
	.short	0x9240
	.short	0x80f8
	.short	0x1000
	.short	0x9240
	.short	0xf0
	.short	0x1fc
	.short	0x9241
	.short	0x8
	.short	0x21fc
	.short	0x9241
	.short	0xfc
	.short	0x1f0
	.short	0x9261
	.short	0xfc
	.short	0x3008
	.short	0x9261
	.align	1, 0
	.type	 sRinkaMotherBrainOAM_Spawning_Frame5,object
	.size	 sRinkaMotherBrainOAM_Spawning_Frame5,38
sRinkaMotherBrainOAM_Spawning_Frame5:
	.short	0x6
	.short	0x80f8
	.short	0x1f8
	.short	0x9242
	.short	0x80f8
	.short	0x1000
	.short	0x9242
	.short	0xf0
	.short	0x1fc
	.short	0x9243
	.short	0x8
	.short	0x21fc
	.short	0x9243
	.short	0xfc
	.short	0x1f0
	.short	0x9263
	.short	0xfc
	.short	0x1008
	.short	0x9263
	.align	2, 0
	.type	 sRinkaMotherBrainOAM_Spawning,object
	.size	 sRinkaMotherBrainOAM_Spawning,128
sRinkaMotherBrainOAM_Spawning:
	.word	sRinkaMotherBrainOAM_Spawning_Frame0
	.byte	0x4
	.space	3
	.word	sRinkaMotherBrainOAM_Spawning_Frame1
	.byte	0x4
	.space	3
	.word	sRinkaMotherBrainOAM_Spawning_Frame2
	.byte	0x4
	.space	3
	.word	sRinkaMotherBrainOAM_Spawning_Frame3
	.byte	0x4
	.space	3
	.word	sRinkaMotherBrainOAM_Spawning_Frame4
	.byte	0x4
	.space	3
	.word	sRinkaMotherBrainOAM_Spawning_Frame5
	.byte	0x4
	.space	3
	.word	sRinkaMotherBrainOAM_Spawning_Frame3
	.byte	0x8
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame0
	.byte	0x6
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame1
	.byte	0x6
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame2
	.byte	0x6
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame1
	.byte	0x8
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame0
	.byte	0x7
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame1
	.byte	0x7
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame2
	.byte	0x7
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame1
	.byte	0x7
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sRinkaMotherBrainOAM_Moving,object
	.size	 sRinkaMotherBrainOAM_Moving,40
sRinkaMotherBrainOAM_Moving:
	.word	sRinkaMotherBrainOAM_Moving_Frame0
	.byte	0xc
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame1
	.byte	0xc
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame2
	.byte	0xc
	.space	3
	.word	sRinkaMotherBrainOAM_Moving_Frame1
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
