@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ConductorDeactivated_Frame0,object
	.size	 sZiplineGeneratorPartOAM_ConductorDeactivated_Frame0,62
sZiplineGeneratorPartOAM_ConductorDeactivated_Frame0:
	.short	0xa
	.short	0x80a0
	.short	0x81e8
	.short	0x8200
	.short	0xc0
	.short	0x41e8
	.short	0x8280
	.short	0x80a0
	.short	0x81f8
	.short	0x8202
	.short	0x80c0
	.short	0x81f8
	.short	0x8282
	.short	0x80a0
	.short	0x8008
	.short	0x8204
	.short	0xc0
	.short	0x4008
	.short	0x8284
	.short	0x80e0
	.short	0x81e8
	.short	0x8206
	.short	0xf8
	.short	0x1e0
	.short	0x821f
	.short	0x80e0
	.short	0x8008
	.short	0x8208
	.short	0xf8
	.short	0x18
	.short	0x823f
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ConductorActivating_Frame1,object
	.size	 sZiplineGeneratorPartOAM_ConductorActivating_Frame1,104
sZiplineGeneratorPartOAM_ConductorActivating_Frame1:
	.short	0x11
	.short	0xae
	.short	0x1fc
	.short	0x82ae
	.short	0x80a0
	.short	0x41e9
	.short	0x820e
	.short	0xc0
	.short	0x1e9
	.short	0x828e
	.short	0x80a0
	.short	0x81f8
	.short	0x820f
	.short	0xc0
	.short	0x41f8
	.short	0x828f
	.short	0x80a8
	.short	0xf
	.short	0x82ce
	.short	0x80b8
	.short	0x100f
	.short	0x826e
	.short	0x80a0
	.short	0x81e8
	.short	0x8200
	.short	0xc0
	.short	0x41e8
	.short	0x8280
	.short	0x80a0
	.short	0x81f8
	.short	0x8202
	.short	0x80c0
	.short	0x81f8
	.short	0x8282
	.short	0x80a0
	.short	0x8008
	.short	0x8204
	.short	0xc0
	.short	0x4008
	.short	0x8284
	.short	0x80e0
	.short	0x81e8
	.short	0x8206
	.short	0xf8
	.short	0x1e0
	.short	0x821f
	.short	0x80e0
	.short	0x8008
	.short	0x8208
	.short	0xf8
	.short	0x18
	.short	0x823f
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ConductorActivating_Frame2,object
	.size	 sZiplineGeneratorPartOAM_ConductorActivating_Frame2,104
sZiplineGeneratorPartOAM_ConductorActivating_Frame2:
	.short	0x11
	.short	0xae
	.short	0x1fc
	.short	0x82b1
	.short	0x80a0
	.short	0x41e9
	.short	0x8211
	.short	0xc0
	.short	0x1e9
	.short	0x8291
	.short	0x80a0
	.short	0x81f8
	.short	0x8212
	.short	0xc0
	.short	0x41f8
	.short	0x8292
	.short	0x80a8
	.short	0xf
	.short	0x82d1
	.short	0x80b8
	.short	0x100f
	.short	0x8271
	.short	0x80a0
	.short	0x81e8
	.short	0x8200
	.short	0xc0
	.short	0x41e8
	.short	0x8280
	.short	0x80a0
	.short	0x81f8
	.short	0x8202
	.short	0x80c0
	.short	0x81f8
	.short	0x8282
	.short	0x80a0
	.short	0x8008
	.short	0x8204
	.short	0xc0
	.short	0x4008
	.short	0x8284
	.short	0x80e0
	.short	0x81e8
	.short	0x8206
	.short	0xf8
	.short	0x1e0
	.short	0x821f
	.short	0x80e0
	.short	0x8008
	.short	0x8208
	.short	0xf8
	.short	0x18
	.short	0x823f
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ConductorActivating_Frame3,object
	.size	 sZiplineGeneratorPartOAM_ConductorActivating_Frame3,104
sZiplineGeneratorPartOAM_ConductorActivating_Frame3:
	.short	0x11
	.short	0xae
	.short	0x1fc
	.short	0x82b4
	.short	0x80a0
	.short	0x41e9
	.short	0x8214
	.short	0xc0
	.short	0x1e9
	.short	0x8294
	.short	0x80a0
	.short	0x81f8
	.short	0x8215
	.short	0xc0
	.short	0x41f8
	.short	0x8295
	.short	0x80a8
	.short	0xf
	.short	0x82d4
	.short	0x80b8
	.short	0x100f
	.short	0x8274
	.short	0x80a0
	.short	0x81e8
	.short	0x8200
	.short	0xc0
	.short	0x41e8
	.short	0x8280
	.short	0x80a0
	.short	0x81f8
	.short	0x8202
	.short	0x80c0
	.short	0x81f8
	.short	0x8282
	.short	0x80a0
	.short	0x8008
	.short	0x8204
	.short	0xc0
	.short	0x4008
	.short	0x8284
	.short	0x80e0
	.short	0x81e8
	.short	0x8206
	.short	0xf8
	.short	0x1e0
	.short	0x821f
	.short	0x80e0
	.short	0x8008
	.short	0x8208
	.short	0xf8
	.short	0x18
	.short	0x823f
	.align	1, 0
	.type	 sZiplineGeneratorOAM_Deactivated_Frame0,object
	.size	 sZiplineGeneratorOAM_Deactivated_Frame0,38
sZiplineGeneratorOAM_Deactivated_Frame0:
	.short	0x6
	.short	0xd0
	.short	0x41e8
	.short	0x82c0
	.short	0xd0
	.short	0x4008
	.short	0x82c4
	.short	0x80e0
	.short	0x81f8
	.short	0x820a
	.short	0x40d8
	.short	0x1f8
	.short	0x820c
	.short	0xe0
	.short	0x1f0
	.short	0x822c
	.short	0xe0
	.short	0x8
	.short	0x822d
	.align	1, 0
	.type	 sZiplineGeneratorOAM_Activating_Frame1,object
	.size	 sZiplineGeneratorOAM_Activating_Frame1,62
sZiplineGeneratorOAM_Activating_Frame1:
	.short	0xa
	.short	0xd0
	.short	0x41e8
	.short	0x8286
	.short	0xd0
	.short	0x4008
	.short	0x82cf
	.short	0xe2
	.short	0x41f8
	.short	0x82c6
	.short	0x40f2
	.short	0x1f8
	.short	0x82c8
	.short	0xd0
	.short	0x41e8
	.short	0x82c0
	.short	0xd0
	.short	0x4008
	.short	0x82c4
	.short	0x80e0
	.short	0x81f8
	.short	0x820a
	.short	0x40d8
	.short	0x1f8
	.short	0x820c
	.short	0xe0
	.short	0x1f0
	.short	0x822c
	.short	0xe0
	.short	0x8
	.short	0x822d
	.align	1, 0
	.type	 sZiplineGeneratorOAM_Activating_Frame2,object
	.size	 sZiplineGeneratorOAM_Activating_Frame2,62
sZiplineGeneratorOAM_Activating_Frame2:
	.short	0xa
	.short	0xd0
	.short	0x41e8
	.short	0x8288
	.short	0xd0
	.short	0x4008
	.short	0x82d2
	.short	0xe2
	.short	0x41f8
	.short	0x82ca
	.short	0x40f2
	.short	0x1f8
	.short	0x82cc
	.short	0xd0
	.short	0x41e8
	.short	0x82c0
	.short	0xd0
	.short	0x4008
	.short	0x82c4
	.short	0x80e0
	.short	0x81f8
	.short	0x820a
	.short	0x40d8
	.short	0x1f8
	.short	0x820c
	.short	0xe0
	.short	0x1f0
	.short	0x822c
	.short	0xe0
	.short	0x8
	.short	0x822d
	.align	1, 0
	.type	 sZiplineGeneratorOAM_Activating_Frame3,object
	.size	 sZiplineGeneratorOAM_Activating_Frame3,62
sZiplineGeneratorOAM_Activating_Frame3:
	.short	0xa
	.short	0xd0
	.short	0x41e8
	.short	0x828a
	.short	0xd0
	.short	0x4008
	.short	0x82d5
	.short	0xe2
	.short	0x41f8
	.short	0x827c
	.short	0x40f2
	.short	0x1f8
	.short	0x82bc
	.short	0xd0
	.short	0x41e8
	.short	0x82c0
	.short	0xd0
	.short	0x4008
	.short	0x82c4
	.short	0x80e0
	.short	0x81f8
	.short	0x820a
	.short	0x40d8
	.short	0x1f8
	.short	0x820c
	.short	0xe0
	.short	0x1f0
	.short	0x822c
	.short	0xe0
	.short	0x8
	.short	0x822d
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame0,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame0,8
sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame0:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8217
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame1,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame1,8
sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame1:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x8219
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame2,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame2,8
sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame2:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x821b
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame3,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame3,8
sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame3:
	.short	0x1
	.short	0xf8
	.short	0x41f8
	.short	0x821d
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame4,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame4,32
sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame4:
	.short	0x5
	.short	0xf0
	.short	0x41f0
	.short	0x824c
	.short	0xf0
	.short	0x5000
	.short	0x824c
	.short	0x0
	.short	0x61f0
	.short	0x824c
	.short	0x0
	.short	0x7000
	.short	0x824c
	.short	0xf8
	.short	0x41f8
	.short	0x821b
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame5,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame5,32
sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame5:
	.short	0x5
	.short	0xf0
	.short	0x41f0
	.short	0x828c
	.short	0xf0
	.short	0x5000
	.short	0x828c
	.short	0x0
	.short	0x61f0
	.short	0x828c
	.short	0x0
	.short	0x7000
	.short	0x828c
	.short	0xf8
	.short	0x41f8
	.short	0x8219
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame3,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame3,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame3:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x824c
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame0,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame0,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame0:
	.short	0x1
	.short	0x80f0
	.short	0x41f8
	.short	0x925f
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame1,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame1,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame1:
	.short	0x1
	.short	0xfb
	.short	0x41f8
	.short	0x92de
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame2,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame2,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame2:
	.short	0x1
	.short	0x4001
	.short	0x41f0
	.short	0x925b
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame4,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame4,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame4:
	.short	0x1
	.short	0x80f0
	.short	0x7000
	.short	0x925f
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame5,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame5,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame5:
	.short	0x1
	.short	0xf5
	.short	0x71f8
	.short	0x92de
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame7,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating_Frame7,8
sZiplineGeneratorPartOAM_ElectricityActivating_Frame7:
	.short	0x1
	.short	0x40f7
	.short	0x71f0
	.short	0x925b
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame0,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame0,8
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame0:
	.short	0x1
	.short	0x80f0
	.short	0x41fc
	.short	0x9277
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame1,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame1,8
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame1:
	.short	0x1
	.short	0xf0
	.short	0x81f0
	.short	0x9278
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame2,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame2,8
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame2:
	.short	0x1
	.short	0x40fc
	.short	0x41f0
	.short	0x9257
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame3,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame3,8
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame3:
	.short	0x1
	.short	0xf0
	.short	0x91f0
	.short	0x9278
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame4,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame4,8
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame4:
	.short	0x1
	.short	0x80f8
	.short	0x1fc
	.short	0x92dc
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame5,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame5,32
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame5:
	.short	0x5
	.short	0xfc
	.short	0x1fc
	.short	0x92fa
	.short	0xf0
	.short	0x41f0
	.short	0x824c
	.short	0xf0
	.short	0x5000
	.short	0x824c
	.short	0x0
	.short	0x61f0
	.short	0x824c
	.short	0x0
	.short	0x7000
	.short	0x824c
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame6,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame6,32
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame6:
	.short	0x5
	.short	0xfc
	.short	0x1fc
	.short	0x92f9
	.short	0xf0
	.short	0x41f0
	.short	0x828c
	.short	0xf0
	.short	0x5000
	.short	0x828c
	.short	0x0
	.short	0x61f0
	.short	0x828c
	.short	0x0
	.short	0x7000
	.short	0x828c
	.align	1, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame7,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame7,8
sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame7:
	.short	0x1
	.short	0xfc
	.short	0x1fc
	.short	0x92f8
	.align	2, 0
	.type	 sZiplineGeneratorPartOAM_ConductorDeactivated,object
	.size	 sZiplineGeneratorPartOAM_ConductorDeactivated,16
sZiplineGeneratorPartOAM_ConductorDeactivated:
	.word	sZiplineGeneratorPartOAM_ConductorDeactivated_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorOAM_Deactivated,object
	.size	 sZiplineGeneratorOAM_Deactivated,16
sZiplineGeneratorOAM_Deactivated:
	.word	sZiplineGeneratorOAM_Deactivated_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorPartOAM_ConductorActivating,object
	.size	 sZiplineGeneratorPartOAM_ConductorActivating,56
sZiplineGeneratorPartOAM_ConductorActivating:
	.word	sZiplineGeneratorPartOAM_ConductorDeactivated_Frame0
	.byte	0xc
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame1
	.byte	0x6
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame2
	.byte	0x5
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame3
	.byte	0x5
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame2
	.byte	0x5
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame1
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorOAM_Activating,object
	.size	 sZiplineGeneratorOAM_Activating,56
sZiplineGeneratorOAM_Activating:
	.word	sZiplineGeneratorOAM_Deactivated_Frame0
	.byte	0xc
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame1
	.byte	0x6
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame2
	.byte	0x5
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame3
	.byte	0x5
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame2
	.byte	0x5
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame1
	.byte	0x6
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorPartOAM_ConductorActivated,object
	.size	 sZiplineGeneratorPartOAM_ConductorActivated,56
sZiplineGeneratorPartOAM_ConductorActivated:
	.word	sZiplineGeneratorPartOAM_ConductorDeactivated_Frame0
	.byte	0x10
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame1
	.byte	0x10
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame2
	.byte	0xc
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame3
	.byte	0xa
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame2
	.byte	0xc
	.space	3
	.word	sZiplineGeneratorPartOAM_ConductorActivating_Frame1
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorOAM_Activated,object
	.size	 sZiplineGeneratorOAM_Activated,56
sZiplineGeneratorOAM_Activated:
	.word	sZiplineGeneratorOAM_Deactivated_Frame0
	.byte	0x10
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame1
	.byte	0x10
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame2
	.byte	0xc
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame3
	.byte	0xa
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame2
	.byte	0xc
	.space	3
	.word	sZiplineGeneratorOAM_Activating_Frame1
	.byte	0x10
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivating,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivating,56
sZiplineGeneratorPartOAM_MorphSymbolActivating:
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame0
	.byte	0x4
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame1
	.byte	0x4
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame2
	.byte	0x4
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame3
	.byte	0x4
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame4
	.byte	0x4
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivating_Frame5
	.byte	0x4
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorPartOAM_MorphSymbolActivated,object
	.size	 sZiplineGeneratorPartOAM_MorphSymbolActivated,72
sZiplineGeneratorPartOAM_MorphSymbolActivated:
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame0
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame1
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame2
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame3
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame4
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame5
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame6
	.byte	0x2
	.space	3
	.word	sZiplineGeneratorPartOAM_MorphSymbolActivated_Frame7
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineGeneratorPartOAM_ElectricityActivating,object
	.size	 sZiplineGeneratorPartOAM_ElectricityActivating,96
sZiplineGeneratorPartOAM_ElectricityActivating:
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame0
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame1
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame2
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame3
	.byte	0xa
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame4
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame5
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame3
	.byte	0xa
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame7
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame3
	.byte	0xa
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame0
	.byte	0x3
	.space	3
	.word	sZiplineGeneratorPartOAM_ElectricityActivating_Frame4
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
