@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sZiplineOAM_OffIdle_Frame0,object
	.size	 sZiplineOAM_OffIdle_Frame0,14
sZiplineOAM_OffIdle_Frame0:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.short	0x4000
	.short	0x1f8
	.short	0x8208
	.align	1, 0
	.type	 sZiplineOAM_OffGrabbingSamus_Frame1,object
	.size	 sZiplineOAM_OffGrabbingSamus_Frame1,14
sZiplineOAM_OffGrabbingSamus_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.short	0x4000
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sZiplineOAM_OffGrabbingSamus_Frame2,object
	.size	 sZiplineOAM_OffGrabbingSamus_Frame2,14
sZiplineOAM_OffGrabbingSamus_Frame2:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.short	0x4000
	.short	0x1f8
	.short	0x820a
	.align	1, 0
	.type	 sZiplineOAM_OnGrabbingSamus_Frame1,object
	.size	 sZiplineOAM_OnGrabbingSamus_Frame1,14
sZiplineOAM_OnGrabbingSamus_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8206
	.short	0x4000
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sZiplineOAM_OnSamusGrabbed_Frame2,object
	.size	 sZiplineOAM_OnSamusGrabbed_Frame2,14
sZiplineOAM_OnSamusGrabbed_Frame2:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8204
	.short	0x4000
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sZiplineOAM_OnSamusGrabbed_Frame1,object
	.size	 sZiplineOAM_OnSamusGrabbed_Frame1,14
sZiplineOAM_OnSamusGrabbed_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8202
	.short	0x4000
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sZiplineOAM_OnSamusGrabbed_Frame0,object
	.size	 sZiplineOAM_OnSamusGrabbed_Frame0,14
sZiplineOAM_OnSamusGrabbed_Frame0:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8200
	.short	0x4000
	.short	0x1f8
	.short	0x8228
	.align	1, 0
	.type	 sZiplineOAM_OnIdle_Frame3,object
	.size	 sZiplineOAM_OnIdle_Frame3,14
sZiplineOAM_OnIdle_Frame3:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8206
	.short	0x4000
	.short	0x1f8
	.short	0x8208
	.align	1, 0
	.type	 sZiplineOAM_OnGrabbingSamus_Frame2,object
	.size	 sZiplineOAM_OnGrabbingSamus_Frame2,14
sZiplineOAM_OnGrabbingSamus_Frame2:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8206
	.short	0x4000
	.short	0x1f8
	.short	0x820a
	.align	1, 0
	.type	 sZiplineOAM_OnIdle_Frame1,object
	.size	 sZiplineOAM_OnIdle_Frame1,14
sZiplineOAM_OnIdle_Frame1:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8202
	.short	0x4000
	.short	0x1f8
	.short	0x8208
	.align	1, 0
	.type	 sZiplineOAM_OnIdle_Frame2,object
	.size	 sZiplineOAM_OnIdle_Frame2,14
sZiplineOAM_OnIdle_Frame2:
	.short	0x2
	.short	0xf0
	.short	0x41f8
	.short	0x8204
	.short	0x4000
	.short	0x1f8
	.short	0x8208
	.align	1, 0
	.type	 sZiplineButtonOAM_OffIdle_Frame0,object
	.size	 sZiplineButtonOAM_OffIdle_Frame0,14
sZiplineButtonOAM_OffIdle_Frame0:
	.short	0x2
	.short	0x0
	.short	0x41f8
	.short	0x820c
	.short	0x4010
	.short	0x1f8
	.short	0x8214
	.align	1, 0
	.type	 sZiplineButtonOAM_OnIdle_Frame1,object
	.size	 sZiplineButtonOAM_OnIdle_Frame1,14
sZiplineButtonOAM_OnIdle_Frame1:
	.short	0x2
	.short	0x0
	.short	0x41f8
	.short	0x820e
	.short	0x4010
	.short	0x1f8
	.short	0x8234
	.align	1, 0
	.type	 sZiplineButtonOAM_OnIdle_Frame2,object
	.size	 sZiplineButtonOAM_OnIdle_Frame2,14
sZiplineButtonOAM_OnIdle_Frame2:
	.short	0x2
	.short	0x0
	.short	0x41f8
	.short	0x8210
	.short	0x4010
	.short	0x1f8
	.short	0x8216
	.align	1, 0
	.type	 sZiplineButtonOAM_OnIdle_Frame3,object
	.size	 sZiplineButtonOAM_OnIdle_Frame3,14
sZiplineButtonOAM_OnIdle_Frame3:
	.short	0x2
	.short	0x0
	.short	0x41f8
	.short	0x8212
	.short	0x4010
	.short	0x1f8
	.short	0x8236
	.align	2, 0
	.type	 sZiplineOAM_OffIdle,object
	.size	 sZiplineOAM_OffIdle,16
sZiplineOAM_OffIdle:
	.word	sZiplineOAM_OffIdle_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OffGrabbingSamus,object
	.size	 sZiplineOAM_OffGrabbingSamus,32
sZiplineOAM_OffGrabbingSamus:
	.word	sZiplineOAM_OffIdle_Frame0
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OffGrabbingSamus_Frame1
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OffGrabbingSamus_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OffSamusGrabbed,object
	.size	 sZiplineOAM_OffSamusGrabbed,16
sZiplineOAM_OffSamusGrabbed:
	.word	sZiplineOAM_OffGrabbingSamus_Frame1
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OffReleasingSamus,object
	.size	 sZiplineOAM_OffReleasingSamus,32
sZiplineOAM_OffReleasingSamus:
	.word	sZiplineOAM_OffGrabbingSamus_Frame2
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OffGrabbingSamus_Frame1
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OffIdle_Frame0
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OnIdle,object
	.size	 sZiplineOAM_OnIdle,56
sZiplineOAM_OnIdle:
	.word	sZiplineOAM_OffIdle_Frame0
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnIdle_Frame1
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnIdle_Frame2
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnIdle_Frame3
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnIdle_Frame2
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnIdle_Frame1
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OnGrabbingSamus,object
	.size	 sZiplineOAM_OnGrabbingSamus,32
sZiplineOAM_OnGrabbingSamus:
	.word	sZiplineOAM_OnIdle_Frame3
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OnGrabbingSamus_Frame1
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OnGrabbingSamus_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OnSamusGrabbed,object
	.size	 sZiplineOAM_OnSamusGrabbed,56
sZiplineOAM_OnSamusGrabbed:
	.word	sZiplineOAM_OnSamusGrabbed_Frame0
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnSamusGrabbed_Frame1
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnSamusGrabbed_Frame2
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnSamusGrabbed_Frame1
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnSamusGrabbed_Frame2
	.byte	0x8
	.space	3
	.word	sZiplineOAM_OnSamusGrabbed_Frame1
	.byte	0x8
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineOAM_OnReleasingSamus,object
	.size	 sZiplineOAM_OnReleasingSamus,32
sZiplineOAM_OnReleasingSamus:
	.word	sZiplineOAM_OnGrabbingSamus_Frame2
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OnGrabbingSamus_Frame1
	.byte	0x2
	.space	3
	.word	sZiplineOAM_OnIdle_Frame3
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineButtonOAM_OffIdle,object
	.size	 sZiplineButtonOAM_OffIdle,16
sZiplineButtonOAM_OffIdle:
	.word	sZiplineButtonOAM_OffIdle_Frame0
	.byte	0xff
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineButtonOAM_OnIdle,object
	.size	 sZiplineButtonOAM_OnIdle,56
sZiplineButtonOAM_OnIdle:
	.word	sZiplineButtonOAM_OffIdle_Frame0
	.byte	0xc
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame1
	.byte	0xc
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame2
	.byte	0xc
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame3
	.byte	0xc
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame2
	.byte	0xc
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame1
	.byte	0xc
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZiplineButtonOAM_Active,object
	.size	 sZiplineButtonOAM_Active,56
sZiplineButtonOAM_Active:
	.word	sZiplineButtonOAM_OffIdle_Frame0
	.byte	0x2
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame1
	.byte	0x2
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame2
	.byte	0x2
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame3
	.byte	0x4
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame2
	.byte	0x2
	.space	3
	.word	sZiplineButtonOAM_OnIdle_Frame1
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
