@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 sZoomerOAM_Falling_Frame0,object
	.size	 sZoomerOAM_Falling_Frame0,26
sZoomerOAM_Falling_Frame0:
	.short	0x4
	.short	0xee
	.short	0x41f4
	.short	0x8200
	.short	0x80ee
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f6
	.short	0x820f
	.short	0xf8
	.short	0x1001
	.short	0x820f
	.align	1, 0
	.type	 sZoomerOAM_Falling_Frame1,object
	.size	 sZoomerOAM_Falling_Frame1,26
sZoomerOAM_Falling_Frame1:
	.short	0x4
	.short	0xef
	.short	0x41f4
	.short	0x8203
	.short	0x80ef
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f6
	.short	0x8210
	.short	0xf8
	.short	0x1001
	.short	0x8210
	.align	1, 0
	.type	 sZoomerOAM_Falling_Frame2,object
	.size	 sZoomerOAM_Falling_Frame2,26
sZoomerOAM_Falling_Frame2:
	.short	0x4
	.short	0xf0
	.short	0x41f4
	.short	0x8205
	.short	0x80f0
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f6
	.short	0x822f
	.short	0xf8
	.short	0x1001
	.short	0x822f
	.align	1, 0
	.type	 sZoomerOAM_OnGround_Frame0,object
	.size	 sZoomerOAM_OnGround_Frame0,26
sZoomerOAM_OnGround_Frame0:
	.short	0x4
	.short	0xef
	.short	0x41f4
	.short	0x8200
	.short	0x80ef
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f4
	.short	0x8207
	.short	0xf8
	.short	0x1001
	.short	0x8227
	.align	1, 0
	.type	 sZoomerOAM_OnGround_Frame1,object
	.size	 sZoomerOAM_OnGround_Frame1,26
sZoomerOAM_OnGround_Frame1:
	.short	0x4
	.short	0xee
	.short	0x41f4
	.short	0x8203
	.short	0x80ee
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f6
	.short	0x8208
	.short	0xf8
	.short	0x1001
	.short	0x8228
	.align	1, 0
	.type	 sZoomerOAM_OnGround_Frame2,object
	.size	 sZoomerOAM_OnGround_Frame2,26
sZoomerOAM_OnGround_Frame2:
	.short	0x4
	.short	0xef
	.short	0x41f4
	.short	0x8205
	.short	0x80ef
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f6
	.short	0x8227
	.short	0xf8
	.short	0x1003
	.short	0x8207
	.align	1, 0
	.type	 sZoomerOAM_OnGround_Frame3,object
	.size	 sZoomerOAM_OnGround_Frame3,26
sZoomerOAM_OnGround_Frame3:
	.short	0x4
	.short	0xf0
	.short	0x41f4
	.short	0x8203
	.short	0x80f0
	.short	0x4
	.short	0x8202
	.short	0xf8
	.short	0x1f6
	.short	0x8228
	.short	0xf8
	.short	0x1001
	.short	0x8208
	.align	1, 0
	.type	 sZoomerOAM_TurningEdgeLeft_Frame0,object
	.size	 sZoomerOAM_TurningEdgeLeft_Frame0,20
sZoomerOAM_TurningEdgeLeft_Frame0:
	.short	0x3
	.short	0xf5
	.short	0x41f7
	.short	0x8211
	.short	0x40ed
	.short	0x1f7
	.short	0x8217
	.short	0x80f5
	.short	0x7
	.short	0x821b
	.align	1, 0
	.type	 sZoomerOAM_TurningEdgeLeft_Frame1,object
	.size	 sZoomerOAM_TurningEdgeLeft_Frame1,20
sZoomerOAM_TurningEdgeLeft_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x41fb
	.short	0x8213
	.short	0x40f0
	.short	0x1fb
	.short	0x8237
	.short	0x80f8
	.short	0xb
	.short	0x821c
	.align	1, 0
	.type	 sZoomerOAM_TurningEdgeLeft_Frame2,object
	.size	 sZoomerOAM_TurningEdgeLeft_Frame2,20
sZoomerOAM_TurningEdgeLeft_Frame2:
	.short	0x3
	.short	0xf9
	.short	0x41fa
	.short	0x8215
	.short	0x40f1
	.short	0x1fa
	.short	0x8219
	.short	0x80f9
	.short	0xa
	.short	0x821d
	.align	1, 0
	.type	 sZoomerOAM_OnWall_Frame0,object
	.size	 sZoomerOAM_OnWall_Frame0,26
sZoomerOAM_OnWall_Frame0:
	.short	0x4
	.short	0xf4
	.short	0x4001
	.short	0x8209
	.short	0x4004
	.short	0x1
	.short	0x8239
	.short	0xf4
	.short	0x0
	.short	0x821e
	.short	0x1
	.short	0x2000
	.short	0x823e
	.align	1, 0
	.type	 sZoomerOAM_OnWall_Frame1,object
	.size	 sZoomerOAM_OnWall_Frame1,26
sZoomerOAM_OnWall_Frame1:
	.short	0x4
	.short	0xf4
	.short	0x4002
	.short	0x820b
	.short	0x4004
	.short	0x2
	.short	0x8239
	.short	0xf6
	.short	0x0
	.short	0x821f
	.short	0x1
	.short	0x2000
	.short	0x823f
	.align	1, 0
	.type	 sZoomerOAM_OnWall_Frame2,object
	.size	 sZoomerOAM_OnWall_Frame2,26
sZoomerOAM_OnWall_Frame2:
	.short	0x4
	.short	0xf4
	.short	0x4001
	.short	0x820d
	.short	0x4004
	.short	0x1
	.short	0x8239
	.short	0xf6
	.short	0x0
	.short	0x823e
	.short	0x3
	.short	0x2000
	.short	0x821e
	.align	1, 0
	.type	 sZoomerOAM_OnWall_Frame3,object
	.size	 sZoomerOAM_OnWall_Frame3,26
sZoomerOAM_OnWall_Frame3:
	.short	0x4
	.short	0xf4
	.short	0x4000
	.short	0x820b
	.short	0x4004
	.short	0x0
	.short	0x8239
	.short	0xf6
	.short	0x0
	.short	0x823f
	.short	0x1
	.short	0x2000
	.short	0x821f
	.align	1, 0
	.type	 sZoomerOAM_TurningCornerRight_Frame0,object
	.size	 sZoomerOAM_TurningCornerRight_Frame0,20
sZoomerOAM_TurningCornerRight_Frame0:
	.short	0x3
	.short	0xf5
	.short	0x41f7
	.short	0x8211
	.short	0x40ed
	.short	0x1f7
	.short	0x8217
	.short	0x80f5
	.short	0x7
	.short	0x821b
	.align	1, 0
	.type	 sZoomerOAM_TurningCornerRight_Frame1,object
	.size	 sZoomerOAM_TurningCornerRight_Frame1,20
sZoomerOAM_TurningCornerRight_Frame1:
	.short	0x3
	.short	0xf3
	.short	0x41f6
	.short	0x8213
	.short	0x40eb
	.short	0x1f6
	.short	0x8237
	.short	0x80f3
	.short	0x6
	.short	0x821c
	.align	1, 0
	.type	 sZoomerOAM_TurningCornerRight_Frame2,object
	.size	 sZoomerOAM_TurningCornerRight_Frame2,20
sZoomerOAM_TurningCornerRight_Frame2:
	.short	0x3
	.short	0xf1
	.short	0x41f5
	.short	0x8215
	.short	0x40e9
	.short	0x1f5
	.short	0x8219
	.short	0x80f1
	.short	0x5
	.short	0x821d
	.align	1, 0
	.type	 sZoomerOAM_TurningCornerLeft_Frame0,object
	.size	 sZoomerOAM_TurningCornerLeft_Frame0,20
sZoomerOAM_TurningCornerLeft_Frame0:
	.short	0x3
	.short	0xf8
	.short	0x41fe
	.short	0x8215
	.short	0x40f0
	.short	0x1fe
	.short	0x8219
	.short	0x80f8
	.short	0xe
	.short	0x821d
	.align	1, 0
	.type	 sZoomerOAM_TurningCornerLeft_Frame1,object
	.size	 sZoomerOAM_TurningCornerLeft_Frame1,20
sZoomerOAM_TurningCornerLeft_Frame1:
	.short	0x3
	.short	0xf8
	.short	0x4000
	.short	0x8213
	.short	0x40f0
	.short	0x0
	.short	0x8237
	.short	0x80f8
	.short	0x10
	.short	0x821c
	.align	1, 0
	.type	 sZoomerOAM_TurningCornerLeft_Frame2,object
	.size	 sZoomerOAM_TurningCornerLeft_Frame2,20
sZoomerOAM_TurningCornerLeft_Frame2:
	.short	0x3
	.short	0xf8
	.short	0x41ff
	.short	0x8211
	.short	0x40f0
	.short	0x1ff
	.short	0x8217
	.short	0x80f8
	.short	0xf
	.short	0x821b
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnLeftSlope_Frame0,object
	.size	 sZoomerOAM_WalkingOnLeftSlope_Frame0,26
sZoomerOAM_WalkingOnLeftSlope_Frame0:
	.short	0x4
	.short	0xf0
	.short	0x41f6
	.short	0x8240
	.short	0x80f0
	.short	0x6
	.short	0x8242
	.short	0xf6
	.short	0x41f8
	.short	0x8244
	.short	0xf6
	.short	0x1f0
	.short	0x8243
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnLeftSlope_Frame1,object
	.size	 sZoomerOAM_WalkingOnLeftSlope_Frame1,20
sZoomerOAM_WalkingOnLeftSlope_Frame1:
	.short	0x3
	.short	0xf1
	.short	0x41f6
	.short	0x8240
	.short	0x80f1
	.short	0x6
	.short	0x8242
	.short	0xf6
	.short	0x41f8
	.short	0x8246
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnLeftSlope_Frame2,object
	.size	 sZoomerOAM_WalkingOnLeftSlope_Frame2,20
sZoomerOAM_WalkingOnLeftSlope_Frame2:
	.short	0x3
	.short	0xf1
	.short	0x41f7
	.short	0x8240
	.short	0x80f1
	.short	0x7
	.short	0x8242
	.short	0xf6
	.short	0x41f9
	.short	0x8248
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnLeftSlope_Frame3,object
	.size	 sZoomerOAM_WalkingOnLeftSlope_Frame3,20
sZoomerOAM_WalkingOnLeftSlope_Frame3:
	.short	0x3
	.short	0xf0
	.short	0x41f7
	.short	0x8240
	.short	0x80f0
	.short	0x7
	.short	0x8242
	.short	0xf6
	.short	0x41f7
	.short	0x824a
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnRightSlope_Frame0,object
	.size	 sZoomerOAM_WalkingOnRightSlope_Frame0,26
sZoomerOAM_WalkingOnRightSlope_Frame0:
	.short	0x4
	.short	0xf0
	.short	0x51fa
	.short	0x8240
	.short	0x80f0
	.short	0x11f2
	.short	0x8242
	.short	0xf6
	.short	0x51f8
	.short	0x8244
	.short	0xf6
	.short	0x1008
	.short	0x8243
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnRightSlope_Frame1,object
	.size	 sZoomerOAM_WalkingOnRightSlope_Frame1,26
sZoomerOAM_WalkingOnRightSlope_Frame1:
	.short	0x3
	.short	0xf1
	.short	0x51fa
	.short	0x8240
	.short	0x80f1
	.short	0x11f2
	.short	0x8242
	.short	0xf6
	.short	0x51f8
	.short	0x8246
	.space	6
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnRightSlope_Frame2,object
	.size	 sZoomerOAM_WalkingOnRightSlope_Frame2,20
sZoomerOAM_WalkingOnRightSlope_Frame2:
	.short	0x3
	.short	0xf1
	.short	0x51f9
	.short	0x8240
	.short	0x80f1
	.short	0x11f1
	.short	0x8242
	.short	0xf6
	.short	0x51f7
	.short	0x8248
	.align	1, 0
	.type	 sZoomerOAM_WalkingOnRightSlope_Frame3,object
	.size	 sZoomerOAM_WalkingOnRightSlope_Frame3,20
sZoomerOAM_WalkingOnRightSlope_Frame3:
	.short	0x3
	.short	0xf0
	.short	0x51f9
	.short	0x8240
	.short	0x80f0
	.short	0x11f1
	.short	0x8242
	.short	0xf6
	.short	0x51f9
	.short	0x824a
	.align	2, 0
	.type	 sZoomerOAM_Falling,object
	.size	 sZoomerOAM_Falling,40
sZoomerOAM_Falling:
	.word	sZoomerOAM_Falling_Frame0
	.byte	0x3
	.space	3
	.word	sZoomerOAM_Falling_Frame1
	.byte	0x3
	.space	3
	.word	sZoomerOAM_Falling_Frame2
	.byte	0x3
	.space	3
	.word	sZoomerOAM_Falling_Frame1
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_OnGround,object
	.size	 sZoomerOAM_OnGround,40
sZoomerOAM_OnGround:
	.word	sZoomerOAM_OnGround_Frame0
	.byte	0x3
	.space	3
	.word	sZoomerOAM_OnGround_Frame1
	.byte	0x3
	.space	3
	.word	sZoomerOAM_OnGround_Frame2
	.byte	0x3
	.space	3
	.word	sZoomerOAM_OnGround_Frame3
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_TurningEdgeLeft,object
	.size	 sZoomerOAM_TurningEdgeLeft,32
sZoomerOAM_TurningEdgeLeft:
	.word	sZoomerOAM_TurningEdgeLeft_Frame0
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningEdgeLeft_Frame1
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningEdgeLeft_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_TurningEdgeRight,object
	.size	 sZoomerOAM_TurningEdgeRight,32
sZoomerOAM_TurningEdgeRight:
	.word	sZoomerOAM_TurningEdgeLeft_Frame2
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningEdgeLeft_Frame1
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningEdgeLeft_Frame0
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_OnWall,object
	.size	 sZoomerOAM_OnWall,40
sZoomerOAM_OnWall:
	.word	sZoomerOAM_OnWall_Frame0
	.byte	0x3
	.space	3
	.word	sZoomerOAM_OnWall_Frame1
	.byte	0x3
	.space	3
	.word	sZoomerOAM_OnWall_Frame2
	.byte	0x3
	.space	3
	.word	sZoomerOAM_OnWall_Frame3
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_TurningCornerRight,object
	.size	 sZoomerOAM_TurningCornerRight,32
sZoomerOAM_TurningCornerRight:
	.word	sZoomerOAM_TurningCornerRight_Frame0
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningCornerRight_Frame1
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningCornerRight_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_TurningCornerLeft,object
	.size	 sZoomerOAM_TurningCornerLeft,32
sZoomerOAM_TurningCornerLeft:
	.word	sZoomerOAM_TurningCornerLeft_Frame0
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningCornerLeft_Frame1
	.byte	0x2
	.space	3
	.word	sZoomerOAM_TurningCornerLeft_Frame2
	.byte	0x2
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_WalkingOnLeftSlope,object
	.size	 sZoomerOAM_WalkingOnLeftSlope,40
sZoomerOAM_WalkingOnLeftSlope:
	.word	sZoomerOAM_WalkingOnLeftSlope_Frame0
	.byte	0x3
	.space	3
	.word	sZoomerOAM_WalkingOnLeftSlope_Frame1
	.byte	0x3
	.space	3
	.word	sZoomerOAM_WalkingOnLeftSlope_Frame2
	.byte	0x3
	.space	3
	.word	sZoomerOAM_WalkingOnLeftSlope_Frame3
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align	2, 0
	.type	 sZoomerOAM_WalkingOnRightSlope,object
	.size	 sZoomerOAM_WalkingOnRightSlope,40
sZoomerOAM_WalkingOnRightSlope:
	.word	sZoomerOAM_WalkingOnRightSlope_Frame0
	.byte	0x3
	.space	3
	.word	sZoomerOAM_WalkingOnRightSlope_Frame1
	.byte	0x3
	.space	3
	.word	sZoomerOAM_WalkingOnRightSlope_Frame2
	.byte	0x3
	.space	3
	.word	sZoomerOAM_WalkingOnRightSlope_Frame3
	.byte	0x3
	.space	3
	.word	0x0
	.byte	0x0
	.space	3
	.align 2, 0 @ dont insert nops
