#ifndef SRAM_MISC
#define SRAM_MISC

#include "types.h"

enum SramOperation {
    SRAM_OPERATION_WRITE_FILE_SCREEN_OPTIONS,

    SRAM_OPERATION_SAVE_MOST_RECENT_FILE = 5,
    SRAM_OPERATION_SAVE_LANGUAGE,
    SRAM_OPERATION_SAVE_LANGUAGE2,
    SRAM_OPERATION_SAVE_SOUND_MODE,
    SRAM_OPERATION_SAVE_TIME_ATTACK,
    SRAM_OPERATION_SAVE_TIME_ATTACK2,
    SRAM_OPERATION_SAVE_RECORDED_DEMO,
    SRAM_OPERATION_SAVE_BOOT_DEBUG_RAM,
    SRAM_OPERATION_SAVE_DEMO_RAM,
    SRAM_OPERATION_READ_ALL_FLASH,
    SRAM_OPERATION_READ_RECENT_FILE_UNCHECKED,
    SRAM_OPERATION_CHECK_ALL,
};

void EraseSram(void);
u8* DoSramOperation(u8 operation);
u32 unk_fbc(u8 param_1);

#endif /* SRAM_MISC */
