#ifndef SRAM_MISC
#define SRAM_MISC

#include "types.h"

#define SRAM_OPERATION_WRITE_FILE_SCREEN_OPTIONS 0
#define SRAM_OPERATION_SAVE_MOST_RECENT_FILE 5
#define SRAM_OPERATION_SAVE_LANGUAGE 6
#define SRAM_OPERATION_SAVE_LANGUAGE2 7
#define SRAM_OPERATION_SAVE_SOUND_MODE 8
#define SRAM_OPERATION_SAVE_TIME_ATTACK 9
#define SRAM_OPERATION_SAVE_TIME_ATTACK2 10
#define SRAM_OPERATION_SAVE_RECORDED_DEMO 11
#define SRAM_OPERATION_SAVE_DEMO_RAM 13
#define SRAM_OPERATION_READ_ALL_FLASH 14
#define SRAM_OPERATION_READ_RECENT_FILE_UNCHECKED 15
#define SRAM_OPERATION_CHECK_ALL 16

void EraseSram(void);
u8* DoSramOperation(u8 operation);
u32 unk_fbc(u8 param_1);

#endif /* SRAM_MISC */
