#ifndef BOOT_DEBUG_CONSTANTS_H
#define BOOT_DEBUG_CONSTANTS_H

enum BootDebugMenuDepth {
    BOOT_DEBUG_MENU_MAIN,
    BOOT_DEBUG_MENU_SUB,
    BOOT_DEBUG_MENU_OPTION
};

enum BootDebugSubMenu {
    BOOT_DEBUG_SUB_MENU_HEADER,
    BOOT_DEBUG_SUB_MENU_SECTION,
    BOOT_DEBUG_SUB_MENU_MODE,
    BOOT_DEBUG_SUB_MENU_SAVE,
    BOOT_DEBUG_SUB_MENU_SAMUS,
    BOOT_DEBUG_SUB_MENU_SOUND,
    BOOT_DEBUG_SUB_MENU_DEMO,
    BOOT_DEBUG_SUB_MENU_ETC,
    BOOT_DEBUG_SUB_MENU_BOOT,
    BOOT_DEBUG_SUB_MENU_ERASE,

    BOOT_DEBUG_SUB_MENU_COUNT
};

enum BootDebugOam {
    BOOT_DEBUG_OAM_MENU_CURSOR,
    BOOT_DEBUG_OAM_SAVE_BRACKETS,
    BOOT_DEBUG_OAM_R_BUTTON_TITLE,
    BOOT_DEBUG_OAM_MAP_CURSOR
};

enum BootDebugSectionMenu {
    BOOT_DEBUG_SECTION_BRINSTAR,
    BOOT_DEBUG_SECTION_KRAID,
    BOOT_DEBUG_SECTION_NORFAIR,
    BOOT_DEBUG_SECTION_RIDLEY,
    BOOT_DEBUG_SECTION_TOURIAN,
    BOOT_DEBUG_SECTION_CRATERIA,
    BOOT_DEBUG_SECTION_CHOZODIA,
    BOOT_DEBUG_SECTION_BLANK,
    BOOT_DEBUG_SECTION_TEST_1,
    BOOT_DEBUG_SECTION_TEST_2,
    BOOT_DEBUG_SECTION_TEST_3,
    BOOT_DEBUG_SECTION_TITLE,
    BOOT_DEBUG_SECTION_SAVE_A,
    BOOT_DEBUG_SECTION_SAVE_B,
    BOOT_DEBUG_SECTION_SAVE_C,

    BOOT_DEBUG_SECTION_COUNT
};

enum BootDebugModeMenu {
    BOOT_DEBUG_MODE_LANGUAGE,
    BOOT_DEBUG_MODE_DIFFICULTY,

    BOOT_DEBUG_MODE_COUNT
};

enum BootDebugSaveMenu {
    BOOT_DEBUG_SAVE_GALLERY_IMAGES,
    BOOT_DEBUG_SAVE_DIFFICULTIES_CLEARED,
    BOOT_DEBUG_SAVE_LINKED_WITH_FUSION,
    BOOT_DEBUG_SAVE_ID,
    BOOT_DEBUG_SAVE_SAVE,

    BOOT_DEBUG_SAVE_COUNT
};

enum BootDebugSamusMenu {
    BOOT_DEBUG_SAMUS_GET_MAP,
    BOOT_DEBUG_SAMUS_ARM_WEAPON,
    BOOT_DEBUG_SAMUS_DIAGONAL_AIM,
    BOOT_DEBUG_SAMUS_PAUSE,
    BOOT_DEBUG_SAMUS_SWAP_MISSILES,

    BOOT_DEBUG_SAMUS_COUNT
};

enum BootDebugSoundMenu {
    BOOT_DEBUG_SOUND_BGM,
    BOOT_DEBUG_SOUND_STEREO,
    BOOT_DEBUG_SOUND_TEST,

    BOOT_DEBUG_SOUND_COUNT
};

enum BootDebugDemoMenu {
    BOOT_DEBUG_DEMO_CUTSCENE_SWITCH,
    BOOT_DEBUG_DEMO_CUTSCENE_A,
    BOOT_DEBUG_DEMO_CUTSCENE_B,
    BOOT_DEBUG_DEMO_DEMO_MODE,
    BOOT_DEBUG_DEMO_DEMO_NUM,

    BOOT_DEBUG_DEMO_COUNT
};

enum BootDebugEtcMenu {
    BOOT_DEBUG_ETC_ENDING,
    BOOT_DEBUG_ETC_STAFF_ROLL,
    BOOT_DEBUG_ETC_MAIN_END_OBJ,
    BOOT_DEBUG_ETC_DOOR_TRANSITION,

    BOOT_DEBUG_ETC_COUNT
};

enum BootDebugColor {
    BOOT_DEBUG_COLOR_AZURE_WHITE = 8,
    BOOT_DEBUG_COLOR_RED,
    BOOT_DEBUG_COLOR_GREEN,
    BOOT_DEBUG_COLOR_BLUE,
    BOOT_DEBUG_COLOR_YELLOW,
    BOOT_DEBUG_COLOR_AZURE_WHITE_SUB_MENU,
    BOOT_DEBUG_COLOR_AZURE_WHITE_3,
    BOOT_DEBUG_COLOR_BLACK,
};

#endif
