#ifndef ERASE_SRAM_CONSTANTS_H
#define ERASE_SRAM_CONSTANTS_H

#define ERASE_SRAM_OPTION_CHANGED_FLAG 0x80

enum EraseSramOption {
    ERASE_SRAM_OPTION_QUESTION_NO,
    ERASE_SRAM_OPTION_QUESTION_YES,
    ERASE_SRAM_OPTION_CONFIRM_NO,
    ERASE_SRAM_OPTION_CONFIRM_YES,

    ERASE_SRAM_OPTION_END
};

#define ERASE_SRAM_INPUT_ACTION_NONE 0
#define ERASE_SRAM_INPUT_ACTION_ERASING 1
#define ERASE_SRAM_INPUT_ACTION_OPENING_SUB_WINDOW 2

enum EraseSramOamId {
    ERASE_SRAM_OAM_ID_CURSOR_IDLE = 1,
    ERASE_SRAM_OAM_ID_CURSOR_SELECTING,
    ERASE_SRAM_OAM_ID_QUESTION_WINDOW_NO_SELECTED,
    ERASE_SRAM_OAM_ID_QUESTION_WINDOW_YES_SELECTED,
    ERASE_SRAM_OAM_ID_CONFIRM_WINDOW_NO_SELECTED,
    ERASE_SRAM_OAM_ID_CONFIRM_WINDOW_YES_SELECTED,

    ERASE_SRAM_OAM_ID_END
};

enum EraseSramSound {
    ERASE_SRAM_SOUND_CONFIRM = 1,
    ERASE_SRAM_SOUND_SELECT_YES,
    ERASE_SRAM_SOUND_REFUSE,
    ERASE_SRAM_SOUND_CURSOR,

    ERASE_SRAM_SOUND_END
};

#endif