#ifndef FILE_SELECT_CONSTANTS_H
#define FILE_SELECT_CONSTANTS_H

#define FILE_SELECT_TILE_TWO_DOTS_HIGH 0x1CA
#define FILE_SELECT_TILE_TWO_DOTS_LOW 0x1EA
#define FILE_SELECT_TILE_MINUS_HIGH 0x1CB
#define FILE_SELECT_TILE_MINUS_LOW 0x1EB
#define FILE_SELECT_TILE_NUMBER_HIGH 0x1CC
#define FILE_SELECT_TILE_NUMBER_LOW 0x1EC

#define FILE_SELECT_SELECTION_SET_ALL_FILES 0
#define FILE_SELECT_SELECTION_SET_ONLY_FILES 1
#define FILE_SELECT_SELECTION_SET_ALL_FILES_NO_COPY 2

enum FileSelectFadingStage {
    FILE_SELECT_FADING_STAGE_FADE_IN,
    FILE_SELECT_FADING_STAGE_CHECK_FADE_IN,
    FILE_SELECT_FADING_STAGE_FADE_OUT,
    FILE_SELECT_FADING_STAGE_CHECK_FADE_OUT
};

enum FileScreenProcessTextStage {
    FILE_SCREEN_PROCESS_TEXT_STAGE_NONE,
    FILE_SCREEN_PROCESS_TEXT_STAGE_INIT,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_1,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_2,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_3,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_4,
    FILE_SCREEN_PROCESS_TEXT_STAGE_UPDATE_QUEUE
};

enum FileSelectEraseFileSubroutineStage {
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_INIT,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_WAIT_FOR_CHOOSE,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_UPDATE_CHOOSE,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_WAIT_FOR_CONFIRM,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_UPDATE_CONFIRM,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_CANCEL_CONFIRM,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_RESTART_CHOOSE,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_ERASE_FILE,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_BEGIN_EXIT,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_WAIT_FOR_EXIT,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_UPDATE_ERASED_FILE,
    FILE_SELECT_ERASE_FILE_SUBROUTINE_STAGE_EXIT
};

// Offsets in the RAM OAM array for the file select screen

enum FileSelectOam {
    FILE_SELECT_OAM_MEDIUM_PANEL = 4,

    FILE_SELECT_OAM_COPY_ARROW,
    FILE_SELECT_OAM_SUB_CURSOR,
    FILE_SELECT_OAM_CURSOR,

    FILE_SELECT_OAM_FILE_A_MARKER,
    FILE_SELECT_OAM_FILE_B_MARKER,
    FILE_SELECT_OAM_FILE_C_MARKER,

    FILE_SELECT_OAM_SMALL_PANEL,

    FILE_SELECT_OAM_FILE_A_LOGO,
    FILE_SELECT_OAM_FILE_B_LOGO,
    FILE_SELECT_OAM_FILE_C_LOGO,

    FILE_SELECT_OAM_END
};

// ----
// Offsets in the RAM OAM array for the options screen

enum OptionsOam {
    OPTIONS_OAM_FUSION_LINK_GBAS,
    OPTIONS_OAM_TIME_ATTACK_LEFT_ARROW,
    OPTIONS_OAM_TIME_ATTACK_RIGHT_ARROW,
    OPTIONS_OAM_LARGE_PANEL,
    OPTIONS_OAM_HUGE_PANEL,

    OPTIONS_OAM_CURSOR,
    OPTIONS_OAM_SPEAKER,
    OPTIONS_OAM_SOUND_TEST_ID,
    OPTIONS_OAM_SOUND_TEST_LEFT_ARROW,
    OPTIONS_OAM_SOUND_TEST_RIGHT_ARROW,
    OPTIONS_OAM_SOUND_TEST_PANEL,

    OPTIONS_OAM_END
};

// ----
// OAM IDs for the file select menu

enum FileSelectOamId {
    FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING_ON = 1,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_IDLE,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING_OFF,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_OFF,
// #define FILE_SELECT_OAM_ID_SAMUS_HEAD_ 5
    FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING = 6,

    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING_ON,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_IDLE,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING_OFF,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_OFF,
// #define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_ 11
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING = 12,

    FILE_SELECT_OAM_ID_FILE_A_MARKER_IDLE,
    FILE_SELECT_OAM_ID_FILE_B_MARKER_IDLE,
    FILE_SELECT_OAM_ID_FILE_C_MARKER_IDLE,
    FILE_SELECT_OAM_ID_FILE_A_MARKER_SELECTED_RED,
    FILE_SELECT_OAM_ID_FILE_B_MARKER_SELECTED_RED,
    FILE_SELECT_OAM_ID_FILE_C_MARKER_SELECTED_RED,
    FILE_SELECT_OAM_ID_FILE_A_MARKER_SELECTED_GREEN,
    FILE_SELECT_OAM_ID_FILE_B_MARKER_SELECTED_GREEN,
    FILE_SELECT_OAM_ID_FILE_C_MARKER_SELECTED_GREEN,

    FILE_SELECT_OAM_ID_CURSOR,
    FILE_SELECT_OAM_ID_CURSOR_IDLE,
    FILE_SELECT_OAM_ID_CURSOR_SELECTED,

    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_DOWN_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_DOWN_INACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_DOWN_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_DOWN_INACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_UP_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_UP_INACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_UP_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_UP_INACTIVE,

    FILE_SELECT_OAM_ID_METROID_LOGO,

    FILE_SELECT_OAM_ID_SMALL_PANEL,
// #define FILE_SELECT_OAM_ID_ 35
    FILE_SELECT_OAM_ID_LARGE_PANEL = 36,
// #define FILE_SELECT_OAM_ID_ 37
    FILE_SELECT_OAM_ID_MEDIUM_PANEL = 38,
// #define FILE_SELECT_OAM_ID_ 39
    FILE_SELECT_OAM_ID_END = 40
};

// ----
// OAM IDs for the options menu

enum OptionsOamId {
    OPTIONS_OAM_ID_CURSOR = 1,
    OPTIONS_OAM_ID_CURSOR_SELECTED,
    OPTIONS_OAM_ID_GBA_IDLE,
    OPTIONS_OAM_ID_SPEAKERS_IDLE,
    OPTIONS_OAM_ID_GBA_ACTIVE,
    OPTIONS_OAM_ID_SPEAKERS_ACTIVE,
    OPTIONS_OAM_ID_SOUND_TEST_ID,
    OPTIONS_OAM_ID_LEFT_ARROW_MOVING,
    OPTIONS_OAM_ID_LEFT_ARROW_IDLE,
    OPTIONS_OAM_ID_RIGHT_ARROW_MOVING,
    OPTIONS_OAM_ID_RIGHT_ARROW_IDLE,
    OPTIONS_OAM_ID_GBA_LINKING,
    OPTIONS_OAM_ID_GBA_STOPPED,
    OPTIONS_OAM_ID_SMALL_PANEL,
// #define OPTIONS_OAM_ID_ 15
    OPTIONS_OAM_ID_LARGE_PANEL = 16,
// #define OPTIONS_OAM_ID_ 17
    OPTIONS_OAM_ID_MEDIUM_PANEL = 18,
// #define OPTIONS_OAM_ID_ 19
    OPTIONS_OAM_ID_HUGE_PANEL = 20,
// #define OPTIONS_OAM_ID_ 21
    OPTIONS_OAM_ID_END = 22
};

// ----
// Tilemap update requests

enum TilemapRequest {
    TILEMAP_REQUEST_START_GAME_INIT,
    TILEMAP_REQUEST_START_GAME,

    TILEMAP_REQUEST_DIFFICULTY_SPAWN_INIT = 6,
    TILEMAP_REQUEST_DIFFICULTY_SPAWN,
    TILEMAP_REQUEST_DIFFICULTY_DESPAWN_INIT,
    TILEMAP_REQUEST_DIFFICULTY_DESPAWN,

    TILEMAP_REQUEST_ERASE_SPAWN_INIT,
    TILEMAP_REQUEST_ERASE_SPAWN,
    TILEMAP_REQUEST_ERASE_DESPAWN_INIT,
    TILEMAP_REQUEST_ERASE_DESPAWN,
    TILEMAP_REQUEST_ERASE_YES_NO_SPAWN_INIT,
    TILEMAP_REQUEST_ERASE_YES_NO_SPAWN,
    TILEMAP_REQUEST_ERASE_YES_NO_DESPAWN_INIT,
    TILEMAP_REQUEST_ERASE_YES_NO_DESPAWN,

    TILEMAP_REQUEST_COPY_SPAWN_INIT,
    TILEMAP_REQUEST_COPY_SPAWN,
    TILEMAP_REQUEST_COPY_DESPAWN_INIT,
    TILEMAP_REQUEST_COPY_DESPAWN,
    TILEMAP_REQUEST_COPY_OVERRIDE_SPAWN_INIT,
    TILEMAP_REQUEST_COPY_OVERRIDE_SPAWN,
    TILEMAP_REQUEST_COPY_OVERRIDE_DESPAWN_INIT,
    TILEMAP_REQUEST_COPY_OVERRIDE_DESPAWN,
    TILEMAP_REQUEST_COPY_DESTINATION_DESPAWN,
    TILEMAP_REQUEST_COPY_DESTINATION_SPAWN,
};

// Cursor poses

enum CursorPose {
    CURSOR_POSE_DEFAULT,
    CURSOR_POSE_MOVING,
    CURSOR_POSE_OPENING_OPTIONS,

    CURSOR_POSE_SELECTING_FILE = 5,
    CURSOR_POSE_DESELECTING_FILE,
    CURSOR_POSE_STARTING_GAME,
};

enum CursorCopyPose {
    CURSOR_COPY_POSE_DEFAULT,
    CURSOR_COPY_POSE_MOVING,
    CURSOR_COPY_POSE_SELECTING_FILE,
    CURSOR_COPY_POSE_COPIED,
};

enum ArrowCopyPose {
    ARROW_COPY_POSE_DEFAULT,
    ARROW_COPY_POSE_MOVING,
    ARROW_COPY_POSE_COPYING,
    ARROW_COPY_POSE_KILL,
};

enum CursorErasePose {
    CURSOR_ERASE_POSE_DEFAULT,
    CURSOR_ERASE_POSE_MOVING,
    CURSOR_ERASE_POSE_SELECTING_FILE,
    CURSOR_ERASE_POSE_ERASED,
};

enum CursorOptionsPose {
    CURSOR_OPTIONS_POSE_MOVING,
    CURSOR_OPTIONS_POSE_ENTERING,
    CURSOR_OPTIONS_POSE_SELECTING,
    CURSOR_OPTIONS_POSE_DESELECTING,
};

#define STEREO_UPDATE_FLAGS_IDLE       (1 << 0)
#define STEREO_UPDATE_FLAGS_ACTIVE     (1 << 1)
#define STEREO_UPDATE_FLAGS_SOUND_TEST (1 << 2)

// ----

enum FileSelectCursorPosition {
    FILE_SELECT_CURSOR_POSITION_FILE_A,
    FILE_SELECT_CURSOR_POSITION_FILE_B,
    FILE_SELECT_CURSOR_POSITION_FILE_C,
    FILE_SELECT_CURSOR_POSITION_COPY,
    FILE_SELECT_CURSOR_POSITION_ERASE,
    FILE_SELECT_CURSOR_POSITION_OPTIONS,

    FILE_SELECT_CURSOR_POSITION_END
};

// ----

enum OptionId {
    OPTION_NONE,
    OPTION_STEREO_SELECT,
    OPTION_SOUND_TEST,
    OPTION_TIME_ATTACK,
    OPTION_GALLERY,
    OPTION_FUSION_GALLERY,
    OPTION_FUSION_LINK,
    OPTION_NES_METROID,

    OPTION_END
};

// Sound request ids for FileSelectPlayMenuSound

enum MenuSoundRequest {
    MENU_SOUND_REQUEST_SUB_MENU_CURSOR,
    MENU_SOUND_REQUEST_ACCEPT_CONFIRM_MENU,
    MENU_SOUND_REQUEST_CURSOR,
    MENU_SOUND_REQUEST_FILE_SELECT,
    MENU_SOUND_REQUEST_START_GAME,
    MENU_SOUND_REQUEST_OPEN_SUB_MENU,
    MENU_SOUND_REQUEST_CLOSE_SUB_MENU,
    MENU_SOUND_REQUEST_CLOSE_SUB_MENU2,
    MENU_SOUND_REQUEST_COPY_DELETE,
    MENU_SOUND_REQUEST_COPY_DELETE_MOVING,
    MENU_SOUND_REQUEST_COPY_CONFIRM,
    MENU_SOUND_REQUEST_GAME_OVER_MENU_CURSOR,
    MENU_SOUND_REQUEST_GAME_OVER_START_GAME,

    MENU_SOUND_REQUEST_END
};

// Enabled menus flags

#define MENU_FLAG_FILE_A  (1 << 0)
#define MENU_FLAG_FILE_B  (1 << 1)
#define MENU_FLAG_FILE_C  (1 << 2)
#define MENU_FLAG_COPY    (1 << 3)
#define MENU_FLAG_ERASE   (1 << 4)
#define MENU_FLAG_OPTIONS (1 << 5)

#endif /* FILE_SELECT_CONSTANTS_H */
