// Offsets in the RAM OAM array for the file select screen

#define FILE_SELECT_OAM_CURSOR 7

#define FILE_SELECT_OAM_FILE_A_MARKER 8
#define FILE_SELECT_OAM_FILE_B_MARKER 9
#define FILE_SELECT_OAM_FILE_C_MARKER 10

#define FILE_SELECT_OAM_FILE_A_LOGO 12
#define FILE_SELECT_OAM_FILE_B_LOGO 13
#define FILE_SELECT_OAM_FILE_C_LOGO 14

// ----
// OAM IDs for the file select menu

#define FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING_ON 1
#define FILE_SELECT_OAM_ID_SAMUS_HEAD_IDLE 2
#define FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING_OFF 3
#define FILE_SELECT_OAM_ID_SAMUS_HEAD_OFF 4
// #define FILE_SELECT_OAM_ID_SAMUS_HEAD_ 5
#define FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING 6

#define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING_ON 7
#define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_IDLE 8
#define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING_OFF 9
#define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_OFF 10
// #define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_ 11
#define FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING 12

#define FILE_SELECT_OAM_ID_FILE_A_MARKER_IDLE 13
#define FILE_SELECT_OAM_ID_FILE_B_MARKER_IDLE 14
#define FILE_SELECT_OAM_ID_FILE_C_MARKER_IDLE 15
#define FILE_SELECT_OAM_ID_FILE_A_MARKER_SELECTED_RED 16
#define FILE_SELECT_OAM_ID_FILE_B_MARKER_SELECTED_RED 17
#define FILE_SELECT_OAM_ID_FILE_C_MARKER_SELECTED_RED 18
#define FILE_SELECT_OAM_ID_FILE_A_MARKER_SELECTED_GREEN 19
#define FILE_SELECT_OAM_ID_FILE_B_MARKER_SELECTED_GREEN 20
#define FILE_SELECT_OAM_ID_FILE_C_MARKER_SELECTED_GREEN 21

#define FILE_SELECT_OAM_ID_CURSOR 22
#define FILE_SELECT_OAM_ID_CURSOR_IDLE 23
#define FILE_SELECT_OAM_ID_CURSOR_SELECTED 24

#define FILE_SELECT_OAM_ID_COPY_ARROW_ONE_DOWN_ACTIVE 25
#define FILE_SELECT_OAM_ID_COPY_ARROW_ONE_DOWN_INACTIVE 26
#define FILE_SELECT_OAM_ID_COPY_ARROW_TWO_DOWN_ACTIVE 27
#define FILE_SELECT_OAM_ID_COPY_ARROW_TWO_DOWN_INACTIVE 28
#define FILE_SELECT_OAM_ID_COPY_ARROW_ONE_UP_ACTIVE 29
#define FILE_SELECT_OAM_ID_COPY_ARROW_ONE_UP_INACTIVE 30
#define FILE_SELECT_OAM_ID_COPY_ARROW_TWO_UP_ACTIVE 31
#define FILE_SELECT_OAM_ID_COPY_ARROW_TWO_UP_INACTIVE 32

#define FILE_SELECT_OAM_ID_METROID_LOGO 33

#define FILE_SELECT_OAM_ID_SMALL_PANEL 34
// #define FILE_SELECT_OAM_ID_ 35
#define FILE_SELECT_OAM_ID_LARGE_PANEL 36
// #define FILE_SELECT_OAM_ID_ 37
#define FILE_SELECT_OAM_ID_MEDIUM_PANEL 38
// #define FILE_SELECT_OAM_ID_ 39

// ----
// OAM IDs for the options menu


// ----

#define CURSOR_POSE_DEFAULT 0
#define CURSOR_POSE_MOVING 1
#define CURSOR_POSE_OPENING_OPTIONS 2
#define CURSOR_POSE_SELECTING_FILE 5
#define CURSOR_POSE_DESELECTING_FILE 6
#define CURSOR_POSE_STARTING_GAME 7

// ...

#define FILE_SELECT_CURSOR_POSITION_FILE_A 0
#define FILE_SELECT_CURSOR_POSITION_FILE_B 1
#define FILE_SELECT_CURSOR_POSITION_FILE_C 2
#define FILE_SELECT_CURSOR_POSITION_COPY 3
#define FILE_SELECT_CURSOR_POSITION_ERASE 4
#define FILE_SELECT_CURSOR_POSITION_OPTIONS 5
