#define ITEM_TOGGLE_CHECKING 0
#define ITEM_TOGGLE_TOGGLING 1
#define ITEM_TOGGLE_CHECKING2 2

#define ABILITY_GROUP_BEAMS 0
#define ABILITY_GROUP_BOMBS 1
#define ABILITY_GROUP_SUITS 2
#define ABILITY_GROUP_MISC 3
#define ABILITY_GROUP_MISSILES 4
#define ABILITY_GROUP_CURRENT_ENERGY 5
#define ABILITY_GROUP_MAX_ENERGY 6
#define ABILITY_GROUP_CURRENT_MISSILES 7
#define ABILITY_GROUP_MAX_MISSILES 8
#define ABILITY_GROUP_CURRENT_SUPER_MISSILES 9
#define ABILITY_GROUP_MAX_SUPER_MISSILES 10
#define ABILITY_GROUP_CURRENT_POWER_BOMBS 11
#define ABILITY_GROUP_MAX_POWER_BOMBS 12