#ifndef TITLE_SCREEN_CONSTANTS_H
#define TITLE_SCREEN_CONSTANTS_H

#define TITLE_SCREEN_TYPE_FIRST_COMET_ACTIVE    (1 << 0)
#define TITLE_SCREEN_TYPE_FIRST_COMET_ENDED     (1 << 1)
#define TITLE_SCREEN_TYPE_SECOND_COMET_ACTIVE   (1 << 2)
#define TITLE_SCREEN_TYPE_SECOND_COMET_ENDED    (1 << 3)
#define TITLE_SCREEN_TYPE_TOP_SPARKLE_ACTIVE    (1 << 4)
#define TITLE_SCREEN_TYPE_TOP_SPARKLE_ENDED     (1 << 5)
#define TITLE_SCREEN_TYPE_BOTTOM_SPARKLE_ACTIVE (1 << 6)
#define TITLE_SCREEN_TYPE_BOTTOM_SPARKLE_ENDED  (1 << 7)

#define TITLE_SCREEN_TYPE_ALL_SPARKLES_ENDED (TITLE_SCREEN_TYPE_TOP_SPARKLE_ENDED | TITLE_SCREEN_TYPE_BOTTOM_SPARKLE_ENDED)

#define TITLE_SCREEN_SPARKLE_DELAY 22

#define TITLE_SCREEN_IDLE_STAGE_COMETS 0
#define TITLE_SCREEN_IDLE_STAGE_TITLE_FADING 1
#define TITLE_SCREEN_IDLE_STAGE_IDLE 2

#define TITLE_SCREEN_ANIMATED_PALETTE_SKY_DECORATIONS (1 << 0)
#define TITLE_SCREEN_ANIMATED_PALETTE_TITLE           (1 << 1)
#define TITLE_SCREEN_ANIMATED_PALETTE_PROMPT          (1 << 2)

enum TitleScreenOamId {
    TITLE_SCREEN_OAM_ID_COMET_SPAWNING = 1,
    TITLE_SCREEN_OAM_ID_COMET_APPEARING,
    TITLE_SCREEN_OAM_ID_COMET_FLYING,
    TITLE_SCREEN_OAM_ID_SPARKLE_IDLE,
    TITLE_SCREEN_OAM_ID_SPARKLE_GROWING,
    TITLE_SCREEN_OAM_ID_SPARKLE_DISAPPEARING,

    TITLE_SCREEN_OAM_ID_END
};

enum TitleScreenCopyrightSymbol {
    TITLE_SCREEN_COPYRIGHT_SYMBOL_NONE,
    TITLE_SCREEN_COPYRIGHT_SYMBOL_REGISTERED_TRADEMARK, // ®️
    TITLE_SCREEN_COPYRIGHT_SYMBOL_TRADEMARK // ™️
};

#endif
