#include "save_platform_chozodia.h"
#include "save_platform.h"
#include "../../data/data.h"
#include "../globals.h"

const u32 sSavePlatformChozodiaGFX[552];
const u16 sSavePlatformChozodiaPAL[64];

const u16 sSavePlatformChozodiaOAM_Idle_Frame0[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1f4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xf0, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1e3, OBJ_SPRITE_OAM | 0x201,
    0xf0, OBJ_SIZE_16x16 | 0x1eb, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x201,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x5, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1e3, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfa, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0xff, 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x208,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x208,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Idle_Frame1[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1f4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1f0, OBJ_SPRITE_OAM | 0x255,
    0xf0, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x255,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1e3, OBJ_SPRITE_OAM | 0x204,
    0xf0, OBJ_SIZE_16x16 | 0x1eb, OBJ_SPRITE_OAM | 0x205,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x204,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x5, OBJ_SPRITE_OAM | 0x205,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1e3, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfa, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0xff, 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x208,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x208,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Idle_Frame2[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1f4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1f0, OBJ_SPRITE_OAM | 0x256,
    0xf0, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x256,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1e3, OBJ_SPRITE_OAM | 0x241,
    0xf0, OBJ_SIZE_16x16 | 0x1eb, OBJ_SPRITE_OAM | 0x242,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x241,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x5, OBJ_SPRITE_OAM | 0x242,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1e3, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfa, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0xff, 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x208,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x208,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Idle_Frame3[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1f4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1f0, OBJ_SPRITE_OAM | 0x257,
    0xf0, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x257,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1e3, OBJ_SPRITE_OAM | 0x244,
    0xf0, OBJ_SIZE_16x16 | 0x1eb, OBJ_SPRITE_OAM | 0x245,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x244,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x5, OBJ_SPRITE_OAM | 0x245,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1e3, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfa, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0xff, 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x208,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x208,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opening_Frame0[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1f4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xef, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xef, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xef, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xef, 0x1e3, OBJ_SPRITE_OAM | 0x201,
    0xef, OBJ_SIZE_16x16 | 0x1eb, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xef, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x201,
    0xef, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x5, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf0, 0x1e3, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | 0x15, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xef, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xef, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfa, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0xff, 0x1e7, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | 0x9, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x248,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x248,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opening_Frame1[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xee, 0x1f4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xee, OBJ_X_FLIP | 0x4, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xee, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xee, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xee, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xee, 0x1e2, OBJ_SPRITE_OAM | 0x201,
    0xee, OBJ_SIZE_16x16 | 0x1ea, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xee, OBJ_X_FLIP | 0x16, OBJ_SPRITE_OAM | 0x201,
    0xee, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x6, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xee, 0x1e2, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xee, OBJ_X_FLIP | 0x16, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfb, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x0, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x20c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x20c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opening_Frame2[61] = {
    0x14,
    OBJ_SHAPE_VERTICAL | 0xec, 0x1f3, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xec, OBJ_X_FLIP | 0x5, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xed, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xed, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xed, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xed, 0x1e0, OBJ_SPRITE_OAM | 0x201,
    0xed, OBJ_SIZE_16x16 | 0x1e8, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xed, OBJ_X_FLIP | 0x18, OBJ_SPRITE_OAM | 0x201,
    0xed, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xec, 0x1e0, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xec, OBJ_X_FLIP | 0x18, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf1, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf1, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xfd, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x1, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x1, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x24c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x24c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opening_Frame3[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xed, 0x1f2, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xed, OBJ_X_FLIP | 0x6, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xf1, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xf1, 0x1df, OBJ_SPRITE_OAM | 0x201,
    0xf1, OBJ_SIZE_16x16 | 0x1e7, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x201,
    0xf1, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x9, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xed, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xed, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x3, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x3, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x208,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x208
};

const u16 sSavePlatformChozodiaOAM_Opening_Frame4[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xef, 0x1f1, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xef, OBJ_X_FLIP | 0x7, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf5, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xf5, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf5, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xf5, 0x1de, OBJ_SPRITE_OAM | 0x201,
    0xf5, OBJ_SIZE_16x16 | 0x1e6, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf5, OBJ_X_FLIP | 0x1a, OBJ_SPRITE_OAM | 0x201,
    0xf5, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0xa, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xef, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xef, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x4, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x4, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x248,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x248,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opening_Frame5[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xf3, 0x1f1, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf3, OBJ_X_FLIP | 0x7, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf7, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xf7, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf7, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xf7, 0x1de, OBJ_SPRITE_OAM | 0x201,
    0xf7, OBJ_SIZE_16x16 | 0x1e6, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf7, OBJ_X_FLIP | 0x1a, OBJ_SPRITE_OAM | 0x201,
    0xf7, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0xa, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf3, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf3, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x3, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x3, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x20c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x20c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opened_Frame0[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1f1, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x7, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1f0, OBJ_SPRITE_OAM | 0x215,
    0xf6, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x215,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1de, OBJ_SPRITE_OAM | 0x201,
    0xf6, OBJ_SIZE_16x16 | 0x1e6, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x1a, OBJ_SPRITE_OAM | 0x201,
    0xf6, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0xa, OBJ_SPRITE_OAM | 0x202,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xfe, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x1, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x1, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x24c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x24c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opened_Frame1[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1f1, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x7, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1f0, OBJ_SPRITE_OAM | 0x255,
    0xf6, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x255,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1de, OBJ_SPRITE_OAM | 0x204,
    0xf6, OBJ_SIZE_16x16 | 0x1e6, OBJ_SPRITE_OAM | 0x205,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x1a, OBJ_SPRITE_OAM | 0x204,
    0xf6, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0xa, OBJ_SPRITE_OAM | 0x205,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xfe, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x1, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x1, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x24c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x24c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opened_Frame2[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1f1, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x7, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1f0, OBJ_SPRITE_OAM | 0x256,
    0xf6, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x256,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1de, OBJ_SPRITE_OAM | 0x241,
    0xf6, OBJ_SIZE_16x16 | 0x1e6, OBJ_SPRITE_OAM | 0x242,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x1a, OBJ_SPRITE_OAM | 0x241,
    0xf6, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0xa, OBJ_SPRITE_OAM | 0x242,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xfe, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x1, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x1, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x24c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x24c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaOAM_Opened_Frame3[67] = {
    0x16,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1f1, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x7, OBJ_SPRITE_OAM | 0x214,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1f0, OBJ_SPRITE_OAM | 0x257,
    0xf6, OBJ_SIZE_16x16 | 0x1f8, OBJ_SPRITE_OAM | 0x216,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x257,
    OBJ_SHAPE_VERTICAL | 0xf6, 0x1de, OBJ_SPRITE_OAM | 0x244,
    0xf6, OBJ_SIZE_16x16 | 0x1e6, OBJ_SPRITE_OAM | 0x245,
    OBJ_SHAPE_VERTICAL | 0xf6, OBJ_X_FLIP | 0x1a, OBJ_SPRITE_OAM | 0x244,
    0xf6, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0xa, OBJ_SPRITE_OAM | 0x245,
    OBJ_SHAPE_VERTICAL | 0xf2, 0x1df, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | 0x19, OBJ_SPRITE_OAM | 0x200,
    OBJ_SHAPE_HORIZONTAL | 0xf2, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2c2,
    0xf2, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2c2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xf0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2d2,
    OBJ_SHAPE_HORIZONTAL | 0xfe, OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x282,
    OBJ_SHAPE_HORIZONTAL | 0x1, 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x1, OBJ_X_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x0, OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x24c,
    0x0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x24c,
    0xf0, OBJ_SIZE_16x16 | 0x1de, OBJ_SPRITE_OAM | 0x2c6,
    0xf0, OBJ_X_FLIP | OBJ_SIZE_16x16 | 0x12, OBJ_SPRITE_OAM | 0x2c6
};

const u16 sSavePlatformChozodiaPartOAM_TopIdle_Frame0[76] = {
    0x19,
    OBJ_SHAPE_HORIZONTAL | 0xc6, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd2, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xde, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xc8, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xc8, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xd8, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xd8, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xea, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf6, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x20, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x20, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0x0, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0x0, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xe0, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e
};

const u16 sSavePlatformChozodiaPartOAM_TopExtending_Frame0[82] = {
    0x1b,
    OBJ_SHAPE_HORIZONTAL | 0xc7, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e7, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0x9, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd3, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e7, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0x9, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdf, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e7, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0x9, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcc, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xcc, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xdc, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xdc, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xeb, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e7, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0x9, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf7, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e7, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0x9, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x24, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x24, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0x4, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0x4, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xe4, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xe4, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_HORIZONTAL | 0xc4, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xc4, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae
};

const u16 sSavePlatformChozodiaPartOAM_TopExtending_Frame1[82] = {
    0x1b,
    OBJ_SHAPE_HORIZONTAL | 0xc8, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd4, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe0, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd0, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xd0, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xe0, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xe0, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xec, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf8, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x28, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x28, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0x8, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0x8, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xe8, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xe8, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_HORIZONTAL | 0xc8, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xc8, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae
};

const u16 sSavePlatformChozodiaPartOAM_TopExtending_Frame2[82] = {
    0x1b,
    OBJ_SHAPE_HORIZONTAL | 0xc9, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd5, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe1, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd4, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xd4, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xe4, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xe4, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xed, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf9, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x2c, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x2c, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0xc, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0xc, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xec, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xec, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_HORIZONTAL | 0xcc, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xcc, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae
};

const u16 sSavePlatformChozodiaPartOAM_TopExtending_Frame3[82] = {
    0x1b,
    OBJ_SHAPE_HORIZONTAL | 0xca, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e4, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0xc, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd6, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e4, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0xc, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe2, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e4, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0xc, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xda, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xda, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xea, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xea, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xee, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e4, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0xc, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xfa, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e4, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0xc, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x32, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x32, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0x12, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0x12, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xf2, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xf2, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_HORIZONTAL | 0xd2, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xd2, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae
};

const u16 sSavePlatformChozodiaPartOAM_TopExtending_Frame4[82] = {
    0x1b,
    OBJ_SHAPE_HORIZONTAL | 0xc9, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd5, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe1, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd9, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xd9, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xe9, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xe9, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xed, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf9, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e5, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0xb, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x31, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x31, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0x11, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0x11, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xf1, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xf1, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_HORIZONTAL | 0xd1, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xd1, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae
};

const u16 sSavePlatformChozodiaPartOAM_TopExtended_Frame0[82] = {
    0x1b,
    OBJ_SHAPE_HORIZONTAL | 0xc8, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xcf, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd4, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xdb, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe0, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xe7, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xd8, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1e8, OBJ_SPRITE_OAM | 0x2ce,
    0xd8, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x16 | 0x8, OBJ_SPRITE_OAM | 0x2ce,
    OBJ_SHAPE_HORIZONTAL | 0xe8, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xe8, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xec, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf3, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xf8, OBJ_Y_FLIP | OBJ_SIZE_32x16 | 0x1f0, OBJ_SPRITE_OAM | 0x292,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_Y_FLIP | 0x1e6, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0xff, OBJ_X_FLIP | OBJ_Y_FLIP | 0xa, OBJ_SPRITE_OAM | 0x280,
    OBJ_SHAPE_HORIZONTAL | 0x30, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2f2,
    OBJ_SHAPE_HORIZONTAL | 0x30, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2f2,
    0x10, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e0, OBJ_SPRITE_OAM | 0x28a,
    0x10, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x0, OBJ_SPRITE_OAM | 0x28a,
    0xf0, OBJ_Y_FLIP | OBJ_SIZE_32x32 | 0x1e8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_VERTICAL | 0xf0, OBJ_X_FLIP | OBJ_Y_FLIP | OBJ_SIZE_16x32 | 0x8, OBJ_SPRITE_OAM | 0x28e,
    OBJ_SHAPE_HORIZONTAL | 0xd0, OBJ_Y_FLIP | OBJ_SIZE_32x8 | 0x1e8, OBJ_SPRITE_OAM | 0x2ae,
    OBJ_SHAPE_HORIZONTAL | 0xd0, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x2ae
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame0[4] = {
    0x1,
    0xcc, 0x1fc, OBJ_SPRITE_OAM | 0x27f
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame2[4] = {
    0x1,
    0xcc, 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame4[4] = {
    0x1,
    OBJ_SHAPE_VERTICAL | 0xc8, 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame6[7] = {
    0x2,
    OBJ_SHAPE_VERTICAL | 0xc4, 0x1fc, OBJ_SPRITE_OAM | 0x218,
    0xd4, 0x1fc, OBJ_SPRITE_OAM | 0x258
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame8[4] = {
    0x1,
    OBJ_SHAPE_VERTICAL | 0xc0, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame10[7] = {
    0x2,
    OBJ_SHAPE_VERTICAL | 0xbc, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218,
    0xdc, 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame12[7] = {
    0x2,
    OBJ_SHAPE_VERTICAL | 0xb8, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218,
    OBJ_SHAPE_VERTICAL | 0xd8, 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame14[7] = {
    0x2,
    OBJ_SHAPE_VERTICAL | 0xb4, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218,
    OBJ_SHAPE_VERTICAL | 0xcc, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame16[7] = {
    0x2,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x218
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame18[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1fb, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1fb, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x1fd, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x1fd, OBJ_SPRITE_OAM | 0x219
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame20[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f7, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f7, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x1, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x1, OBJ_SPRITE_OAM | 0x219
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame22[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x4, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x4, OBJ_SPRITE_OAM | 0x219
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame24[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f3, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f3, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x5, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x5, OBJ_SPRITE_OAM | 0x219,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame26[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f2, OBJ_SPRITE_OAM | 0x21a,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f2, OBJ_SPRITE_OAM | 0x21a,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x6, OBJ_SPRITE_OAM | 0x21a,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x6, OBJ_SPRITE_OAM | 0x21a
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame28[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f1, OBJ_SPRITE_OAM | 0x21a,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f1, OBJ_SPRITE_OAM | 0x21a,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x7, OBJ_SPRITE_OAM | 0x21a,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x7, OBJ_SPRITE_OAM | 0x21a
};

const u16 sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_Tube_Unused_Frame1[7] = {
    0x2,
    0xb0, OBJ_SIZE_32x32 | 0x1f0, OBJ_SPRITE_OAM | 0x210,
    0xd0, OBJ_SIZE_32x32 | 0x1f0, OBJ_SPRITE_OAM | 0x210
};

const u16 sSavePlatformChozodiaPartOAM_TubeShadow_Frame0[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1ec, OBJ_SPRITE_OAM | 0x21c,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1ec, OBJ_SPRITE_OAM | 0x21c,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0xc, OBJ_SPRITE_OAM | 0x21c,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0xc, OBJ_SPRITE_OAM | 0x21c
};

const u16 sSavePlatformChozodiaPartOAM_TubeShadow_Frame2[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1ee, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1ee, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0xa, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0xa, OBJ_SPRITE_OAM | 0x21d
};

const u16 sSavePlatformChozodiaPartOAM_TubeShadow_Frame4[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f1, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f1, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x7, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x7, OBJ_SPRITE_OAM | 0x21d
};

const u16 sSavePlatformChozodiaPartOAM_TubeShadow_Frame6[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f5, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f5, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x3, OBJ_SPRITE_OAM | 0x21d,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x3, OBJ_SPRITE_OAM | 0x21d
};

const u16 sSavePlatformChozodiaPartOAM_TubeShadow_Frame8[13] = {
    0x4,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1f9, OBJ_SPRITE_OAM | 0x21c,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f9, OBJ_SPRITE_OAM | 0x21c,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x1ff, OBJ_SPRITE_OAM | 0x21c,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_X_FLIP | OBJ_SIZE_8x32 | 0x1ff, OBJ_SPRITE_OAM | 0x21c
};

const u16 sSavePlatformChozodiaPartOAM_TubeShadow_Frame10[7] = {
    0x2,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x21e,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1fc, OBJ_SPRITE_OAM | 0x21e
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame0[31] = {
    0xa,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xbe, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd2, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xbe, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd2, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xe0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame2[31] = {
    0xa,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xbc, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd4, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xbc, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd4, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xe0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame4[31] = {
    0xa,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb8, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd8, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb8, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xe0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame6[31] = {
    0xa,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb4, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xdc, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb4, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xdc, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xe0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame8[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    OBJ_SHAPE_VERTICAL | 0xe0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame10[37] = {
    0xc,
    0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    0xe8, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    0xe8, OBJ_Y_FLIP | 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xe8, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    0xb8, 0x1f3, OBJ_SPRITE_OAM | 0x23f,
    0xb4, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xb4, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    0xe0, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x23f,
    0xe4, OBJ_Y_FLIP | 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xe4, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame12[19] = {
    0x6,
    0xb0, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    0xb0, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xb0, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    0xe8, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    0xe8, OBJ_Y_FLIP | 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xe8, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_TubeDespawning_Frame14[31] = {
    0x6,
    0xac, 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    0xac, 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xac, OBJ_X_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b,
    0xec, OBJ_Y_FLIP | 0x1f3, OBJ_SPRITE_OAM | 0x21f,
    0xec, OBJ_Y_FLIP | 0x1f0, OBJ_SPRITE_OAM | 0x21b,
    0xec, OBJ_X_FLIP | OBJ_Y_FLIP | 0x8, OBJ_SPRITE_OAM | 0x21b
};

const u16 sSavePlatformChozodiaPartOAM_Ray_Frame0[7] = {
    0x2,
    OBJ_SHAPE_HORIZONTAL | 0xf8, 0x1f0, OBJ_SPRITE_OAM | 0x1296,
    OBJ_SHAPE_HORIZONTAL | 0xf8, OBJ_X_FLIP | 0x0, OBJ_SPRITE_OAM | 0x1296
};

const u16 sSavePlatformChozodiaPartOAM_Ray_Frame2[7] = {
    0x2,
    OBJ_SHAPE_HORIZONTAL | 0xf8, 0x1f0, OBJ_SPRITE_OAM | 0x12b6,
    OBJ_SHAPE_HORIZONTAL | 0xf8, OBJ_X_FLIP | 0x0, OBJ_SPRITE_OAM | 0x12b6
};

const u16 sSavePlatformChozodiaPartOAM_Ray_Frame4[7] = {
    0x2,
    OBJ_SHAPE_HORIZONTAL | 0xf8, 0x1f0, OBJ_SPRITE_OAM | 0x12d6,
    OBJ_SHAPE_HORIZONTAL | 0xf8, OBJ_X_FLIP | 0x0, OBJ_SPRITE_OAM | 0x12d6
};

const u16 sSavePlatformChozodiaPartOAM_Ray_Frame6[7] = {
    0x2,
    OBJ_SHAPE_HORIZONTAL | 0xf8, 0x1f0, OBJ_SPRITE_OAM | 0x12f6,
    OBJ_SHAPE_HORIZONTAL | 0xf8, OBJ_X_FLIP | 0x0, OBJ_SPRITE_OAM | 0x12f6
};

const u16 sSavePlatformChozodiaPartOAM_Empty[4] = {
    0x1,
    0xfc, 0x1fc, 0x25f
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame0[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x1f0, OBJ_SPRITE_OAM | 0x1299,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x129b,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x5, OBJ_SPRITE_OAM | 0x1298,
    0xe8, 0x2, OBJ_SPRITE_OAM | 0x12fa,
    0xc0, 0x1fd, OBJ_SPRITE_OAM | 0x1298,
    0xe4, 0x1ed, OBJ_SPRITE_OAM | 0x12fa
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame1[22] = {
    0x7,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f0, OBJ_SPRITE_OAM | 0x1299,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_SIZE_8x32 | 0x1f8, OBJ_SPRITE_OAM | 0x129c,
    OBJ_SHAPE_VERTICAL | 0xc8, 0x1f4, OBJ_SPRITE_OAM | 0x129b,
    OBJ_SHAPE_VERTICAL | 0xd0, 0x5, OBJ_SPRITE_OAM | 0x1298,
    0xe4, 0x2, OBJ_SPRITE_OAM | 0x12da,
    0xe8, 0x1f1, OBJ_SPRITE_OAM | 0x12fa,
    0xe0, 0x1ed, OBJ_SPRITE_OAM | 0x12da
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame2[31] = {
    0xa,
    OBJ_SHAPE_VERTICAL | 0xc8, OBJ_SIZE_8x32 | 0x1f0, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x1f8, OBJ_SPRITE_OAM | 0x129c,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x0, OBJ_SPRITE_OAM | 0x1299,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x1299,
    0xe0, 0x2, OBJ_SPRITE_OAM | 0x12ba,
    0xe4, 0x1f1, OBJ_SPRITE_OAM | 0x12da,
    0xc0, 0x1f4, OBJ_SPRITE_OAM | 0x129b,
    0xc8, 0x5, OBJ_SPRITE_OAM | 0x1298,
    0xdc, 0x1ed, OBJ_SPRITE_OAM | 0x12ba,
    0xe8, 0xa, OBJ_SPRITE_OAM | 0x12fa
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame3[31] = {
    0xa,
    OBJ_SHAPE_VERTICAL | 0xc0, 0x1f0, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f8, OBJ_SPRITE_OAM | 0x129b,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x8, OBJ_SPRITE_OAM | 0x129c,
    OBJ_SHAPE_VERTICAL | 0xc8, OBJ_SIZE_8x32 | 0x0, OBJ_SPRITE_OAM | 0x1299,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x1299,
    0xdc, 0x2, OBJ_SPRITE_OAM | 0x129a,
    0xe0, 0x1f1, OBJ_SPRITE_OAM | 0x12ba,
    0xe8, 0x1fa, OBJ_SPRITE_OAM | 0x12fa,
    0xd8, 0x1ed, OBJ_SPRITE_OAM | 0x129a,
    0xe4, 0xa, OBJ_SPRITE_OAM | 0x12da
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame4[34] = {
    0xb,
    OBJ_SHAPE_VERTICAL | 0xc8, 0x1f8, OBJ_SPRITE_OAM | 0x129b,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x8, OBJ_SPRITE_OAM | 0x129c,
    OBJ_SHAPE_VERTICAL | 0xc0, OBJ_SIZE_8x32 | 0x0, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_SIZE_8x32 | 0x1fd, OBJ_SPRITE_OAM | 0x1299,
    0xdc, 0x1f1, OBJ_SPRITE_OAM | 0x129a,
    0xe4, 0x1fa, OBJ_SPRITE_OAM | 0x12da,
    0xb8, 0x1f0, OBJ_SPRITE_OAM | 0x1298,
    0xe8, 0x5, OBJ_SPRITE_OAM | 0x12fa,
    0xe0, 0xa, OBJ_SPRITE_OAM | 0x12ba,
    0xe8, 0x1ef, OBJ_SPRITE_OAM | 0x12fa
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame5[28] = {
    0x9,
    OBJ_SHAPE_VERTICAL | 0xc8, OBJ_SIZE_8x32 | 0x8, OBJ_SPRITE_OAM | 0x129b,
    OBJ_SHAPE_VERTICAL | 0xb8, 0x0, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xc8, 0x1f4, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x1fd, OBJ_SPRITE_OAM | 0x1299,
    0xe0, 0x1fa, OBJ_SPRITE_OAM | 0x12ba,
    0xc0, 0x1f8, OBJ_SPRITE_OAM | 0x129b,
    0xe4, 0x5, OBJ_SPRITE_OAM | 0x12da,
    0xdc, 0xa, OBJ_SPRITE_OAM | 0x129a,
    0xe4, 0x1ef, OBJ_SPRITE_OAM | 0x12da
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame6[28] = {
    0x9,
    OBJ_SHAPE_VERTICAL | 0xc0, 0x8, OBJ_SPRITE_OAM | 0x129b,
    OBJ_SHAPE_VERTICAL | 0xd0, OBJ_SIZE_8x32 | 0x1fd, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x129c,
    OBJ_SHAPE_VERTICAL | 0xe8, OBJ_SIZE_8x32 | 0x5, OBJ_SPRITE_OAM | 0x1299,
    0xdc, 0x1fa, OBJ_SPRITE_OAM | 0x129a,
    0xb0, 0x0, OBJ_SPRITE_OAM | 0x1298,
    0xc0, 0x1f4, OBJ_SPRITE_OAM | 0x1298,
    0xe0, 0x5, OBJ_SPRITE_OAM | 0x12ba,
    0xe0, 0x1ef, OBJ_SPRITE_OAM | 0x12ba
};

const u16 sSavePlatformChozodiaPartOAM_RefillLight_Frame7[19] = {
    0x6,
    OBJ_SHAPE_VERTICAL | 0xc8, 0x1fd, OBJ_SPRITE_OAM | 0x1298,
    OBJ_SHAPE_VERTICAL | 0xd8, OBJ_SIZE_8x32 | 0x1f4, OBJ_SPRITE_OAM | 0x129c,
    OBJ_SHAPE_VERTICAL | 0xe0, OBJ_SIZE_8x32 | 0x5, OBJ_SPRITE_OAM | 0x1299,
    0xb8, 0x8, OBJ_SPRITE_OAM | 0x129b,
    0xdc, 0x5, OBJ_SPRITE_OAM | 0x129a,
    0xdc, 0x1ef, OBJ_SPRITE_OAM | 0x129a
};

const struct FrameData sSavePlatformChozodiaOAM_Idle[7] = {
    sSavePlatformChozodiaOAM_Idle_Frame0,
    0xC,
    sSavePlatformChozodiaOAM_Idle_Frame1,
    0xC,
    sSavePlatformChozodiaOAM_Idle_Frame2,
    0xC,
    sSavePlatformChozodiaOAM_Idle_Frame3,
    0xC,
    sSavePlatformChozodiaOAM_Idle_Frame2,
    0xC,
    sSavePlatformChozodiaOAM_Idle_Frame1,
    0xC,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaOAM_Opening[7] = {
    sSavePlatformChozodiaOAM_Opening_Frame0,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame1,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame2,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame3,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame4,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame5,
    0x3,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaOAM_Opened[7] = {
    sSavePlatformChozodiaOAM_Opened_Frame0,
    0xC,
    sSavePlatformChozodiaOAM_Opened_Frame1,
    0xC,
    sSavePlatformChozodiaOAM_Opened_Frame2,
    0xC,
    sSavePlatformChozodiaOAM_Opened_Frame3,
    0xC,
    sSavePlatformChozodiaOAM_Opened_Frame2,
    0xC,
    sSavePlatformChozodiaOAM_Opened_Frame1,
    0xC,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaOAM_Saving[7] = {
    sSavePlatformChozodiaOAM_Opened_Frame0,
    0x2,
    sSavePlatformChozodiaOAM_Opened_Frame1,
    0x2,
    sSavePlatformChozodiaOAM_Opened_Frame2,
    0x2,
    sSavePlatformChozodiaOAM_Opened_Frame3,
    0x2,
    sSavePlatformChozodiaOAM_Opened_Frame2,
    0x2,
    sSavePlatformChozodiaOAM_Opened_Frame1,
    0x2,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaOAM_IdleOff[2] = {
    sSavePlatformChozodiaOAM_Opened_Frame0,
    0xFF,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaOAM_Closing[7] = {
    sSavePlatformChozodiaOAM_Opening_Frame5,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame4,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame3,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame2,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame1,
    0x3,
    sSavePlatformChozodiaOAM_Opening_Frame0,
    0x3,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaOAM_OpenedOff[2] = {
    sSavePlatformChozodiaOAM_Idle_Frame0,
    0xFF,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TopIdle[2] = {
    sSavePlatformChozodiaPartOAM_TopIdle_Frame0,
    0xFF,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TopExtending[6] = {
    sSavePlatformChozodiaPartOAM_TopExtending_Frame0,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame1,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame2,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame3,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame4,
    0x4,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TopExtended[2] = {
    sSavePlatformChozodiaPartOAM_TopExtended_Frame0,
    0xFF,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TopRetracting[6] = {
    sSavePlatformChozodiaPartOAM_TopExtending_Frame4,
    0x6,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame3,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame2,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame1,
    0x4,
    sSavePlatformChozodiaPartOAM_TopExtending_Frame0,
    0x4,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TubeSpawning[39] = {
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame0,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame2,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame4,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame6,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame8,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame10,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame12,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame14,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame16,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame18,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame20,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame22,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame24,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame26,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame28,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame28,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TubeShadow[13] = {
    sSavePlatformChozodiaPartOAM_TubeShadow_Frame0,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeShadow_Frame2,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeShadow_Frame4,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeShadow_Frame6,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeShadow_Frame8,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeShadow_Frame10,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TubeIdle[3] = {
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_Tube_Unused[5] = {
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32,
    0x1,
    sSavePlatformChozodiaPartOAM_Tube_Unused_Frame1,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeSpawning_Frame32,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_TubeDespawning[17] = {
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame0,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame2,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame4,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame6,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame8,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame10,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame12,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_TubeDespawning_Frame14,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_Ray[9] = {
    sSavePlatformChozodiaPartOAM_Ray_Frame0,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_Ray_Frame2,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_Ray_Frame4,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    sSavePlatformChozodiaPartOAM_Ray_Frame6,
    0x1,
    sSavePlatformChozodiaPartOAM_Empty,
    0x1,
    NULL,
    0x0
};

const struct FrameData sSavePlatformChozodiaPartOAM_RefillLight[9] = {
    sSavePlatformChozodiaPartOAM_RefillLight_Frame0,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame1,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame2,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame3,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame4,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame5,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame6,
    0x3,
    sSavePlatformChozodiaPartOAM_RefillLight_Frame7,
    0x3,
    NULL,
    0x0
};


/**
 * @brief 46708 | 168 | Initializes a save platform (Chozodia) sprite
 * 
 */
void SavePlatformChozodiaInit(void)
{
    gCurrentSprite.properties |= SP_ALWAYS_ACTIVE;
    gCurrentSprite.yPositionSpawn = 0x0;
    gCurrentSprite.samusCollision = SSC_NONE;

    gCurrentSprite.drawDistanceTopOffset = 0x18;
    gCurrentSprite.drawDistanceBottomOffset = 0x10;
    gCurrentSprite.drawDistanceHorizontalOffset = 0x28;

    gCurrentSprite.hitboxTopOffset = -0x4;
    gCurrentSprite.hitboxBottomOffset = 0x4;
    gCurrentSprite.hitboxLeftOffset = -0x4;
    gCurrentSprite.hitboxRightOffset = 0x4;

    if (gAlarmTimer != 0x0)
        gCurrentSprite.workVariable2 = TRUE;
    else
        gCurrentSprite.workVariable2 = FALSE;

    gCurrentSprite.animationDurationCounter = 0x0;
    gCurrentSprite.currentAnimationFrame = 0x0;
    gCurrentSprite.timer = 0xA;

    if (gCurrentSprite.workVariable2 || EscapeDetermineTimer() != ESCAPE_NONE)
    {
        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_OpenedOff;
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_OFF;
    }
    else if (gIsLoadingFile)
    {
        SpriteSpawnSecondary(SSPRITE_CHOZODIA_SAVE_PLATFORM_PART, SAVE_PLATFORM_CHOZODIA_PART_TUBE,
            gCurrentSprite.spritesetGFXSlot, gCurrentSprite.primarySpriteRAMSlot,
            gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);

        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_IdleOff;
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_RELEASE_SAMUS;
        gCurrentSprite.yPositionSpawn = 0x154;
    }
    else
    {
        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Idle;
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_IDLE;
    }

    gCurrentSprite.arrayOffset = SpriteSpawnSecondary(SSPRITE_CHOZODIA_SAVE_PLATFORM_PART, SAVE_PLATFORM_CHOZODIA_PART_TOP,
        gCurrentSprite.spritesetGFXSlot, gCurrentSprite.primarySpriteRAMSlot,
        gCurrentSprite.yPosition - BLOCK_SIZE * 8, gCurrentSprite.xPosition, 0x0);

    if (gCurrentSprite.pose == SAVE_PLATFORM_CHOZODIA_POSE_OFF)
    {
        gCurrentSprite.paletteRow = 0x3;
        gSpriteData[gCurrentSprite.arrayOffset].paletteRow = 0x3;
    }

    TransparencyUpdateBLDCNT(0x1, BLDCNT_BG0_FIRST_TARGET_PIXEL | BLDCNT_ALPHA_BLENDING_EFFECT |
        BLDCNT_BG1_SECOND_TARGET_PIXEL | BLDCNT_BG2_SECOND_TARGET_PIXEL |
        BLDCNT_BG3_SECOND_TARGET_PIXEL | BLDCNT_OBJ_SECOND_TARGET_PIXEL | BLDCNT_BACKDROP_SECOND_TARGET_PIXEL);
    
    TransparencySpriteUpdateBLDALPHA(0x0, 0x10, 0x0, 0x10);
}

/**
 * @brief 46870 | 58 | Handles a save platform (Chozodia) being idle
 * 
 */
void SavePlatformChozodiaSamusDetection(void)
{
    if (SavePlatformDetectSamus() && !SpriteUtilCheckCrouchingOrMorphed())
    {
        gCurrentSprite.timer--;
        if (gCurrentSprite.timer == 0x0)
        {
            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_OPENING;
            gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Opening;
            gCurrentSprite.animationDurationCounter = 0x0;
            gCurrentSprite.currentAnimationFrame = 0x0;
            SoundPlay(0x127);
        }
    }
    else
        gCurrentSprite.timer = 0xA;
}

/**
 * @brief 468c8 | 2c | Handles a save platform opening
 * 
 */
void SavePlatformChozodiaCheckOpeningAnimEnded(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_OPENED;
        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Opened;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
    }
}

/**
 * @brief 468f4 | 78 | Handles a save platform (Chozodia) being opened
 * 
 */
void SavePlatformChozodiaSecondSamusDetection(void)
{
    if (SavePlatformDetectSamus())
    {
        if (!SpriteUtilCheckCrouchingOrMorphed())
        {
            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_CHECK_REFILL;
            gCurrentSprite.timer = 0x4;
            gSamusData.xPosition = gCurrentSprite.xPosition;

            if (gSamusData.invincibilityTimer != 0x0)
                gSamusData.invincibilityTimer = 0x0;

            SamusSetPose(SPOSE_TURNING_FROM_FACING_THE_FOREGROUND);
            gSamusData.timer = TRUE;
            gDisablePause = TRUE;
        }
    }
    else
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_CLOSING;
        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Closing;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
        SoundPlay(0x128);
    }
}

/**
 * @brief 4696c | 30 | Handles a save platform (Chozodia) closing
 * 
 */
void SavePlatformChozodiaCheckClosingAnimEnded(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_IDLE;
        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Idle;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
        gCurrentSprite.timer = 0xA;
    }
}

/**
 * @brief 4699c | 34 | Handles a save platform (Chozodia) releasing Samus
 * 
 */
void SavePlatformChozodiaReleaseSamus(void)
{
    if (gCurrentSprite.yPositionSpawn != 0x0)
        gCurrentSprite.yPositionSpawn--;
    else
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_AFTER_SAVE;
        SamusSetPose(SPOSE_FACING_THE_FOREGROUND);
        gDisablePause = FALSE;
    }
}

/**
 * @brief 469d0 | 34 | Handles a save platform after a save
 * 
 */
void SavePlatformChozodiaSamusDetectionOut(void)
{
    if (!SavePlatformDetectSamus())
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_CLOSING;
        gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Closing;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
        SoundPlay(0x128);
    }
}

/**
 * @brief 46a04 | c0 | Checksif Samus needs a refill
 * 
 */
void SavePlatformChozodiaCheckRefill(void)
{
    u8 isFull;

    isFull = FALSE;

    if (gCurrentSprite.timer != 0x0)
        gCurrentSprite.timer--;
    else
    {
        if (gEquipment.suitType == SUIT_SUITLESS)
        {
            if (gEquipment.currentEnergy == gEquipment.maxEnergy)
                isFull = TRUE;
        }
        else
        {
            if (gEquipment.currentEnergy == gEquipment.maxEnergy && gEquipment.currentMissiles == gEquipment.maxMissiles &&
                gEquipment.currentSuperMissiles == gEquipment.maxSuperMissiles)
            {
                if (gEquipment.currentPowerBombs == gEquipment.maxPowerBombs)
                    isFull = TRUE;
            }
        }

        if (isFull)
        {
            gCurrentSprite.timer = 0xA;
            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_SAVE_PROMPT;
        }
        else
        {
            gSamusData.timer = FALSE;
            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_REFILL;
            gCurrentSprite.timer = 0x5;

            SpriteSpawnSecondary(SSPRITE_CHOZODIA_SAVE_PLATFORM_PART, SAVE_PLATFORM_CHOZODIA_PART_REFILL_LIGHT,
                gCurrentSprite.spritesetGFXSlot, gCurrentSprite.primarySpriteRAMSlot,
                gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);

            TransparencySpriteUpdateBLDALPHA(0x7, 0x10, 0x0, 0x10);
            SoundPlay(0x129);
        }
    }
}

/**
 * @brief 46ac4 | 194 | Handles a save platform (Chozodia) refilling Samus
 * 
 */
void SavePlatformChozodiaRefill(void)
{
    if (gEquipment.suitType == SUIT_SUITLESS)
    {
        if (gCurrentSprite.timer == 0x5)
        {
            if (!SpriteUtilRefillEnergy())
            {
                gCurrentSprite.timer--;
                gEnergyRefillAnimation = 0xD;
            }
        }
        else if (gCurrentSprite.timer == 0x4)
        {
            if (gEnergyRefillAnimation != 0x0)
                gEnergyRefillAnimation--;
            else
                gCurrentSprite.timer--;
        }
        else if (gCurrentSprite.timer != 0x0)
        {
            gCurrentSprite.timer--;
            if (gCurrentSprite.timer == 0x0)
            {
                gSamusData.timer = TRUE;
                TransparencySpriteUpdateBLDALPHA(0x0, 0x10, 0x0, 0x10);
                SoundFade(0x129, 0x14);
            }
        }
        else
        {
            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_AFTER_REFILL;
            gCurrentSprite.workVariable = SpriteSpawnPrimary(PSPRITE_ITEM_BANNER, MESSAGE_ENERGY_TANK_RECHARGE_COMPLETE,
                0x6, gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);
        }
    }
    else
    {
        if (gCurrentSprite.timer == 0x5)
        {
            if (!SpriteUtilRefillEnergy())
            {
                gCurrentSprite.timer--;
                gEnergyRefillAnimation = 0xD;
            }
        }
        else if (gCurrentSprite.timer == 0x4)
        {
            if (gEnergyRefillAnimation != 0x0)
                gEnergyRefillAnimation--;
            else if (!SpriteUtilRefillMissiles())
            {
                gCurrentSprite.timer--;
                gMissileRefillAnimation = 0xD;
            }
        }
        else if (gCurrentSprite.timer == 0x3)
        {
            if (gMissileRefillAnimation != 0x0)
                gMissileRefillAnimation--;
            else if (!SpriteUtilRefillSuperMissiles())
            {
                gCurrentSprite.timer--;
                gSuperMissileRefillAnimation = 0xD;
            }
        }
        else if (gCurrentSprite.timer == 0x2)
        {
            if (gSuperMissileRefillAnimation != 0x0)
                gSuperMissileRefillAnimation--;
            else if (!SpriteUtilRefillPowerBombs())
            {
                gCurrentSprite.timer--;
                gPowerBombRefillAnimation = 0xD;
            }
        }
        else if (gPowerBombRefillAnimation != 0x0)
                gPowerBombRefillAnimation--;
        else if (gCurrentSprite.timer != 0x0)
        {
            gCurrentSprite.timer--;
            if (gCurrentSprite.timer == 0x0)
            {
                gSamusData.timer = TRUE;
                TransparencySpriteUpdateBLDALPHA(0x0, 0x10, 0x0, 0x10);
                SoundFade(0x129, 0x14);
            }
        }
        else
        {
            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_AFTER_REFILL;
            gCurrentSprite.workVariable = SpriteSpawnPrimary(PSPRITE_ITEM_BANNER, MESSAGE_WEAPONS_AND_ENERGY_RESTORED,
                0x6, gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);
        }
    }
}

/**
 * @brief 46c58 | 38 | Handles a save platform (Complete) waiting for the "Refill complete" message to be done
 * 
 */
void SavePlatformChozodiaAfterRefill(void)
{
    u8 ramSlot;

    ramSlot = gCurrentSprite.workVariable;
    if (gSpriteData[ramSlot].pose == ITEM_BANNER_POSE_REMOVAL_ANIMATION)
    {
        gCurrentSprite.timer = 0x14;
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_SAVE_PROMPT;
    }
}

/**
 * @brief 46c90 | d0 | Handles a save platform (Chozodia) during a save prompt
 * 
 */
void SavePlatformChozodiaSavePrompt(void)
{
    u8 ramSlot;

    if (gCurrentSprite.timer != 0x0)
    {
        gCurrentSprite.timer--;
        if (gCurrentSprite.timer == 0x0)
        {
            gCurrentSprite.workVariable = SpriteSpawnPrimary(PSPRITE_ITEM_BANNER, MESSAGE_SAVE_PROMPT,
                0x6, gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);
        }
    }
    else
    {
        ramSlot = gCurrentSprite.workVariable;
        if (gSpriteData[ramSlot].pose == ITEM_BANNER_POSE_REMOVAL_ANIMATION)
        {
            if (gSpriteData[ramSlot].workVariable == TRUE)
            {
                gCurrentSprite.pOam = sSavePlatformChozodiaOAM_Saving;
                gCurrentSprite.animationDurationCounter = 0x0;
                gCurrentSprite.currentAnimationFrame = 0x0;

                gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_SAVING;

                SpriteSpawnSecondary(SSPRITE_CHOZODIA_SAVE_PLATFORM_PART, SAVE_PLATFORM_CHOZODIA_PART_TUBE,
                    gCurrentSprite.spritesetGFXSlot, gCurrentSprite.primarySpriteRAMSlot, gCurrentSprite.yPosition,
                    gCurrentSprite.xPosition, 0x0);

                gSpriteData[gCurrentSprite.arrayOffset].pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_EXTENDING_INIT;
                gSamusData.timer = FALSE;
                SoundPlay(0x114);
            }
            else
            {
                gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_DELAY_BEFORE_RELEASING;
                gCurrentSprite.timer = 0xA;
            }
        }
    }
}

/**
 * @brief 46d60 | 40 | Handles a save platform (Chozodia) saving
 * 
 */
void SavePlatformChozodiaSaving(void)
{
    u8 ramSlot;

    ramSlot = gCurrentSprite.arrayOffset;
    if (gCurrentSprite.currentAnimationFrame & 0x1)
    {
        gCurrentSprite.paletteRow = 0x0;
        gSpriteData[ramSlot].paletteRow = 0x0;
    }
    else
    {
        gCurrentSprite.paletteRow = 0x2;
        gSpriteData[ramSlot].paletteRow = 0x2;
    }
}

/**
 * @brief 46da0 | 44 | Initializes a save platform (Chozodia) to be opened (off)
 * 
 */
void SavePlatformChozodiaOpenedOffInit(void)
{
    gCurrentSprite.pOam = sSavePlatformChozodiaOAM_IdleOff;
    gCurrentSprite.animationDurationCounter = 0x0;
    gCurrentSprite.currentAnimationFrame = 0x0;

    gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_SPAWN_SAVE_DONE_MESSAGE;
    gCurrentSprite.timer = 0x3C;
    gCurrentSprite.paletteRow = 0x0;
    gSpriteData[gCurrentSprite.arrayOffset].paletteRow = 0x0;
}

/**
 * @brief 46de4 | 44 | Spawns the "save complete" message
 * 
 */
void SavePlatformChozodiaSpawnSaveDoneMessage(void)
{
    gCurrentSprite.timer--;
    if (gCurrentSprite.timer == 0x0)
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_WAIT_FOR_MESSAGE_OUT;
        gCurrentSprite.workVariable = SpriteSpawnPrimary(PSPRITE_ITEM_BANNER, MESSAGE_SAVE_COMPLETE,
            0x6, gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);
    }
}

/**
 * @brief 46e28 | 38 | Handles a save platform (Chozodia) waiting for the "Save complete" message to be done
 * 
 */
void SavePlatformChozodiaCheckMessageBannerOut(void)
{
    u8 ramSlot;

    ramSlot = gCurrentSprite.workVariable;

    if (gSpriteData[ramSlot].pose == ITEM_BANNER_POSE_REMOVAL_ANIMATION)
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_DELAY_BEFORE_RELEASING;
        gCurrentSprite.timer = 0xA;
    }
}

/**
 * @brief 46e60 | 24 | andles the delay before a save platform (Chozodia) releases Samus
 * 
 */
void SavePlatformChozodiaDelayBeforeReleasingSamus(void)
{
    gCurrentSprite.timer--;
    if (gCurrentSprite.timer == 0x0)
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_POSE_RELEASE_SAMUS;
}

/**
 * @brief 46e84 | 1b6 | Initializes a save platform (Chozodia) part sprite
 * 
 */
void SavePlatformChozodiaPartInit(void)
{
    u8 ramSlot;

    ramSlot = gCurrentSprite.primarySpriteRAMSlot;

    gCurrentSprite.status &= ~SPRITE_STATUS_NOT_DRAWN;
    gCurrentSprite.properties |= SP_ALWAYS_ACTIVE;
    gCurrentSprite.samusCollision = SSC_NONE;

    gCurrentSprite.hitboxTopOffset = -0x4;
    gCurrentSprite.hitboxBottomOffset = 0x4;
    gCurrentSprite.hitboxLeftOffset = -0x4;
    gCurrentSprite.hitboxRightOffset = 0x4;

    gCurrentSprite.animationDurationCounter = 0x0;
    gCurrentSprite.currentAnimationFrame = 0x0;

    switch (gCurrentSprite.roomSlot)
    {
        case SAVE_PLATFORM_CHOZODIA_PART_TUBE:
            gCurrentSprite.drawDistanceTopOffset = 0x50;
            gCurrentSprite.drawDistanceBottomOffset = 0x0;
            gCurrentSprite.drawDistanceHorizontalOffset = 0x18;

            if (gSpriteData[ramSlot].pose == SAVE_PLATFORM_CHOZODIA_POSE_RELEASE_SAMUS)
            {
                gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TubeIdle;
                gCurrentSprite.yPositionSpawn = 0x136;
                gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_IDLE;
            }
            else
            {
                gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TubeSpawning;
                gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_SPAWNING;
            }
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_TUBE_SHADOW:
            gCurrentSprite.drawOrder = 0xC;
            gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TubeShadow;

            gCurrentSprite.drawDistanceTopOffset = 0x50;
            gCurrentSprite.drawDistanceBottomOffset = 0x0;
            gCurrentSprite.drawDistanceHorizontalOffset = 0x18;

            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_SHADOW_IDLE;
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_RAY:
            gCurrentSprite.drawOrder = 0x5;
            gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_Ray;
            
            gCurrentSprite.drawDistanceTopOffset = 0x8;
            gCurrentSprite.drawDistanceBottomOffset = 0x0;
            gCurrentSprite.drawDistanceHorizontalOffset = 0x18;

            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_RAY_IDLE;
            gCurrentSprite.timer = 0x60;
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_TOP:
            gCurrentSprite.drawOrder = 0x3;
            gCurrentSprite.drawDistanceTopOffset = 0x40;
            gCurrentSprite.drawDistanceBottomOffset = 0x40;
            gCurrentSprite.drawDistanceHorizontalOffset = 0x20;

            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_IDLE;

            if (gSpriteData[ramSlot].pose == SAVE_PLATFORM_CHOZODIA_POSE_RELEASE_SAMUS)
                gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TopExtended;
            else
                gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TopIdle;
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_REFILL_LIGHT:
            gCurrentSprite.drawOrder = 0x5;
            gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_RefillLight;

            gCurrentSprite.drawDistanceTopOffset = 0x50;
            gCurrentSprite.drawDistanceBottomOffset = 0x8;
            gCurrentSprite.drawDistanceHorizontalOffset = 0x14;

            gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_REFILL_LIGHT_IDLE;
            break;

        default:
            gCurrentSprite.status = 0x0;
    }
}

/**
 * @brief 4703c | 2c | Handles the refill light part being idle
 * 
 */
void SavePlatformChozodiaPartRefillLightIdle(void)
{
    u8 ramSlot;

    ramSlot = gCurrentSprite.primarySpriteRAMSlot;
    if (gSpriteData[ramSlot].pose == SAVE_PLATFORM_CHOZODIA_POSE_AFTER_REFILL)
        gCurrentSprite.status = 0x0;
}

/**
 * @brief 47068 | 4 | Empty function
 * 
 */
void SavePlatformChozodiaPart_Empty(void)
{
    return;
}

/**
 * @brief 4706c | 1c | Initializes the top part to be extending
 * 
 */
void SavePlatformChozodiaPartTopExtendingInit(void)
{
    gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TopExtending;
    gCurrentSprite.animationDurationCounter = 0x0;
    gCurrentSprite.currentAnimationFrame = 0x0;

    gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_EXTENDING;
}

/**
 * @brief 47088 | 2c | Handles the top part extending
 * 
 */
void SavePlatformChozodiaPartTopExtending(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_IDLE;

        gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TopExtended;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
    }
}

/**
 * @brief 470b4 | 34 | Initializes the top part to be retracting
 * 
 */
void SavePlatformChozodiaPartTopRetractingInit(void)
{
    gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TopRetracting;
    gCurrentSprite.animationDurationCounter = 0x0;
    gCurrentSprite.currentAnimationFrame = 0x0;

    gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_RETRACTING;

    gSamusData.timer = TRUE;
    SoundPlay(0x115);
}

/**
 * @brief 470e8 | 2c | Handles the top part retracting
 * 
 */
void SavePlatformChozodiaPartTopRetracting(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_IDLE;

        gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TopIdle;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
    }
}

/**
 * @brief 47114 | 50 | Handles the tube part spawning
 * 
 */
void SavePlatformChozodiaPartTubeSpawning(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_CHECK_SHADOW_DISAPPEARED;
        
        gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TubeIdle;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;

        gCurrentSprite.workVariable = SpriteSpawnSecondary(SSPRITE_CHOZODIA_SAVE_PLATFORM_PART, SAVE_PLATFORM_CHOZODIA_PART_TUBE_SHADOW,
            gCurrentSprite.spritesetGFXSlot, gCurrentSprite.primarySpriteRAMSlot, gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);
    }
}

/**
 * @brief 47164 | 54 | Handles the tube part spawning the ray part
 * 
 */
void SavePlatformChozodiaPartSpawnRay(void)
{
    u8 ramSlot;

    ramSlot = gCurrentSprite.workVariable;

    if (gSpriteData[ramSlot].status == 0x0)
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_IDLE;
        gCurrentSprite.yPositionSpawn = 0x78;
        SpriteSpawnSecondary(SSPRITE_CHOZODIA_SAVE_PLATFORM_PART, SAVE_PLATFORM_CHOZODIA_PART_RAY,
            gCurrentSprite.spritesetGFXSlot, gCurrentSprite.primarySpriteRAMSlot, gCurrentSprite.yPosition, gCurrentSprite.xPosition, 0x0);
    }
}

/**
 * @brief 471b8 | 30 | Handles the tube part being idle
 * 
 */
void SavePlatformChozodiaPartTubeIdle(void)
{
    gCurrentSprite.yPositionSpawn--;
    if (gCurrentSprite.yPositionSpawn == 0x0)
    {
        gCurrentSprite.pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_DESPAWNING;
        gCurrentSprite.pOam = sSavePlatformChozodiaPartOAM_TubeDespawning;
        gCurrentSprite.animationDurationCounter = 0x0;
        gCurrentSprite.currentAnimationFrame = 0x0;
    }
}

/**
 * @brief 471e8 | 3c | Handles the tube part despawning
 * 
 */
void SavePlatformChozodiaPartTubeDespawning(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
    {
        gCurrentSprite.status = 0x0;
        gSpriteData[gSpriteData[gCurrentSprite.primarySpriteRAMSlot].arrayOffset].pose = SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_RETRACTING_INIT;
    }
}

/**
 * @brief 47224 | 18 | Handles the shadow part being idle
 * 
 */
void SavePlatformChozodiaPartTubeShadowIdle(void)
{
    if (SpriteUtilCheckEndCurrentSpriteAnim())
        gCurrentSprite.status = 0x0;
}

/**
 * @brief 4723c | 44 | Handles the ray part being idle
 * 
 */
void SavePlatformChozodiaPartRayIdle(void)
{
    gCurrentSprite.yPosition -= 0x4;
    gCurrentSprite.timer--;

    if (gCurrentSprite.timer == 0x0)
    {
        gSpriteData[gCurrentSprite.primarySpriteRAMSlot].pose = SAVE_PLATFORM_CHOZODIA_POSE_OPENED_OFF_INIT;
        gCurrentSprite.status = 0x0;
    }
}

/**
 * @brief 47280 | 1e8 | Save platform (Chozodia) AI
 * 
 */
void SavePlatformChozodia(void)
{
    gCurrentSprite.ignoreSamusCollisionTimer = 0x1;

    switch (gCurrentSprite.pose)
    {
        case 0x0:
            SavePlatformChozodiaInit();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_IDLE:
            SavePlatformChozodiaSamusDetection();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_OPENING:
            MechaRidleyCheckOpeningMouthAnimEnded();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_OPENED:
            SavePlatformChozodiaSecondSamusDetection();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_CLOSING:
            SavePlatformChozodiaCheckClosingAnimEnded();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_RELEASE_SAMUS:
            SavePlatformChozodiaReleaseSamus();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_AFTER_SAVE:
            SavePlatformChozodiaSamusDetectionOut();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_SAVE_PROMPT:
            SavePlatformChozodiaSavePrompt();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_SAVING:
            SavePlatformChozodiaSaving();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_OPENED_OFF_INIT:
            SavePlatformChozodiaOpenedOffInit();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_SPAWN_SAVE_DONE_MESSAGE:
            SavePlatformChozodiaSpawnSaveDoneMessage();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_WAIT_FOR_MESSAGE_OUT:
            SavePlatformChozodiaCheckMessageBannerOut();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_DELAY_BEFORE_RELEASING:
            SavePlatformChozodiaDelayBeforeReleasingSamus();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_CHECK_REFILL:
            SavePlatformChozodiaCheckRefill();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_REFILL:
            SavePlatformChozodiaRefill();
            break;

        case SAVE_PLATFORM_CHOZODIA_POSE_AFTER_REFILL:
            SavePlatformChozodiaAfterRefill();
            break;
    }
}

/**
 * @brief 47468 | 198 | Save platform (Chozodia) part AI
 * 
 */
void SavePlatformChozodiaPart(void)
{
    gCurrentSprite.ignoreSamusCollisionTimer = 0x1;

    switch (gCurrentSprite.pose)
    {
        case 0x0:
            SavePlatformChozodiaPartInit();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_SPAWNING:
            SavePlatformChozodiaPartTubeSpawning();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_CHECK_SHADOW_DISAPPEARED:
            SavePlatformChozodiaPartSpawnRay();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_IDLE:
            SavePlatformChozodiaPartTubeIdle();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_DESPAWNING:
            SavePlatformChozodiaPartTubeDespawning();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TUBE_SHADOW_IDLE:
            SavePlatformChozodiaPartTubeShadowIdle();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_RAY_IDLE:
            SavePlatformChozodiaPartRayIdle();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_IDLE:
            SavePlatformChozodiaPart_Empty();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_EXTENDING_INIT:
            SavePlatformChozodiaPartTopExtendingInit();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_EXTENDING:
            SavePlatformChozodiaPartTopExtending();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_RETRACTING_INIT:
            SavePlatformChozodiaPartTopRetractingInit();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_TOP_RETRACTING:
            SavePlatformChozodiaPartTopRetracting();
            break;

        case SAVE_PLATFORM_CHOZODIA_PART_POSE_REFILL_LIGHT_IDLE:
            SavePlatformChozodiaPartRefillLightIdle();
            break;
    }
}
