#ifndef SAVE_PLATFORM_CHOZODIA_AI_H
#define SAVE_PLATFORM_CHOZODIA_AI_H

#include "../types.h"

#define SAVE_PLATFORM_CHOZODIA_POSE_IDLE 0x9
#define SAVE_PLATFORM_CHOZODIA_POSE_OPENING 0x23
#define SAVE_PLATFORM_CHOZODIA_POSE_OPENED 0x25
#define SAVE_PLATFORM_CHOZODIA_POSE_CLOSING 0x27
#define SAVE_PLATFORM_CHOZODIA_POSE_RELEASE_SAMUS 0x28
#define SAVE_PLATFORM_CHOZODIA_POSE_AFTER_SAVE 0x29
#define SAVE_PLATFORM_CHOZODIA_POSE_SAVE_PROMPT 0x42
#define SAVE_PLATFORM_CHOZODIA_POSE_SAVING 0x43
#define SAVE_PLATFORM_CHOZODIA_POSE_OPENED_OFF_INIT 0x45
#define SAVE_PLATFORM_CHOZODIA_POSE_SPAWN_SAVE_DONE_MESSAGE 0x47
#define SAVE_PLATFORM_CHOZODIA_POSE_WAIT_FOR_MESSAGE_OUT 0x49
#define SAVE_PLATFORM_CHOZODIA_POSE_DELAY_BEFORE_RELEASING 0x4B
#define SAVE_PLATFORM_CHOZODIA_POSE_OFF 0x51

// Save platform chozodia part

#define SAVE_PLATFORM_CHOZODIA_PART_TUBE 0x0
#define SAVE_PLATFORM_CHOZODIA_PART_TUBE_SHADOW 0x1
#define SAVE_PLATFORM_CHOZODIA_PART_RAY 0x2
#define SAVE_PLATFORM_CHOZODIA_PART_TOP 0x3
#define SAVE_PLATFORM_CHOZODIA_PART_REFILL_LIGHT 0x4

void SavePlatformChozodiaInit(void);
void SavePlatformChozodiaSamusDetection(void);
void SavePlatformChozodiaCheckOpeningAnimEnded(void);
void SavePlatformChozodiaSecondSamusDetection(void);
void SavePlatformChozodiaCheckClosingAnimEnded(void);
void SavePlatformChozodiaReleaseSamus(void);
void SavePlatformChozodiaSamusDetectionOut(void);
void SavePlatformChozodiaCheckRefill(void);
void SavePlatformChozodiaRefill(void);
void SavePlatformChozodiaAfterRefill(void);
void SavePlatformChozodiaSaveInput(void);
void SavePlatformChozodiaFlashingAnim(void);
void SavePlatformChozodiaFlashingAnimEnd(void);
void SavePlatformChozodiaTextTimer(void);
void SavePlatformChozodiaCheckMessageBannerOut(void);
void SavePlatformChozodiaMessageBannerDisappearingTimer(void);
void SavePlatformChozodiaPartInit(void);
void SavePlatformChozodiaPartCheckRefillAnimEnded(void);
void SavePlatformChozodiaPart_Empty(void);
void SavePlatformChozodiaPartExtendGFXInit(void);
void SavePlatformChozodiaPartCheckExtendingAnimEnded(void);
void SavePlatformChozodiaPartRetractingGFXInit(void);
void SavePlatformChozodiaPartCheckRetractingAnimEnded(void);
void SavePlatformChozodiaPartCheckTubeAnimSpawnEnded(void);
void SavePlatformChozodiaPartCheckSpawnBigLight(void);
void SavePlatformChozodiaPartCheckTubeAnimEnded(void);
void SavePlatformChozodiaPartCheckTubeDespawningAnimEnded(void);
void SavePlatformChozodiaPartCheckTubeAroundAnimEnded(void);
void SavePlatformChozodiaPartTubeDownUpAnim(void);
void SavePlatformChozodia(void);
void SavePlatformChozodiaPart(void);

#endif /* SAVE_PLATFORM_CHOZODIA_AI_H */